CREATE TABLE [dbo].[DACPAC_VERSION_HISTORY]
(
    [ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [DEPLOYMENT_VERSION] INT NOT NULL, 
    [DEPLOYMENT_DESCRIPTION] NVARCHAR(MAX) NULL, 
    [INSTALLED_TIME] DATETIME2 NULL, 
    [DEPLOYMENT_TYPE] CHAR(10) NOT NULL
)
