-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE [VWSDEST].[POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION](
	[ID] BIGINT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION]),
	[DATE_OF_REPORT] [datetime] NULL,
	[DATE_OF_REPORT_UNIX] [bigint] NULL,
	[VRCODE] [varchar](100) NULL,
	[INFECTED_GGD] [int] NULL,
	[PERCENTAGE_INFECTED_GGD] [decimal](16, 2) NULL,
	[TOTAL_TESTED_GGD] [int] NULL,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
) 