-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordination for more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_G_NUMBER_NL]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_G_NUMBER_NL
  START WITH 1
  INCREMENT BY 1;
GO

 CREATE TABLE VWSDEST.G_NUMBER_NL(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_G_NUMBER_NL]),
	DATE_OF_REPORT DATETIME NULL,
	DATE_OF_REPORT_UNIX BIGINT NULL,
	DATE_OF_REPORT_START DATETIME NULL,
	POSITIVE_DAILY_7D_SUM INT NULL,
	G_NUMBER DECIMAL(16, 1) NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
 );