-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_CORONAMELDER]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_CORONAMELDER
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.CORONAMELDER(
      [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_CORONAMELDER])
      ,[DOWNLOADED_TOTAL] INT NULL
      ,[WARNED_DAILY] INT NULL
      ,[DATE_OF_REPORT] DATETIME NULL
      ,DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);

CREATE NONCLUSTERED INDEX IX_CORONAMELDER
ON VWSDEST.CORONAMELDER([DATE_OF_REPORT], [DATE_LAST_INSERTED])
;

