-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_RIVM_IC_OPNAME]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_RIVM_IC_OPNAME
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.RIVM_IC_OPNAME(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSDEST_RIVM_IC_OPNAME]),
    [VERSION] VARCHAR(100) NULL,
	DATE_OF_REPORT DATETIME NULL,
    [DATE_OF_REPORT_UNIX] BIGINT NULL,
    DATE_OF_STATISTICS DATETIME NULL,
    [DATE_OF_STATISTICS_UNIX] BIGINT NULL,
    IC_ADMISSION_NOTIFICATION INT NULL,
    IC_ADMISSION INT NULL,
    OLD_DATE_OF_STATISTICS_UNIX BIGINT NULL,
    OLD_IC_ADMISSION_NOTIFICATION INT NULL,
    DIFFERENCE_IC_ADMISSION_NOTIFICATION INT NULL,
    OLD_IC_ADMISSION INT NULL,
    DIFFERENCE_IC_ADMISSION INT NULL,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE(),
	WEEK_START DATETIME NULL,
	IC_ADMISSION_7D_AVG DECIMAL(16,2),
	WEEK_START_LAG DATETIME NULL,
	IC_ADMISSION_7D_AVG_LAG DECIMAL(16,2) NULL,
    IC_ADMISSION_NOTIFICATION_7D_AVG DECIMAL(16,2) NULL,
	IC_ADMISSION_NOTIFICATION_7D_AVG_LAG DECIMAL(16,2) NULL
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_IC_OPNAME_DEST')
    CREATE NONCLUSTERED INDEX IX_RIVM_IC_OPNAME_DEST
    ON VWSDEST.RIVM_IC_OPNAME(DATE_LAST_INSERTED,DATE_OF_STATISTICS)
    INCLUDE (DATE_OF_REPORT, IC_ADMISSION_NOTIFICATION, IC_ADMISSION,
    OLD_DATE_OF_STATISTICS_UNIX,
    OLD_IC_ADMISSION_NOTIFICATION,
    DIFFERENCE_IC_ADMISSION_NOTIFICATION,
    OLD_IC_ADMISSION,
    DIFFERENCE_IC_ADMISSION);
GO