-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_VACCINATION_AVAILABILITY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_VACCINATION_AVAILABILITY
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.VWS_VACCINATION_AVAILABILITY(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_VACCINATION_AVAILABILITY]),
    [DATE_START] DATE NULL,
    [DATE_END] DATE NULL,
    [DATE_START_UNIX] BIGINT NULL,
    [DATE_END_UNIX] BIGINT NULL,
    [AstraZeneca] FLOAT NULL,
    [BioNTech/Pfizer] FLOAT NULL,
    [CureVac] FLOAT NULL,
    [Janssen] FLOAT NULL,
    [Moderna] FLOAT NULL,
    [Sanofi] FLOAT NULL,
    DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);
  

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE NAME='IX_VWS_VACCINATION_AVAILABILITY')
CREATE NONCLUSTERED INDEX IX_VWS_VACCINATION_AVAILABILITY
ON VWSDEST.VWS_VACCINATION_AVAILABILITY([DATE_LAST_INSERTED], DATE_START, DATE_END)
INCLUDE (
    [DATE_START_UNIX],
    [DATE_END_UNIX],
    [AstraZeneca],
    [BioNTech/Pfizer],
    [CureVac],
    [Janssen],
    [Moderna],
    [Sanofi]
);  
GO