-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_VWS_VACCINE_PLANNED]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_VWS_VACCINE_PLANNED
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.VWS_VACCINE_PLANNED
(
    [ID] INT NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSDEST_VWS_VACCINE_PLANNED]),
    DOSES BIGINT NOT NULL,
    DATE_START_UNIX BIGINT NOT NULL,
    DATE_END_UNIX BIGINT NOT NULL,
    DATE_LAST_INSERTED DATETIME DEFAULT GETDATE() NOT NULL
)

CREATE CLUSTERED INDEX [IX_VWS_VACCINE_PLANNED] ON [VWSDEST].[VWS_VACCINE_PLANNED]
(
	[DATE_LAST_INSERTED] DESC
)