-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_ELDERLY_AT_HOME]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_ELDERLY_AT_HOME
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.ELDERLY_AT_HOME(
  [ID] [int] NOT NULL,
	[DATE_OF_REPORT] [datetime] NULL,
	[DATE_OF_REPORT_UNIX] [bigint] NULL,
	[INFECTED_ELDERLY_AT_HOME_DAILY] [int] NULL,
	[INFECTED_ELDERLY_AT_HOME_DAILY_PER_100K] [float] NULL,
	[DECEASED_ELDERLY_AT_HOME_DAILY] [int] NULL,
	[DATE_LAST_INSERTED] [datetime] NULL,
	[DATE_RANGE_START] [datetime] NULL,
	[DATE_OF_REPORTS_LAG] [datetime] NULL,
	[DATE_RANGE_START_LAG] [datetime] NULL,
	[7D_AVERAGE_INFECTED_ELDERLY_AT_HOME_DAILY] [decimal](16, 2) NULL,
	[7D_AVERAGE_INFECTED_ELDERLY_AT_HOME_DAILY_LAG] [decimal](16, 2) NULL,
	[7D_AVERAGE_DECEASED_ELDERLY_AT_HOME_DAILY] [decimal](16, 2) NULL,
	[7D_AVERAGE_DECEASED_ELDERLY_AT_HOME_DAILY_LAG] [decimal](16, 2) NULL
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWSDEST_ELDERLY_AT_HOME')
    CREATE NONCLUSTERED INDEX IX_VWSDEST_ELDERLY_AT_HOME
    ON VWSDEST.ELDERLY_AT_HOME(DATE_LAST_INSERTED, DATE_OF_REPORT);
GO