-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_ESCALATIONLEVELS_PER_REGION]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_ESCALATIONLEVELS_PER_REGION
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.ESCALATIONLEVELS_PER_REGION(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_ESCALATIONLEVELS_PER_REGION]),
	DATE_OF_REPORT DATETIME NULL,
	DATE_OF_REPORT_UNIX BIGINT NULL,
	VRCODE VARCHAR(100) NULL,
	ESCALATION_LEVEL INT NULL,
	DATE_OF_START_VALIDITY DATETIME NULL,
	DATE_OF_END_VALIDITY DATETIME NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE(),
	DATE_LAST_DETERMINED DATETIME NULL,
	[DATUM_VOLGENDE_INSCHALING] DATETIME NULL, [START_METING] DATETIME NULL, [EINDE_METING] DATETIME NULL, [POS_PER_100K_METING]varchar(255) NULL, [ZKH_PER_1000K_METING]varchar(255) NULL

);