-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSDEST_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]),
	DATE_OF_REPORT DATETIME NULL,
    DATE_OF_STATISTICS_WEEK_START DATE NULL,
	DATE_OF_STATISTICS_WEEK_END DATE NULL,
    AGE_GROUP_GROUPED VARCHAR(100) NULL,
    HOSPITAL_ADMISSION_NOTIFICATION INT NULL,
    HOSPITAL_ADMISSION INT NULL,
    IC_ADMISSION_NOTIFICATION INT NULL,
    IC_ADMISSION INT NULL,    
	[HOSPITAL_ADMISSION_PER1M] decimal(19,1) NULL,
	[IC_ADMISSION_PER1M] decimal(19,1) NULL,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP')
    CREATE NONCLUSTERED INDEX IX_DEST_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP
    ON VWSDEST.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP(DATE_LAST_INSERTED, DATE_OF_STATISTICS_WEEK_START);
GO