-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY
  START WITH 1
  INCREMENT BY 1;
GO

 CREATE TABLE VWSDEST.POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]),
	DATE_OF_REPORT DATETIME NULL,
	DATE_OF_REPORT_UNIX BIGINT NULL,
	MUNICIPALITY_CODE VARCHAR(100) NULL,
	MUNICIPALITY_NAME VARCHAR(200) NULL,
	INFECTED_DAILY_TOTAL INT NULL,
	INFECTED_DAILY_INCREASE DECIMAL(16,1) NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE(),
	[DATE_RANGE_START] datetime,
	[DATE_OF_REPORTS_LAG] datetime,
	[DATE_RANGE_START_LAG] datetime,
	[7D_AVERAGE_INFECTED_DAILY_INCREASE_TOTAL] decimal (16,2),
    [7D_AVERAGE_INFECTED_DAILY_INCREASE_LAG] decimal (16,2),
	[7D_AVERAGE_INFECTED_DAILY_INCREASE_ABSOLUTE] decimal (16,2)
 );

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY_DOR')
CREATE NONCLUSTERED INDEX IX_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY_DOR
      ON VWSDEST.POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY (DATE_OF_REPORT)
      INCLUDE(MUNICIPALITY_CODE, DATE_LAST_INSERTED);
GO