-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_REPRODUCTION_NUMBER]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_REPRODUCTION_NUMBER
  START WITH 1
  INCREMENT BY 1;
GO

 CREATE TABLE VWSDEST.REPRODUCTION_NUMBER(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_REPRODUCTION_NUMBER]),
	DATE_OF_REPORT DATETIME NULL,
	DATE_OF_REPORT_UNIX BIGINT NULL,
	REPRODUCTION_INDEX_LOW DECIMAL(16,4) NULL,
	REPRODUCTION_INDEX_AVG DECIMAL(16,4) NULL,
	REPRODUCTION_INDEX_HIGH DECIMAL(16,4) NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
 );