-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP_OVER_TIME]') AND type = 'SO')
CREATE SEQUENCE SEQ_POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP_OVER_TIME
  START WITH 1
  INCREMENT BY 1;
GO


CREATE TABLE [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP_OVER_TIME](
  [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP_OVER_TIME]),
	[AGEGROUP] [varchar](100) NULL,
	[DATE] [datetime] NULL,
	[DATE_UNIX] [bigint] NULL,
	[CASES_7D_MOVING_AVERAGE] [decimal](38, 6) NULL,
	[CASES_7D_MOVING_AVERAGE_100K] [numeric](38, 6) NULL,
	[CASES] [int] NULL,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP_OVER_TIME
ON VWSDEST.POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP_OVER_TIME (DATE_LAST_INSERTED, DATE_UNIX)
