-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_GGD_TESTED_PEOPLE_NL]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_GGD_TESTED_PEOPLE_NL
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.GGD_TESTED_PEOPLE_NL(
       [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_GGD_TESTED_PEOPLE_NL])
      ,[DATE_OF_STATISTICS] DATETIME
      ,[DATE_RANGE_START] DATETIME NULL
      ,DATE_OF_STATISTICS_LAG DATETIME NULL
      ,DATE_RANGE_START_LAG DATETIME NULL
      ,NEW_DATE_OF_REPORT_UNIX BIGINT
      ,DATE_RANGE_START_UNIX BIGINT NULL
      ,OLD_DATE_OF_REPORT_UNIX BIGINT NULL
--      ,[REGION_CODE] VARCHAR(100) NULL
--      ,[REGION_NAME] VARCHAR(100) NULL
      ,TESTS INT NULL
      ,POSITIVE_TESTS INT NULL
      ,[PERCENTAGE_POSITIVE] DECIMAL(16, 1) NULL
      ,[7D_AVERAGE_TESTS] INT NULL
      ,[7D_AVERAGE_TESTS_LAG] INT NULL
      ,[7D_AVERAGE_TESTS_DIFF] INT NULL
      ,[7D_AVERAGE_POSITIVE_TESTS] INT NULL
      ,[7D_AVERAGE_POSITIVE_TESTS_LAG] INT NULL
      ,[7D_AVERAGE_POSITIVE_TESTS_DIFF] INT NULL
      ,[7D_AVERAGE_PERCENTAGE_POSITIVE] DECIMAL(16, 1) NULL
      ,[7D_AVERAGE_PERCENTAGE_POSITIVE_LAG] DECIMAL(16, 1) NULL
      ,[7D_AVERAGE_PERCENTAGE_POSITIVE_DIFF] DECIMAL(16, 1) NULL
      ,DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);

CREATE NONCLUSTERED INDEX IX_GGD_TESTED_PEOPLE_NL
ON VWSDEST.GGD_TESTED_PEOPLE_NL([DATE_OF_STATISTICS], DATE_OF_STATISTICS_LAG, DATE_LAST_INSERTED)
INCLUDE (
       DATE_RANGE_START
      ,DATE_RANGE_START_LAG
      ,NEW_DATE_OF_REPORT_UNIX
      ,DATE_RANGE_START_UNIX
      ,OLD_DATE_OF_REPORT_UNIX
      ,TESTS
      ,POSITIVE_TESTS
      ,[PERCENTAGE_POSITIVE]
      ,[7D_AVERAGE_TESTS]
      ,[7D_AVERAGE_TESTS_LAG]
      ,[7D_AVERAGE_TESTS_DIFF]
      ,[7D_AVERAGE_POSITIVE_TESTS]
      ,[7D_AVERAGE_POSITIVE_TESTS_LAG]
      ,[7D_AVERAGE_POSITIVE_TESTS_DIFF]
      ,[7D_AVERAGE_PERCENTAGE_POSITIVE]
      ,[7D_AVERAGE_PERCENTAGE_POSITIVE_LAG]
      ,[7D_AVERAGE_PERCENTAGE_POSITIVE_DIFF]
);
