-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_BEHAVIOR_NATIONAL]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_BEHAVIOR_NATIONAL
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE [VWSDEST].[BEHAVIOR_NATIONAL](
  [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_BEHAVIOR_NATIONAL]),
	[DATE_OF_REPORT] [datetime] NULL,
	[NUMBER_OF_PARTICIPANTS] [int] NULL,
	[WASH_HANDS_COMPLIANCE] [int] NULL,
	[WASH_HANDS_COMPLIANCE_TREND] [varchar](10) NULL,
	[KEEP_DISTANCE_COMPLIANCE] [int] NULL,
	[KEEP_DISTANCE_COMPLIANCE_TREND] [varchar](10) NULL,
	[WORK_FROM_HOME_COMPLIANCE] [int] NULL,
	[WORK_FROM_HOME_COMPLIANCE_TREND] [varchar](10) NULL,
	[AVOID_CROWDS_COMPLIANCE] [int] NULL,
	[AVOID_CROWDS_COMPLIANCE_TREND] [varchar](10) NULL,
	[SYMPTOMS_STAY_HOME_COMPLIANCE] [int] NULL,
	[SYMPTOMS_STAY_HOME_COMPLIANCE_TREND] [varchar](10) NULL,
	[SYMPTOMS_GET_TESTED_COMPLIANCE] [int] NULL,
	[SYMPTOMS_GET_TESTED_COMPLIANCE_TREND] [varchar](10) NULL,
	[WEAR_MASK_PUBLIC_INDOORS_COMPLIANCE] [int] NULL,
	[WEAR_MASK_PUBLIC_INDOORS_COMPLIANCE_TREND] [varchar](10) NULL,
	[WEAR_MASK_PUBLIC_TRANSPORT_COMPLIANCE] [int] NULL,
	[WEAR_MASK_PUBLIC_TRANSPORT_COMPLIANCE_TREND] [varchar](10) NULL,
	[SNEEZE_COUGH_ELBOW_COMPLIANCE] [int] NULL,
	[SNEEZE_COUGH_ELBOW_COMPLIANCE_TREND] [varchar](10) NULL,
	[MAX_VISITORS_COMPLIANCE] [int] NULL,
	[MAX_VISITORS_COMPLIANCE_TREND] [varchar](10) NULL,
	[WASH_HANDS_SUPPORT] [int] NULL,
	[WASH_HANDS_SUPPORT_TREND] [varchar](10) NULL,
	[KEEP_DISTANCE_SUPPORT] [int] NULL,
	[KEEP_DISTANCE_SUPPORT_TREND] [varchar](10) NULL,
	[WORK_FROM_HOME_SUPPORT] [int] NULL,
	[WORK_FROM_HOME_SUPPORT_TREND] [varchar](10) NULL,
	[AVOID_CROWDS_SUPPORT] [int] NULL,
	[AVOID_CROWDS_SUPPORT_TREND] [varchar](10) NULL,
	[SYMPTOMS_STAY_HOME_SUPPORT] [int] NULL,
	[SYMPTOMS_STAY_HOME_SUPPORT_TREND] [varchar](10) NULL,
	[SYMPTOMS_GET_TESTED_SUPPORT] [int] NULL,
	[SYMPTOMS_GET_TESTED_SUPPORT_TREND] [varchar](10) NULL,
	[WEAR_MASK_PUBLIC_INDOORS_SUPPORT] [int] NULL,
	[WEAR_MASK_PUBLIC_INDOORS_SUPPORT_TREND] [varchar](10) NULL,
	[WEAR_MASK_PUBLIC_TRANSPORT_SUPPORT] [int] NULL,
	[WEAR_MASK_PUBLIC_TRANSPORT_SUPPORT_TREND] [varchar](10) NULL,
	[SNEEZE_COUGH_ELBOW_SUPPORT] [int] NULL,
	[SNEEZE_COUGH_ELBOW_SUPPORT_TREND] [varchar](10) NULL,
	[MAX_VISITORS_SUPPORT] [int] NULL,
	[MAX_VISITORS_SUPPORT_TREND] [varchar](10) NULL,
	[CURFEW_COMPLIANCE] [int] NULL,
	[CURFEW_COMPLIANCE_TREND] [varchar](10) NULL,
	[CURFEW_SUPPORT] [int] NULL,
	[CURFEW_SUPPORT_TREND] [varchar](10) NULL,
  [DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
)

CREATE NONCLUSTERED INDEX IX_DEST_BEHAVIOR_NATIONAL_DLI
ON VWSDEST.BEHAVIOR_NATIONAL (DATE_LAST_INSERTED)
INCLUDE (DATE_OF_REPORT);