-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_CBS_DECEASED_VR]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_CBS_DECEASED_VR
  START WITH 1
  INCREMENT BY 1;
GO


CREATE TABLE VWSDEST.CBS_DECEASED_VR
(
   [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_CBS_DECEASED_VR])
,   WEEK_START DATETIME NULL
,   WEEK_END DATETIME NULL
,   WEEK_START_UNIX BIGINT NULL
,   WEEK_END_UNIX BIGINT NULL
,   [YEAR] INT NULL
,   [WEEK] INT NULL
,   VRCODE VARCHAR(100) NULL
,   DECEASED_ACTUAL INT NULL
,   DECEASED_FORECAST INT NULL
,   DECEASED_FORECAST_HIGH INT NULL
,   DECEASED_FORECAST_LOW INT NULL
,   [DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWS_VWSDEST_CBS_DECEASED_VR')
    CREATE NONCLUSTERED INDEX IX_VWS_VWSDEST_CBS_DECEASED_VR
    ON VWSDEST.CBS_DECEASED_VR(DATE_LAST_INSERTED, VRCODE)
    INCLUDE (WEEK_START,  WEEK_END, WEEK_START_UNIX, WEEK_END_UNIX, [YEAR], [WEEK], DECEASED_ACTUAL, 
              DECEASED_FORECAST, DECEASED_FORECAST_LOW, DECEASED_FORECAST_HIGH);
GO
