-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_NICE_HOSPITAL_GM_BASE]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_NICE_HOSPITAL_GM_BASE
START WITH 1
INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.NICE_HOSPITAL_GM_BASE(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_NICE_HOSPITAL_GM_BASE]),
    DATE_OF_REPORT DATETIME NULL,
    NEW_DATE_OF_REPORT_UNIX BIGINT,
    GMCODE VARCHAR(100) NULL,
    OLD_DATE_OF_REPORT_UNIX BIGINT NULL,
    OLD_VALUE DECIMAL(16,2) NULL,
    DIFFERENCE DECIMAL(16,2) NULL,
    [OLD_VALUE_REPORTED] [int] NULL,
	[DIFFERENCE_REPORTED] [int] NULL,
    DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
)

CREATE NONCLUSTERED INDEX IX_NICE_HOSPITAL_GM_BASE
ON VWSDEST.NICE_HOSPITAL_GM_BASE(DATE_OF_REPORT, DATE_LAST_INSERTED, GMCODE)
INCLUDE (DIFFERENCE, OLD_VALUE);