-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_VACCINE_DELIVERIES]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_VACCINE_DELIVERIES
  START WITH 1
  INCREMENT BY 1;
GO


CREATE TABLE VWSDEST.VWS_VACCINE_DELIVERIES
(
   [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_VACCINE_DELIVERIES])
  ,[DATE_FIRST_DAY]   DATETIME NULL
  ,DATE_START_UNIX    BIGINT NULL
  ,DATE_END_UNIX      BIGINT NULL
  ,[VALUE_TYPE]       VARCHAR(100) NULL
  ,[REPORT_STATUS]    VARCHAR(100) NULL
  ,[VALUE]            BIGINT NULL
  ,[DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
  ,DATE_OF_REPORT_UNIX BIGINT
);

CREATE NONCLUSTERED INDEX IX_DEST_VWS_VACCINE_DELIVERIES
ON VWSDEST.VWS_VACCINE_DELIVERIES (DATE_LAST_INSERTED)
INCLUDE (
       [DATE_FIRST_DAY]
      ,DATE_START_UNIX 
      ,DATE_END_UNIX   
      ,[VALUE_TYPE]
      ,[REPORT_STATUS]
      ,[VALUE]
  );
