-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_VACCINE_DELIVERIES_WEEKLY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_VACCINE_DELIVERIES_WEEKLY
  START WITH 1
  INCREMENT BY 1;
GO


CREATE TABLE VWSDEST.VWS_VACCINE_DELIVERIES_WEEKLY
(
   [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_VACCINE_DELIVERIES_WEEKLY])
  ,[DATE_FIRST_DAY]   DATETIME NULL
  ,DATE_OF_REPORT     DATETIME NULL
  ,DATE_START_UNIX    BIGINT NULL
  ,DATE_END_UNIX      BIGINT NULL
  ,[VALUE_TYPE]       VARCHAR(100) NULL
  ,[REPORT_STATUS]    VARCHAR(100) NULL
  ,[AstraZeneca]      BIGINT NULL
  ,[BioNTech/Pfizer]  BIGINT NULL
  ,[CureVac]          BIGINT NULL
  ,[Janssen]          BIGINT NULL
  ,[Moderna]          BIGINT NULL
  ,[Sanofi]           BIGINT NULL
  ,TOTAL_VALUE        BIGINT NULL
  ,[DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);

CREATE NONCLUSTERED INDEX IX_DEST_VWS_VACCINE_DELIVERIES_WEEKLY
ON VWSDEST.VWS_VACCINE_DELIVERIES_WEEKLY (DATE_LAST_INSERTED,[VALUE_TYPE],[REPORT_STATUS])
INCLUDE (
   [DATE_FIRST_DAY]
  ,DATE_OF_REPORT 
  ,DATE_START_UNIX
  ,DATE_END_UNIX
  ,[AstraZeneca]    
  ,[BioNTech/Pfizer]
  ,[CureVac]        
  ,[Janssen]        
  ,[Moderna]        
  ,[Sanofi]         
  ,TOTAL_VALUE
  );
