-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_INFECTIOUS_PEOPLE]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_INFECTIOUS_PEOPLE
  START WITH 1
  INCREMENT BY 1;
GO

 CREATE TABLE VWSDEST.INFECTIOUS_PEOPLE(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_INFECTIOUS_PEOPLE]),
	DATE_OF_REPORT DATETIME NULL,
	DATE_OF_REPORT_UNIX BIGINT NULL,
	INFECTIOUS_LOW INT NULL,
	INFECTIOUS_LOW_NORMALIZED DECIMAL(16,1) NULL,
	INFECTIOUS_AVG INT NULL,
	INFECTIOUS_AVG_NORMALIZED DECIMAL(16,1) NULL,
	INFECTIOUS_HIGH INT NULL,
	INFECTIOUS_HIGH_NORMALIZED DECIMAL(16,1) NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
 );