-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordination for more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_SEWER_MEASUREMENTS_PER_RWZI_2021]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_SEWER_MEASUREMENTS_PER_RWZI_2021
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.SEWER_MEASUREMENTS_PER_RWZI (
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SEWER_MEASUREMENTS_PER_RWZI_2021]),
	[DATE_MEASUREMENT] DATETIME,
	[DATE_MEASUREMENT_UNIX] BIGINT NULL,
	[WEEK] INT NULL,
	[RWZI_AWZI_CODE] VARCHAR(100) NULL,
	[RWZI_AWZI_NAME] VARCHAR(100) NULL,
	RNA_FLOW_PER_100000 DECIMAL(16,2) NULL,
	AVERAGE_RNA_FLOW_PER_100000 DECIMAL(16,2) NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);