-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_HOSPITAL_BED_OCCUPANCY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_HOSPITAL_BED_OCCUPANCY
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.HOSPITAL_BED_OCCUPANCY(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_HOSPITAL_BED_OCCUPANCY]),
    [DATE_OF_REPORT] DATETIME NULL,
	[DATE_OF_REPORT_UNIX] BIGINT NULL,
    [IC_BEDS_OCCUPIED_COVID] INT NULL,
    [IC_BEDS_OCCUPIED_NON_COVID] INT NULL,
    [IC_BEDS_OCCUPIED_COVID_PERCENTAGE] DECIMAL(16, 2) NULL,
    [NON_IC_BEDS_OCCUPIED_COVID] INT NULL,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);