-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_RIVM_DECEASED_DAILY_PER_MUNICIPALITY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_RIVM_DECEASED_DAILY_PER_MUNICIPALITY
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.RIVM_DECEASED_DAILY_PER_MUNICIPALITY(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_RIVM_DECEASED_DAILY_PER_MUNICIPALITY])
,   [DATE_OF_REPORT] DATETIME NULL
,   [DATE_OF_REPORT_UNIX] BIGINT NULL
,   [MUNICIPALITY_CODE] VARCHAR(10)
,	[OLD_DATE_OF_REPORT] DATETIME NULL
,   [OLD_DATE_OF_REPORT_UNIX] BIGINT NULL
,	[OLD_VALUE]  INT NULL
,   [DIFFERENCE] INT NULL
,   [DECEASED_ACTUAL] INT NULL
,   [DECEASED_CUMULATIVE] INT NULL
,   [DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);

CREATE NONCLUSTERED INDEX IX_DEST_RIVM_DECEASED_DAILY_PER_MUNICIPALITY
ON VWSDEST.RIVM_DECEASED_DAILY_PER_MUNICIPALITY (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE (DATE_OF_REPORT_UNIX, DECEASED_ACTUAL, DECEASED_CUMULATIVE, MUNICIPALITY_CODE );