-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_NURSING_HOMES_TOTALS]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_NURSING_HOMES_TOTALS
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.NURSING_HOMES_TOTALS(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSDEST_NURSING_HOMES_TOTALS]),
	DATE_OF_REPORT DATETIME NULL,
	DATE_OF_REPORT_UNIX BIGINT NULL,
	INFECTED_NURSERY_DAILY INT NULL,
	DECEASED_NURSERY_DAILY INT NULL,
	TOTAL_NEW_REPORTED_LOCATIONS INT NULL,
	TOTAL_REPORTED_LOCATIONS INT NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
 );