-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_RESTRICTIONS_PER_REGION]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_RESTRICTIONS_PER_REGION
  START WITH 1
  INCREMENT BY 1;
GO

 CREATE TABLE VWSDEST.RESTRICTIONS_PER_REGION(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_RESTRICTIONS_PER_REGION]),
	VRCODE VARCHAR(100) NULL,
	RESTRICTION_ID VARCHAR(100) NULL,
	TARGET_REGION VARCHAR(100) NULL,
	ESCALATION_LEVEL INT NULL,
	CATEGORY_ID VARCHAR(100) NULL,
	RESTRICTION_ORDER INT NULL,
	VALID_FROM DATETIME NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
 );

CREATE NONCLUSTERED INDEX IX_RESTRICTIONS_PER_REGION_DEST
ON VWSDEST.RESTRICTIONS_PER_REGION(DATE_LAST_INSERTED, VRCODE);