-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_NICE_HOSPITAL_GM]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_NICE_HOSPITAL_GM
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.NICE_HOSPITAL_GM(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_NICE_HOSPITAL_GM]),
	DATE_OF_STATISTICS DATETIME NULL,
	GM_CODE VARCHAR(100) NULL,
	GM_NAME VARCHAR(100) NULL,
	REPORTED INT NULL,
	HOSPITALIZED INT NULL,
	HOSPITALIZED_3D_AVG DECIMAL(16,2) NULL,
	REPORTED_3D_AVG DECIMAL(16,2) NULL,
	OLD_VALUE_REPORTED INT,
	DIFFERENCE_REPORTED INT,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE(),
	REPORTED_PER_MIL_LAST_WEEK INT NULL,
	WEEK_START DATETIME NULL
);

CREATE NONCLUSTERED INDEX IX_NICE_HOSPITAL_GM_DEST
ON VWSDEST.NICE_HOSPITAL_GM(DATE_OF_STATISTICS, DATE_LAST_INSERTED, GM_CODE)
INCLUDE (HOSPITALIZED,HOSPITALIZED_3D_AVG);