-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_SEWER_BASE]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_SEWER_BASE
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.SEWER_BASE_ARCHIVE(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SEWER_BASE]),
	[WEEK] INT NULL,
	[WEEK_UNIX] BIGINT NULL,
  DATE_MEASUREMENT DATETIME NULL,
  RWZI_AWZI_CODE INT NULL,
  RWZI_AWZI_NAME VARCHAR(100) NULL,
  X_COORDINATE DECIMAL(16,2) NULL,
  Y_COORDINATE DECIMAL(16,2) NULL,
  POSTAL_CODE VARCHAR(100) NULL,
  SECURITY_REGION_CODE VARCHAR(100) NULL,
  GM_CODE VARCHAR(100) NULL,
  RNA_PER_ML BIGINT,
  RNA_FLOW_PER_100000 BIGINT NULL,
  PERCENTAGE_IN_SECURITY_REGION FLOAT NULL,
  REPRESENTATIVE_MEASUREMENT INT NULL,
  RANK_PERCENTAGE_IN_SECURITY_REGION INT NULL,
  COUNT_DAILY_MEASUREMENT INT NULL,
  DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);