-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_VACCINE_DELIVERIES_TIMESPAN_EST]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_VACCINE_DELIVERIES_TIMESPAN_EST
  START WITH 1
  INCREMENT BY 1;
GO


CREATE TABLE VWSDEST.VWS_VACCINE_DELIVERIES_TIMESPAN_EST
(
   [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_VACCINE_DELIVERIES_TIMESPAN_EST])
  ,[TIMESPAN_WEEKS]   BIGINT NULL
  ,[DOSES]            BIGINT NULL
  ,[DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);

CREATE NONCLUSTERED INDEX IX_DEST_VWS_VACCINE_DELIVERIES_TIMESPAN_EST
ON VWSDEST.VWS_VACCINE_DELIVERIES_TIMESPAN_EST (DATE_LAST_INSERTED)
INCLUDE (
   [TIMESPAN_WEEKS]
  ,[DOSES]
  );
