-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_ELDERLY_AT_HOME_VR]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_ELDERLY_AT_HOME_VR
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.ELDERLY_AT_HOME_VR(
  [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_ELDERLY_AT_HOME_VR]),
  [DATE_OF_REPORT] DATETIME NULL,
  [DATE_OF_REPORT_UNIX] BIGINT NULL,
  [VRCODE] VARCHAR(100) NULL,
  [INFECTED_ELDERLY_AT_HOME_DAILY] INT NULL,
  [INFECTED_ELDERLY_AT_HOME_DAILY_PER_100K] FLOAT NULL,
  [DECEASED_ELDERLY_AT_HOME_DAILY] INT NULL,
  [DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWSDEST_ELDERLY_AT_HOME_VR')
    CREATE NONCLUSTERED INDEX IX_VWSDEST_ELDERLY_AT_HOME_VR
    ON VWSDEST.ELDERLY_AT_HOME_VR(DATE_LAST_INSERTED, DATE_OF_REPORT);
GO