-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Production table for results of infected and hospital numbers per region

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_ESCALATIONLEVELS_PER_REGION]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_ESCALATIONLEVELS_PER_REGION
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.ESCALATIONLEVELS_PER_REGION(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_ESCALATIONLEVELS_PER_REGION]),
	DATE_OF_REPORT DATETIME NULL,
	DATE_OF_REPORT_UNIX BIGINT NULL,
	VRCODE VARCHAR(100) NULL,
	ESCALATION_LEVEL INT NULL,
	DATE_OF_START_VALIDITY DATETIME NULL,
	DATE_OF_END_VALIDITY DATETIME NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);

CREATE NONCLUSTERED INDEX IX_ESCALATIONLEVELS_PER_REGION_DEST
ON VWSDEST.ESCALATIONLEVELS_PER_REGION(DATE_LAST_INSERTED);