-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Production table for results of infected and hospital numbers per region

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSDEST_SUSPICIONS_GENERAL_PRACTITIONERS]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSDEST_SUSPICIONS_GENERAL_PRACTITIONERS
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSDEST.SUSPICIONS_GENERAL_PRACTITIONERS(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SUSPICIONS_GENERAL_PRACTITIONERS]),
	[DIAGNOSE] [varchar](100) NULL,
	[JAAR] INT NULL,
	[WEEK] INT NULL,
	[WEEK_UNIX] BIGINT NULL,
	[INCIDENTIE] DECIMAL(16,2) NULL,
	[BOVENGRENS] INT NULL,
	[GESCHAT_AANTAL] INT NULL,
	[ONDERGRENS] INT NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);