-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_CBS_DECEASED_VR]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_CBS_DECEASED_VR
  START WITH 1
  INCREMENT BY 1;
GO


CREATE TABLE VWSINTER.CBS_DECEASED_VR(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSINTER_CBS_DECEASED_VR]) ,
    [YEAR] INT NULL ,
    [WEEK] INT NULL , 
    [REGIOS] VARCHAR(100) NULL ,
    [DECEASED_ACTUAL] INT NULL ,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWS_VWSINTER_CBS_DECEASED_VR')
    CREATE NONCLUSTERED INDEX IX_VWS_VWSINTER_CBS_DECEASED_VR
    ON VWSINTER.CBS_DECEASED_VR(DATE_LAST_INSERTED)
    INCLUDE ([YEAR], [WEEK], REGIOS, DECEASED_ACTUAL);
GO
