-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_VACCINATION_AVAILABILITY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_VACCINATION_AVAILABILITY
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.VWS_VACCINATION_AVAILABILITY(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_VACCINATION_AVAILABILITY])
   ,[VALID_FROM] DATETIME NULL
   ,[VACCIN_NAME] VARCHAR(100) NULL
   ,[EXPECTED_OR_OPTIONS] VARCHAR(100) NULL
   ,[DATE_DELIVERY] DATETIME NULL
   ,[AMOUNT_DELIVERY] FLOAT NULL
   ,DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWS_VACCINATION_AVAILABILITY_INTER')
    CREATE NONCLUSTERED INDEX IX_VWS_VACCINATION_AVAILABILITY_INTER
    ON VWSINTER.VWS_VACCINATION_AVAILABILITY(DATE_LAST_INSERTED, VALID_FROM)
    INCLUDE (DATE_DELIVERY,AMOUNT_DELIVERY);
GO
