-- Copyright (c) 2021 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSINTER_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]),
	[VERSION] VARCHAR(100) NULL,
	[DATE_OF_REPORT] DATETIME NULL,
	[DATE_OF_STATISTICS_WEEK_START] DATE NULL,
	[AGE_GROUP] VARCHAR(100) NULL,
	[HOSPITAL_ADMISSION_NOTIFICATION] INT NULL,
	[HOSPITAL_ADMISSION] INT NULL,
	[IC_ADMISSION_NOTIFICATION] INT NULL,
	[IC_ADMISSION] INT NULL,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()    
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP
    ON VWSINTER.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP(DATE_LAST_INSERTED, DATE_OF_STATISTICS_WEEK_START);
GO
