-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_RIVM_COVID_19_CASE_NATIONAL]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_RIVM_COVID_19_CASE_NATIONAL
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.RIVM_COVID_19_CASE_NATIONAL(
	[ID] INT PRIMARY KEY NONCLUSTERED NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_COVID_19_CASE_NATIONAL]),
	DATE_FILE DATETIME NULL,
	DATE_STATISTICS DATETIME NULL,
	DATE_STATISTICS_TYPE VARCHAR(100) NULL,
	AGEGROUP VARCHAR(100) NULL,
	SEX VARCHAR(100) NULL,
	PROVINCE VARCHAR(100) NULL,
	HOSPITAL_ADMISSION VARCHAR(100) NULL,
	DECEASED VARCHAR(100) NULL,
	WEEK_OF_DEATH VARCHAR(100) NULL,
	MUNICIPAL_HEALTH_SERVICE VARCHAR(100) NULL,
	DATE_LAST_INSERTED DATETIME NULL DEFAULT (GETDATE())
);