-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_GGD_TESTED_PEOPLE]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_GGD_TESTED_PEOPLE
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.GGD_TESTED_PEOPLE(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_GGD_TESTED_PEOPLE]),
	[VERSION] BIGINT NULL,
	DATE_OF_REPORT DATETIME NULL,
	DATE_OF_STATISTICS DATETIME NULL,
	SECURITY_REGION_CODE VARCHAR(100) NULL,
	SECURITY_REGION_NAME VARCHAR(100) NULL,
	TESTED_WITH_RESULT BIGINT NULL,
	TESTED_POSITIVE BIGINT NULL,
	[DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_GGD_TESTED_PEOPLE_INTER')
    CREATE NONCLUSTERED INDEX IX_GGD_TESTED_PEOPLE_INTER
    ON VWSINTER.GGD_TESTED_PEOPLE(DATE_LAST_INSERTED);
GO
