-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_VWS_BEHAVIOR]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_VWS_BEHAVIOR
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.VWS_BEHAVIOR(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_VWS_BEHAVIOR]),
    [DATE_OF_REPORT] DATETIME NULL,
    [DATE_OF_MEASUREMENT] DATETIME NULL,
    [WAVE] INT NULL,
    [REGION_CODE] VARCHAR(100) NULL,
    [REGION_NAME] VARCHAR(100) NULL,
    [SUBGROUP_CATEGORY] VARCHAR(100) NULL,
    [SUBGROUP] VARCHAR(100) NULL,
    [INDICATOR_CATEGORY] VARCHAR(100) NULL,
    [INDICATOR] VARCHAR(100) NULL,
    [SAMPLE_SIZE] INT NULL,
    [FIGURE_TYPE] VARCHAR(100) NULL,
    [VALUE] DECIMAL(16,2) NULL,
    [LOWER_LIMIT] DECIMAL(16,2) NULL,
    [UPPER_LIMIT] DECIMAL(16,2) NULL,
    [CHANGE_WRT_PREVIOUS_MEASUREMENT] INT NULL,
    [DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);

CREATE NONCLUSTERED INDEX IX_INTER_VWS_BEHAVIOR_DLI_DOM
ON VWSINTER.VWS_BEHAVIOR (DATE_LAST_INSERTED, DATE_OF_MEASUREMENT)
INCLUDE (INDICATOR, REGION_CODE, SUBGROUP);