-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.



IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_VACC_DELIVER_ADMIN]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_VACC_DELIVER_ADMIN
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.VWS_VACCINE_DELIVERIES_ADMINISTERED(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSINTER_VACC_DELIVER_ADMIN]),
    DATE_OF_REPORT DATETIME NULL,
    DATE_FIRST_DAY DATETIME NULL,
    VALUE_TYPE VARCHAR(100) NULL,
    VALUE_NAME VARCHAR(100) NULL,
    REPORT_STATUS VARCHAR(100) NULL,
    [VALUE] BIGINT NULL,
	  [DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWS_VACCINE_DELIVERIES_ADMINISTERED_INTER')
    CREATE NONCLUSTERED INDEX IX_VWS_VACCINE_DELIVERIES_ADMINISTERED_INTER
    ON VWSINTER.VWS_VACCINE_DELIVERIES_ADMINISTERED(DATE_LAST_INSERTED)
    INCLUDE (DATE_OF_REPORT, DATE_FIRST_DAY, VALUE_TYPE, VALUE_NAME, REPORT_STATUS, [VALUE]);
GO