-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_RIVM_SEWER_MEASUREMENTS_2021]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_RIVM_SEWER_MEASUREMENTS_2021
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.RIVM_SEWER_MEASUREMENTS(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_SEWER_MEASUREMENTS_2021]),
	DATE_MEASUREMENT DATETIME,
	VERSION VARCHAR(100) NULL,
	RWZI_AWZI_CODE BIGINT,
	RWZI_AWZI_NAME VARCHAR(100) NULL,
	RNA_PER_ML BIGINT,
	RNA_FLOW_PER_100000 BIGINT,
	[DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);