-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_DISABILITY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_DISABILITY
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.DISABILITY(
  [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_DISABILITY]),
  [DATE_OF_REPORT] DATETIME NULL,
  [DATE_OF_STATISTIC_REPORTED] DATETIME NULL,
  [SECURITY_REGION_CODE] VARCHAR(100) NULL,
  [TOTAL_CASES_REPORTED] INT NULL,
  [TOTAL_DECEASED_REPORTED] INT NULL,
  [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED] INT NULL,
  [TOTAL_INFECTED_LOCATIONS_REPORTED] INT NULL,
  [DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);