-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_LNAZ_HOSPITAL_BED_OCCUPANCY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_LNAZ_HOSPITAL_BED_OCCUPANCY
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.LNAZ_HOSPITAL_BED_OCCUPANCY(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_LNAZ_HOSPITAL_BED_OCCUPANCY]),
    [DATUM] DATETIME NULL,
    [IC_BEDDEN_COVID] INT NULL,
    [IC_BEDDEN_NON_COVID] INT NULL,
    [KLINIEK_BEDDEN] INT NULL,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);