-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_CBS_DECEASED_VR_FORECAST]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_CBS_DECEASED_VR_FORECAST
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.CBS_DECEASED_VR_FORECAST(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSINTER_CBS_DECEASED_VR_FORECAST]) ,
    [YEAR] INT NULL,
    [WEEK] INT NULL,
    [DECEASED_FORECAST] INT NULL,
    [DECEASED_FORECAST_LOW] INT NULL,
    [DECEASED_FORECAST_HIGH] INT NULL,
    [VRNAME] VARCHAR(100),
    [VRCODE] VARCHAR(100),
	  [DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWS_VWSINTER_CBS_DECEASED_VR_FORECAST')
    CREATE NONCLUSTERED INDEX IX_VWS_VWSINTER_CBS_DECEASED_VR_FORECAST
    ON VWSINTER.CBS_DECEASED_VR_FORECAST(DATE_LAST_INSERTED)
    INCLUDE ([YEAR], [WEEK], DECEASED_FORECAST, DECEASED_FORECAST_LOW, DECEASED_FORECAST_HIGH, VRNAME, VRCODE);
GO
