-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Intermediate table for nursery cases from RIVM

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_RIVM_NURSING_HOMES_INTAKE]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_RIVM_NURSING_HOMES_INTAKE
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.RIVM_NURSING_HOMES_INTAKE(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_NURSING_HOMES_INTAKE]),
	DATE_OF_REPORT DATETIME NULL,
	TOTAL_NEW_REPORTED_LOCATIONS INT NULL,
	TOTAL_REPORTED_LOCATIONS INT NULL,
	TOTAL_REPORTED_NURSING_HOMES INT NULL,
	DECEASED_NURSING_HOMES INT NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);

