-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSINTER_RIVM_NURSING_HOMES_DECEASED_PER_REGION]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSINTER_RIVM_NURSING_HOMES_DECEASED_PER_REGION
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSINTER.RIVM_NURSING_HOMES_DECEASED_PER_REGION(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_NURSING_HOMES_DECEASED_PER_REGION]),
  VEILIGHEIDSREGIOCODE VARCHAR(100) NULL,
  VEILIGHEIDSREGIONAAM VARCHAR(100) NULL,
	DATUM_VAN_OVERLIJDEN DATETIME NULL,
  AANTAL INT NULL,
	[DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);