# Required Azure Pipelines Tasks: https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens

parameters:
  ENVIRONMENT:
    required: true
    description: "Available values: 'development', 'acceptance', 'production'"
  AZURE_RM_SERVICE_PRINCIPAL_NAME:
    required: true
    description: "Name of the Azure Service Prinicpal"
  WORKING_DIRECTORY:
    required: true

jobs:
  - deployment: ${{ parameters.ENVIRONMENT }}
    environment: ${{ parameters.ENVIRONMENT }}-BusinessLogic
    variables:
      - group: "business-logic-${{ parameters.environment }}-vg"
    strategy:
      runOnce:
        deploy:
          steps:
          
            - checkout: none

            - bash: |
                echo $(Build.SourceBranch)
                echo $(Build.Reason)

            # Replace Tokens
            - task: replacetokens@5
              displayName: 'Task 1: Replace Tokens'
              inputs:
                rootDirectory: ${{ parameters.WORKING_DIRECTORY }}/src
                targetFiles: '**/*.sql'
                encoding: 'auto'
                tokenPattern: 'custom'
                tokenPrefix: '#{'
                tokenSuffix: '}#'
                writeBOM: false
                actionOnMissing: 'error' # warn is also possible
                keepToken: true
                actionOnNoFiles: 'continue'
                enableTransforms: false
                enableRecursion: false
                useLegacyPattern: false
                enableTelemetry: true
        
            # Execute Scripts
            - task: AzurePowerShell@5
              displayName: 'Task 2: Execute Scripts'
              inputs:
                azureSubscription: '${{ parameters.AZURE_RM_SERVICE_PRINCIPAL_NAME }}'
                ScriptType: 'InlineScript'
                Inline: |
                  & "./.devops/scripts/release-script.ps1" `
                      -Server "$(AZURE_SQL_SERVER_NAME)" `
                      -Database "$(AZURE_SQL_DATABASE_NAME)" `
                      -SourceDirectory "./src" `
                      -Password "$(AZURE_SQL_DATABASE_LOGIN_PASSWORD)" `
                      -Username "$(AZURE_SQL_DATABASE_LOGIN_USERNAME)"
                FailOnStandardError: true
                azurePowerShellVersion: 'LatestVersion'
                pwsh: true
                workingDirectory: ${{ parameters.WORKING_DIRECTORY }}
                
            # Post Deploy
            - script: | 
                rm -rfv ${{ parameters.WORKING_DIRECTORY }}
              displayName: "Task 3: Post Deploy"
              condition: always()