-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Move data Nursery data from intermediate to destination table.
CREATE OR ALTER PROCEDURE DBO.SP_NURSING_HOME_TOTALS
AS
BEGIN
    INSERT INTO VWSDEST.NURSING_HOMES_TOTALS
        (DATE_OF_REPORT,
        DATE_OF_REPORT_UNIX,
        INFECTED_NURSERY_DAILY,
	    DECEASED_NURSERY_DAILY,
        TOTAL_NEW_REPORTED_LOCATIONS,
        TOTAL_REPORTED_LOCATIONS)
    SELECT 
        DATE_OF_REPORT,
        dbo.CONVERT_DATETIME_TO_UNIX(DATE_OF_REPORT),
        TOTAL_REPORTED_NURSING_HOMES ,
        DECEASED_NURSING_HOMES,
        TOTAL_NEW_REPORTED_LOCATIONS,
        TOTAL_REPORTED_LOCATIONS
    FROM 
       VWSINTER.RIVM_NURSING_HOMES_INTAKE
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from VWSINTER.RIVM_NURSING_HOME_INTAKE)
    AND DATE_OF_REPORT > '1900-01-01 00:00:00.000'
END;