-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Move sewer measurements data from staging to intermediate table.
CREATE OR ALTER PROCEDURE [dbo].[SP_RIVM_SEWER_MEASUREMENTS_INTER]
AS
BEGIN
    INSERT INTO VWSINTER.RIVM_SEWER_MEASUREMENTS (
            DATE_MEASUREMENT
        ,   RWZI_AWZI_CODE
        ,   RWZI_AWZI_NAME
        ,   X_COORDINATE
        ,   Y_COORDINATE
        ,   POSTAL_CODE
        ,   SECURITY_REGION_CODE
        ,   SECURITY_REGION_NAME
        ,   PERCENTAGE_IN_SECURITY_REGION
        ,   RNA_PER_ML
        ,   REPRESENTATIVE_MEASUREMENT)
    SELECT 
            CONVERT(DATETIME, DATE_MEASUREMENT,101) AS DATE_MEASUREMENT
        ,   RWZI_AWZI_CODE
        ,   RWZI_AWZI_NAME
        ,   (SELECT CONVERT(DECIMAL(16, 2), ISNULL(NULLIF(X_COORDINATE, ''), '0'))) as X_COORDINATE
        ,   (SELECT CONVERT(DECIMAL(16, 2), ISNULL(NULLIF(Y_COORDINATE, ''), '0'))) as Y_COORDINATE
        ,   POSTAL_CODE
        ,   SECURITY_REGION_CODE
        ,   SECURITY_REGION_NAME
        ,   CAST (REPLACE(ISNULL(NULLIF(PERCENTAGE_IN_SECURITY_REGION, ''), '0'), ',', '.') AS FLOAT) AS PERCENTAGE_IN_SECURITY_REGION
        ,   (SELECT CONVERT(BIGINT, ISNULL(NULLIF(RNA_PER_ML, ''), '0'))) as RNA_PER_ML
        ,   (SELECT CAST(ISNULL(NULLIF(REPRESENTATIVE_MEASUREMENT, ''), 'FALSE') AS BIT)) AS REPRESENTATIVE_MEASUREMENT
    FROM 
       VWSSTAGE.RIVM_SEWER_MEASUREMENTS
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from VWSSTAGE.RIVM_SEWER_MEASUREMENTS)
END;