CREATE TABLE [VWSSTAGE].[CBS_DECEASED_VR_FORECAST] (
    [ID]                         INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_CBS_DECEASED_VR_FORECAST]) NOT NULL,
    [WEEK]                       VARCHAR (100) NULL,
    [SEIZOENSPATROON MET MARGES] VARCHAR (100) NULL,
    [ONDERGRENS]                 VARCHAR (100) NULL,
    [BOVENGRENS]                 VARCHAR (100) NULL,
    [VR NAAM]                    VARCHAR (100) NULL,
    [VR CODE]                    VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]         DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_VWSSTAGE_CBS_DECEASED_VR_FORECAST]
    ON [VWSSTAGE].[CBS_DECEASED_VR_FORECAST]([DATE_LAST_INSERTED] ASC)
    INCLUDE([WEEK], [SEIZOENSPATROON MET MARGES], [ONDERGRENS], [BOVENGRENS], [VR NAAM], [VR CODE]);

