CREATE TABLE [VWSSTAGE].[CBS_DECEASED_PER_WEEK] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CBS_DECEASED_PER_WEEK]) NOT NULL,
    [PERIODEN]           VARCHAR (100) NULL,
    [OVERLEDENEN_1]      VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_CBS_DECEASED_PER_WEEK_DLI]
    ON [VWSSTAGE].[CBS_DECEASED_PER_WEEK]([DATE_LAST_INSERTED] ASC)
    INCLUDE([PERIODEN], [OVERLEDENEN_1]);


GO
CREATE NONCLUSTERED INDEX [IX_DLI_CBS_DECEASED_PER_WEEK]
    ON [VWSSTAGE].[CBS_DECEASED_PER_WEEK]([DATE_LAST_INSERTED] ASC);

