CREATE TABLE [VWSSTAGE].[CBS_DECEASED_VR] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_CBS_DECEASED_VR]) NOT NULL,
    [PERIODEN]           VARCHAR (100) NULL,
    [REGIOS]             VARCHAR (100) NULL,
    [OVERLEDENEN_1]      VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_VWSSTAGE_CBS_DECEASED_VR]
    ON [VWSSTAGE].[CBS_DECEASED_VR]([DATE_LAST_INSERTED] ASC)
    INCLUDE([PERIODEN], [REGIOS], [OVERLEDENEN_1]);

