CREATE TABLE [VWSSTAGE].[CBS_INHABITANTS_PER_MUNICIPALITY] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CBS_INHABITANTS_PER_MUNICIPALITY]) NOT NULL,
    [REGIOS]             VARCHAR (100) NULL,
    [CODE_1]             VARCHAR (100) NULL,
    [CODE_42]            VARCHAR (100) NULL,
    [NAAM_43]            VARCHAR (100) NULL,
    [INWONERTAL_50]      VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

