CREATE TABLE [VWSSTAGE].[CBS_POPULATION_RWZI_MUTATIONS] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CBS_POPULATION_RWZI_MUTATIONS]) NOT NULL,
    [RWZI_CODE]          VARCHAR (100) NULL,
    [RWZI_NAAM]          VARCHAR (100) NULL,
    [STARTDATUM]         VARCHAR (100) NULL,
    [EINDDATUM]          VARCHAR (100) NULL,
    [INWONERS]           VARCHAR (100) NULL,
    [REGIO_TYPE]         VARCHAR (100) NULL,
    [REGIO_CODE]         VARCHAR (100) NULL,
    [REGIO_NAAM]         VARCHAR (100) NULL,
    [AANDEEL]            VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

