CREATE TABLE [VWSSTAGE].[CBS_DECEASED_PER_WEEK_FORECAST] (
    [ID]                          INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CBS_DECEASED_PER_WEEK_FORECAST]) NOT NULL,
    [PERIODEN]                    VARCHAR (100) NULL,
    [VERWACHT_AANTAL_OVERLEDENEN] VARCHAR (100) NULL,
    [ONDERGRENS]                  VARCHAR (100) NULL,
    [BOVENGRENS]                  VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]          DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DLI_CBS_DECEASED_PER_WEEK_FORECAST]
    ON [VWSSTAGE].[CBS_DECEASED_PER_WEEK_FORECAST]([DATE_LAST_INSERTED] ASC);

