CREATE TABLE [VWSSTAGE].[CBS_AGEGROUP_MAPPING] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CBS_AGEGROUP_MAPPING]) NOT NULL,
    [KEY]                VARCHAR (100) NULL,
    [TITLE]              VARCHAR (100) NULL,
    [DESCRIPTION]        VARCHAR (100) NULL,
    [CATEGORYGROUPID]    VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

