CREATE TABLE [VWSSTAGE].[CIMS_VACCINATED_AGE_GROUP] (
    [ID]                             INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CIMS_VACCINATED_AGE_GROUP]) NOT NULL,
    [VERSION]                        VARCHAR (100) NULL,
    [DATE_OF_REPORT]                 VARCHAR (100) NULL,
    [DATE_OF_STATISTICS_WEEK_START]  VARCHAR (100) NULL,
    [DATE_OF_STATISTICS_WEEK_END]    VARCHAR (100) NULL,
    [BIRTH_COHORT]                   VARCHAR (100) NULL,
    [RECEIVED_PARTIAL_VACCINATION]   VARCHAR (100) NULL,
    [VACCINATION_COVERAGE_PARTLY]    VARCHAR (100) NULL,
    [RECEIVED_COMPLETE_VACCINATION]  VARCHAR (100) NULL,
    [VACCINATION_COVERAGE_COMPLETED] VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]             DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCI_DLI_VWSSTAGE_CIMS_VACCINATED_AGE_GROUP]
    ON [VWSSTAGE].[CIMS_VACCINATED_AGE_GROUP]([DATE_LAST_INSERTED] ASC, [DATE_OF_STATISTICS_WEEK_START] ASC, [DATE_OF_STATISTICS_WEEK_END] ASC, [BIRTH_COHORT] ASC);


GO
CREATE CLUSTERED INDEX [CI_DLI_VWSSTAGE_CIMS_VACCINATED_AGE_GROUP]
    ON [VWSSTAGE].[CIMS_VACCINATED_AGE_GROUP]([DATE_LAST_INSERTED] ASC);

