CREATE TABLE [VWSSTAGE].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR] (
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]   DATETIME      DEFAULT (getdate()) NOT NULL,
    [VERSION]              VARCHAR (256) NULL,
    [DATE_OF_REPORT]       VARCHAR (256) NULL,
    [DATE_OF_STATISTICS]   VARCHAR (256) NULL,
    [POPULATION]           VARCHAR (256) NULL,
    [REGION_CODE]          VARCHAR (256) NULL,
    [REGION_LEVEL]         VARCHAR (256) NULL,
    [REGION_NAME]          VARCHAR (256) NULL,
    [AGE_GROUP]            VARCHAR (256) NULL,
    [BIRTH_YEAR]           VARCHAR (256) NULL,
    [VACCINATION_CAMPAIGN] VARCHAR (256) NULL,
    [PERCENTAGE]           VARCHAR (256) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_STAGE_CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR]
    ON [VWSSTAGE].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR]([DATE_LAST_INSERTED] ASC);

