CREATE TABLE [VWSSTAGE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR] (
    [ID]                             INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]) NOT NULL,
    [VERSION]                        VARCHAR (100) NULL,
    [DATE_OF_REPORT]                 VARCHAR (100) NULL,
    [DATE_OF_STATISTICS]             VARCHAR (100) NULL,
    [REGION_LEVEL]                   VARCHAR (100) NULL,
    [REGION_CODE]                    VARCHAR (100) NULL,
    [REGION_NAME]                    VARCHAR (100) NULL,
    [BIRTH_YEAR]                     VARCHAR (100) NULL,
    [VACCINATION_COVERAGE_PARTLY]    VARCHAR (100) NULL,
    [VACCINATION_COVERAGE_COMPLETED] VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]             DATETIME      DEFAULT (getdate()) NULL,
    [POPULATION]                     VARCHAR (100) NULL,
    [AGE_GROUP]                      VARCHAR (100) NULL,
    [VACCINATION_SERIE]              VARCHAR (100) NULL,
    [PERCENTAGE]                     VARCHAR (100) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCI_VWSSTAGE_CIMS_VACCINATED_AGE_GROUP]
    ON [VWSSTAGE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC, [DATE_OF_STATISTICS] ASC, [REGION_CODE] ASC)
    INCLUDE([REGION_LEVEL], [REGION_NAME], [BIRTH_YEAR], [VACCINATION_COVERAGE_PARTLY], [VACCINATION_COVERAGE_COMPLETED]);


GO
CREATE CLUSTERED INDEX [CI_DLI_VWSSTAGE_CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]
    ON [VWSSTAGE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]([DATE_LAST_INSERTED] ASC);

