CREATE TABLE [VWSSTAGE].[CORONAMELDER_POSITIVES] (
    [ID]                                                                INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CORONAMELDER_POSITIVES]) NOT NULL,
    [DATE (YYYY-MM-DD)]                                                 VARCHAR (100) NULL,
    [REPORTED POSITIVE TESTS THROUGH APP AUTHORISED BY GGD (DAILY)]     VARCHAR (100) NULL,
    [REPORTED POSITIVE TEST THROUGH APP AUTHORISED BY GGD (CUMULATIVE)] VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]                                                DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CORONAMELDER_POSITIVES_STAGE]
    ON [VWSSTAGE].[CORONAMELDER_POSITIVES]([DATE_LAST_INSERTED] ASC);

