CREATE TABLE [VWSSTAGE].[CORONAMELDER_DOWNLOADS] (
    [ID]                                             INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CORONAMELDER_DOWNLOADS]) NOT NULL,
    [DATE (YYYY-MM-DD)]                              VARCHAR (100) NULL,
    [DOWNLOADS APP STORE (IOS) (DAILY)]              VARCHAR (100) NULL,
    [DOWNLOADS PLAY STORE (ANDROID) (DAILY)]         VARCHAR (100) NULL,
    [DOWNLOADS HUAWEI APP GALLERY (ANDROID) (DAILY)] VARCHAR (100) NULL,
    [TOTAL DOWNLOADS (DAILY)]                        VARCHAR (100) NULL,
    [TOTAL DOWNLOADS (CUMULATIVE)]                   VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]                             DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CORONAMELDER_DOWNLOADS_STAGE]
    ON [VWSSTAGE].[CORONAMELDER_DOWNLOADS]([DATE_LAST_INSERTED] ASC);

