CREATE TABLE [VWSSTAGE].[DISABILITY] (
    [ID]                                    INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_DISABILITY]) NOT NULL,
    [DATE_OF_REPORT]                        VARCHAR (100) NULL,
    [DATE_OF_STATISTIC_REPORTED]            VARCHAR (100) NULL,
    [SECURITY_REGION_CODE]                  VARCHAR (100) NULL,
    [SECURITY_REGION_NAME]                  VARCHAR (100) NULL,
    [TOTAL_CASES_REPORTED]                  VARCHAR (100) NULL,
    [TOTAL_DECEASED_REPORTED]               VARCHAR (100) NULL,
    [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED] VARCHAR (100) NULL,
    [TOTAL_INFECTED_LOCATIONS_REPORTED]     VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]                    DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_DISABILITY_DLI]
    ON [VWSSTAGE].[DISABILITY]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_STATISTIC_REPORTED], [SECURITY_REGION_CODE], [TOTAL_CASES_REPORTED], [TOTAL_DECEASED_REPORTED], [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED], [TOTAL_INFECTED_LOCATIONS_REPORTED]);

