CREATE TABLE [VWSSTAGE].[ECDC_CASES] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_ECDC_CASES]) NOT NULL,
    [COUNTRY]            VARCHAR (100) NULL,
    [COUNTRY_CODE]       VARCHAR (100) NULL,
    [CONTINENT]          VARCHAR (100) NULL,
    [POPULATION]         VARCHAR (100) NULL,
    [INDICATOR]          VARCHAR (100) NULL,
    [WEEKLY_COUNT]       VARCHAR (100) NULL,
    [YEAR_WEEK]          VARCHAR (100) NULL,
    [RATE_14_DAY]        VARCHAR (100) NULL,
    [CUMULATIVE_COUNT]   VARCHAR (100) NULL,
    [SOURCE]             VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_ECDC_CASES]
    ON [VWSSTAGE].[ECDC_CASES]([DATE_LAST_INSERTED] ASC)
    INCLUDE([COUNTRY], [COUNTRY_CODE], [CONTINENT], [POPULATION], [INDICATOR], [WEEKLY_COUNT], [YEAR_WEEK], [RATE_14_DAY], [CUMULATIVE_COUNT], [SOURCE]);

