CREATE TABLE [VWSSTAGE].[ECDC_VARIANTS] (
    [ID]                        INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_ECDC_VARIANTS]) NOT NULL,
    [COUNTRY]                   VARCHAR (100) NULL,
    [COUNTRY_CODE]              VARCHAR (100) NULL,
    [YEAR_WEEK]                 VARCHAR (100) NULL,
    [SOURCE]                    VARCHAR (100) NULL,
    [NEW_CASES]                 VARCHAR (100) NULL,
    [NUMBER_SEQUENCED]          VARCHAR (100) NULL,
    [PERCENT_CASES_SEQUENCED]   VARCHAR (100) NULL,
    [VALID_DENOMINATOR]         VARCHAR (100) NULL,
    [VARIANT]                   VARCHAR (100) NULL,
    [NUMBER_DETECTIONS_VARIANT] VARCHAR (100) NULL,
    [PERCENT_VARIANT]           VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]        DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_ECDC_VARIANTS]
    ON [VWSSTAGE].[ECDC_VARIANTS]([DATE_LAST_INSERTED] ASC);

