CREATE TABLE [VWSSTAGE].[GGD_TESTED_PEOPLE] (
    [ID]                   INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_GGD_TESTED_PEOPLE]) NOT NULL,
    [VERSION]              VARCHAR (100) NULL,
    [DATE_OF_REPORT]       VARCHAR (100) NULL,
    [DATE_OF_STATISTICS]   VARCHAR (100) NULL,
    [SECURITY_REGION_CODE] VARCHAR (100) NULL,
    [SECURITY_REGION_NAME] VARCHAR (100) NULL,
    [TESTED_WITH_RESULT]   VARCHAR (100) NULL,
    [TESTED_POSITIVE]      VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]   DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_STAGE]
    ON [VWSSTAGE].[GGD_TESTED_PEOPLE]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_DATE_LAST_INSERTED]
    ON [VWSSTAGE].[GGD_TESTED_PEOPLE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([VERSION], [DATE_OF_REPORT], [DATE_OF_STATISTICS], [SECURITY_REGION_CODE], [SECURITY_REGION_NAME], [TESTED_WITH_RESULT], [TESTED_POSITIVE]);

