CREATE TABLE [VWSSTAGE].[LCPS_API_LNAZ_HOSPITAL_BED_OCCUPANCY_2023] (
    [ID]                                INT           IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]                DATETIME      DEFAULT (getdate()) NOT NULL,
    [DATUM]                             VARCHAR (256) NULL,
    [IC_CAPACITEIT_TOTAAL]              VARCHAR (256) NULL,
    [KLINIEK_CAPACITEIT_TOTAAL]         VARCHAR (256) NULL,
    [IC_BEZETTING_COVID]                VARCHAR (256) NULL,
    [IC_BEZETTING_COVID_INTERNATIONAAL] VARCHAR (256) NULL,
    [IC_BEZETTING_ONTLABELD]            VARCHAR (256) NULL,
    [IC_BEZETTING_NONCOVID]             VARCHAR (256) NULL,
    [KLINIEK_BEZETTING_COVID]           VARCHAR (256) NULL,
    [KLINIEK_BEZETTING_ONTLABELD]       VARCHAR (256) NULL,
    [KLINIEK_BEZETTING_NONCOVID]        VARCHAR (256) NULL,
    [IC_OPNAMES_COVID]                  VARCHAR (256) NULL,
    [KLINIEK_OPNAMES_COVID]             VARCHAR (256) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_LCPS_API_LNAZ_HOSPITAL_BED_OCCUPANCY_2023]
    ON [VWSSTAGE].[LCPS_API_LNAZ_HOSPITAL_BED_OCCUPANCY_2023]([DATE_LAST_INSERTED] ASC);

