CREATE TABLE [VWSSTAGE].[MANUAL_INPUT_BOOSTER_AND_THIRD_SHOTS] (
    [ID]                 INT            IDENTITY (1, 1) NOT NULL,
    [CATEGORY]           NVARCHAR (255) NULL,
    [KEY]                NVARCHAR (255) NULL,
    [VALUE]              NVARCHAR (255) NULL,
    [DATE_LAST_INSERTED] DATETIME       DEFAULT (getdate()) NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_MANUAL_INPUT_BOOSTER_AND_THIRD_SHOTS]
    ON [VWSSTAGE].[MANUAL_INPUT_BOOSTER_AND_THIRD_SHOTS]([DATE_LAST_INSERTED] ASC);

