CREATE TABLE [VWSSTAGE].[MASTERDATA_VARIANTS] (
    [ID]                     BIGINT        IDENTITY (1, 1) NOT NULL,
    [VARIANT_CODE]           VARCHAR (100) NULL,
    [IS_SUBVARIANT_OF]       VARCHAR (100) NULL,
    [SHOWS_ON_VWS_DASHBOARD] VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    [LABEL_EN]               VARCHAR (100) NULL,
    [LABEL_NL]               VARCHAR (100) NULL,
    [SORT_ORDER]             VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

