CREATE TABLE [VWSSTAGE].[NICE_HOSPITAL_ADMISSIONS] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_NICE_HOSPITAL_ADMISSIONS]) NOT NULL,
    [DATE]               VARCHAR (100) NULL,
    [VALUE]              VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_NICE_HOSPITAL_ADMISSIONS]
    ON [VWSSTAGE].[NICE_HOSPITAL_ADMISSIONS]([DATE_LAST_INSERTED] ASC);

