CREATE TABLE [VWSSTAGE].[NICE_HOSPITAL] (
    [ID]                              INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_NICE_HOSPITAL]) NOT NULL,
    [VERSION]                         VARCHAR (100) NULL,
    [DATE_OF_REPORT]                  VARCHAR (100) NULL,
    [DATE_OF_STATISTICS]              VARCHAR (100) NULL,
    [MUNICIPALITY_CODE]               VARCHAR (100) NULL,
    [MUNICIPALITY_NAME]               VARCHAR (100) NULL,
    [SECURITY_REGION_CODE]            VARCHAR (100) NULL,
    [SECURITY_REGION_NAME]            VARCHAR (100) NULL,
    [HOSPITAL_ADMISSION_NOTIFICATION] VARCHAR (100) NULL,
    [HOSPITAL_ADMISSION]              VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]              DATETIME      DEFAULT (getdate()) NULL
);


GO
CREATE CLUSTERED INDEX [IX_NICE_HOSPITAL_STAGE_IC]
    ON [VWSSTAGE].[NICE_HOSPITAL]([DATE_LAST_INSERTED] ASC);

