CREATE TABLE [VWSSTAGE].[OIWD_International_Data] (
    [ID]                                    INT          DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_OIWD_International_Data]) NOT NULL,
    [ISO_CODE]                              VARCHAR (50) NULL,
    [CONTINENT]                             VARCHAR (50) NULL,
    [LOCATION]                              VARCHAR (50) NULL,
    [DATE]                                  VARCHAR (50) NULL,
    [TOTAL_CASES]                           VARCHAR (50) NULL,
    [NEW_CASES]                             VARCHAR (50) NULL,
    [NEW_CASES_SMOOTHED]                    VARCHAR (50) NULL,
    [TOTAL_DEATHS]                          VARCHAR (50) NULL,
    [NEW_DEATHS]                            VARCHAR (50) NULL,
    [NEW_DEATHS_SMOOTHED]                   VARCHAR (50) NULL,
    [TOTAL_CASES_PER_MILLION]               VARCHAR (50) NULL,
    [NEW_CASES_PER_MILLION]                 VARCHAR (50) NULL,
    [NEW_CASES_SMOOTHED_PER_MILLION]        VARCHAR (50) NULL,
    [TOTAL_DEATHS_PER_MILLION]              VARCHAR (50) NULL,
    [NEW_DEATHS_PER_MILLION]                VARCHAR (50) NULL,
    [NEW_DEATHS_SMOOTHED_PER_MILLION]       VARCHAR (50) NULL,
    [REPRODUCTION_RATE]                     VARCHAR (50) NULL,
    [ICU_PATIENTS]                          VARCHAR (50) NULL,
    [ICU_PATIENTS_PER_MILLION]              VARCHAR (50) NULL,
    [HOSP_PATIENTS]                         VARCHAR (50) NULL,
    [HOSP_PATIENTS_PER_MILLION]             VARCHAR (50) NULL,
    [WEEKLY_ICU_ADMISSIONS]                 VARCHAR (50) NULL,
    [WEEKLY_ICU_ADMISSIONS_PER_MILLION]     VARCHAR (50) NULL,
    [WEEKLY_HOSP_ADMISSIONS]                VARCHAR (50) NULL,
    [WEEKLY_HOSP_ADMISSIONS_PER_MILLION]    VARCHAR (50) NULL,
    [NEW_TESTS]                             VARCHAR (50) NULL,
    [TOTAL_TESTS]                           VARCHAR (50) NULL,
    [TOTAL_TESTS_PER_THOUSAND]              VARCHAR (50) NULL,
    [NEW_TESTS_PER_THOUSAND]                VARCHAR (50) NULL,
    [NEW_TESTS_SMOOTHED]                    VARCHAR (50) NULL,
    [NEW_TESTS_SMOOTHED_PER_THOUSAND]       VARCHAR (50) NULL,
    [POSITIVE_RATE]                         VARCHAR (50) NULL,
    [TESTS_PER_CASE]                        VARCHAR (50) NULL,
    [TESTS_UNITS]                           VARCHAR (50) NULL,
    [TOTAL_VACCINATIONS]                    VARCHAR (50) NULL,
    [PEOPLE_VACCINATED]                     VARCHAR (50) NULL,
    [PEOPLE_FULLY_VACCINATED]               VARCHAR (50) NULL,
    [NEW_VACCINATIONS]                      VARCHAR (50) NULL,
    [NEW_VACCINATIONS_SMOOTHED]             VARCHAR (50) NULL,
    [TOTAL_VACCINATIONS_PER_HUNDRED]        VARCHAR (50) NULL,
    [PEOPLE_VACCINATED_PER_HUNDRED]         VARCHAR (50) NULL,
    [PEOPLE_FULLY_VACCINATED_PER_HUNDRED]   VARCHAR (50) NULL,
    [NEW_VACCINATIONS_SMOOTHED_PER_MILLION] VARCHAR (50) NULL,
    [STRINGENCY_INDEX]                      VARCHAR (50) NULL,
    [POPULATION]                            VARCHAR (50) NULL,
    [POPULATION_DENSITY]                    VARCHAR (50) NULL,
    [MEDIAN_AGE]                            VARCHAR (50) NULL,
    [AGED_65_OLDER]                         VARCHAR (50) NULL,
    [AGED_70_OLDER]                         VARCHAR (50) NULL,
    [GDP_PER_CAPITA]                        VARCHAR (50) NULL,
    [EXTREME_POVERTY]                       VARCHAR (50) NULL,
    [CARDIOVASC_DEATH_RATE]                 VARCHAR (50) NULL,
    [DIABETES_PREVALENCE]                   VARCHAR (50) NULL,
    [FEMALE_SMOKERS]                        VARCHAR (50) NULL,
    [MALE_SMOKERS]                          VARCHAR (50) NULL,
    [HANDWASHING_FACILITIES]                VARCHAR (50) NULL,
    [HOSPITAL_BEDS_PER_THOUSAND]            VARCHAR (50) NULL,
    [LIFE_EXPECTANCY]                       VARCHAR (50) NULL,
    [HUMAN_DEVELOPMENT_INDEX]               VARCHAR (50) NULL,
    [DATE_LAST_INSERTED]                    DATETIME     DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_VWSSTAGE_OIWD_International_Data]
    ON [VWSSTAGE].[OIWD_International_Data]([DATE_LAST_INSERTED] ASC)
    INCLUDE([ISO_CODE], [DATE]);

