CREATE TABLE [VWSSTAGE].[RISK_LEVEL_THRESHOLDS] (
    [ID]                                   INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RISK_LEVEL_THRESHOLDS]) NOT NULL,
    [RISICO NIVEAU]                        VARCHAR (100) NULL,
    [OMSCHRIJVING RISICONIVEAU]            VARCHAR (100) NULL,
    [7 DAAGS GEMIDDELDE IC OPNAMES]        VARCHAR (100) NULL,
    [7 DAAGS GEMIDDELDE ZIEKENHUISOPNAMES] VARCHAR (100) NULL,
    [GELDIG VANAF]                         VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]                   DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

