CREATE TABLE [VWSSTAGE].[RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP] (
    [ID]                              INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]) NOT NULL,
    [VERSION]                         VARCHAR (100) NULL,
    [DATE_OF_REPORT]                  VARCHAR (100) NULL,
    [DATE_OF_STATISTICS_WEEK_START]   VARCHAR (100) NULL,
    [AGE_GROUP]                       VARCHAR (100) NULL,
    [HOSPITAL_ADMISSION_NOTIFICATION] VARCHAR (100) NULL,
    [HOSPITAL_ADMISSION]              VARCHAR (100) NULL,
    [IC_ADMISSION_NOTIFICATION]       VARCHAR (100) NULL,
    [IC_ADMISSION]                    VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]              DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]
    ON [VWSSTAGE].[RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]([DATE_LAST_INSERTED] ASC);

