CREATE TABLE [VWSSTAGE].[RIVM_SEWER_MEASUREMENTS] (
    [ID]                  INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_SEWER_MEASUREMENTS_2021]) NOT NULL,
    [VERSION]             VARCHAR (100) NULL,
    [DATE_MEASUREMENT]    VARCHAR (100) NULL,
    [RWZI_AWZI_CODE]      VARCHAR (100) NULL,
    [RWZI_AWZI_NAME]      VARCHAR (100) NULL,
    [RNA_PER_ML]          VARCHAR (100) NULL,
    [RNA_FLOW_PER_100000] VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [DATE_OF_REPORT]      VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

