CREATE TABLE [VWSSTAGE].[RIVM_NURSING_HOMES_HANDICAPPED_INFECTED_LOCATIONS_PER_REGION] (
    [ID]                                                                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_NURSING_HOMES_HANDICAPPED_INFECTED_LOCATIONS_PER_REGION]) NOT NULL,
    [VEILIGHEIDSREGIOCODE]                                               VARCHAR (100) NULL,
    [VEILIGHEIDSREGIONAAM]                                               VARCHAR (100) NULL,
    [PUBLICATIEDATUMRIVM]                                                VARCHAR (100) NULL,
    [AANTAL_NIEUW_BESMETTE_GEHANDICAPTENZORGINSTELLING_LOCATIES]         VARCHAR (100) NULL,
    [AANTAL_NIEUW_BESMETTINGSVRIJE_GEHANDICAPTENZORGINSTELLING_LOCATIES] VARCHAR (100) NULL,
    [AANTAL_BESMETTE_GEHANDICAPTENZORGINSTELLING_LOCATIES]               VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]                                                 DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

