CREATE TABLE [VWSSTAGE].[RIVM_CLUSTERS_INFECTED_PEOPLE] (
    [ID]                   INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_CLUSTERS_INFECTED_PEOPLE]) NOT NULL,
    [DATE_OF_REPORT]       VARCHAR (100) NULL,
    [DATE_STATISTICS]      VARCHAR (100) NULL,
    [SECURITY_REGION_NAME] VARCHAR (100) NULL,
    [SECURITY_REGION_CODE] VARCHAR (100) NULL,
    [ACTIVE_CLUSTERS]      VARCHAR (100) NULL,
    [AVERAGE_SIZE]         VARCHAR (100) NULL,
    [MEDIAN_SIZE]          VARCHAR (100) NULL,
    [MIN_SIZE]             VARCHAR (100) NULL,
    [MAX_SIZE]             VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]   DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

