CREATE TABLE [VWSSTAGE].[RIVM_SEWER_MEASUREMENTS_ARCHIVE] (
    [ID]                            INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_SEWER_MEASUREMENTS]) NOT NULL,
    [DATE_MEASUREMENT]              VARCHAR (100) NULL,
    [RWZI_AWZI_CODE]                VARCHAR (100) NULL,
    [RWZI_AWZI_NAME]                VARCHAR (100) NULL,
    [X_COORDINATE]                  VARCHAR (100) NULL,
    [Y_COORDINATE]                  VARCHAR (100) NULL,
    [POSTAL_CODE]                   VARCHAR (100) NULL,
    [SECURITY_REGION_CODE]          VARCHAR (100) NULL,
    [SECURITY_REGION_NAME]          VARCHAR (100) NULL,
    [PERCENTAGE_IN_SECURITY_REGION] VARCHAR (100) NULL,
    [RNA_PER_ML]                    VARCHAR (100) NULL,
    [REPRESENTATIVE_MEASUREMENT]    VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]            DATETIME      DEFAULT (getdate()) NULL,
    [RNA_FLOW_PER_100000]           VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_SEWER_MEASUREMENTS_DLI]
    ON [VWSSTAGE].[RIVM_SEWER_MEASUREMENTS_ARCHIVE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_MEASUREMENT], [RWZI_AWZI_CODE], [RWZI_AWZI_NAME], [X_COORDINATE], [Y_COORDINATE], [POSTAL_CODE], [SECURITY_REGION_CODE], [SECURITY_REGION_NAME], [PERCENTAGE_IN_SECURITY_REGION], [RNA_PER_ML], [REPRESENTATIVE_MEASUREMENT], [RNA_FLOW_PER_100000]);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_SEWER_MEASUREMENTS]
    ON [VWSSTAGE].[RIVM_SEWER_MEASUREMENTS_ARCHIVE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_MEASUREMENT], [RWZI_AWZI_CODE], [RWZI_AWZI_NAME], [X_COORDINATE], [Y_COORDINATE], [POSTAL_CODE], [SECURITY_REGION_CODE], [SECURITY_REGION_NAME], [PERCENTAGE_IN_SECURITY_REGION], [RNA_PER_ML], [REPRESENTATIVE_MEASUREMENT]);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_SEWER_MEASUREMENTS]
    ON [VWSSTAGE].[RIVM_SEWER_MEASUREMENTS_ARCHIVE]([DATE_LAST_INSERTED] ASC);

