CREATE TABLE [VWSSTAGE].[RIVM_INFECTIE_RADAR_POSITIVE_TESTS_DAILY_NL] (
    [ID]                              INT           IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]              DATETIME      DEFAULT (getdate()) NOT NULL,
    [VERSION]                         VARCHAR (256) NULL,
    [DATE_OF_REPORT]                  VARCHAR (256) NULL,
    [DATE_OF_STATISTICS]              VARCHAR (256) NULL,
    [N_PARTICIPANTS_TOTAL]            VARCHAR (256) NULL,
    [N_WITH_SYMPTOMS]                 VARCHAR (256) NULL,
    [N_WITH_SHARED_COVID_TEST_RESULT] VARCHAR (256) NULL,
    [N_TESTED_POSITIVE]               VARCHAR (256) NULL,
    [PERC_COVID_TEST_POSITIVE]        VARCHAR (256) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_RIVM_INFECTIE_RADAR_POSITIVE_TESTS_DAILY_NL]
    ON [VWSSTAGE].[RIVM_INFECTIE_RADAR_POSITIVE_TESTS_DAILY_NL]([DATE_LAST_INSERTED] ASC);

