CREATE TABLE [VWSSTAGE].[RIVM_SEWER_MEASUREMENTS_NL_2023] (
    [ID]                  INT           IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]  DATETIME      DEFAULT (getdate()) NOT NULL,
    [VERSION]             VARCHAR (256) NULL,
    [DATE_OF_REPORT]      VARCHAR (256) NULL,
    [DATE_MEASUREMENT]    VARCHAR (256) NULL,
    [RNA_FLOW_PER_100000] VARCHAR (256) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_RIVM_SEWER_MEASUREMENTS_NL_2023]
    ON [VWSSTAGE].[RIVM_SEWER_MEASUREMENTS_NL_2023]([DATE_LAST_INSERTED] ASC);

