CREATE TABLE [VWSSTAGE].[RIVM_NURSING_HOMES_HANDICAPPED_INFECTED_LOCATIONS] (
    [ID]                                                                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_NURSING_HOMES_HANDICAPPED_INFECTED_LOCATIONS]) NOT NULL,
    [PUBLICATIEDATUMRIVM]                                                VARCHAR (100) NULL,
    [AANTAL_NIEUW_BESMETTE_GEHANDICAPTENZORGINSTELLING_LOCATIES]         VARCHAR (100) NULL,
    [AANTAL_NIEUW_BESMETTINGSVRIJE_GEHANDICAPTENZORGINSTELLING_LOCATIES] VARCHAR (100) NULL,
    [AANTAL_BESMETTE_GEHANDICAPTENZORGINSTELLING_LOCATIES]               VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]                                                 DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_NURSING_HOMES_HANDICAPPED_INFECTED_LOCATIONS]
    ON [VWSSTAGE].[RIVM_NURSING_HOMES_HANDICAPPED_INFECTED_LOCATIONS]([DATE_LAST_INSERTED] ASC)
    INCLUDE([PUBLICATIEDATUMRIVM], [AANTAL_BESMETTE_GEHANDICAPTENZORGINSTELLING_LOCATIES], [AANTAL_NIEUW_BESMETTE_GEHANDICAPTENZORGINSTELLING_LOCATIES], [AANTAL_NIEUW_BESMETTINGSVRIJE_GEHANDICAPTENZORGINSTELLING_LOCATIES]);

