CREATE TABLE [VWSSTAGE].[RIVM_IC_OPNAME] (
    [ID]                        INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_RIVM_IC_OPNAME]) NOT NULL,
    [VERSION]                   VARCHAR (100) NULL,
    [DATE_OF_REPORT]            VARCHAR (100) NULL,
    [DATE_OF_STATISTICS]        VARCHAR (100) NULL,
    [IC_ADMISSION_NOTIFICATION] VARCHAR (100) NULL,
    [IC_ADMISSION]              VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]        DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_IC_OPNAME_STAGE]
    ON [VWSSTAGE].[RIVM_IC_OPNAME]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_STATISTICS], [IC_ADMISSION_NOTIFICATION], [IC_ADMISSION]);

