CREATE TABLE [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM]) NOT NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NOT NULL,
    [VERSION]            VARCHAR (256) NULL,
    [DATE_OF_REPORT]     VARCHAR (256) NULL,
    [DATE_OF_STATISTICS] VARCHAR (256) NULL,
    [POPULATION]         VARCHAR (256) NULL,
    [REGION_CODE]        VARCHAR (256) NULL,
    [REGION_LEVEL]       VARCHAR (256) NULL,
    [REGION_NAME]        VARCHAR (256) NULL,
    [AGE_GROUP]          VARCHAR (256) NULL,
    [BIRTH_YEAR]         VARCHAR (256) NULL,
    [VACCINATION_SERIE]  VARCHAR (256) NULL,
    [PERCENTAGE]         VARCHAR (256) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM]
    ON [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM]
    ON [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM]([DATE_LAST_INSERTED] ASC);

