CREATE TABLE [VWSSTAGE].[RIVM_NURSING_HOMES_DECEASED] (
    [ID]                   INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_NURSING_HOMES_DECEASED]) NOT NULL,
    [DATUM_VAN_OVERLIJDEN] VARCHAR (100) NULL,
    [AANTAL]               VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]   DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_NURSING_HOMES_DECEASED]
    ON [VWSSTAGE].[RIVM_NURSING_HOMES_DECEASED]([DATE_LAST_INSERTED] ASC);

