CREATE TABLE [VWSSTAGE].[RIVM_NURSING_HOMES_INFECTED_LOCATIONS_PER_REGION] (
    [ID]                                                  INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_NURSING_HOMES_INFECTED_LOCATIONS_PER_REGION]) NOT NULL,
    [VEILIGHEIDSREGIOCODE]                                VARCHAR (100) NULL,
    [VEILIGHEIDSREGIONAAM]                                VARCHAR (100) NULL,
    [PUBLICATIEDATUMRIVM]                                 VARCHAR (100) NULL,
    [AANTAL_NIEUW_BESMETTE_VERPLEEGHUIS_LOCATIES]         VARCHAR (100) NULL,
    [AANTAL_NIEUW_BESMETTINGSVRIJE_VERPLEEGHUIS_LOCATIES] VARCHAR (100) NULL,
    [AANTAL_BESMETTE_VERPLEEGHUIS_LOCATIES]               VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]                                  DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_NURSING_HOMES_INFECTED_LOCATIONS_PER_REGION]
    ON [VWSSTAGE].[RIVM_NURSING_HOMES_INFECTED_LOCATIONS_PER_REGION]([DATE_LAST_INSERTED] ASC)
    INCLUDE([VEILIGHEIDSREGIOCODE], [VEILIGHEIDSREGIONAAM], [PUBLICATIEDATUMRIVM], [AANTAL_NIEUW_BESMETTE_VERPLEEGHUIS_LOCATIES], [AANTAL_NIEUW_BESMETTINGSVRIJE_VERPLEEGHUIS_LOCATIES], [AANTAL_BESMETTE_VERPLEEGHUIS_LOCATIES]);

