CREATE TABLE [VWSSTAGE].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL]) NOT NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NOT NULL,
    [DATE_OF_STATISTICS] VARCHAR (100) NULL,
    [TOTAL_VACCINATIONS] VARCHAR (100) NULL,
    [ASTRA_ZENECA]       VARCHAR (100) NULL,
    [COMIRNATY]          VARCHAR (100) NULL,
    [MODERNA]            VARCHAR (100) NULL,
    [UNKNOWN]            VARCHAR (100) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL]
    ON [VWSSTAGE].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL]([DATE_LAST_INSERTED] ASC);

