CREATE TABLE [VWSSTAGE].[RIVM_SITUATIONS] (
    [ID]                               INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_SITUATIONS]) NOT NULL,
    [VERSION]                          VARCHAR (100) NULL,
    [DATE_OF_REPORT]                   VARCHAR (100) NULL,
    [DATE_OF_PUBLICATION]              VARCHAR (100) NULL,
    [SECURITY_REGION_NAME]             VARCHAR (100) NULL,
    [SECURITY_REGION_CODE]             VARCHAR (100) NULL,
    [SOURCE_AND_CONTACT_TRACING_PHASE] VARCHAR (100) NULL,
    [TOTAL_REPORTED]                   VARCHAR (100) NULL,
    [REPORTS_WITH_SETTINGS]            VARCHAR (100) NULL,
    [SETTING_REPORTED]                 VARCHAR (100) NULL,
    [NUMBER_SETTINGS_REPORTED]         VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]               DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

