CREATE TABLE [VWSSTAGE].[RIVM_VACCINATIONS_PARTLY_FULLY] (
    [ID]                           INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_VACCINATIONS_PARTLY_FULLY]) NOT NULL,
    [RECORDID]                     VARCHAR (100) NULL,
    [REPORTINGCOUNTRY]             VARCHAR (100) NULL,
    [RECORDTYPE]                   VARCHAR (100) NULL,
    [RECORDTYPEVERSION]            VARCHAR (100) NULL,
    [SUBJECT]                      VARCHAR (100) NULL,
    [DATASOURCE]                   VARCHAR (100) NULL,
    [STATUS]                       VARCHAR (100) NULL,
    [DATEUSEDFORSTATISTICS]        VARCHAR (100) NULL,
    [REGION]                       VARCHAR (100) NULL,
    [VACCINE]                      VARCHAR (100) NULL,
    [NUMBERDOSESRECEIVED]          VARCHAR (100) NULL,
    [TARGETGROUP]                  VARCHAR (100) NULL,
    [DOSEFIRST]                    VARCHAR (100) NULL,
    [DOSESECOND]                   VARCHAR (100) NULL,
    [DOSEUNK]                      VARCHAR (100) NULL,
    [DOSEFIRSTREFUSED]             VARCHAR (100) NULL,
    [DENOMINATOR]                  VARCHAR (100) NULL,
    [TARGETGROUPCOMMENT]           VARCHAR (100) NULL,
    [GENERALCOMMENT]               VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]           DATETIME      DEFAULT (getdate()) NULL,
    [DATE_OF_REPORT]               VARCHAR (100) NULL,
    [DATE_OF_STATISTICS]           VARCHAR (100) NULL,
    [END_ISO_WEEK]                 VARCHAR (100) NULL,
    [BIRTH_YEAR]                   VARCHAR (100) NULL,
    [CUMSUM_VACCINATION_PARTLY]    VARCHAR (100) NULL,
    [CUMSUM_VACCINATION_COMPLETED] VARCHAR (100) NULL,
    [POPULATION]                   VARCHAR (100) NULL,
    [CUMSUM_VACCINATION_BOOSTER]   VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_VACCINATIONS_PARTLY_FULLY]
    ON [VWSSTAGE].[RIVM_VACCINATIONS_PARTLY_FULLY]([DATE_LAST_INSERTED] ASC);

