CREATE TABLE [VWSSTAGE].[RIVM_VACCINATION_INCIDENCE_HOSPITAL] (
    [ID]                              INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_VACCINATION_INCIDENCE_HOSPITAL]) NOT NULL,
    [DATUM_PERIODE_START]             VARCHAR (100) NULL,
    [DATUM_PERIODE_EINDE]             VARCHAR (100) NULL,
    [lEEFTIJDSCOHORT_CATEGORIE]       VARCHAR (100) NULL,
    [LEEFTIJDSCOHORT_CATEGORIE_LABEL] VARCHAR (100) NULL,
    [VACC_STATUS]                     VARCHAR (100) NULL,
    [INCIDENTIE_OPNAMES_GEM]          VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]              DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWSSTAGE_VACCINATION_INCIDENCE_HOSPITAL]
    ON [VWSSTAGE].[RIVM_VACCINATION_INCIDENCE_HOSPITAL]([DATE_LAST_INSERTED] ASC);

