CREATE TABLE [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL] (
    [ID]                                  INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL]) NOT NULL,
    [DATE_LAST_INSERTED]                  DATETIME      DEFAULT (getdate()) NOT NULL,
    [VERSION]                             VARCHAR (256) NULL,
    [DATE_OF_REPORT]                      VARCHAR (256) NULL,
    [DATE_OF_STATISTICS]                  VARCHAR (256) NULL,
    [BIRTH_COHORT]                        VARCHAR (256) NULL,
    [POPULATION_PER_AGE_GROUP]            VARCHAR (256) NULL,
    [BASIC_SERIE_AMOUNT]                  VARCHAR (256) NULL,
    [BOOSTER_TYPE]                        VARCHAR (256) NULL,
    [CUMULATIVE_AMOUNT]                   VARCHAR (256) NULL,
    [VACCINATION_COVERAGE_PER_AGE_GROUP]  VARCHAR (256) NULL,
    [VACCINATION_COVERAGE_VS_BASIC_SERIE] VARCHAR (256) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE CLUSTERED INDEX [CIX_DLI_VWSSTAGE_RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL]
    ON [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL]([DATE_LAST_INSERTED] ASC);

