CREATE TABLE [VWSSTAGE].[RIVM_VACCINE_STOCK] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_VACCINE_STOCK]) NOT NULL,
    [DATE_OF_STATISTICS] VARCHAR (100) NULL,
    [VACCINE_NAME]       VARCHAR (50)  NULL,
    [TOTAL_STOCK]        VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    [FREE_STOCK]         VARCHAR (100) NULL,
    [DATE_OF_REPORT]     VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

