CREATE TABLE [VWSSTAGE].[RIVM_NURSING_HOMES_HANDICAPPED_TOTALS] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_NURSING_HOMES_HANDICAPPED_TOTAlS]) NOT NULL,
    [MELDINGSDATUM]      VARCHAR (100) NULL,
    [AANTAL]             VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_NURSING_HOMES_HANDICAPPED_TOTALS]
    ON [VWSSTAGE].[RIVM_NURSING_HOMES_HANDICAPPED_TOTALS]([DATE_LAST_INSERTED] ASC)
    INCLUDE([MELDINGSDATUM], [AANTAL]);

