CREATE TABLE [VWSSTAGE].[RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD] (
    [ID]                     BIGINT       IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]     DATETIME     DEFAULT GETDATE() NOT NULL,
    [VERSION]                VARCHAR (50) NULL,
    [DATE_OF_REPORT]         VARCHAR (50) NULL,
    [DATE_OF_STATISTICS]     VARCHAR (50) NULL,
    [AGE_GROUPS]             VARCHAR (50) NULL,
    [N_PARTICIPANTS]         VARCHAR (50) NULL,
    [PERC_COVID_SYMPTOMS]    VARCHAR (50) NULL,
    [MA_PERC_COVID_SYMPTOMS] VARCHAR (50) NULL
);

