CREATE TABLE [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL] (
    [ID]                    INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL]) NOT NULL,
    [DATE_LAST_INSERTED]    DATETIME      DEFAULT (getdate()) NOT NULL,
    [VERSION]               VARCHAR (256) NULL,
    [DATE_OF_REPORT]        VARCHAR (256) NULL,
    [DATE_OF_STATISTICS]    VARCHAR (256) NULL,
    [PLANNED_DATE]          VARCHAR (256) NULL,
    [TYPE_PLANNED_DATE]     VARCHAR (256) NULL,
    [PLANNED_BOOSTER_SHOTS] VARCHAR (256) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL]
    ON [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL]([DATE_LAST_INSERTED] ASC);

