CREATE TABLE [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL] (
    [ID]                      INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL]) NOT NULL,
    [DATE_LAST_INSERTED]      DATETIME      DEFAULT (getdate()) NOT NULL,
    [VERSION]                 VARCHAR (256) NULL,
    [DATE_OF_REPORT]          VARCHAR (256) NULL,
    [DATE_OF_STATISTICS]      VARCHAR (256) NULL,
    [YEAR_OF_BIRTH]           VARCHAR (256) NULL,
    [COVERAGE_BOOSTER_SHOTS]  VARCHAR (256) NULL,
    [CUMSUM_BOOSTER_SHOTS]    VARCHAR (256) NULL,
    [BIRTH_COHORT]            VARCHAR (256) NULL,
    [POPULATION_AGEGROUP]     VARCHAR (256) NULL,
    [BASE_SERIES]             VARCHAR (256) NULL,
    [BOOSTER1]                VARCHAR (256) NULL,
    [AMOUNT_CUMULATIVE]       VARCHAR (256) NULL,
    [COVERAGE_AGEGROUP]       VARCHAR (256) NULL,
    [COVERAGE_TO_BASE_SERIES] VARCHAR (256) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL]
    ON [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL]
    ON [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL]([DATE_LAST_INSERTED] ASC);

