CREATE TABLE [VWSSTAGE].[RIVM_INFECTIOUS_PEOPLE] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_INFECTIOUS_PEOPLE]) NOT NULL,
    [DATE]               VARCHAR (100) NULL,
    [PREV_LOW]           VARCHAR (100) NULL,
    [PREV_AVG]           VARCHAR (100) NULL,
    [PREV_UP]            VARCHAR (100) NULL,
    [POPULATION]         VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    [VERSION]            VARCHAR (20)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STAGE_RIVM_INFECTIOUS_PEOPLE_DLI]
    ON [VWSSTAGE].[RIVM_INFECTIOUS_PEOPLE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE], [PREV_LOW], [PREV_AVG], [PREV_UP]);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_INFECTIOUS_PEOPLE]
    ON [VWSSTAGE].[RIVM_INFECTIOUS_PEOPLE]([DATE_LAST_INSERTED] ASC);

