CREATE TABLE [VWSSTAGE].[RIVM_NURSING_HOMES_INFECTED_LOCATIONS_OLD] (
    [ID]                                   INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_NURSING_HOMES_INFECTED_LOCATIONS]) NOT NULL,
    [DATUM]                                VARCHAR (100) NULL,
    [AANTAL_NIEUW_BESMETTE_VERPLEEGHUIZEN] VARCHAR (100) NULL,
    [AANTAL_BESMETTE_VERPLEEGHUIZEN]       VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]                   DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_NURSING_HOMES_INFECTED_LOCATIONS]
    ON [VWSSTAGE].[RIVM_NURSING_HOMES_INFECTED_LOCATIONS_OLD]([DATE_LAST_INSERTED] ASC);

