CREATE TABLE [VWSSTAGE].[RIVM_NURSING_HOMES_HANDICAPPED_TOTALS_PER_REGION] (
    [ID]                   INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_NURSING_HOMES_HANDICAPPED_TOTAlS_PER_REGION]) NOT NULL,
    [VEILIGHEIDSREGIOCODE] VARCHAR (100) NULL,
    [VEILIGHEIDSREGIONAAM] VARCHAR (100) NULL,
    [MELDINGSDATUMGGD]     VARCHAR (100) NULL,
    [AANTAL]               VARCHAR (100) NULL,
    [AANTAL_CUM]           VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]   DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

