CREATE TABLE [VWSSTAGE].[RWZI_CONNECTED_INHABITANTS] (
    [ID]                    BIGINT        IDENTITY (1, 1) NOT NULL,
    [REGIO_CODE]            VARCHAR (100) NULL,
    [REGIO_NAME]            VARCHAR (100) NULL,
    [CONNECTED_INHABITANTS] VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]    DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

