CREATE TABLE [VWSSTAGE].[RWZI_AWZI] (
    [ID]                 BIGINT        IDENTITY (1, 1) NOT NULL,
    [RWZI_AWZI_CODE]     VARCHAR (100) NULL,
    [RWZI_AWZI_NAME]     VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

