CREATE TABLE [VWSSTAGE].[VACCINE_ADMINISTERED_TEMP] (
    [ID]                  INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_VACCINE_ADMINISTERED_TEMP]) NOT NULL,
    [DATE_OF_REPORT]      VARCHAR (100) NULL,
    [DATE_OF_STATISTIC]   VARCHAR (100) NULL,
    [TARGET_GROUP]        VARCHAR (100) NULL,
    [SUB_TARGET_GROUP]    VARCHAR (100) NULL,
    [VACCINATION_NAME]    VARCHAR (100) NULL,
    [SHOT_ROUND]          VARCHAR (100) NULL,
    [VACCINATIONS_AMOUNT] VARCHAR (100) NULL,
    [SOURCE]              VARCHAR (100) NULL,
    [REPORT_STATUS]       VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_VWSSTAGE_VACCINE_ADMINISTERED_TEMP]
    ON [VWSSTAGE].[VACCINE_ADMINISTERED_TEMP]([DATE_LAST_INSERTED] ASC);

