CREATE TABLE [VWSSTAGE].[VWS_BEHAVIOR_ANNOTATIONS_NL] (
    [ID]                           INT           IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]           DATETIME      DEFAULT (getdate()) NOT NULL,
    [VERSION]                      VARCHAR (100) NULL,
    [DATE_OF_REPORT]               VARCHAR (100) NULL,
    [DATE_OF_CHANGE]               VARCHAR (100) NULL,
    [FIRST_WAVE]                   VARCHAR (100) NULL,
    [DATE_OF_FIRST_MEASUREMENT]    VARCHAR (100) NULL,
    [MEASUREMENT_DURATION_IN_DAYS] VARCHAR (100) NULL,
    [INDICATOR]                    VARCHAR (100) NULL,
    [STATUS]                       VARCHAR (100) NULL,
    [MESSAGE_RIVM]                 VARCHAR (255) NULL,
    [MESSAGE_TITLE_NL]             VARCHAR (255) NULL,
    [MESSAGE_TEXT_NL]              VARCHAR (255) NULL,
    [MESSAGE_TITLE_EN]             VARCHAR (255) NULL,
    [MESSAGE_TEXT_EN]              VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_VWS_BEHAVIOR_ANNOTATIONS_NL]
    ON [VWSSTAGE].[VWS_BEHAVIOR_ANNOTATIONS_NL]([DATE_LAST_INSERTED] ASC);

