CREATE TABLE [VWSSTAGE].[VWS_RESTRICTIONS_MAPPING] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_VWS_RESTRICTIONS_MAPPING]) NOT NULL,
    [IDENTIFIER]         VARCHAR (100) NULL,
    [TARGET_REGION]      VARCHAR (100) NULL,
    [ESCALATION_LEVEL]   VARCHAR (100) NULL,
    [CATEGORY_ID]        VARCHAR (100) NULL,
    [RESTRICTION_ORDER]  VARCHAR (100) NULL,
    [VALID_FROM]         VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_RESTRICTIONS_MAPPING_STAGE]
    ON [VWSSTAGE].[VWS_RESTRICTIONS_MAPPING]([DATE_LAST_INSERTED] ASC);

