CREATE TABLE [VWSSTAGE].[VWS_VACCINATION_AVAILABILITY] (
    [ID]                  INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_VACCINATION_AVAILABILITY]) NOT NULL,
    [VALID_FROM]          VARCHAR (100) NULL,
    [VACCIN_NAME]         VARCHAR (100) NULL,
    [EXPECTED_OR_OPTIONS] VARCHAR (100) NULL,
    [DATE_DELIVERY]       VARCHAR (100) NULL,
    [AMOUNT_DELIVERY]     VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_VACCINATION_AVAILABILITY_STAGE]
    ON [VWSSTAGE].[VWS_VACCINATION_AVAILABILITY]([DATE_LAST_INSERTED] ASC);

