CREATE TABLE [VWSSTAGE].[VWS_CORONALEVEL_REGIONS] (
    [ID]                        INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_VWS_CORONALEVEL_REGIONS]) NOT NULL,
    [VEILIGHEIDSREGIO_NAAM]     VARCHAR (100) NULL,
    [VEILIGHEIDSREGIO_CODE]     VARCHAR (100) NULL,
    [CORONANIVEAU_CODE]         VARCHAR (100) NULL,
    [CORONANIVEAU_NAAM]         VARCHAR (100) NULL,
    [GELDIG_VANAF_DATUM]        VARCHAR (100) NULL,
    [GELDIG_TM_DATUM]           VARCHAR (100) NULL,
    [TEKSTUELE_DUIDING]         VARCHAR (100) NULL,
    [CONTACTPERSOON_1_NAAM]     VARCHAR (100) NULL,
    [CONTACTPERSOON_2_NAAM]     VARCHAR (100) NULL,
    [CONTACTPERSOON_1_EMAIL]    VARCHAR (100) NULL,
    [CONTACTPERSOON_2_EMAIL]    VARCHAR (100) NULL,
    [DOOR_WIE_INGEVULD]         VARCHAR (100) NULL,
    [DOOR_WIE_GECHECKT]         VARCHAR (100) NULL,
    [DATUM_INSCHALING]          VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]        DATETIME      DEFAULT (getdate()) NULL,
    [DATUM_VOLGENDE_INSCHALING] VARCHAR (250) NULL,
    [START_METING]              VARCHAR (250) NULL,
    [EINDE_METING]              VARCHAR (250) NULL,
    [POS_PER_100K_METING]       VARCHAR (255) NULL,
    [ZKH_PER_1000K_METING]      VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_CORONALEVEL_REGIONS_STAGE]
    ON [VWSSTAGE].[VWS_CORONALEVEL_REGIONS]([DATE_LAST_INSERTED] ASC);

