
CREATE   VIEW [DATATINO_PROTO_1].[POWERAPPS_PROTO_CONFIGURATIONS] AS

SELECT
	   [ID]
      ,[PROTO_ID]
      ,[PROTO_NAME]
      ,[ITEM_NAME]
	  ,  REPLACE( 
				REPLACE ( 
					REPLACE([VIEW_NAME], ']', '') 
					, '[', '')  
		, 'VWSDEST.', '')  AS [VIEW_NAME]
      ,[LAST_UPDATE_NAME]
      ,[CONSTRAINED]
      ,[CONSTRAINT_KEY_NAME]
      ,[CONSTRAINT_VALUE]
      ,[GROUPED]
      ,[GROUPED_KEY_NAME]
      ,[GROUPED_LAST_UPDATE_NAME]
      ,[LAYOUT_ID]
      ,[ACTIVE]
      ,[COLUMNS]
  FROM [DATATINO_PROTO_1].[V_PROTO_CONFIGURATIONS]