

CREATE   VIEW  [DATATINO_PROTO_1].[V_CONFIGURATIONS] AS

SELECT T0.[ID]
      ,T0.[NAME]            AS CONFIG_NAME
      ,T0.[PROTO_ID]
      ,T1.NAME              AS PROTO_NAME
      ,T0.[VIEW_ID]   
      ,T2.NAME              AS VIEW_NAME
      ,T0.[CONSTRAINED]
      ,T2.CONSTRAINT_KEY_NAME
      ,T2.CONSTRAINT_VALUE
      ,T2.GROUPED_KEY_NAME
      ,T2.GROUPED_LAST_UPDATE_NAME
      ,T2.LAST_UPDATE_NAME
      ,T0.[GROUPED]
      ,T0.[COLUMNS]
      ,T0.[MAPPING]
      ,T0.[LAYOUT_TYPE_ID]
      ,T3.NAME              AS LAYOUT_TYPE_NAME
      ,T0.[MOCK_ID]
      ,T0.[ACTIVE]
      ,T0.[DESCRIPTION]
  FROM [DATATINO_PROTO_1].[CONFIGURATIONS]      AS T0
  LEFT JOIN DATATINO_PROTO_1.PROTOS             AS T1 ON T1.ID = T0.PROTO_ID
  LEFT JOIN DATATINO_PROTO_1.VIEWS              AS T2 ON T2.ID = T0.VIEW_ID 
  LEFT JOIN DATATINO_PROTO_1.LAYOUT_TYPES       AS T3 ON T3.ID = T0.LAYOUT_TYPE_ID