-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSARCHIVE_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSARCHIVE_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY
  START WITH 1
  INCREMENT BY 1;
GO

 CREATE TABLE [VWSARCHIVE].[HOSPITAL_ADMISSIONS_PER_MUNICIPALITY](
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSARCHIVE_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY]),
	[DATE_OF_REPORT] [datetime] NULL,
	[DATE_OF_REPORT_UNIX] [bigint] NULL,
	[MUNICIPALITY_CODE] [varchar](100) NULL,
	[MUNICIPALITY_NAME] [varchar](200) NULL,
	[TOTAL_COUNTS_PER_DAY] [int] NULL,
	[MOVING_AVERAGE_HOSPITAL] [decimal](16, 1) NULL,
	[DATE_LAST_INSERTED] [datetime] NULL
);