-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSARCHIVE_COVID19_MUNICIPALITY_ARCHIVE_STAGE2]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSARCHIVE_COVID19_MUNICIPALITY_ARCHIVE_STAGE2
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSARCHIVE.RIVM_COVID_19_NUMBER_MUNICIPALITY_ARCHIVE_STAGE(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSARCHIVE_COVID19_MUNICIPALITY_ARCHIVE_STAGE2]),
    DATE_OF_REPORT VARCHAR(100) NULL,
	DATE_OF_PUBLICATION VARCHAR(100) NULL,
	MUNICIPALITY_CODE VARCHAR(100) NULL,
	MUNICIPALITY_NAME VARCHAR(100) NULL,
	PROVINCE VARCHAR(100) NULL,
	SECURITY_REGION_CODE VARCHAR(100) NULL,
	SECURITY_REGION_NAME VARCHAR(100) NULL,
	MUNICIPAL_HEALTH_SERVICE VARCHAR(100) NULL,
	ROAZ_REGION VARCHAR(100) NULL,
	TOTAL_REPORTED VARCHAR(100) NULL,
	HOSPITAL_ADMISSION VARCHAR(100) NULL,
	DECEASED VARCHAR(100) NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);