IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSARCHIVE_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSARCHIVE_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY
  START WITH 1
  INCREMENT BY 1;
GO

 CREATE TABLE VWSARCHIVE.POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSARCHIVE_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]),
	DATE_OF_REPORT DATETIME NULL,
	DATE_OF_REPORT_UNIX BIGINT NULL,
	MUNICIPALITY_CODE VARCHAR(100) NULL,
	MUNICIPALITY_NAME VARCHAR(200) NULL,
	INFECTED_DAILY_TOTAL INT NULL,
	INFECTED_DAILY_INCREASE DECIMAL(16,1) NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
 );