-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Intermediate table for casus municipality data from the RIVM

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSARCHIVE_COVID19_MUNICIPALITY_ARCHIVE_INTER]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSARCHIVE_COVID19_MUNICIPALITY_ARCHIVE_INTER
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSARCHIVE.RIVM_COVID_19_NUMBER_MUNICIPALITY_CUMULATIVE_ARCHIVE_INTER(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSARCHIVE_COVID19_MUNICIPALITY_ARCHIVE_INTER]),
	DATE_OF_REPORT DATETIME NULL,
	MUNICIPALITY_CODE VARCHAR(100) NULL,
	MUNICIPALITY_NAME VARCHAR(100) NULL,
	PROVINCE VARCHAR(100) NULL,
	TOTAL_REPORTED INT NULL,
	HOSPITAL_ADMISSION INT NULL,
	DECEASED INT NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);