IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSARCHIVE_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSARCHIVE_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY
  START WITH 1
  INCREMENT BY 1;
GO

 CREATE TABLE VWSARCHIVE.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSARCHIVE_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY]),
	DATE_OF_REPORT DATETIME NULL,
	DATE_OF_REPORT_UNIX BIGINT NULL,
	MUNICIPALITY_CODE VARCHAR(100) NULL,
	MUNICIPALITY_NAME VARCHAR(200) NULL,
	TOTAL_COUNTS_PER_DAY INT NULL,
	MOVING_AVERAGE_HOSPITAL DECIMAL(16, 1) NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
 );
