CREATE   PROCEDURE DATATINO.UPSERT_CHECK(
 @check_id BIGINT NULL,
 @workflow_name VARCHAR(200),
 @proto_name VARCHAR(200),
 @item_name VARCHAR(200)
) AS
DECLARE @workflow_id BIGINT;
SET @workflow_id = (SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = @workflow_name);
DECLARE @proto_id BIGINT;
SET @proto_id = (SELECT ID FROM DATATINO_PROTO.PROTOS WHERE PROTO_NAME = @proto_name);
DECLARE @item_id BIGINT;
SET @item_id = (SELECT ID FROM DATATINO_PROTO.V_PROTO_CONFIGURATIONS WHERE ITEM_NAME = @item_name AND PROTO_ID = @proto_id);
 
IF @check_id IS NULL
INSERT DATATINO.CHECKS (WORKFLOW_ID, PROTO_ID, ITEM_ID) 
VALUES (@workflow_id,
 @proto_id,
 @item_id);
ELSE
UPDATE DATATINO.CHECKS SET
 WORKFLOW_ID = @workflow_id,
 PROTO_ID = @proto_id,
 ITEM_ID = @item_id
WHERE ID = @check_id