-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.





-- all process_names in combination with the workflow should be unique

-- make the process_names unique - load national
UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Load_Nursing_Homes_Totalen_Verpleeghuis'
    WHERE PROCESS_NAME = 'Load_Nursing_Homes'
    AND NAME = 'Totalen_bewoners_verpleeghuis_per_meldingsdatumGGD_*.csv'
    AND [EXEC_ORDER]= 1
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');


UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Load_Nursing_Homes_Sterfte_Verpleeghuis'
    WHERE PROCESS_NAME = 'Load_Nursing_Homes'
    AND NAME = 'Sterfte_bewoners_verpleeghuis_per_overlijdensdatum_*.csv'
    AND [EXEC_ORDER]= 2
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Load_Nursing_Homes_Besmette_verpleeghuis'
    WHERE PROCESS_NAME = 'Load_Nursing_Homes'
    AND NAME = 'Aantal_besmette_verpleeghuis_locaties_per_publicatiedatumRIVM_*.csv'
    AND [EXEC_ORDER]= 3
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Load_Nursing_Homes_Totalen_gehandicaptenzorg'
    WHERE PROCESS_NAME = 'Load_Nursing_Homes'
    AND NAME = 'Totalen_bewoners_gehandicaptenzorginstelling_per_meldingsdatumGGD_*.csv'
    AND [EXEC_ORDER]= 4
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Load_Nursing_Homes_Besmette_gehandicaptenzorg'
    WHERE PROCESS_NAME = 'Load_Nursing_Homes'
    AND NAME = 'Aantal_besmette_gehandicaptenzorginstelling_locaties_per_publicatiedatumRIVM_*.csv'
    AND [EXEC_ORDER]= 5
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

-- make the process_names unique - load per security region
UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Load_Nursing_Homes_Totalen_Verpleeghuis_VR'
    WHERE PROCESS_NAME = 'Load_Nursing_Homes'
    AND NAME = 'Totalen_bewoners_verpleeghuis_per_meldingsdatumGGD_naar_veiligheidsregio_*.csv'
    AND [EXEC_ORDER]= 6
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Load_Nursing_Homes_Sterfte_Verpleeghuis_VR'
    WHERE PROCESS_NAME = 'Load_Nursing_Homes'
    AND NAME = 'Sterfte_bewoners_verpleeghuis_per_overlijdensdatum_naar_veiligheidsregio_*.csv'
    AND [EXEC_ORDER]= 7
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Load_Nursing_Homes_Besmette_verpleeghuis_VR'
    WHERE PROCESS_NAME = 'Load_Nursing_Homes'
    AND NAME = 'Aantal_besmette_verpleeghuis_locaties_per_publicatiedatumRIVM_naar_veiligheidsregio_*.csv'
    AND [EXEC_ORDER]= 8
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET 
    [PROCESS_NAME]= 'Load_Nursing_Homes_Totalen_gehandicaptenzorg_VR',
    -- Also set this to non-active due to current data source fault
    ACTIVE = 'false'
    WHERE PROCESS_NAME = 'Load_Nursing_Homes'
    AND NAME = 'Totalen_bewoners_gehandicaptenzorginstelling_per_meldingsdatumGGD_naar_veiligheidsregio_*.csv'
    AND [EXEC_ORDER]= 9
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Load_Nursing_Homes_Besmette_gehandicaptenzorg_VR'
    WHERE PROCESS_NAME = 'Load_Nursing_Homes'
    AND NAME = 'Aantal_besmette_gehandicaptenzorginstelling_locaties_per_publicatiedatumRIVM_naar_veiligheidsregio_*.csv'
    AND [EXEC_ORDER]= 10
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

-- make the process_names unique - inter national

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Inter_Nursing_Homes_Intake_totals'
    WHERE PROCESS_NAME = 'Inter_Nursing_Homes'
    AND NAME = 'DBO.SP_RIVM_INTAKE_NURSING_HOMES_TOTALS_INTER'
    AND [EXEC_ORDER]= 11
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Inter_Nursing_Homes_Deceased'
    WHERE PROCESS_NAME = 'Inter_Nursing_Homes'
    AND NAME = 'DBO.SP_RIVM_INTAKE_NURSING_HOMES_DECEASED_INTER'
    AND [EXEC_ORDER]= 12
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Inter_Nursing_Homes_Infected_Locations'
    WHERE PROCESS_NAME = 'Inter_Nursing_Homes'
    AND NAME = 'DBO.SP_RIVM_INTAKE_NURSING_HOMES_INFECTED_LOCATIONS_INTER'
    AND [EXEC_ORDER]= 13
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Inter_Nursing_Homes_Intake_totals_handicapped'
    WHERE PROCESS_NAME = 'Inter_Nursing_Homes'
    AND NAME = 'DBO.SP_RIVM_INTAKE_NURSING_HOMES_HANDICAPPED_TOTALS_INTER'
    AND [EXEC_ORDER]= 14
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Inter_Nursing_Homes_Infected_Locations_handicapped'
    WHERE PROCESS_NAME = 'Inter_Nursing_Homes'
    AND NAME = 'DBO.SP_RIVM_INTAKE_NURSING_HOMES_HANDICAPPED_INFECTED_LOCATIONS_INTER'
    AND [EXEC_ORDER]= 15
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

-- make the process_names unique - inter per VR

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Inter_Nursing_Homes_Intake_totals_VR'
    WHERE PROCESS_NAME = 'Inter_Nursing_Homes'
    AND NAME = 'DBO.SP_RIVM_INTAKE_NURSING_HOMES_TOTALS_PER_REGION_INTER'
    AND [EXEC_ORDER]= 16
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Inter_Nursing_Homes_Deceased_VR'
    WHERE PROCESS_NAME = 'Inter_Nursing_Homes'
    AND NAME = 'DBO.SP_RIVM_INTAKE_NURSING_HOMES_DECEASED_PER_REGION_INTER'
    AND [EXEC_ORDER]= 17
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Inter_Nursing_Homes_Infected_Locations_VR'
    WHERE PROCESS_NAME = 'Inter_Nursing_Homes'
    AND NAME = 'DBO.SP_RIVM_INTAKE_NURSING_HOMES_INFECTED_LOCATIONS_PER_REGION_INTER'
    AND [EXEC_ORDER]= 18
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Inter_Nursing_Homes_Intake_totals_handicapped_VR'
    WHERE PROCESS_NAME = 'Inter_Nursing_Homes'
    AND NAME = 'DBO.SP_RIVM_INTAKE_NURSING_HOMES_HANDICAPPED_TOTALS_PER_REGION_INTER'
    AND [EXEC_ORDER]= 19
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');

UPDATE DATATINO_ORCHESTRATOR.PROCESSES SET [PROCESS_NAME]= 'Inter_Nursing_Homes_Infected_Locations_handicapped_VR'
    WHERE PROCESS_NAME = 'Inter_Nursing_Homes'
    AND NAME = 'DBO.SP_RIVM_INTAKE_NURSING_HOMES_HANDICAPPED_INFECTED_LOCATIONS_PER_REGION_INTER'
    AND [EXEC_ORDER]= 20
    AND WORKFLOW_ID=(SELECT ID FROM DATATINO_ORCHESTRATOR.WORKFLOWS WHERE WORKFLOW_NAME = 'RIVM_NURSING_HOME_INTAKE');


-- after all processes are unique per workflow in the latest version, the duplicated ones should be removed
CREATE TABLE DATATINO_ORCHESTRATOR.[H_PROCESSES_ARCHIVE](
	[ID] [bigint] NOT NULL,
    [IDENTIFIER] bigint NOT NULL,
	[NAME] [varchar](200) NOT NULL,
	[LAST_RUN] [datetime] NULL,
    [STATUS] [CHAR](5) NOT NULL,
);

BEGIN TRANSACTION T1;
WITH BASE_CTE AS(
select * from [DATATINO_ORCHESTRATOR].[PROCESSES]
    WHERE ID in
        (SELECT ID
            FROM (
            SELECT
                T1.ID as ID,
                T1.WORKFLOW_ID as WORKFLOW_ID,
                T1.PROCESS_NAME as PROCESS_NAME,
                T1.NAME,
                T1.ACTIVE,
                ROW_NUMBER() OVER (PARTITION BY T1.workflow_id, T1.PROCESS_NAME ORDER BY T1.ACTIVE DESC) AS ROW_NUMBER
            FROM [DATATINO_ORCHESTRATOR].[PROCESSES] T1
            INNER JOIN (
                SELECT workflow_id, PROCESS_NAME from [DATATINO_ORCHESTRATOR].[PROCESSES] group by workflow_id, PROCESS_NAME HAVING COUNT(*)>1
            )  dup on
            T1.Workflow_id = dup.Workflow_id
            AND T1.PROCESS_NAME = dup.PROCESS_NAME
            ) a
        WHERE row_number != 1 and active = 'false'
        )
)

-- Copy history rows to archiving table.
INSERT INTO DATATINO_ORCHESTRATOR.[H_PROCESSES_ARCHIVE] (
    [ID], 
    [IDENTIFIER], 
    [NAME], 
    [LAST_RUN], 
    [STATUS]
)
(SELECT [ID], [IDENTIFIER], [NAME], [LAST_RUN], [STATUS] FROM DATATINO_ORCHESTRATOR.H_PROCESSES 
    WHERE IDENTIFIER IN (SELECT ID FROM BASE_CTE))

-- Delete old rows history rows
DELETE FROM DATATINO_ORCHESTRATOR.H_PROCESSES
     WHERE ID IN (SELECT ID FROM DATATINO_ORCHESTRATOR.[H_PROCESSES_ARCHIVE]);

-- Delete process rows
DELETE FROM DATATINO_ORCHESTRATOR.PROCESSES
    WHERE ID IN (SELECT IDENTIFIER FROM DATATINO_ORCHESTRATOR.[H_PROCESSES_ARCHIVE]);

COMMIT TRANSACTION T1;