CREATE TABLE [VWSDEST].[BEHAVIOR_NATIONAL_BY_AGE_GROUP] (
    [ID]                  INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_BEHAVIOR_NATIONAL_BY_AGE_GROUP]) NOT NULL,
    [DATE_OF_REPORT]      DATETIME      NULL,
    [DATE_OF_MEASUREMENT] DATETIME      NULL,
    [WAVE]                INT           NULL,
    [REGION_CODE]         VARCHAR (100) NULL,
    [SUBGROUP_CATEGORY]   VARCHAR (100) NULL,
    [SUBGROUP]            VARCHAR (100) NULL,
    [INDICATOR_CATEGORY]  VARCHAR (100) NULL,
    [INDICATOR]           VARCHAR (100) NULL,
    [SAMPLE_SIZE]         INT           NULL,
    [FIGURE_TYPE]         VARCHAR (100) NULL,
    [VALUE]               INT           NULL,
    [DATE_LAST_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_BEHAVIOR_NATIONAL_BY_AGE_GROUP]
    ON [VWSDEST].[BEHAVIOR_NATIONAL_BY_AGE_GROUP]([DATE_LAST_INSERTED] ASC);

