CREATE TABLE [VWSDEST].[BEHAVIOR_VACCINE_WILLINGNESS_BY_AGE_GROUP] (
    [ID]                  INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_BEHAVIOR_VACCINE_WILLINGNESS_BY_AGE_GROUP]) NOT NULL,
    [DATE_OF_MEASUREMENT] DATETIME        NULL,
    [DATE_START_UNIX]     BIGINT          NULL,
    [DATE_END_UNIX]       BIGINT          NULL,
    [WAVE]                INT             NULL,
    [AGE_GROUP]           VARCHAR (100)   NULL,
    [VACCINE_WILLINGNESS] NUMERIC (10, 1) NULL,
    [DATE_LAST_INSERTED]  DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_BEHAVIOR_VACCINE_WILLINGNESS_BY_AGE_GROUP]
    ON [VWSDEST].[BEHAVIOR_VACCINE_WILLINGNESS_BY_AGE_GROUP]([DATE_LAST_INSERTED] ASC, [DATE_OF_MEASUREMENT] ASC)
    INCLUDE([DATE_START_UNIX], [DATE_END_UNIX], [WAVE], [VACCINE_WILLINGNESS]);

