CREATE TABLE [VWSDEST].[BEHAVIOR_VACCINE_WILLINGNESS] (
    [ID]                  INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_BEHAVIOR_VACCINE_WILLINGNESS]) NOT NULL,
    [DATE_OF_MEASUREMENT] DATETIME        NULL,
    [DATE_START_UNIX]     BIGINT          NULL,
    [DATE_END_UNIX]       BIGINT          NULL,
    [WAVE]                INT             NULL,
    [VACCINE_WILLINGNESS] NUMERIC (10, 2) NULL,
    [VACCINATED]          NUMERIC (10, 2) NULL,
    [DATE_LAST_INSERTED]  DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_BEHAVIOR_VACCINE_WILLINGNESS]
    ON [VWSDEST].[BEHAVIOR_VACCINE_WILLINGNESS]([DATE_LAST_INSERTED] ASC, [DATE_OF_MEASUREMENT] ASC)
    INCLUDE([DATE_START_UNIX], [DATE_END_UNIX], [WAVE], [VACCINE_WILLINGNESS], [VACCINATED]);

