CREATE TABLE [VWSDEST].[CBS_DECEASED_VR] (
    [ID]                     INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_CBS_DECEASED_VR]) NOT NULL,
    [WEEK_START]             DATETIME      NULL,
    [WEEK_END]               DATETIME      NULL,
    [WEEK_START_UNIX]        BIGINT        NULL,
    [WEEK_END_UNIX]          BIGINT        NULL,
    [YEAR]                   INT           NULL,
    [WEEK]                   INT           NULL,
    [VRCODE]                 VARCHAR (100) NULL,
    [DECEASED_ACTUAL]        INT           NULL,
    [DECEASED_FORECAST]      INT           NULL,
    [DECEASED_FORECAST_HIGH] INT           NULL,
    [DECEASED_FORECAST_LOW]  INT           NULL,
    [DATE_LAST_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_VWSDEST_CBS_DECEASED_VR]
    ON [VWSDEST].[CBS_DECEASED_VR]([DATE_LAST_INSERTED] ASC, [VRCODE] ASC)
    INCLUDE([WEEK_START], [WEEK_END], [WEEK_START_UNIX], [WEEK_END_UNIX], [YEAR], [WEEK], [DECEASED_ACTUAL], [DECEASED_FORECAST], [DECEASED_FORECAST_LOW], [DECEASED_FORECAST_HIGH]);

