CREATE TABLE [VWSDEST].[CBS_DECEASED_PER_WEEK] (
    [ID]                     INT      DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_CBS_DECEASED_PER_WEEK]) NOT NULL,
    [WEEK_START]             DATETIME NULL,
    [WEEK_END]               DATETIME NULL,
    [WEEK_START_UNIX]        BIGINT   NULL,
    [WEEK_END_UNIX]          BIGINT   NULL,
    [YEAR]                   INT      NULL,
    [WEEK]                   INT      NULL,
    [DECEASED_ACTUAL]        INT      NULL,
    [DECEASED_FORECAST]      INT      NULL,
    [DECEASED_FORECAST_HIGH] INT      NULL,
    [DECEASED_FORECAST_LOW]  INT      NULL,
    [DATE_LAST_INSERTED]     DATETIME DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_WS_CBS_DECEASED_PER_WEEK]
    ON [VWSDEST].[CBS_DECEASED_PER_WEEK]([DATE_LAST_INSERTED] ASC, [WEEK_START] ASC)
    INCLUDE([WEEK_START_UNIX], [WEEK_END_UNIX], [DECEASED_ACTUAL], [DECEASED_FORECAST], [DECEASED_FORECAST_HIGH], [DECEASED_FORECAST_LOW]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_CBS_DECEASED_PER_WEEK_WS]
    ON [VWSDEST].[CBS_DECEASED_PER_WEEK]([WEEK_START] ASC)
    INCLUDE([WEEK_START_UNIX], [WEEK_END_UNIX], [DECEASED_ACTUAL], [DECEASED_FORECAST], [DECEASED_FORECAST_HIGH], [DECEASED_FORECAST_LOW], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_CBS_DECEASED_PER_WEEK_DLI_WS]
    ON [VWSDEST].[CBS_DECEASED_PER_WEEK]([DATE_LAST_INSERTED] ASC, [WEEK_START] ASC)
    INCLUDE([WEEK_START_UNIX], [WEEK_END_UNIX], [DECEASED_ACTUAL], [DECEASED_FORECAST], [DECEASED_FORECAST_HIGH], [DECEASED_FORECAST_LOW]);

