CREATE TABLE [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR] (
    [ID]                   INT             IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]   DATETIME        DEFAULT (getdate()) NOT NULL,
    [VERSION]              INT             NULL,
    [DATE_OF_REPORT]       DATETIME        NULL,
    [DATE_OF_STATISTICS]   DATETIME        NULL,
    [POPULATION]           BIGINT          NULL,
    [REGION_CODE]          VARCHAR (256)   NULL,
    [REGION_LEVEL]         VARCHAR (256)   NULL,
    [REGION_NAME]          VARCHAR (256)   NULL,
    [AGE_GROUP]            VARCHAR (256)   NULL,
    [BIRTHYEAR_RANGE]      VARCHAR (256)   NULL,
    [VACCINATION_CAMPAIGN] VARCHAR (256)   NULL,
    [PERCENTAGE]           NUMERIC (10, 2) NULL,
    [PERCENTAGE_LABEL]     VARCHAR (256)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DEST_CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR]
    ON [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [nci_CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR_REGIONCODE_AGEGROUP]
    ON [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR]([REGION_CODE] ASC, [AGE_GROUP] ASC)
    INCLUDE([BIRTHYEAR_RANGE], [DATE_LAST_INSERTED], [DATE_OF_STATISTICS], [PERCENTAGE], [PERCENTAGE_LABEL], [VACCINATION_CAMPAIGN]);

