CREATE TABLE [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR] (
    [ID]                                   INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]) NOT NULL,
    [DATE_OF_REPORT]                       DATETIME        NULL,
    [DATE_OF_STATISTICS]                   DATETIME        NULL,
    [REGION_CODE]                          VARCHAR (10)    NULL,
    [BIRTH_YEAR]                           VARCHAR (100)   NULL,
    [AGE_GROUP]                            VARCHAR (10)    NULL,
    [VACCINATION_COVERAGE_ALL]             VARCHAR (100)   NULL,
    [VACCINATION_COVERAGE_ALL_LABEL]       VARCHAR (100)   NULL,
    [VACCINATION_COVERAGE_COMPLETED]       VARCHAR (100)   NULL,
    [VACCINATION_COVERAGE_COMPLETED_LABEL] VARCHAR (100)   NULL,
    [DATE_LAST_INSERTED]                   DATETIME        DEFAULT (getdate()) NULL,
    [VACCINATION_SERIE]                    VARCHAR (100)   NULL,
    [PERCENTAGE]                           DECIMAL (19, 3) NULL,
    [PERCENTAGE_LABEL]                     VARCHAR (100)   NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_DOF_DOS_RC_CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]
    ON [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC, [DATE_OF_STATISTICS] ASC, [REGION_CODE] ASC)
    INCLUDE([BIRTH_YEAR], [AGE_GROUP], [VACCINATION_SERIE], [PERCENTAGE], [PERCENTAGE_LABEL]);


GO
CREATE NONCLUSTERED INDEX [NCI_VWSDEST_CIMS_VACCINATED_AGE_GROUP]
    ON [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC, [DATE_OF_STATISTICS] ASC, [REGION_CODE] ASC)
    INCLUDE([BIRTH_YEAR], [AGE_GROUP], [VACCINATION_COVERAGE_ALL], [VACCINATION_COVERAGE_ALL_LABEL], [VACCINATION_COVERAGE_COMPLETED], [VACCINATION_COVERAGE_COMPLETED_LABEL]);


GO
CREATE CLUSTERED INDEX [CI_DLI_VWSDEST_CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]
    ON [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]([DATE_LAST_INSERTED] ASC);

