CREATE TABLE [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN] (
    [ID]                              BIGINT          IDENTITY (1, 1) NOT NULL,
    [DATE_OF_REPORT]                  DATETIME        NULL,
    [DATE_OF_STATISTICS_WEEK_START]   DATETIME        NULL,
    [DATE_OF_STATISTICS_WEEK_END]     DATETIME        NULL,
    [BIRTH_COHORT]                    VARCHAR (100)   NULL,
    [AGE_GROUP]                       VARCHAR (100)   NULL,
    [AGE_GROUP_POPULATION]            BIGINT          NULL,
    [AGE_GROUP_POPULATION_PERCENTAGE] DECIMAL (16, 2) NULL,
    [VACCINATION_CAMPAIGN]            VARCHAR (100)   NULL,
    [RECEIVED]                        BIGINT          NULL,
    [COVERAGE]                        DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED]              DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_DOS_AG_CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN]
    ON [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN]([DATE_LAST_INSERTED] ASC, [DATE_OF_STATISTICS_WEEK_START] ASC, [DATE_OF_STATISTICS_WEEK_END] ASC, [AGE_GROUP] ASC);

