CREATE TABLE [VWSDEST].[CLUSTERS_INFECTED_PEOPLE] (
    [ID]                  INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_RIVM_CLUSTERS_INFECTED_PEOPLE]) NOT NULL,
    [DATE_OF_REPORT]      DATETIME        NULL,
    [DATE_OF_REPORT_UNIX] BIGINT          NULL,
    [ACTIVE_CLUSTERS]     INT             NULL,
    [CLUSTER_AVERAGE]     DECIMAL (16, 1) NULL,
    [DATE_LAST_INSERTED]  DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

