CREATE TABLE [VWSDEST].[DECEASED_PER_AGE_GROUP] (
    [ID]                     INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SP_DECEASED_PER_AGE_GROUP]) NOT NULL,
    [AGEGROUP]               VARCHAR (100)   NULL,
    [INHABITANTS_PERCENTAGE] DECIMAL (16, 1) NULL,
    [DEATHS]                 INT             NULL,
    [DEATHS_PERCENTAGE]      DECIMAL (16, 1) NULL,
    [DATE_LAST_INSERTED]     DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DECEASED_PER_AGE_GROUP]
    ON [VWSDEST].[DECEASED_PER_AGE_GROUP]([DATE_LAST_INSERTED] ASC)
    INCLUDE([AGEGROUP], [INHABITANTS_PERCENTAGE], [DEATHS], [DEATHS_PERCENTAGE]);

