CREATE TABLE [VWSDEST].[DECEASED_PER_MUNICIPALITY] (
    [ID]                  INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_DECEASED_PER_MUNICIPALITY]) NOT NULL,
    [DATE_OF_REPORT]      DATETIME      NULL,
    [DATE_OF_REPORT_UNIX] BIGINT        NULL,
    [MUNICIPALITY_CODE]   VARCHAR (100) NULL,
    [MUNICIPALITY_NAME]   VARCHAR (200) NULL,
    [DECEASED]            INT           NULL,
    [DATE_LAST_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

