CREATE TABLE [VWSDEST].[DISABILITY_VR] (
    [ID]                            INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_DISABILITY_VR]) NOT NULL,
    [DATE_OF_REPORT]                DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]           BIGINT          NULL,
    [VRCODE]                        VARCHAR (100)   NULL,
    [INFECTED_DISABILITY_DAILY]     INT             NULL,
    [DECEASED_DISABILITY_DAILY]     INT             NULL,
    [TOTAL_NEW_INFECTED_LOCATIONS]  INT             NULL,
    [TOTAL_INFECTED_LOCATIONS]      INT             NULL,
    [TOTAL_LOCATIONS]               INT             NULL,
    [PERCENTAGE_INFECTED_LOCATIONS] FLOAT (53)      NULL,
    [DATE_LAST_INSERTED]            DATETIME        DEFAULT (getdate()) NULL,
    [DATE_RANGE_START]              DATETIME        NULL,
    [DATE_OF_REPORTS_LAG]           DATETIME        NULL,
    [DATE_RANGE_START_LAG]          DATETIME        NULL,
    [7D_AVERAGE_TOTAL_INFECTED]     DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_INFECTED_LAG] DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_DECEASED]     DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_DECEASED_LAG] DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWSDEST_DISABILITY_VR]
    ON [VWSDEST].[DISABILITY_VR]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_DISABILITY_VR_DOR]
    ON [VWSDEST].[DISABILITY_VR]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [VRCODE], [INFECTED_DISABILITY_DAILY], [DECEASED_DISABILITY_DAILY], [TOTAL_NEW_INFECTED_LOCATIONS], [TOTAL_INFECTED_LOCATIONS], [PERCENTAGE_INFECTED_LOCATIONS], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_DISABILITY_VR_DLI_DOR]
    ON [VWSDEST].[DISABILITY_VR]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [VRCODE], [INFECTED_DISABILITY_DAILY], [DECEASED_DISABILITY_DAILY], [TOTAL_NEW_INFECTED_LOCATIONS], [TOTAL_INFECTED_LOCATIONS], [PERCENTAGE_INFECTED_LOCATIONS]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_DISABILITY_VR_DLI]
    ON [VWSDEST].[DISABILITY_VR]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT]);

