CREATE TABLE [VWSDEST].[DISABILITY_OLD] (
    [ID]                            INT        DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_DISABILITY]) NOT NULL,
    [DATE_OF_REPORT]                DATETIME   NULL,
    [DATE_OF_REPORT_UNIX]           BIGINT     NULL,
    [INFECTED_DISABILITY_DAILY]     INT        NULL,
    [DECEASED_DISABILITY_DAILY]     INT        NULL,
    [TOTAL_NEW_INFECTED_LOCATIONS]  INT        NULL,
    [TOTAL_INFECTED_LOCATIONS]      INT        NULL,
    [TOTAL_LOCATIONS]               INT        NULL,
    [PERCENTAGE_INFECTED_LOCATIONS] FLOAT (53) NULL,
    [DATE_LAST_INSERTED]            DATETIME   DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWSDEST_DISABILITY_DEST]
    ON [VWSDEST].[DISABILITY_OLD]([DATE_LAST_INSERTED] ASC);

