CREATE TABLE [VWSDEST].[ECDC_VACCINE_COVERAGE_TOTAL] (
    [ID]                             INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_ECDC_VACCINE_COVERAGE_TOTAL]) NOT NULL,
    [DATE_OF_REPORT]                 DATETIME        NULL,
    [DATE_OF_STATISTICS]             DATETIME        NULL,
    [BIRTH_YEAR]                     VARCHAR (100)   NULL,
    [VACCINATION_COVERAGE_ALL]       DECIMAL (19, 3) NULL,
    [VACCINATION_COVERAGE_COMPLETED] DECIMAL (19, 3) NULL,
    [DATE_LAST_INSERTED]             DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE CLUSTERED INDEX [CI_DLI_VWSDEST_ECDC_VACCINE_COVERAGE_TOTAL]
    ON [VWSDEST].[ECDC_VACCINE_COVERAGE_TOTAL]([DATE_LAST_INSERTED] ASC);

