CREATE TABLE [VWSDEST].[ELDERLY_AT_HOME_VR] (
    [ID]                                            INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_ELDERLY_AT_HOME_VR]) NOT NULL,
    [DATE_OF_REPORT]                                DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]                           BIGINT          NULL,
    [VRCODE]                                        VARCHAR (100)   NULL,
    [INFECTED_ELDERLY_AT_HOME_DAILY]                INT             NULL,
    [INFECTED_ELDERLY_AT_HOME_DAILY_PER_100K]       FLOAT (53)      NULL,
    [DECEASED_ELDERLY_AT_HOME_DAILY]                INT             NULL,
    [DATE_LAST_INSERTED]                            DATETIME        DEFAULT (getdate()) NULL,
    [DATE_RANGE_START]                              DATETIME        NULL,
    [DATE_OF_REPORTS_LAG]                           DATETIME        NULL,
    [DATE_RANGE_START_LAG]                          DATETIME        NULL,
    [7D_AVERAGE_INFECTED_ELDERLY_AT_HOME_DAILY]     DECIMAL (16, 2) NULL,
    [7D_AVERAGE_INFECTED_ELDERLY_AT_HOME_DAILY_LAG] DECIMAL (16, 2) NULL,
    [7D_AVERAGE_DECEASED_ELDERLY_AT_HOME_DAILY]     DECIMAL (16, 2) NULL,
    [7D_AVERAGE_DECEASED_ELDERLY_AT_HOME_DAILY_LAG] DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWSDEST_ELDERLY_AT_HOME_VR]
    ON [VWSDEST].[ELDERLY_AT_HOME_VR]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_ELDERLY_AT_HOME_VR_DLI_DOR]
    ON [VWSDEST].[ELDERLY_AT_HOME_VR]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [VRCODE], [INFECTED_ELDERLY_AT_HOME_DAILY], [INFECTED_ELDERLY_AT_HOME_DAILY_PER_100K], [DECEASED_ELDERLY_AT_HOME_DAILY]);

