CREATE TABLE [VWSDEST].[ESCALATIONLEVELS_PER_REGION] (
    [ID]                        INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_ESCALATIONLEVELS_PER_REGION]) NOT NULL,
    [DATE_OF_REPORT]            DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]       BIGINT          NULL,
    [VRCODE]                    VARCHAR (100)   NULL,
    [ESCALATION_LEVEL]          INT             NULL,
    [DATE_OF_START_VALIDITY]    DATETIME        NULL,
    [DATE_OF_END_VALIDITY]      DATETIME        NULL,
    [DATE_LAST_INSERTED]        DATETIME        DEFAULT (getdate()) NULL,
    [DATE_LAST_DETERMINED]      DATETIME        NULL,
    [DATUM_VOLGENDE_INSCHALING] DATETIME        NULL,
    [START_METING]              DATETIME        NULL,
    [EINDE_METING]              DATETIME        NULL,
    [POS_PER_100K_METING]       DECIMAL (16, 2) NULL,
    [ZKH_PER_1000K_METING]      DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_ESCALATIONLEVELS_PER_REGION_DEST]
    ON [VWSDEST].[ESCALATIONLEVELS_PER_REGION]([DATE_LAST_INSERTED] ASC);

