CREATE TABLE [VWSDEST].[G_NUMBER_VR] (
    [ID]                    INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_G_NUMBER_VR]) NOT NULL,
    [DATE_OF_REPORT]        DATETIME        NULL,
    [DATE_RANGE_START]      DATETIME        NULL,
    [VRCODE]                VARCHAR (100)   NULL,
    [POSITIVE_DAILY_7D_SUM] INT             NULL,
    [G_NUMBER]              DECIMAL (16, 1) NULL,
    [DATE_LAST_INSERTED]    DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_G_NUMBER_VR_VRCODE_G_NUMBER]
    ON [VWSDEST].[G_NUMBER_VR]([VRCODE] ASC, [G_NUMBER] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_RANGE_START], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_G_NUMBER_VR_VRCODE_DATE_LAST_INSERTED_G_NUMBER]
    ON [VWSDEST].[G_NUMBER_VR]([VRCODE] ASC, [DATE_LAST_INSERTED] ASC, [G_NUMBER] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_RANGE_START]);

