CREATE TABLE [VWSDEST].[GGD_TESTED_PEOPLE_NL] (
    [ID]                                  INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_GGD_TESTED_PEOPLE_NL]) NOT NULL,
    [DATE_OF_STATISTICS]                  DATETIME        NULL,
    [DATE_RANGE_START]                    DATETIME        NULL,
    [DATE_OF_STATISTICS_LAG]              DATETIME        NULL,
    [DATE_RANGE_START_LAG]                DATETIME        NULL,
    [NEW_DATE_OF_REPORT_UNIX]             BIGINT          NULL,
    [DATE_RANGE_START_UNIX]               BIGINT          NULL,
    [OLD_DATE_OF_REPORT_UNIX]             BIGINT          NULL,
    [TESTS]                               INT             NULL,
    [POSITIVE_TESTS]                      INT             NULL,
    [PERCENTAGE_POSITIVE]                 DECIMAL (16, 1) NULL,
    [7D_AVERAGE_TESTS]                    DECIMAL (16, 1) NULL,
    [7D_AVERAGE_TESTS_LAG]                INT             NULL,
    [7D_AVERAGE_TESTS_DIFF]               INT             NULL,
    [7D_AVERAGE_POSITIVE_TESTS]           DECIMAL (16, 1) NULL,
    [7D_AVERAGE_POSITIVE_TESTS_LAG]       INT             NULL,
    [7D_AVERAGE_POSITIVE_TESTS_DIFF]      INT             NULL,
    [7D_AVERAGE_PERCENTAGE_POSITIVE]      DECIMAL (16, 1) NULL,
    [7D_AVERAGE_PERCENTAGE_POSITIVE_LAG]  DECIMAL (16, 1) NULL,
    [7D_AVERAGE_PERCENTAGE_POSITIVE_DIFF] DECIMAL (16, 1) NULL,
    [DATE_LAST_INSERTED]                  DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_NL_DATE_LAST_INSERTED_7]
    ON [VWSDEST].[GGD_TESTED_PEOPLE_NL]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_STATISTICS]);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_NL_DATE_LAST_INSERTED_6]
    ON [VWSDEST].[GGD_TESTED_PEOPLE_NL]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_STATISTICS]);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_NL_DATE_LAST_INSERTED_5]
    ON [VWSDEST].[GGD_TESTED_PEOPLE_NL]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_STATISTICS], [NEW_DATE_OF_REPORT_UNIX], [TESTS]);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_NL_DATE_LAST_INSERTED_4]
    ON [VWSDEST].[GGD_TESTED_PEOPLE_NL]([DATE_LAST_INSERTED] ASC)
    INCLUDE([NEW_DATE_OF_REPORT_UNIX], [DATE_RANGE_START_UNIX], [7D_AVERAGE_TESTS], [7D_AVERAGE_POSITIVE_TESTS], [7D_AVERAGE_PERCENTAGE_POSITIVE]);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_NL_DATE_LAST_INSERTED_3]
    ON [VWSDEST].[GGD_TESTED_PEOPLE_NL]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_STATISTICS], [NEW_DATE_OF_REPORT_UNIX], [PERCENTAGE_POSITIVE]);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_NL_DATE_LAST_INSERTED_2]
    ON [VWSDEST].[GGD_TESTED_PEOPLE_NL]([DATE_LAST_INSERTED] ASC)
    INCLUDE([NEW_DATE_OF_REPORT_UNIX], [TESTS], [POSITIVE_TESTS], [PERCENTAGE_POSITIVE]);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_NL_DATE_LAST_INSERTED]
    ON [VWSDEST].[GGD_TESTED_PEOPLE_NL]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_STATISTICS]);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_NL]
    ON [VWSDEST].[GGD_TESTED_PEOPLE_NL]([DATE_OF_STATISTICS] ASC, [DATE_OF_STATISTICS_LAG] ASC, [DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_RANGE_START], [DATE_RANGE_START_LAG], [NEW_DATE_OF_REPORT_UNIX], [DATE_RANGE_START_UNIX], [OLD_DATE_OF_REPORT_UNIX], [TESTS], [POSITIVE_TESTS], [PERCENTAGE_POSITIVE], [7D_AVERAGE_TESTS], [7D_AVERAGE_TESTS_LAG], [7D_AVERAGE_TESTS_DIFF], [7D_AVERAGE_POSITIVE_TESTS], [7D_AVERAGE_POSITIVE_TESTS_LAG], [7D_AVERAGE_POSITIVE_TESTS_DIFF], [7D_AVERAGE_PERCENTAGE_POSITIVE], [7D_AVERAGE_PERCENTAGE_POSITIVE_LAG], [7D_AVERAGE_PERCENTAGE_POSITIVE_DIFF]);

