CREATE TABLE [VWSDEST].[HOSPITAL_ADMISSIONS] (
    [ID]                      INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_HOSPITAL_ADMISSIONS]) NOT NULL,
    [DATE_OF_REPORT]          DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]     BIGINT          NULL,
    [TOTAL_COUNTS_PER_DAY]    INT             NULL,
    [MOVING_AVERAGE_HOSPITAL] DECIMAL (16, 1) NULL,
    [DATE_LAST_INSERTED]      DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_HOSPITAL_ADMISSIONS_DOR_2]
    ON [VWSDEST].[HOSPITAL_ADMISSIONS]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MOVING_AVERAGE_HOSPITAL], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_HOSPITAL_ADMISSIONS_DOR]
    ON [VWSDEST].[HOSPITAL_ADMISSIONS]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MOVING_AVERAGE_HOSPITAL], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_HOSPITAL_ADMISSIONS_DLI_DOR_2]
    ON [VWSDEST].[HOSPITAL_ADMISSIONS]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MOVING_AVERAGE_HOSPITAL]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_HOSPITAL_ADMISSIONS_DLI_DOR]
    ON [VWSDEST].[HOSPITAL_ADMISSIONS]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MOVING_AVERAGE_HOSPITAL]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_HOSPITAL_ADMISSIONS_DLI]
    ON [VWSDEST].[HOSPITAL_ADMISSIONS]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_REPORT_UNIX], [TOTAL_COUNTS_PER_DAY], [MOVING_AVERAGE_HOSPITAL]);

