CREATE TABLE [VWSDEST].[HOSPITAL_ADMISSIONS_PER_MUNICIPALITY] (
    [ID]                      INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY]) NOT NULL,
    [DATE_OF_REPORT]          DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]     BIGINT          NULL,
    [MUNICIPALITY_CODE]       VARCHAR (100)   NULL,
    [MUNICIPALITY_NAME]       VARCHAR (200)   NULL,
    [TOTAL_COUNTS_PER_DAY]    INT             NULL,
    [MOVING_AVERAGE_HOSPITAL] DECIMAL (16, 1) NULL,
    [DATE_LAST_INSERTED]      DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_TOTAL]
    ON [VWSDEST].[HOSPITAL_ADMISSIONS_PER_MUNICIPALITY]([MUNICIPALITY_CODE] ASC, [DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MUNICIPALITY_NAME], [MOVING_AVERAGE_HOSPITAL]);


GO
CREATE NONCLUSTERED INDEX [IX_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY]
    ON [VWSDEST].[HOSPITAL_ADMISSIONS_PER_MUNICIPALITY]([MUNICIPALITY_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_DOR]
    ON [VWSDEST].[HOSPITAL_ADMISSIONS_PER_MUNICIPALITY]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MUNICIPALITY_CODE], [MOVING_AVERAGE_HOSPITAL], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_DLI_DOR_2]
    ON [VWSDEST].[HOSPITAL_ADMISSIONS_PER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MUNICIPALITY_CODE], [MOVING_AVERAGE_HOSPITAL]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_DLI_DOR]
    ON [VWSDEST].[HOSPITAL_ADMISSIONS_PER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MUNICIPALITY_CODE], [MUNICIPALITY_NAME], [MOVING_AVERAGE_HOSPITAL]);

