CREATE TABLE [VWSDEST].[HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_BASE] (
    [ID]                      INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_BASE]) NOT NULL,
    [DATE_OF_REPORT]          DATETIME        NULL,
    [NEW_DATE_OF_REPORT_UNIX] BIGINT          NULL,
    [GMCODE]                  VARCHAR (20)    NULL,
    [OLD_DATE_OF_REPORT_UNIX] BIGINT          NULL,
    [OLD_VALUE]               DECIMAL (16, 2) NULL,
    [DIFFERENCE]              DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_BASE]
    ON [VWSDEST].[HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_BASE]([DATE_OF_REPORT] ASC, [GMCODE] ASC)
    INCLUDE([NEW_DATE_OF_REPORT_UNIX], [OLD_DATE_OF_REPORT_UNIX], [OLD_VALUE], [DIFFERENCE]);

