CREATE TABLE [VWSDEST].[INFECTIOUS_PEOPLE] (
    [ID]                         INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_INFECTIOUS_PEOPLE]) NOT NULL,
    [DATE_OF_REPORT]             DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]        BIGINT          NULL,
    [INFECTIOUS_LOW]             INT             NULL,
    [INFECTIOUS_LOW_NORMALIZED]  DECIMAL (16, 1) NULL,
    [INFECTIOUS_AVG]             INT             NULL,
    [INFECTIOUS_AVG_NORMALIZED]  DECIMAL (16, 1) NULL,
    [INFECTIOUS_HIGH]            INT             NULL,
    [INFECTIOUS_HIGH_NORMALIZED] DECIMAL (16, 1) NULL,
    [DATE_LAST_INSERTED]         DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_INFECTIOUS_PEOPLE_DOR]
    ON [VWSDEST].[INFECTIOUS_PEOPLE]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTIOUS_AVG_NORMALIZED], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_INFECTIOUS_PEOPLE_DLI_DOR]
    ON [VWSDEST].[INFECTIOUS_PEOPLE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_REPORT_UNIX], [INFECTIOUS_LOW], [INFECTIOUS_LOW_NORMALIZED], [INFECTIOUS_AVG], [INFECTIOUS_AVG_NORMALIZED], [INFECTIOUS_HIGH], [INFECTIOUS_HIGH_NORMALIZED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_INFECTIOUS_PEOPLE_DLI_ALL]
    ON [VWSDEST].[INFECTIOUS_PEOPLE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTIOUS_LOW_NORMALIZED], [INFECTIOUS_AVG_NORMALIZED], [INFECTIOUS_HIGH_NORMALIZED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_INFECTIOUS_PEOPLE_DLI]
    ON [VWSDEST].[INFECTIOUS_PEOPLE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTIOUS_LOW], [INFECTIOUS_AVG], [INFECTIOUS_HIGH]);

