CREATE TABLE [VWSDEST].[INTENSIVE_CARE_ADMISSIONS] (
    [ID]                  INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_INTENSIVE_CARE_ADMISSIONS]) NOT NULL,
    [DATE_OF_REPORT]      DATETIME        NULL,
    [DATE_OF_REPORT_UNIX] BIGINT          NULL,
    [MOVING_AVERAGE_IC]   DECIMAL (16, 1) NULL,
    [TOTAL_COUNT]         INT             NULL,
    [DATE_LAST_INSERTED]  DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_INTENSIVE_CARE_ADMISSIONS_DOR]
    ON [VWSDEST].[INTENSIVE_CARE_ADMISSIONS]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MOVING_AVERAGE_IC], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_INTENSIVE_CARE_ADMISSIONS_DLI_DOR]
    ON [VWSDEST].[INTENSIVE_CARE_ADMISSIONS]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MOVING_AVERAGE_IC]);

