CREATE TABLE [VWSDEST].[NICE_HOSPITAL_GM] (
    [ID]                         INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_NICE_HOSPITAL_GM]) NOT NULL,
    [DATE_OF_STATISTICS]         DATETIME        NULL,
    [GM_CODE]                    VARCHAR (100)   NULL,
    [GM_NAME]                    VARCHAR (100)   NULL,
    [REPORTED]                   INT             NULL,
    [HOSPITALIZED]               INT             NULL,
    [HOSPITALIZED_3D_AVG]        DECIMAL (16, 2) NULL,
    [REPORTED_3D_AVG]            DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED]         DATETIME        DEFAULT (getdate()) NULL,
    [REPORTED_PER_MIL_LAST_WEEK] INT             NULL,
    [WEEK_START]                 DATETIME        NULL,
    [HOSPITALIZED_7D_AVG]        DECIMAL (16, 2) NULL,
    [WEEK_START_LAG]             DATETIME        NULL,
    [HOSPITALIZED_7D_AVG_LAG]    DECIMAL (16, 2) NULL,
    [REPORTED_7D_AVG]            DECIMAL (16, 2) NULL,
    [REPORTED_7D_AVG_LAG]        DECIMAL (16, 2) NULL,
    [HOSPITALIZED_7D_AVG_CUTOFF] DECIMAL (16, 2) NULL,
    [HOSPITALIZED_PER_100000]    DECIMAL (16, 2) NULL,
    [HOSPITALIZED_7D]            INT             NULL,
    [HOSPITALIZED_7D_PER_100000] DECIMAL (16, 2) NULL
);


GO
CREATE CLUSTERED INDEX [IX_VWSDEST_NICE_HOSPITAL_GM_CI]
    ON [VWSDEST].[NICE_HOSPITAL_GM]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_NICE_HOSPITAL_GM_DEST]
    ON [VWSDEST].[NICE_HOSPITAL_GM]([DATE_OF_STATISTICS] ASC, [DATE_LAST_INSERTED] ASC, [GM_CODE] ASC)
    INCLUDE([HOSPITALIZED], [HOSPITALIZED_3D_AVG]);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_NICE_HOSPITAL_GM_DLI_DS]
    ON [VWSDEST].[NICE_HOSPITAL_GM]([DATE_LAST_INSERTED] ASC, [DATE_OF_STATISTICS] ASC)
    INCLUDE([GM_CODE], [REPORTED], [HOSPITALIZED_3D_AVG]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NICE_HOSPITAL_GM_DS]
    ON [VWSDEST].[NICE_HOSPITAL_GM]([DATE_OF_STATISTICS] ASC)
    INCLUDE([GM_CODE], [GM_NAME], [HOSPITALIZED_3D_AVG], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NICE_HOSPITAL_GM_DLI_DS]
    ON [VWSDEST].[NICE_HOSPITAL_GM]([DATE_LAST_INSERTED] ASC, [DATE_OF_STATISTICS] ASC)
    INCLUDE([GM_CODE], [GM_NAME], [HOSPITALIZED_3D_AVG]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NICE_HOSPITAL_GM_DLI_3]
    ON [VWSDEST].[NICE_HOSPITAL_GM]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_STATISTICS], [GM_CODE], [GM_NAME], [REPORTED], [HOSPITALIZED], [HOSPITALIZED_7D_AVG]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NICE_HOSPITAL_GM_DLI_2]
    ON [VWSDEST].[NICE_HOSPITAL_GM]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_STATISTICS], [GM_CODE], [GM_NAME], [REPORTED], [HOSPITALIZED]);

