CREATE TABLE [VWSDEST].[NICE_HOSPITAL_GM_BASE] (
    [ID]                      INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_NICE_HOSPITAL_GM_BASE]) NOT NULL,
    [DATE_OF_REPORT]          DATETIME        NULL,
    [NEW_DATE_OF_REPORT_UNIX] BIGINT          NULL,
    [GMCODE]                  VARCHAR (100)   NULL,
    [OLD_DATE_OF_REPORT_UNIX] BIGINT          NULL,
    [OLD_VALUE]               DECIMAL (16, 2) NULL,
    [DIFFERENCE]              DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED]      DATETIME        DEFAULT (getdate()) NULL,
    [OLD_VALUE_REPORTED]      INT             NULL,
    [DIFFERENCE_REPORTED]     INT             NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_NICE_HOSPITAL_GM_BASE_GMCODE_DATE_LAST_INSERTED]
    ON [VWSDEST].[NICE_HOSPITAL_GM_BASE]([GMCODE] ASC, [DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [NEW_DATE_OF_REPORT_UNIX], [OLD_DATE_OF_REPORT_UNIX], [OLD_VALUE_REPORTED], [DIFFERENCE_REPORTED]);


GO
CREATE NONCLUSTERED INDEX [IX_NICE_HOSPITAL_GM_BASE_GMCODE]
    ON [VWSDEST].[NICE_HOSPITAL_GM_BASE]([GMCODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_NICE_HOSPITAL_GM_BASE]
    ON [VWSDEST].[NICE_HOSPITAL_GM_BASE]([DATE_OF_REPORT] ASC, [DATE_LAST_INSERTED] ASC, [GMCODE] ASC)
    INCLUDE([DIFFERENCE], [OLD_VALUE]);

