CREATE TABLE [VWSDEST].[NICE_HOSPITAL_NL] (
    [ID]                         INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_NICE_HOSPITAL_NL]) NOT NULL,
    [DATE_OF_STATISTICS]         DATETIME        NULL,
    [REPORTED]                   INT             NULL,
    [HOSPITALIZED]               INT             NULL,
    [HOSPITALIZED_3D_AVG]        DECIMAL (16, 2) NULL,
    [REPORTED_3D_AVG]            DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED]         DATETIME        DEFAULT (getdate()) NULL,
    [REPORTED_PER_MIL_LAST_WEEK] INT             NULL,
    [WEEK_START]                 DATETIME        NULL,
    [HOSPITALIZED_7D_AVG]        DECIMAL (16, 2) NULL,
    [WEEK_START_LAG]             DATETIME        NULL,
    [HOSPITALIZED_7D_AVG_LAG]    DECIMAL (16, 2) NULL,
    [REPORTED_7D_AVG]            DECIMAL (16, 2) NULL,
    [REPORTED_7D_AVG_LAG]        DECIMAL (16, 2) NULL,
    [HOSPITALIZED_7D_AVG_CUTOFF] DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_NICE_HOSPITAL_NL_DATE_LAST_INSERTED_10]
    ON [VWSDEST].[NICE_HOSPITAL_NL]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_STATISTICS], [REPORTED], [HOSPITALIZED]);

