CREATE TABLE [VWSDEST].[NURSING_HOMES_PER_REGION] (
    [ID]                            INT             DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSDEST_NURSING_HOMES_PER_REGION]) NOT NULL,
    [DATE_OF_REPORT]                DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]           BIGINT          NULL,
    [VRCODE]                        VARCHAR (100)   NULL,
    [INFECTED_NURSERY_DAILY]        INT             NULL,
    [DECEASED_NURSERY_DAILY]        INT             NULL,
    [TOTAL_NEW_REPORTED_LOCATIONS]  INT             NULL,
    [TOTAL_REPORTED_LOCATIONS]      INT             NULL,
    [INFECTED_LOCATIONS_PERCENTAGE] DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED]            DATETIME        DEFAULT (getdate()) NULL,
    [DATE_RANGE_START]              DATETIME        NULL,
    [DATE_OF_REPORTS_LAG]           DATETIME        NULL,
    [DATE_RANGE_START_LAG]          DATETIME        NULL,
    [7D_AVERAGE_TOTAL_INFECTED]     DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_INFECTED_LAG] DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_DECEASED]     DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_DECEASED_LAG] DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DIFFERENCE_NURSING_HOME__NEWLY_INFECTED_PEOPLE_PER_REGION_DOR]
    ON [VWSDEST].[NURSING_HOMES_PER_REGION]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [VRCODE], [INFECTED_NURSERY_DAILY], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DIFFERENCE_NURSING_HOME__NEWLY_INFECTED_PEOPLE_PER_REGION_DLI_DOR]
    ON [VWSDEST].[NURSING_HOMES_PER_REGION]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [VRCODE], [INFECTED_NURSERY_DAILY]);


GO
CREATE NONCLUSTERED INDEX [IX_DIFFERENCE_NURSING_HOME__INFECTED_LOCATIONS_TOTAL_PER_REGION_VR_DOR]
    ON [VWSDEST].[NURSING_HOMES_PER_REGION]([VRCODE] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [TOTAL_REPORTED_LOCATIONS], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DIFFERENCE_NURSING_HOME__INFECTED_LOCATIONS_TOTAL_PER_REGION_VR_DLI_DOR]
    ON [VWSDEST].[NURSING_HOMES_PER_REGION]([VRCODE] ASC, [DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [TOTAL_REPORTED_LOCATIONS]);


GO
CREATE NONCLUSTERED INDEX [IX_DIFFERENCE_NURSING_HOME__INFECTED_LOCATIONS_TOTAL_PER_REGION_DOR]
    ON [VWSDEST].[NURSING_HOMES_PER_REGION]([VRCODE] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DIFFERENCE_NURSING_HOME__DECEASED_DAILY_PER_REGION_DOR_VR]
    ON [VWSDEST].[NURSING_HOMES_PER_REGION]([DATE_OF_REPORT] ASC)
    INCLUDE([VRCODE], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DIFFERENCE_NURSING_HOME__DECEASED_DAILY_PER_REGION_DOR]
    ON [VWSDEST].[NURSING_HOMES_PER_REGION]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [VRCODE], [DECEASED_NURSERY_DAILY], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DIFFERENCE_NURSING_HOME__DECEASED_DAILY_PER_REGION_DLI_DOR]
    ON [VWSDEST].[NURSING_HOMES_PER_REGION]([DATE_OF_REPORT] ASC, [DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [VRCODE], [DECEASED_NURSERY_DAILY]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOMES_PER_REGION]
    ON [VWSDEST].[NURSING_HOMES_PER_REGION]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [VRCODE], [INFECTED_NURSERY_DAILY], [DECEASED_NURSERY_DAILY], [TOTAL_NEW_REPORTED_LOCATIONS], [TOTAL_REPORTED_LOCATIONS], [INFECTED_LOCATIONS_PERCENTAGE]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOME_REGIONS_DOR_VR]
    ON [VWSDEST].[NURSING_HOMES_PER_REGION]([DATE_OF_REPORT] ASC, [VRCODE] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTED_NURSERY_DAILY], [DECEASED_NURSERY_DAILY], [TOTAL_NEW_REPORTED_LOCATIONS], [TOTAL_REPORTED_LOCATIONS], [INFECTED_LOCATIONS_PERCENTAGE], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOME_REGIONS_DLI_DOR]
    ON [VWSDEST].[NURSING_HOMES_PER_REGION]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [VRCODE], [INFECTED_NURSERY_DAILY], [DECEASED_NURSERY_DAILY], [TOTAL_NEW_REPORTED_LOCATIONS], [TOTAL_REPORTED_LOCATIONS], [INFECTED_LOCATIONS_PERCENTAGE]);

