CREATE TABLE [VWSDEST].[NURSING_HOMES_TOTALS] (
    [ID]                            INT             DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSDEST_NURSING_HOMES_TOTALS]) NOT NULL,
    [DATE_OF_REPORT]                DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]           BIGINT          NULL,
    [INFECTED_NURSERY_DAILY]        INT             NULL,
    [DECEASED_NURSERY_DAILY]        INT             NULL,
    [TOTAL_NEW_REPORTED_LOCATIONS]  INT             NULL,
    [TOTAL_REPORTED_LOCATIONS]      INT             NULL,
    [DATE_LAST_INSERTED]            DATETIME        DEFAULT (getdate()) NULL,
    [DATE_RANGE_START]              DATETIME        NULL,
    [DATE_OF_REPORTS_LAG]           DATETIME        NULL,
    [DATE_RANGE_START_LAG]          DATETIME        NULL,
    [7D_AVERAGE_TOTAL_INFECTED]     DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_INFECTED_LAG] DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_DECEASED]     DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_DECEASED_LAG] DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOMES_TOTALS_DOR_TRL]
    ON [VWSDEST].[NURSING_HOMES_TOTALS]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [TOTAL_REPORTED_LOCATIONS], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOMES_TOTALS_DOR_TNRL]
    ON [VWSDEST].[NURSING_HOMES_TOTALS]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [TOTAL_NEW_REPORTED_LOCATIONS], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOMES_TOTALS_DOR_IND]
    ON [VWSDEST].[NURSING_HOMES_TOTALS]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTED_NURSERY_DAILY], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOMES_TOTALS_DOR_DND]
    ON [VWSDEST].[NURSING_HOMES_TOTALS]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [DECEASED_NURSERY_DAILY], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOMES_TOTALS_DOR]
    ON [VWSDEST].[NURSING_HOMES_TOTALS]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTED_NURSERY_DAILY], [DECEASED_NURSERY_DAILY], [TOTAL_NEW_REPORTED_LOCATIONS], [TOTAL_REPORTED_LOCATIONS], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_TRL]
    ON [VWSDEST].[NURSING_HOMES_TOTALS]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [TOTAL_REPORTED_LOCATIONS]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_TNRL]
    ON [VWSDEST].[NURSING_HOMES_TOTALS]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [TOTAL_NEW_REPORTED_LOCATIONS]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_IND]
    ON [VWSDEST].[NURSING_HOMES_TOTALS]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTED_NURSERY_DAILY]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_DND]
    ON [VWSDEST].[NURSING_HOMES_TOTALS]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [DECEASED_NURSERY_DAILY]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR]
    ON [VWSDEST].[NURSING_HOMES_TOTALS]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTED_NURSERY_DAILY], [DECEASED_NURSERY_DAILY], [TOTAL_NEW_REPORTED_LOCATIONS], [TOTAL_REPORTED_LOCATIONS]);

