CREATE TABLE [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE] (
    [ID]                      INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]) NOT NULL,
    [DATE_OF_REPORT]          DATETIME        NULL,
    [NEW_DATE_OF_REPORT_UNIX] BIGINT          NULL,
    [GMCODE]                  VARCHAR (20)    NULL,
    [OLD_DATE_OF_REPORT_UNIX] BIGINT          NULL,
    [OLD_VALUE]               DECIMAL (16, 2) NULL,
    [DIFFERENCE]              DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED]      DATETIME        DEFAULT (getdate()) NULL,
    [OLD_VALUE_PER_100K]      DECIMAL (16, 2) NULL,
    [DIFFERENCE_PER_100K]     DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_6]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]([GMCODE] ASC)
    INCLUDE([DATE_OF_REPORT], [NEW_DATE_OF_REPORT_UNIX], [OLD_DATE_OF_REPORT_UNIX], [OLD_VALUE], [DIFFERENCE], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_5]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]([DATE_OF_REPORT] ASC)
    INCLUDE([GMCODE], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_4]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [NEW_DATE_OF_REPORT_UNIX], [GMCODE], [OLD_DATE_OF_REPORT_UNIX], [OLD_VALUE], [DIFFERENCE]);


GO
CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_3]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]([GMCODE] ASC, [DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_2]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]([GMCODE] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_100K]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]([DATE_LAST_INSERTED] ASC, [GMCODE] ASC)
    INCLUDE([NEW_DATE_OF_REPORT_UNIX], [OLD_DATE_OF_REPORT_UNIX], [OLD_VALUE_PER_100K], [DIFFERENCE_PER_100K]);


GO
CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]([DATE_OF_REPORT] ASC, [GMCODE] ASC)
    INCLUDE([NEW_DATE_OF_REPORT_UNIX], [OLD_DATE_OF_REPORT_UNIX], [OLD_VALUE], [DIFFERENCE]);

