CREATE TABLE [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY] (
    [ID]                                          INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]) NOT NULL,
    [DATE_OF_REPORT]                              DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]                         BIGINT          NULL,
    [MUNICIPALITY_CODE]                           VARCHAR (100)   NULL,
    [MUNICIPALITY_NAME]                           VARCHAR (200)   NULL,
    [INFECTED_DAILY_TOTAL]                        INT             NULL,
    [INFECTED_DAILY_INCREASE]                     DECIMAL (16, 1) NULL,
    [DATE_LAST_INSERTED]                          DATETIME        DEFAULT (getdate()) NULL,
    [DATE_RANGE_START]                            DATETIME        NULL,
    [DATE_OF_REPORTS_LAG]                         DATETIME        NULL,
    [DATE_RANGE_START_LAG]                        DATETIME        NULL,
    [7D_AVERAGE_INFECTED_DAILY_INCREASE_TOTAL]    DECIMAL (16, 2) NULL,
    [7D_AVERAGE_INFECTED_DAILY_INCREASE_LAG]      DECIMAL (16, 2) NULL,
    [7D_AVERAGE_INFECTED_DAILY_INCREASE_ABSOLUTE] DECIMAL (16, 2) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY_TOTAL]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MUNICIPALITY_NAME], [MUNICIPALITY_CODE], [INFECTED_DAILY_TOTAL], [INFECTED_DAILY_INCREASE]);


GO
CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY_DOR]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]([DATE_OF_REPORT] ASC)
    INCLUDE([MUNICIPALITY_CODE], [DATE_LAST_INSERTED]);


GO
CREATE CLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY_CI]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]([MUNICIPALITY_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY_MC_DLI_DOR]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]([MUNICIPALITY_CODE] ASC, [DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [MUNICIPALITY_NAME], [INFECTED_DAILY_TOTAL], [INFECTED_DAILY_INCREASE], [7D_AVERAGE_INFECTED_DAILY_INCREASE_TOTAL]);

