CREATE TABLE [VWSDEST].[POSITIVE_TESTED_PEOPLE_WEEKLY] (
    [ID]                    INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE_WEEKLY]) NOT NULL,
    [WEEK_START]            DATE            NULL,
    [WEEK_END]              DATE            NULL,
    [TOT_INFECTED]          INT             NULL,
    [TOT_INFECTED_RATE]     DECIMAL (19, 3) NULL,
    [TOT_INFECTED_CML]      INT             NULL,
    [TOT_INFECTED_14D]      INT             NULL,
    [TOT_INFECTED_14D_RATE] DECIMAL (19, 3) NULL,
    [REL_INFECTED]          DECIMAL (19, 3) NULL,
    [REL_INFECTED_RATE]     DECIMAL (19, 3) NULL,
    [REL_INFECTED_CML]      DECIMAL (19, 3) NULL,
    [REL_INFECTED_14D]      DECIMAL (19, 3) NULL,
    [REL_INFECTED_14D_RATE] DECIMAL (19, 3) NULL,
    [POPULATION]            INT             NULL,
    [DATE_LAST_INSERTED]    DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_POSITIVE_TESTED_PEOPLE_WEEKLY]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_WEEKLY]([DATE_LAST_INSERTED] ASC)
    INCLUDE([WEEK_START], [WEEK_END], [TOT_INFECTED], [TOT_INFECTED_RATE], [TOT_INFECTED_CML], [TOT_INFECTED_14D], [TOT_INFECTED_14D_RATE], [REL_INFECTED], [REL_INFECTED_RATE], [REL_INFECTED_CML], [REL_INFECTED_14D], [REL_INFECTED_14D_RATE]);

