CREATE TABLE [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_SMALL_AGE_GROUP] (
    [ID]                              INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE_PER_SMALL_AGE_GROUP]) NOT NULL,
    [DATE_OF_REPORT]                  DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]             BIGINT          NULL,
    [AGEGROUP]                        VARCHAR (100)   NULL,
    [INFECTED_PER_AGEGROUP_INCREASE]  INT             NULL,
    [INFECTED_PER_AGEGROUP_TOTALS]    INT             NULL,
    [NUMBER_OF_INFECTED]              INT             NULL,
    [NUMBER_OF_INFECTED_PREVIOUS_DAY] INT             NULL,
    [DATE_LAST_INSERTED]              DATETIME        DEFAULT (getdate()) NULL,
    [INHABITANTS_PERCENTAGE]          DECIMAL (10, 3) NULL,
    [INFECTED_PERCENTAGE]             DECIMAL (10, 3) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_POSITIVE_PER_SMALL_AGE_GROUP_DEST]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_SMALL_AGE_GROUP]([DATE_LAST_INSERTED] ASC);

