CREATE TABLE [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP] (
    [ID]                             INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP]) NOT NULL,
    [DATE_OF_REPORT]                 DATETIME      NULL,
    [DATE_OF_REPORT_UNIX]            BIGINT        NULL,
    [AGEGROUP]                       VARCHAR (100) NULL,
    [INFECTED_PER_AGEGROUP_INCREASE] INT           NULL,
    [INFECTED_PER_AGEGROUP_TOTALS]   INT           NULL,
    [DATE_LAST_INSERTED]             DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

