CREATE TABLE [VWSDEST].[POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION] (
    [ID]                      INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_GGD_PERCENTAGE_POSITIVE_TESTED_PEOPLE_PER_REGION]) NOT NULL,
    [DATE_OF_REPORT]          DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]     BIGINT          NULL,
    [VRCODE]                  VARCHAR (100)   NULL,
    [INFECTED_GGD]            INT             NULL,
    [PERCENTAGE_INFECTED_GGD] DECIMAL (16, 2) NULL,
    [TOTAL_TESTED_GGD]        INT             NULL,
    [DATE_LAST_INSERTED]      DATETIME        DEFAULT (getdate()) NULL
);


GO
CREATE CLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION_IC]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION_DLI_DOR]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_REPORT_UNIX], [VRCODE], [INFECTED_GGD], [PERCENTAGE_INFECTED_GGD], [TOTAL_TESTED_GGD]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION_DLI]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [VRCODE], [INFECTED_GGD], [PERCENTAGE_INFECTED_GGD], [TOTAL_TESTED_GGD]);

