CREATE TABLE [VWSDEST].[POSITIVE_TESTED_PEOPLE] (
    [ID]                                          INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_POSITIVE_TESTED_PEOPLE]) NOT NULL,
    [DATE_OF_REPORT]                              DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]                         BIGINT          NULL,
    [INFECTED_DAILY_INCREASE]                     DECIMAL (16, 1) NULL,
    [INFECTED_DAILY_TOTAL]                        INT             NULL,
    [DATE_LAST_INSERTED]                          DATETIME        DEFAULT (getdate()) NULL,
    [DATE_RANGE_START]                            DATETIME        NULL,
    [DATE_OF_REPORTS_LAG]                         DATETIME        NULL,
    [DATE_RANGE_START_LAG]                        DATETIME        NULL,
    [7D_AVERAGE_INFECTED_DAILY_INCREASE_TOTAL]    DECIMAL (16, 2) NULL,
    [7D_AVERAGE_INFECTED_DAILY_INCREASE_LAG]      DECIMAL (16, 2) NULL,
    [7D_AVERAGE_INFECTED_DAILY_INCREASE_ABSOLUTE] DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_POSITIVE_TESTED_PEOPLE_DOR_DT]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTED_DAILY_TOTAL]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_POSITIVE_TESTED_PEOPLE_DOR]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE]([DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTED_DAILY_INCREASE], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_POSITIVE_TESTED_PEOPLE_DLI_DOR_DT]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTED_DAILY_TOTAL]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_POSITIVE_TESTED_PEOPLE_DLI_DOR]
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [INFECTED_DAILY_INCREASE]);

