CREATE TABLE [VWSDEST].[RESTRICTIONS_PER_REGION] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_RESTRICTIONS_PER_REGION]) NOT NULL,
    [VRCODE]             VARCHAR (100) NULL,
    [RESTRICTION_ID]     VARCHAR (100) NULL,
    [TARGET_REGION]      VARCHAR (100) NULL,
    [ESCALATION_LEVEL]   INT           NULL,
    [CATEGORY_ID]        VARCHAR (100) NULL,
    [RESTRICTION_ORDER]  INT           NULL,
    [VALID_FROM]         DATETIME      NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RESTRICTIONS_PER_REGION_DEST]
    ON [VWSDEST].[RESTRICTIONS_PER_REGION]([DATE_LAST_INSERTED] ASC, [VRCODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_RESTRICTIONS_PER_REGION_DLI_ALL]
    ON [VWSDEST].[RESTRICTIONS_PER_REGION]([DATE_LAST_INSERTED] ASC)
    INCLUDE([VRCODE], [RESTRICTION_ID], [TARGET_REGION], [ESCALATION_LEVEL], [CATEGORY_ID], [RESTRICTION_ORDER], [VALID_FROM]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_RESTRICTIONS_PER_REGION_DLI]
    ON [VWSDEST].[RESTRICTIONS_PER_REGION]([DATE_LAST_INSERTED] ASC)
    INCLUDE([VRCODE], [RESTRICTION_ID], [ESCALATION_LEVEL], [CATEGORY_ID], [RESTRICTION_ORDER], [VALID_FROM]);

