CREATE TABLE [VWSDEST].[RIVM_DECEASED_DAILY] (
    [ID]                  INT         DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_RIVM_DECEASED_DAILY]) NOT NULL,
    [DATE_OF_REPORT]      DATETIME    NULL,
    [DATE_OF_REPORT_UNIX] BIGINT      NULL,
    [DECEASED_ACTUAL]     INT         NULL,
    [VRCODE]              VARCHAR (5) NULL,
    [DATE_LAST_INSERTED]  DATETIME    DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

