CREATE TABLE [VWSDEST].[RIVM_SEWER_MEASUREMENTS_GM_2023] (
    [ID]                 INT           IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NOT NULL,
    [GMCODE]             VARCHAR (256) NULL,
    [DATE_START_UNIX]    BIGINT        NULL,
    [DATE_END_UNIX]      BIGINT        NULL,
    [AVERAGE]            INT           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_RIVM_SEWER_MEASUREMENTS_GM_2023]
    ON [VWSDEST].[RIVM_SEWER_MEASUREMENTS_GM_2023]([DATE_LAST_INSERTED] ASC);

