CREATE TABLE [VWSDEST].[RIVM_BOOSTER_SHOT_COVERAGES_NL] (
    [ID]                 BIGINT       IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED] DATETIME     DEFAULT (getdate()) NULL,
    [DATE_OF_STATISTICS] DATETIME     NULL,
    [DATE_OF_REPORT]     DATETIME     NULL,
    [AGE_GROUP]          VARCHAR (50) NULL,
    [BIRTH_YEAR]         VARCHAR (50) NULL,
    [PERCENTAGE]         FLOAT (53)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_RIVM_BOOSTER_SHOT_COVERAGES_NL]
    ON [VWSDEST].[RIVM_BOOSTER_SHOT_COVERAGES_NL]([DATE_LAST_INSERTED] ASC);

