CREATE TABLE [VWSDEST].[RIVM_VACCINATION_SHOTS_PLANNED_NL] (
    [ID]                       BIGINT   IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]       DATETIME DEFAULT (getdate()) NULL,
    [DOSES]                    INT      NULL,
    [DATE_OF_STATISTICS_START] DATETIME NULL,
    [DATE_OF_STATISTICS_END]   DATETIME NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_RIVM_VACCINATION_SHOTS_PLANNED_NL]
    ON [VWSDEST].[RIVM_VACCINATION_SHOTS_PLANNED_NL]([DATE_LAST_INSERTED] ASC);

