CREATE TABLE [VWSDEST].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY] (
	[ID] [BIGINT] PRIMARY KEY IDENTITY(1,1),
	[DATE_LAST_INSERTED] [DATETIME] DEFAULT GETDATE(),
	[VERSION] [INT] NOT NULL,
	[DATE_OF_REPORT] [DATETIME] NOT NULL,
	[DATE_OF_STATISTICS_WEEK_END] [DATETIME] NOT NULL,
	[AGE_GROUPS] VARCHAR(50),
	[N_PARTICIPANTS] INT NOT NULL,
	[PERC_COVID_SYMPTOMS] DECIMAL(5,2) NOT NULL
)


GO

CREATE INDEX [IX_RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY_Column] ON [VWSDEST].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY] ([DATE_LAST_INSERTED] DESC)
