CREATE TABLE [VWSDEST].[RIVM_IC_OPNAME] (
    [ID]                                   INT             DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSDEST_RIVM_IC_OPNAME]) NOT NULL,
    [VERSION]                              VARCHAR (100)   NULL,
    [DATE_OF_REPORT]                       DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]                  BIGINT          NULL,
    [DATE_OF_STATISTICS]                   DATETIME        NULL,
    [DATE_OF_STATISTICS_UNIX]              BIGINT          NULL,
    [IC_ADMISSION_NOTIFICATION]            INT             NULL,
    [IC_ADMISSION]                         INT             NULL,
    [OLD_DATE_OF_STATISTICS_UNIX]          BIGINT          NULL,
    [OLD_IC_ADMISSION_NOTIFICATION]        INT             NULL,
    [DIFFERENCE_IC_ADMISSION_NOTIFICATION] INT             NULL,
    [OLD_IC_ADMISSION]                     INT             NULL,
    [DIFFERENCE_IC_ADMISSION]              INT             NULL,
    [DATE_LAST_INSERTED]                   DATETIME        DEFAULT (getdate()) NULL,
    [WEEK_START]                           DATETIME        NULL,
    [IC_ADMISSION_7D_AVG]                  DECIMAL (16, 2) NULL,
    [WEEK_START_LAG]                       DATETIME        NULL,
    [IC_ADMISSION_7D_AVG_LAG]              DECIMAL (16, 2) NULL,
    [IC_ADMISSION_NOTIFICATION_7D_AVG]     DECIMAL (16, 2) NULL,
    [IC_ADMISSION_NOTIFICATION_7D_AVG_LAG] DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_IC_OPNAME_DEST]
    ON [VWSDEST].[RIVM_IC_OPNAME]([DATE_LAST_INSERTED] ASC, [DATE_OF_STATISTICS] ASC)
    INCLUDE([DATE_OF_REPORT], [IC_ADMISSION_NOTIFICATION], [IC_ADMISSION], [OLD_DATE_OF_STATISTICS_UNIX], [OLD_IC_ADMISSION_NOTIFICATION], [DIFFERENCE_IC_ADMISSION_NOTIFICATION], [OLD_IC_ADMISSION], [DIFFERENCE_IC_ADMISSION]);

