CREATE TABLE [VWSDEST].[RIVM_MUTATIONS] (
    [ID]                            INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_RIVM_MUTATIONS]) NOT NULL,
    [DATE_OF_REPORT]                DATETIME        NULL,
    [DATE_OF_STATISTICS_WEEK_START] DATETIME        NULL,
    [VARIANT_CODE]                  VARCHAR (100)   NULL,
    [VARIANT_NAME]                  VARCHAR (100)   NULL,
    [IS_VARIANT_OF_CONCERN]         VARCHAR (100)   NULL,
    [SAMPLE_SIZE]                   INT             NULL,
    [VARIANT_CASES]                 INT             NULL,
    [VARIANT_PERCENTAGE]            DECIMAL (16, 3) NULL,
    [DATE_LAST_INSERTED]            DATETIME        DEFAULT (getdate()) NULL,
    [HAS_HISTORICAL_SIGNIFICANCE]   VARCHAR (100)   NULL,
    [LABEL_EN]                      VARCHAR (100)   NULL,
    [LABEL_NL]                      VARCHAR (100)   NULL,
    [SORT_ORDER]                    INT             NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_VN_RIVM_MUTATIONS]
    ON [VWSDEST].[RIVM_MUTATIONS]([VARIANT_NAME] DESC);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_RIVM_MUTATIONS]
    ON [VWSDEST].[RIVM_MUTATIONS]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_STATISTICS_WEEK_START], [VARIANT_CODE], [VARIANT_NAME], [IS_VARIANT_OF_CONCERN], [SAMPLE_SIZE], [VARIANT_CASES], [VARIANT_PERCENTAGE]);

