CREATE TABLE [VWSDEST].[RIVM_VACCINATION_SERIES_NL] (
    [ID]                      BIGINT        IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]      DATETIME      DEFAULT (getdate()) NULL,
    [DATE_OF_REPORT]          DATETIME      NULL,
    [DATE_OF_STATISTICS]      DATETIME      NULL,
    [VACCINE_SERIE_EN]        VARCHAR (255) NULL,
    [TOTAL_VACCINATED]        INT           NULL,
    [TOTAL_VACCINATED_7DAYS]  INT           NULL,
    [CUMSUM_TOTAL_VACCINATED] INT           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_RIVM_VACCINATION_SERIES_NL]
    ON [VWSDEST].[RIVM_VACCINATION_SERIES_NL]([DATE_LAST_INSERTED] ASC);

