CREATE TABLE [VWSDEST].[RIVM_DECEASED_DAILY_PER_REGION] (
    [ID]                  INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_RIVM_DECEASED_DAILY_PER_REGION]) NOT NULL,
    [DATE_OF_REPORT]      DATETIME        NULL,
    [DATE_OF_REPORT_UNIX] BIGINT          NULL,
    [DECEASED_ACTUAL]     INT             NULL,
    [DECEASED_CUMULATIVE] INT             NULL,
    [VRCODE]              VARCHAR (5)     NULL,
    [DATE_LAST_INSERTED]  DATETIME        DEFAULT (getdate()) NULL,
    [WEEK_START]          DATETIME        NULL,
    [DECEASED_7D_AVG]     DECIMAL (16, 2) NULL,
    [WEEK_START_LAG]      DATETIME        NULL,
    [DECEASED_7D_AVG_LAG] DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_DECEASED_DAILY_PER_REGION_VRCODE_DATE_LAST_INSERTED]
    ON [VWSDEST].[RIVM_DECEASED_DAILY_PER_REGION]([VRCODE] ASC, [DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [DECEASED_ACTUAL], [DECEASED_CUMULATIVE]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_RIVM_DECEASED_DAILY_VR_DLI]
    ON [VWSDEST].[RIVM_DECEASED_DAILY_PER_REGION]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_REPORT_UNIX], [DECEASED_ACTUAL], [VRCODE]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_RIVM_DECEASED_DAILY_PER_REGION_VR]
    ON [VWSDEST].[RIVM_DECEASED_DAILY_PER_REGION]([VRCODE] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [DECEASED_ACTUAL], [DECEASED_CUMULATIVE], [DATE_LAST_INSERTED]);

