CREATE TABLE [VWSDEST].[RIVM_SEWER_MEASUREMENTS_NL_2023] (
    [ID]                  INT      IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]  DATETIME DEFAULT (getdate()) NOT NULL,
    [DATE_MEASUREMENT]    DATETIME NULL,
    [RNA_FLOW_PER_100000] BIGINT   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);




GO
CREATE NONCLUSTERED INDEX [NCIX_RIVM_SEWER_MEASUREMENTS_NL_2023]
    ON [VWSDEST].[RIVM_SEWER_MEASUREMENTS_NL_2023]([DATE_LAST_INSERTED] ASC);

