CREATE TABLE [VWSDEST].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY] (
	[ID] [BIGINT] PRIMARY KEY IDENTITY(1,1),
	[DATE_LAST_INSERTED] [DATETIME] DEFAULT GETDATE(),
	[DATE_OF_REPORT] VARCHAR(50),
	[DATE_OF_STATISTICS_WEEK_END] VARCHAR(50),
	[AGE_GROUPS] VARCHAR(50),
	[N_PARTICIPANTS] INT NULL,
	[PERC_COVID_SYMPTOMS] FLOAT NULL
)