CREATE TABLE [VWSDEST].[RIVM_DECEASED_DAILY_PER_MUNICIPALITY] (
    [ID]                      INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_RIVM_DECEASED_DAILY_PER_MUNICIPALITY]) NOT NULL,
    [DATE_OF_REPORT]          DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]     BIGINT          NULL,
    [MUNICIPALITY_CODE]       VARCHAR (10)    NULL,
    [OLD_DATE_OF_REPORT]      DATETIME        NULL,
    [OLD_DATE_OF_REPORT_UNIX] BIGINT          NULL,
    [OLD_VALUE]               INT             NULL,
    [DIFFERENCE]              INT             NULL,
    [DECEASED_ACTUAL]         INT             NULL,
    [DECEASED_CUMULATIVE]     INT             NULL,
    [DATE_LAST_INSERTED]      DATETIME        DEFAULT (getdate()) NULL,
    [WEEK_START]              DATETIME        NULL,
    [DECEASED_7D_AVG]         DECIMAL (16, 2) NULL,
    [WEEK_START_LAG]          DATETIME        NULL,
    [DECEASED_7D_AVG_LAG]     DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_DECEASED_DAILY_PER_MUNICIPALITY_MUNICIPALITY_CODE_DATE_LAST_INSERTED]
    ON [VWSDEST].[RIVM_DECEASED_DAILY_PER_MUNICIPALITY]([MUNICIPALITY_CODE] ASC, [DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_REPORT_UNIX], [OLD_DATE_OF_REPORT_UNIX], [OLD_VALUE], [DIFFERENCE]);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_DECEASED_DAILY_PER_MUNICIPALITY_MUNICIPALITY_CODE]
    ON [VWSDEST].[RIVM_DECEASED_DAILY_PER_MUNICIPALITY]([MUNICIPALITY_CODE] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_REPORT_UNIX], [OLD_DATE_OF_REPORT_UNIX], [OLD_VALUE], [DIFFERENCE], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_RIVM_DECEASED_DAILY_PER_MUNICIPALITY]
    ON [VWSDEST].[RIVM_DECEASED_DAILY_PER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC)
    INCLUDE([DATE_OF_REPORT_UNIX], [DECEASED_ACTUAL], [DECEASED_CUMULATIVE], [MUNICIPALITY_CODE]);

