CREATE TABLE [VWSDEST].[RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP] (
    [ID]                              INT             DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSDEST_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]) NOT NULL,
    [DATE_OF_REPORT]                  DATETIME        NULL,
    [DATE_OF_STATISTICS_WEEK_START]   DATE            NULL,
    [DATE_OF_STATISTICS_WEEK_END]     DATE            NULL,
    [AGE_GROUP_GROUPED]               VARCHAR (100)   NULL,
    [HOSPITAL_ADMISSION_NOTIFICATION] INT             NULL,
    [HOSPITAL_ADMISSION]              INT             NULL,
    [IC_ADMISSION_NOTIFICATION]       INT             NULL,
    [IC_ADMISSION]                    INT             NULL,
    [HOSPITAL_ADMISSION_PER1M]        DECIMAL (19, 1) NULL,
    [IC_ADMISSION_PER1M]              DECIMAL (19, 1) NULL,
    [DATE_LAST_INSERTED]              DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]
    ON [VWSDEST].[RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]([DATE_LAST_INSERTED] ASC, [DATE_OF_STATISTICS_WEEK_START] ASC);

