CREATE TABLE [VWSDEST].[RIVM_VACCINATION_INCIDENCE_HOSPITAL] (
    [ID]                                      INT            DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_VACCINATION_INCIDENCE_HOSPITAL]) NOT NULL,
    [DATE_START]                              DATETIME       NULL,
    [DATE_END]                                DATETIME       NULL,
    [AGE_GROUP_RANGE]                         VARCHAR (100)  NULL,
    [FULLY_VACCINATED_PER_100K]               DECIMAL (8, 2) NULL,
    [HAS_ONE_SHOT_OR_NOT_VACCINATED_PER_100K] DECIMAL (8, 2) NULL,
    [DATE_LAST_INSERTED]                      DATETIME       DEFAULT (getdate()) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWSDEST_VACCINATION_INCIDENCE_HOSPITAL]
    ON [VWSDEST].[RIVM_VACCINATION_INCIDENCE_HOSPITAL]([DATE_LAST_INSERTED] ASC);

