CREATE TABLE [VWSDEST].[RIVM_VACCINATION_SHOT_COVERAGES_NL_AUTUMN_2022] (
    [ID]                     BIGINT       IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]     DATETIME     DEFAULT (getdate()) NULL,
    [DATE_OF_STATISTICS]     DATETIME     NULL,
    [DATE_OF_REPORT]         DATETIME     NULL,
    [AGE_GROUP]              VARCHAR (50) NULL,
    [BIRTH_YEAR]             VARCHAR (50) NULL,
    [AUTUMN_2022_VACCINATED] FLOAT (53)   NULL,
    [PERCENTAGE_COMPLETED]   FLOAT (53)   NULL,
    [PERCENTAGE_PARTLY]      FLOAT (53)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_RIVM_VACCINATION_SHOT_COVERAGES_NL_AUTUMN_2022]
    ON [VWSDEST].[RIVM_VACCINATION_SHOT_COVERAGES_NL_AUTUMN_2022]([DATE_LAST_INSERTED] ASC);

