CREATE TABLE [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_ADMINISTERED_NL] (
    [ID]                                    INT      DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSDEST_RIVM_VACCINATIONS_BOOSTER_SHOTS_ADMINISTERED_NL]) NOT NULL,
    [DATE_LAST_INSERTED]                    DATETIME DEFAULT (getdate()) NOT NULL,
    [VERSION]                               INT      NULL,
    [DATE_OF_REPORT]                        DATETIME NULL,
    [DATE_OF_STATISTICS]                    DATETIME NULL,
    [GGD_ADMINISTERED_BOOSTER_SHOTS]        INT      NULL,
    [GGD_CUMSUM_ADMINISTERED_BOOSTER_SHOTS] INT      NULL,
    [GGD_ADMINISTERED_BOOSTER_SHOTS_7DAYS]  INT      NULL,
    [OTHERS_ESTIMATED_BOOSTER_SHOTS]        INT      NULL,
    [OTHERS_CUMSUM_ESTIMATED_BOOSTER_SHOTS] INT      NULL,
    [OTHERS_ESTIMATED_BOOSTER_SHOTS_7DAYS]  INT      NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_RIVM_VACCINATIONS_BOOSTER_SHOTS_ADMINISTERED_NL]
    ON [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_ADMINISTERED_NL]([DATE_LAST_INSERTED] ASC);

