CREATE TABLE [VWSDEST].[SEWER_MEASUREMENTS] (
    [ID]                          INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SEWER_MEASUREMENTS_2021]) NOT NULL,
    [WEEK_UNIX]                   BIGINT          NULL,
    [AVERAGE_RNA_FLOW_PER_100000] DECIMAL (16, 2) NULL,
    [NUMBER_OF_MEASUREMENTS]      INT             NULL,
    [NUMBER_OF_LOCATIONS]         INT             NULL,
    [TOTAL_LOCATIONS]             INT             NULL,
    [DATE_LAST_INSERTED]          DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_SEWER_MEASUREMENTS]
    ON [VWSDEST].[SEWER_MEASUREMENTS]([DATE_LAST_INSERTED] ASC);

