CREATE TABLE [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY_ARCHIVE] (
    [ID]                          INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY]) NOT NULL,
    [WEEK_UNIX]                   BIGINT          NULL,
    [GMCODE]                      VARCHAR (100)   NULL,
    [AVERAGE]                     DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED]          DATETIME        DEFAULT (getdate()) NULL,
    [NUMBER_OF_MEASUREMENTS]      INT             NULL,
    [NUMBER_OF_LOCATIONS]         INT             NULL,
    [AVERAGE_RNA_FLOW_PER_100000] DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_SEWER_MEASUREMENTS_PER_MUNICIPALITY]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY_ARCHIVE]([GMCODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY_DLI_WU]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY_ARCHIVE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([WEEK_UNIX], [GMCODE], [AVERAGE], [NUMBER_OF_MEASUREMENTS], [NUMBER_OF_LOCATIONS], [AVERAGE_RNA_FLOW_PER_100000]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY_DLI]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY_ARCHIVE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([WEEK_UNIX], [GMCODE], [AVERAGE]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY_ARCHIVE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([WEEK_UNIX], [GMCODE], [NUMBER_OF_LOCATIONS], [AVERAGE_RNA_FLOW_PER_100000]);

