CREATE TABLE [VWSDEST].[SEWER_MEASUREMENTS_PER_Region_ARCHIVE] (
    [ID]                          INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SEWER_MEASUREMENTS_PER_REGION]) NOT NULL,
    [WEEK_UNIX]                   BIGINT          NULL,
    [VRCODE]                      VARCHAR (100)   NULL,
    [AVERAGE]                     DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED]          DATETIME        DEFAULT (getdate()) NULL,
    [NUMBER_OF_MEASUREMENTS]      INT             NULL,
    [NUMBER_OF_LOCATIONS]         INT             NULL,
    [AVERAGE_RNA_FLOW_PER_100000] DECIMAL (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_SEWER_MEASUREMENTS_PER_REGION_VR]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_Region_ARCHIVE]([VRCODE] ASC)
    INCLUDE([WEEK_UNIX], [NUMBER_OF_LOCATIONS], [AVERAGE_RNA_FLOW_PER_100000], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_SEWER_MEASUREMENTS_PER_REGION_DLI]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_Region_ARCHIVE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([WEEK_UNIX], [VRCODE], [NUMBER_OF_LOCATIONS], [AVERAGE_RNA_FLOW_PER_100000]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_SEWER_MEASUREMENTS_PER_REGION]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_Region_ARCHIVE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([WEEK_UNIX], [VRCODE], [AVERAGE]);

