CREATE TABLE [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY] (
    [ID]                          INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY_2021]) NOT NULL,
    [WEEK_UNIX]                   BIGINT          NULL,
    [GMCODE]                      VARCHAR (100)   NULL,
    [AVERAGE_RNA_FLOW_PER_100000] DECIMAL (16, 2) NULL,
    [NUMBER_OF_MEASUREMENTS]      INT             NULL,
    [NUMBER_OF_LOCATIONS]         INT             NULL,
    [TOTAL_LOCATIONS]             INT             NULL,
    [DATE_LAST_INSERTED]          DATETIME        DEFAULT (getdate()) NULL
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_SEWER_MEASUREMENTS_PER_MUNICIPALITY]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC);


GO
CREATE CLUSTERED INDEX [IX_VWSDEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY_CI]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SEWER_MEASUREMENTS_PER_MUNICIPALITY_GMCODE_DATE_LAST_INSERTED]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY]([GMCODE] ASC, [DATE_LAST_INSERTED] ASC)
    INCLUDE([WEEK_UNIX], [AVERAGE_RNA_FLOW_PER_100000], [NUMBER_OF_MEASUREMENTS], [NUMBER_OF_LOCATIONS], [TOTAL_LOCATIONS]);


GO
CREATE NONCLUSTERED INDEX [IX_SEWER_MEASUREMENTS_PER_MUNICIPALITY_DATE_LAST_INSERTED]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC)
    INCLUDE([WEEK_UNIX], [GMCODE], [AVERAGE_RNA_FLOW_PER_100000]);

