CREATE TABLE [VWSDEST].[SEWER_BASE_ARCHIVE] (
    [ID]                                 INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SEWER_BASE]) NOT NULL,
    [WEEK]                               INT             NULL,
    [WEEK_UNIX]                          BIGINT          NULL,
    [DATE_MEASUREMENT]                   DATETIME        NULL,
    [RWZI_AWZI_CODE]                     INT             NULL,
    [RWZI_AWZI_NAME]                     VARCHAR (100)   NULL,
    [X_COORDINATE]                       DECIMAL (16, 2) NULL,
    [Y_COORDINATE]                       DECIMAL (16, 2) NULL,
    [POSTAL_CODE]                        VARCHAR (100)   NULL,
    [SECURITY_REGION_CODE]               VARCHAR (100)   NULL,
    [GM_CODE]                            VARCHAR (100)   NULL,
    [RNA_PER_ML]                         BIGINT          NULL,
    [RNA_FLOW_PER_100000]                BIGINT          NULL,
    [PERCENTAGE_IN_SECURITY_REGION]      FLOAT (53)      NULL,
    [REPRESENTATIVE_MEASUREMENT]         INT             NULL,
    [RANK_PERCENTAGE_IN_SECURITY_REGION] INT             NULL,
    [COUNT_DAILY_MEASUREMENT]            INT             NULL,
    [DATE_LAST_INSERTED]                 DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_SEWER_BASE_RANK_PERCENTAGE_IN_SECURITY_REGION_COUNT_DAILY_MEASUREMENT]
    ON [VWSDEST].[SEWER_BASE_ARCHIVE]([RANK_PERCENTAGE_IN_SECURITY_REGION] ASC, [COUNT_DAILY_MEASUREMENT] ASC)
    INCLUDE([WEEK_UNIX], [RWZI_AWZI_CODE], [SECURITY_REGION_CODE], [RNA_PER_ML], [RNA_FLOW_PER_100000], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_SEWER_BASE]
    ON [VWSDEST].[SEWER_BASE_ARCHIVE]([RANK_PERCENTAGE_IN_SECURITY_REGION] ASC, [COUNT_DAILY_MEASUREMENT] ASC)
    INCLUDE([WEEK_UNIX], [RWZI_AWZI_CODE], [GM_CODE], [RNA_PER_ML], [RNA_FLOW_PER_100000]);

