CREATE TABLE [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI] (
    [ID]                          INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SEWER_MEASUREMENTS_PER_RWZI_2021]) NOT NULL,
    [DATE_MEASUREMENT]            DATETIME        NULL,
    [DATE_MEASUREMENT_UNIX]       BIGINT          NULL,
    [WEEK]                        INT             NULL,
    [RWZI_AWZI_CODE]              VARCHAR (100)   NULL,
    [RWZI_AWZI_NAME]              VARCHAR (100)   NULL,
    [RNA_FLOW_PER_100000]         DECIMAL (16, 2) NULL,
    [AVERAGE_RNA_FLOW_PER_100000] DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED]          DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_RWC_SEWER_MEASUREMENTS_PER_RWZI]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI]([DATE_LAST_INSERTED] ASC, [RWZI_AWZI_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SEWER_MEASUREMENTS_PER_RWZI_RWZI_AWZI_CODE_DATE_MEASUREMENT]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI]([RWZI_AWZI_CODE] ASC, [DATE_MEASUREMENT] ASC)
    INCLUDE([DATE_MEASUREMENT_UNIX], [RWZI_AWZI_NAME], [RNA_FLOW_PER_100000], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_SEWER_MEASUREMENTS_PER_RWZI_DATE_MEASUREMENT_RWZI_AWZI_CODE]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI]([DATE_MEASUREMENT] ASC, [RWZI_AWZI_CODE] ASC)
    INCLUDE([DATE_MEASUREMENT_UNIX], [RWZI_AWZI_NAME], [RNA_FLOW_PER_100000], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_SEWER_MEASUREMENTS_PER_RWZI]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI]([DATE_LAST_INSERTED] ASC, [DATE_MEASUREMENT] ASC)
    INCLUDE([DATE_MEASUREMENT_UNIX], [RWZI_AWZI_CODE], [RWZI_AWZI_NAME], [RNA_FLOW_PER_100000]);

