CREATE TABLE [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI_GM_VR] (
    [ID]                  INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SEWER_MEASUREMENTS_PER_RWZI_GM_VR]) NOT NULL,
    [DATE_MEASUREMENT]    DATETIME        NULL,
    [RWZI_AWZI_CODE]      VARCHAR (100)   NULL,
    [RWZI_AWZI_NAME]      VARCHAR (100)   NULL,
    [RNA_FLOW_PER_100000] DECIMAL (16, 2) NULL,
    [REGIO_TYPE]          VARCHAR (10)    NULL,
    [REGIO_CODE]          VARCHAR (10)    NULL,
    [WEEK]                INT             NULL,
    [DATE_UNIX]           BIGINT          NULL,
    [DATE_START_UNIX]     BIGINT          NULL,
    [DATE_END_UNIX]       BIGINT          NULL,
    [DATE_LAST_INSERTED]  DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_RT_RC_SEWER_MEASUREMENTS_PER_RWZI_GM_VR]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI_GM_VR]([DATE_LAST_INSERTED] ASC, [REGIO_TYPE] ASC, [REGIO_CODE] ASC)
    INCLUDE([RWZI_AWZI_CODE], [RWZI_AWZI_NAME], [RNA_FLOW_PER_100000], [WEEK], [DATE_UNIX], [DATE_START_UNIX], [DATE_END_UNIX]);


GO
CREATE NONCLUSTERED INDEX [NCI_VWSDEST_SEWER_MEASUREMENTS_PER_RWZI_GM_VR]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI_GM_VR]([DATE_LAST_INSERTED] ASC, [REGIO_TYPE] ASC, [REGIO_CODE] ASC)
    INCLUDE([RWZI_AWZI_CODE], [RWZI_AWZI_NAME], [RNA_FLOW_PER_100000], [WEEK], [DATE_UNIX], [DATE_START_UNIX], [DATE_END_UNIX]);


GO
CREATE CLUSTERED INDEX [CI_DLI_VWSDEST_SEWER_MEASUREMENTS_PER_RWZI_GM_VR]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI_GM_VR]([DATE_LAST_INSERTED] ASC);

