CREATE TABLE [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI_MINIMAL] (
    [ID]                 INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_SEWER_MEASUREMENTS_PER_RWZI_MIN]) NOT NULL,
    [DATE_UNIX]          BIGINT          NULL,
    [DATE_START_UNIX]    BIGINT          NULL,
    [DATE_END_UNIX]      BIGINT          NULL,
    [WEEK]               INT             NULL,
    [RWZI_AWZI_CODE]     VARCHAR (100)   NULL,
    [RWZI_AWZI_NAME]     VARCHAR (100)   NULL,
    [GMCODE]             VARCHAR (100)   NULL,
    [RNA_NORMALIZED]     DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED] DATETIME        DEFAULT (getdate()) NULL
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_RWC_SEWER_MEASUREMENTS_PER_RWZI_MINIMAL]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI_MINIMAL]([DATE_LAST_INSERTED] ASC, [RWZI_AWZI_CODE] ASC);


GO
CREATE CLUSTERED INDEX [IX_SEWER_MEASUREMENTS_PER_RWZI_MINIMAL_IC]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI_MINIMAL]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SEWER_MEASUREMENTS_PER_RWZI_MINIMAL]
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI_MINIMAL]([DATE_LAST_INSERTED] ASC, [GMCODE] ASC, [RWZI_AWZI_NAME] ASC);

