CREATE TABLE [VWSDEST].[VWS_VACCINE_DELIVERIES_TIMESPAN_EST] (
    [ID]                 INT      DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_VACCINE_DELIVERIES_TIMESPAN_EST]) NOT NULL,
    [TIMESPAN_WEEKS]     BIGINT   NULL,
    [DOSES]              BIGINT   NULL,
    [DATE_LAST_INSERTED] DATETIME DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_VWS_VACCINE_DELIVERIES_TIMESPAN_EST]
    ON [VWSDEST].[VWS_VACCINE_DELIVERIES_TIMESPAN_EST]([DATE_LAST_INSERTED] ASC)
    INCLUDE([TIMESPAN_WEEKS], [DOSES]);

