CREATE TABLE [VWSDEST].[VWS_VACCINE_PLANNED] (
    [ID]                 INT      DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSDEST_VWS_VACCINE_PLANNED]) NOT NULL,
    [DOSES]              BIGINT   NOT NULL,
    [DATE_START_UNIX]    BIGINT   NOT NULL,
    [DATE_END_UNIX]      BIGINT   NOT NULL,
    [DATE_LAST_INSERTED] DATETIME DEFAULT (getdate()) NOT NULL
);


GO
CREATE CLUSTERED INDEX [IX_VWS_VACCINE_PLANNED]
    ON [VWSDEST].[VWS_VACCINE_PLANNED]([DATE_LAST_INSERTED] DESC);

