CREATE TABLE [VWSDEST].[VWS_VACCINE_DELIVERIES] (
    [ID]                  INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSDEST_VACCINE_DELIVERIES]) NOT NULL,
    [DATE_FIRST_DAY]      DATETIME      NULL,
    [DATE_START_UNIX]     BIGINT        NULL,
    [DATE_END_UNIX]       BIGINT        NULL,
    [VALUE_TYPE]          VARCHAR (100) NULL,
    [REPORT_STATUS]       VARCHAR (100) NULL,
    [VALUE]               BIGINT        NULL,
    [DATE_LAST_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [DATE_OF_REPORT_UNIX] BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DEST_VWS_VACCINE_DELIVERIES]
    ON [VWSDEST].[VWS_VACCINE_DELIVERIES]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_FIRST_DAY], [DATE_START_UNIX], [DATE_END_UNIX], [VALUE_TYPE], [REPORT_STATUS], [VALUE]);

