CREATE TABLE [VWSREPORT].[ANNOTATIONS] (
    [ID]                INT           IDENTITY (1, 1) NOT NULL,
    [START_DATE]        VARCHAR (256) NOT NULL,
    [END_DATE]          VARCHAR (256) NULL,
    [TITLE]             VARCHAR (256) NULL,
    [DESCRIPTION]       VARCHAR (MAX) NULL,
    [CATEGORY]          VARCHAR (256) NULL,
    [SHORT_DESCRIPTION] VARCHAR (512) NULL,
    [LONG_DESCRIPTION]  VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_SD_AND_ED]
    ON [VWSREPORT].[ANNOTATIONS]([START_DATE] ASC, [END_DATE] ASC);

