-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
/****** Object:  View [VWSDEST].[V_DIFFERENCE_INTAKE_INTENSIVECARE_MA__MOVING_AVERAGE_IC]    Script Date: 12-11-2020 14:58:19 ******/
CREATE OR ALTER VIEW [VWSDEST].[V_DIFFERENCE_INTAKE_INTENSIVECARE_REPORTING_DATE_RIVM] AS

WITH BASE_CTE AS(
SELECT  [ID]
      ,[VERSION]
      ,[DATE_OF_REPORT]
      ,[DATE_OF_REPORT_UNIX]
      ,[DATE_OF_STATISTICS]
      ,[DATE_OF_STATISTICS_UNIX]
      ,[IC_ADMISSION_NOTIFICATION]
      ,[IC_ADMISSION]
      ,[OLD_DATE_OF_STATISTICS_UNIX]
      ,[OLD_IC_ADMISSION_NOTIFICATION]
      ,[DIFFERENCE_IC_ADMISSION_NOTIFICATION]
      ,[OLD_IC_ADMISSION]
      ,[DIFFERENCE_IC_ADMISSION]
      ,[DATE_LAST_INSERTED]
  FROM [VWSDEST].[RIVM_IC_OPNAME]
  WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[RIVM_IC_OPNAME] )
)
SELECT 

       DATE_OF_STATISTICS                       AS DATE_OF_REPORT
	  ,DATE_OF_STATISTICS_UNIX                  AS NEW_DATE_UNIX
	  ,OLD_DATE_OF_STATISTICS_UNIX              AS OLD_DATE_UNIX
	  ,OLD_IC_ADMISSION_NOTIFICATION            AS OLD_VALUE
	  ,DIFFERENCE_IC_ADMISSION_NOTIFICATION     AS [DIFFERENCE]
FROM BASE_CTE T1
WHERE DATE_OF_STATISTICS = (SELECT MAX(DATE_OF_STATISTICS) FROM BASE_CTE)

GO


