-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER  VIEW [VWSDEST].[V_DIFFERENCE_GGD__INFECTED_DAILY_PERCENTAGE_PER_REGION] AS

WITH LAST_DATE_OF_REPORT AS (
	SELECT
    REGION_CODE AS VRCODE,
    CAST(MAX(DATE_OF_STATISTICS) as datetime) AS [LAST_DATE_OF_REPORT]
	FROM VWSDEST.GGD_TESTED_PEOPLE_VR
	WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.GGD_TESTED_PEOPLE_VR)
    GROUP BY REGION_CODE
),

BASE_CTE AS (
SELECT 
	DATE_OF_STATISTICS AS DATE_OF_REPORT,
    REGION_CODE AS VRCODE,
    NEW_DATE_OF_REPORT_UNIX AS NEW_DATE_UNIX,
	LAG([NEW_DATE_OF_REPORT_UNIX], 1, NULL) OVER (PARTITION BY [REGION_CODE] ORDER BY [NEW_DATE_OF_REPORT_UNIX]) AS [OLD_DATE_UNIX],
    PERCENTAGE_POSITIVE,
	LAG(PERCENTAGE_POSITIVE, 1, NULL) OVER (PARTITION BY [REGION_CODE] ORDER BY [NEW_DATE_OF_REPORT_UNIX]) AS [OLD_VALUE],
	PERCENTAGE_POSITIVE -
		LAG(PERCENTAGE_POSITIVE, 1, NULL) OVER (PARTITION BY [REGION_CODE] ORDER BY [NEW_DATE_OF_REPORT_UNIX]) AS [DIFFERENCE]
FROM VWSDEST.GGD_TESTED_PEOPLE_VR T1
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.GGD_TESTED_PEOPLE_VR)
)

SELECT
       NEW_DATE_UNIX
	  ,OLD_DATE_UNIX
      ,T1.VRCODE
	  ,ISNULL(OLD_VALUE, 0) AS OLD_VALUE
	  ,ISNULL([DIFFERENCE],0) AS [DIFFERENCE]
FROM BASE_CTE T1
LEFT JOIN LAST_DATE_OF_REPORT T2
	ON T1.[VRCODE] = T2.[VRCODE]
WHERE DATE_OF_REPORT = LAST_DATE_OF_REPORT