-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
/****** Object:  View [VWSDEST].[V_DIFFERENCES_ELDERLY_AT_HOME__POSITIVE_TESTED_DAILY_VR]    Script Date: 18-01-2021 ******/
CREATE OR ALTER  VIEW [VWSDEST].[V_DIFFERENCES_ELDERLY_AT_HOME__POSITIVE_TESTED_DAILY_VR] AS

WITH LAST_DATE_OF_REPORT AS (
	SELECT
		VRCODE,
		CAST(MAX(DATE_OF_REPORT) as datetime) AS [LAST_DATE_OF_REPORT]
	FROM VWSDEST.ELDERLY_AT_HOME_VR
	WHERE DATE_OF_REPORT >=  '2020-02-27 00:00:00.000' --In line with elderly at home views
        AND DATE_OF_REPORT <  (SELECT MAX(DATE_OF_REPORT) FROM VWSDEST.ELDERLY_AT_HOME_VR) --In line with elderly at home views. Neglect last value
		AND DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.ELDERLY_AT_HOME_VR)
	GROUP BY VRCODE
),

BASE_CTE AS (
SELECT 
	DATE_OF_REPORT,
	DATE_OF_REPORT_UNIX AS [NEW_DATE_OF_REPORT_UNIX],
    VRCODE,
	LAG([DATE_OF_REPORT_UNIX], 1, NULL) OVER (PARTITION BY VRCODE ORDER BY [DATE_OF_REPORT_UNIX]) AS [OLD_DATE_OF_REPORT_UNIX],
	LAG(DBO.NO_NEGATIVE_NUMBER_I([INFECTED_ELDERLY_AT_HOME_DAILY]), 1, NULL) OVER (PARTITION BY VRCODE ORDER BY DATE_LAST_INSERTED,[DATE_OF_REPORT_UNIX]) AS [OLD_VALUE],
	DBO.NO_NEGATIVE_NUMBER_I([INFECTED_ELDERLY_AT_HOME_DAILY]) -
		LAG(DBO.NO_NEGATIVE_NUMBER_I([INFECTED_ELDERLY_AT_HOME_DAILY]), 1, NULL) OVER (PARTITION BY VRCODE ORDER BY DATE_LAST_INSERTED,[DATE_OF_REPORT_UNIX]) AS [DIFFERENCE]
FROM VWSDEST.ELDERLY_AT_HOME_VR
WHERE DATE_OF_REPORT >=  '2020-02-27 00:00:00.000' --In line with elderly at home views
AND DATE_LAST_INSERTED = (SELECT max(DATE_LAST_INSERTED) 
                            FROM VWSDEST.ELDERLY_AT_HOME_VR)

)

SELECT DATE_OF_REPORT
	  ,NEW_DATE_OF_REPORT_UNIX AS NEW_DATE_UNIX
	  ,OLD_DATE_OF_REPORT_UNIX AS OLD_DATE_UNIX
      ,T1.VRCODE
	  ,CASE WHEN OLD_VALUE IS NULL THEN 0 ELSE OLD_VALUE END AS OLD_VALUE
	  ,CASE WHEN [DIFFERENCE] IS NULL THEN 0 ELSE [DIFFERENCE] END AS [DIFFERENCE]
FROM BASE_CTE T1
LEFT JOIN LAST_DATE_OF_REPORT T2
	ON T1.[VRCODE] = T2.[VRCODE]
WHERE DATE_OF_REPORT = LAST_DATE_OF_REPORT
GO



