-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER VIEW [VWSDEST].[V_DIFFERENCE_CORONA_APP__WARNED_DAILY] AS

WITH LAST_DATE_OF_REPORT AS (
	SELECT
		CAST(MAX(DATE_OF_REPORT) as datetime) AS [LAST_DATE_OF_REPORT]
	FROM VWSDEST.CORONAMELDER
	WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.CORONAMELDER)
),

BASE_CTE AS (
SELECT 
	DATE_OF_REPORT,
	LAG([DATE_OF_REPORT], 1, NULL) OVER (ORDER BY [DATE_LAST_INSERTED], [DATE_OF_REPORT]) AS [OLD_DATE_OF_REPORT],
	LAG(DBO.NO_NEGATIVE_NUMBER_I([WARNED_DAILY]), 1, NULL) OVER (ORDER BY [DATE_LAST_INSERTED], [DATE_OF_REPORT]) AS [OLD_VALUE],
	DBO.NO_NEGATIVE_NUMBER_I([WARNED_DAILY]) -
		LAG(DBO.NO_NEGATIVE_NUMBER_I([WARNED_DAILY]), 1, NULL) OVER (ORDER BY [DATE_LAST_INSERTED], [DATE_OF_REPORT]) AS [DIFFERENCE]
FROM VWSDEST.CORONAMELDER
WHERE DATE_LAST_INSERTED = (SELECT max(DATE_LAST_INSERTED) FROM VWSDEST.CORONAMELDER)

)

SELECT DBO.CONVERT_DATETIME_TO_UNIX(DATE_OF_REPORT) AS NEW_DATE_UNIX
	  ,DBO.CONVERT_DATETIME_TO_UNIX(OLD_DATE_OF_REPORT) AS OLD_DATE_UNIX
	  ,CASE WHEN OLD_VALUE IS NULL THEN 0 ELSE OLD_VALUE END AS OLD_VALUE
	  ,CASE WHEN [DIFFERENCE] IS NULL THEN 0 ELSE [DIFFERENCE] END AS [DIFFERENCE]
FROM BASE_CTE T1
WHERE DATE_OF_REPORT = (SELECT LAST_DATE_OF_REPORT FROM LAST_DATE_OF_REPORT)
GO