-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER  VIEW [VWSDEST].[V_DIFFERENCE_POSITIVE_TESTED_PEOPLE__INFECTED_DAILY_INCREASE] AS
--This view is used to retrieve the differences for testes per 100k

SELECT DATE_OF_REPORT
	  ,NEW_DATE_OF_REPORT_UNIX AS NEW_DATE_UNIX
	  ,OLD_DATE_OF_REPORT_UNIX AS OLD_DATE_UNIX
	  ,T1.GMCODE
	  ,CASE WHEN OLD_VALUE_PER_100K IS NULL THEN 0 ELSE OLD_VALUE_PER_100K END AS OLD_VALUE
	  ,CASE WHEN [DIFFERENCE_PER_100K] IS NULL THEN 0 ELSE [DIFFERENCE_PER_100K] END AS [DIFFERENCE]
FROM VWSDEST.POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE T1
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE])
;
GO
