-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
/****** Object:  View [VWSDEST].[V_DIFFERENCES_RIVM__DECEASED_DAILY_NL]    Script Date: 18-01-2021 ******/
CREATE OR ALTER  VIEW [VWSDEST].[V_DIFFERENCES_RIVM__DECEASED_DAILY_NL] AS


--For NL, the deceased total is determined as the sum of the safety region numbers
WITH DECEASED_CTE AS (
SELECT
    SUM(DECEASED_ACTUAL) AS DECEASED_ACTUAL
,   DATE_OF_REPORT_UNIX
,   DATE_OF_REPORT
, DATE_LAST_INSERTED
FROM VWSDEST.RIVM_DECEASED_DAILY_PER_REGION
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.RIVM_DECEASED_DAILY_PER_REGION)
GROUP BY DATE_OF_REPORT_UNIX,DATE_OF_REPORT, DATE_LAST_INSERTED
)
,
LAST_DATE_OF_REPORT AS (
	SELECT
		CAST(MAX(DATE_OF_REPORT) as datetime) AS [LAST_DATE_OF_REPORT]
	FROM DECEASED_CTE
),
BASE_CTE AS (
SELECT 
	DATE_OF_REPORT,
	DATE_OF_REPORT_UNIX AS [NEW_DATE_OF_REPORT_UNIX],
	LAG([DATE_OF_REPORT_UNIX], 1, NULL) OVER (ORDER BY [DATE_OF_REPORT_UNIX]) AS [OLD_DATE_OF_REPORT_UNIX],
	LAG(DBO.NO_NEGATIVE_NUMBER_I([DECEASED_ACTUAL]), 1, NULL) OVER (ORDER BY DATE_LAST_INSERTED,[DATE_OF_REPORT_UNIX]) AS [OLD_VALUE],
	DBO.NO_NEGATIVE_NUMBER_I([DECEASED_ACTUAL]) -
		LAG(DBO.NO_NEGATIVE_NUMBER_I([DECEASED_ACTUAL]), 1, NULL) OVER (ORDER BY DATE_LAST_INSERTED,[DATE_OF_REPORT_UNIX]) AS [DIFFERENCE]
FROM DECEASED_CTE
WHERE DATE_LAST_INSERTED = (SELECT max(DATE_LAST_INSERTED) 
                            FROM DECEASED_CTE)
)

SELECT DATE_OF_REPORT
	  ,NEW_DATE_OF_REPORT_UNIX AS NEW_DATE_UNIX
	  ,OLD_DATE_OF_REPORT_UNIX AS OLD_DATE_UNIX
	  ,CASE WHEN OLD_VALUE IS NULL THEN 0 ELSE OLD_VALUE END AS OLD_VALUE
	  ,CASE WHEN [DIFFERENCE] IS NULL THEN 0 ELSE [DIFFERENCE] END AS [DIFFERENCE]
FROM BASE_CTE T1
WHERE DATE_OF_REPORT = (SELECT LAST_DATE_OF_REPORT FROM LAST_DATE_OF_REPORT)
GO


