-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER  VIEW [VWSDEST].[V_DIFFERENCE_GGD__INFECTED_DAILY_PERCENTAGE] AS

WITH LAST_DATE_OF_REPORT AS (
	SELECT
		CAST(MAX(DATE_OF_STATISTICS) as datetime) AS [LAST_DATE_OF_REPORT]
	FROM VWSDEST.GGD_TESTED_PEOPLE_NL
	WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.GGD_TESTED_PEOPLE_NL)
),

BASE_CTE AS (
SELECT 
	DATE_OF_STATISTICS AS DATE_OF_REPORT,
    NEW_DATE_OF_REPORT_UNIX AS NEW_DATE_UNIX,
	LAG([NEW_DATE_OF_REPORT_UNIX], 1, NULL) OVER (ORDER BY [NEW_DATE_OF_REPORT_UNIX]) AS [OLD_DATE_UNIX],
    PERCENTAGE_POSITIVE,
	LAG(PERCENTAGE_POSITIVE, 1, NULL) OVER (ORDER BY [NEW_DATE_OF_REPORT_UNIX]) AS [OLD_VALUE],
	PERCENTAGE_POSITIVE -
		LAG(PERCENTAGE_POSITIVE, 1, NULL) OVER (ORDER BY [NEW_DATE_OF_REPORT_UNIX]) AS [DIFFERENCE]
FROM VWSDEST.GGD_TESTED_PEOPLE_NL T1
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.GGD_TESTED_PEOPLE_NL)
)

SELECT
       NEW_DATE_UNIX
	  ,OLD_DATE_UNIX
	  ,OLD_VALUE
	  ,[DIFFERENCE]
FROM BASE_CTE
WHERE DATE_OF_REPORT = (SELECT LAST_DATE_OF_REPORT FROM LAST_DATE_OF_REPORT)