-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
/****** Object:  View [VWSDEST].[V_DIFFERENCE_POSITIVE_TESTED_PEOPLE__INFECTED_DAILY_TOTAL]    Script Date: 12-11-2020 15:01:38 ******/
CREATE OR ALTER VIEW [VWSDEST].[V_DIFFERENCE_POSITIVE_TESTED_PEOPLE__INFECTED_DAILY_TOTAL] AS

SELECT DATE_OF_REPORT
	  ,NEW_DATE_OF_REPORT_UNIX AS NEW_DATE_UNIX
	  ,OLD_DATE_OF_REPORT_UNIX AS OLD_DATE_UNIX
	  ,T1.GMCODE
	  ,CASE WHEN OLD_VALUE IS NULL THEN 0 ELSE OLD_VALUE END AS OLD_VALUE
	  ,CASE WHEN [DIFFERENCE] IS NULL THEN 0 ELSE [DIFFERENCE] END AS [DIFFERENCE]
FROM VWSDEST.POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE T1
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE])
;
GO
