-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Move national data from staging to intermediate table.
CREATE OR ALTER PROCEDURE dbo.SP_HOSPITAL_BED_OCCUPANCY
AS
BEGIN
    INSERT INTO VWSDEST.HOSPITAL_BED_OCCUPANCY
        (   [DATE_OF_REPORT],
	        [DATE_OF_REPORT_UNIX],
            [IC_BEDS_OCCUPIED_COVID],
            [IC_BEDS_OCCUPIED_NON_COVID],
            [IC_BEDS_OCCUPIED_COVID_PERCENTAGE],
            [NON_IC_BEDS_OCCUPIED_COVID]
        )
    SELECT
        [DATUM] AS DATE_OF_REPORT,
        dbo.CONVERT_DATETIME_TO_UNIX(DATUM) AS DATE_OF_REPORT_UNIX,
        [IC_BEDDEN_COVID] AS IC_BEDS_OCCUPIED_COVID,
        [IC_BEDDEN_NON_COVID] AS IC_BEDS_OCCUPIED_NON_COVID,
        ROUND((CAST([IC_BEDDEN_COVID] as DECIMAL)/([IC_BEDDEN_NON_COVID]+[IC_BEDDEN_COVID]) * 100.0),2) AS IC_BEDS_OCCUPIED_COVID_PERCENTAGE,
        [KLINIEK_BEDDEN] AS NON_IC_BEDS_OCCUPIED_COVID
    FROM
       VWSINTER.LNAZ_HOSPITAL_BED_OCCUPANCY
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSINTER.LNAZ_HOSPITAL_BED_OCCUPANCY)
END;
