-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE [dbo].[SP_NICE_HOSPITAL_VR]
AS
BEGIN
WITH BASE_CTE AS (
SELECT
	DATE_OF_STATISTICS
,	SECURITY_REGION_CODE
,	SUM(HOSPITALIZED) AS HOSPITALIZED
,	SUM(REPORTED) AS REPORTED
FROM VWSINTER.NICE_HOSPITAL
WHERE SECURITY_REGION_CODE!='NA'
AND DATE_LAST_INSERTED=(SELECT MAX(DATE_LAST_INSERTED) FROM VWSINTER.NICE_HOSPITAL)
GROUP BY SECURITY_REGION_CODE, DATE_OF_STATISTICS
)
INSERT INTO VWSDEST.NICE_HOSPITAL_VR(
	DATE_OF_STATISTICS
,	VR_CODE
,	VR_NAME
,	HOSPITALIZED
,	REPORTED
,	HOSPITALIZED_3D_AVG
,	REPORTED_3D_AVG
,	HOSPITALIZED_CUMULATIVE
,	REPORTED_CUMULATIVE
,	REPORTED_PER_MIL_LAST_WEEK
,	WEEK_START
    )
SELECT
	DATE_OF_STATISTICS
,	SECURITY_REGION_CODE
,	VRNAAM AS VR_NAME
,	HOSPITALIZED
,	REPORTED
,	AVG(CAST([HOSPITALIZED] AS FLOAT)) OVER (PARTITION BY SECURITY_REGION_CODE ORDER BY DATE_OF_STATISTICS ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as HOSPITALIZED_3D_AVG
,	AVG(CAST([REPORTED] AS FLOAT)) OVER (PARTITION BY SECURITY_REGION_CODE ORDER BY DATE_OF_STATISTICS ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as REPORTED_3D_AVG
,   (SUM(HOSPITALIZED) OVER (PARTITION BY SECURITY_REGION_CODE ORDER BY DATE_OF_STATISTICS ASC)) AS HOSPITALIZED_CUMULATIVE
,   (SUM(REPORTED) OVER (PARTITION BY SECURITY_REGION_CODE ORDER BY DATE_OF_STATISTICS ASC)) AS REPORTED_CUMULATIVE

-- Reported per 1000000 over the last seven days including today. Do only report when there are seven days that can be totaled.
,   IIF(LAG ([DATE_OF_STATISTICS] ,6) OVER (PARTITION BY SECURITY_REGION_CODE ORDER BY [DATE_OF_STATISTICS]) IS NULL, NULL,
		CAST(ROUND(SUM(REPORTED) OVER 
		(PARTITION BY SECURITY_REGION_CODE ORDER BY [DATE_OF_STATISTICS] ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)
		/(T1.INHABITANTS/1000000.0),0) AS INT)
	) AS REPORTED_PER_MIL_LAST_WEEK
,   LAG ([DATE_OF_STATISTICS] ,6) OVER (PARTITION BY SECURITY_REGION_CODE ORDER BY [DATE_OF_STATISTICS] ASC) WEEK_START
FROM BASE_CTE
LEFT JOIN (
	SELECT VRCODE, VRNAAM FROM [VWSSTATIC].[SAFETY_REGIONS_PER_MUNICIPAL]
	WHERE DATE_LAST_INSERTED=(SELECT MAX(DATE_LAST_INSERTED) FROM [VWSSTATIC].[SAFETY_REGIONS_PER_MUNICIPAL])
	group by VRCODE, VRNAAM
	) AS T ON SECURITY_REGION_CODE=T.VRCODE
LEFT JOIN(
    SELECT VGRNR, INHABITANTS
    FROM [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION])
) AS T1 ON SECURITY_REGION_CODE = T1.VGRNR 
END
