-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
CREATE OR ALTER PROCEDURE dbo.SP_NICE_HOSPITAL_GM_BASE
AS
BEGIN
WITH LAST_DATE_OF_REPORT AS (
SELECT
GM_CODE
,   CAST(MAX(DATE_OF_STATISTICS) as datetime) AS [LAST_DATE_OF_REPORT]
FROM VWSDEST.NICE_HOSPITAL_GM
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.NICE_HOSPITAL_GM)
GROUP BY GM_CODE
),
BASE_CTE AS (
SELECT
    DATE_OF_STATISTICS AS DATE_OF_REPORT,
    dbo.CONVERT_DATETIME_TO_UNIX([DATE_OF_STATISTICS]) AS [NEW_DATE_OF_REPORT_UNIX],
    GM_CODE,
    LAG(dbo.CONVERT_DATETIME_TO_UNIX([DATE_OF_STATISTICS]), 1, NULL) OVER (PARTITION BY [GM_CODE] ORDER BY [DATE_LAST_INSERTED], DATE_OF_STATISTICS) AS [OLD_DATE_OF_REPORT_UNIX],
    LAG(DBO.NO_NEGATIVE_NUMBER_F(HOSPITALIZED_3D_AVG), 1, NULL) OVER (PARTITION BY [GM_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_STATISTICS]) AS [OLD_VALUE],
    DBO.NO_NEGATIVE_NUMBER_F(HOSPITALIZED_3D_AVG) -
    LAG(DBO.NO_NEGATIVE_NUMBER_F(HOSPITALIZED_3D_AVG), 1, NULL) OVER (PARTITION BY [GM_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_STATISTICS]) AS [DIFFERENCE],
    LAG(DBO.NO_NEGATIVE_NUMBER_F(REPORTED), 1, NULL) OVER (PARTITION BY [GM_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_STATISTICS]) AS [OLD_VALUE_REPORTED],
    DBO.NO_NEGATIVE_NUMBER_F(REPORTED) -
    LAG(DBO.NO_NEGATIVE_NUMBER_F(REPORTED), 1, NULL) OVER (PARTITION BY [GM_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_STATISTICS]) AS [DIFFERENCE_REPORTED]
    
-- dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX
FROM VWSDEST.NICE_HOSPITAL_GM
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
FROM VWSDEST.NICE_HOSPITAL_GM)
)
INSERT INTO VWSDEST.NICE_HOSPITAL_GM_BASE
    (DATE_OF_REPORT,
    NEW_DATE_OF_REPORT_UNIX,
    GMCODE,
    OLD_DATE_OF_REPORT_UNIX,
    OLD_VALUE,
    [DIFFERENCE]
    ,OLD_VALUE_REPORTED
    ,DIFFERENCE_REPORTED)
SELECT
    DATE_OF_REPORT
    ,NEW_DATE_OF_REPORT_UNIX
    ,T1.GM_CODE AS GMCODE
    ,OLD_DATE_OF_REPORT_UNIX
    ,OLD_VALUE
    ,[DIFFERENCE]
    ,OLD_VALUE_REPORTED
    ,DIFFERENCE_REPORTED
FROM BASE_CTE T1
LEFT JOIN LAST_DATE_OF_REPORT T2
ON T1.[GM_CODE] = T2.[GM_CODE]
WHERE DATE_OF_REPORT = LAST_DATE_OF_REPORT
END