-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Stored procedure for creating infected people per age group
CREATE OR ALTER PROCEDURE DBO.SP_RIVM_AGEGROUP_TOTALS
AS
BEGIN
WITH BASE_CTE AS(
SELECT [ID]
      ,[DATE_FILE]
      ,[DATE_STATISTICS]
      ,[DATE_STATISTICS_TYPE]
      ,[AGEGROUP]
      ,[SEX]
      ,[PROVINCE]
      ,[HOSPITAL_ADMISSION]
      ,[DECEASED]
      ,[WEEK_OF_DEATH]
      ,[MUNICIPAL_HEALTH_SERVICE]
      ,[DATE_LAST_INSERTED]
  FROM [VWSINTER].[RIVM_COVID_19_CASE_NATIONAL]
  WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSINTER].[RIVM_COVID_19_CASE_NATIONAL])
)
,
SECOND_CTE AS (
SELECT 
       [DATE_FILE]
      ,[AGEGROUP]
      ,COUNT(*)                                                 AS INFECTED
      ,COUNT(IIF(DECEASED           = 'Yes',1,NULL))            AS DECEASED
      ,COUNT(IIF(HOSPITAL_ADMISSION = 'Yes',1,NULL))            AS HOSPITALIZED
    FROM BASE_CTE
    GROUP BY DATE_FILE,AGEGROUP

)      

INSERT INTO VWSDEST.RIVM_AGEGROUP_TOTALS
    (DATE_FILE, AGEGROUP, INFECTED, DECEASED, HOSPITALIZED, INFECTED_TOTAL, DECEASED_TOTAL, HOSPITALIZED_TOTAL)


SELECT 
       [DATE_FILE]
      ,[AGEGROUP]
      ,INFECTED
      ,DECEASED
      ,HOSPITALIZED
      ,SUM(INFECTED) OVER (PARTITION BY DATE_FILE)              AS INFECTED_TOTAL
      ,SUM(DECEASED) OVER (PARTITION BY DATE_FILE)              AS DECEASED_TOTAL
      ,SUM(HOSPITALIZED) OVER (PARTITION BY DATE_FILE)          AS HOSPITALIZED_TOTAL
    FROM SECOND_CTE


END;