-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE [dbo].[SP_DECEASED_PER_AGE_GROUP]
AS
BEGIN
-- Move data from intermediate table to destination table.
WITH BASE_CTE AS (
SELECT
    DATE_LAST_INSERTED
,   CAST(CASE AGEGROUP
             WHEN '0-9'      THEN '0-49'
             WHEN '10-19'    THEN '0-49'
             WHEN '20-29'    THEN '0-49'
             WHEN '30-39'    THEN '0-49'
             WHEN '40-49'    THEN '0-49'
             WHEN '<50'      THEN '0-49'
             ELSE AGEGROUP
    END AS VARCHAR(100)) AS [AGEGROUP]
,   WEEK_OF_DEATH
FROM VWSINTER.RIVM_COVID_19_CASE_NATIONAL T1
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSINTER.RIVM_COVID_19_CASE_NATIONAL)
AND --WEEK_OF_DEATH <> ''
DECEASED = 'Yes'
)
,
TOTAL_DEATHS AS (
 SELECT 
             COUNT(*) AS DEATHS
            ,AGEGROUP
      FROM BASE_CTE
      GROUP BY AGEGROUP
)
,INHABITANTS AS (
SELECT AGEGROUP_CBS, SUM(INHABITANTS_PERCENTAGE) AS INHABITANTS_PERCENTAGE FROM (
SELECT
    CAST(CASE AGEGROUP
        WHEN '0-9'      THEN '0-49'
        WHEN '10-19'    THEN '0-49'
        WHEN '20-29'    THEN '0-49'
        WHEN '30-39'    THEN '0-49'
        WHEN '40-49'    THEN '0-49'
        WHEN '<50'      THEN '0-49'
        ELSE AGEGROUP
    END AS VARCHAR(100)) AS AGEGROUP_CBS
    ,INHABITANTS_PERCENTAGE
FROM [VWSSTATIC].[CBS_AGEGROUP_DISTRIBUTION]
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSSTATIC].[CBS_AGEGROUP_DISTRIBUTION]) AND AGEGROUP IS NOT NULL AND INHABITANTS_PERCENTAGE IS NOT NULL) T3
GROUP BY T3.AGEGROUP_CBS
)

--Insert into dest table

INSERT INTO VWSDEST.DECEASED_PER_AGE_GROUP
    (
    AGEGROUP ,
    INHABITANTS_PERCENTAGE ,
    DEATHS ,
    DEATHS_PERCENTAGE 
    )


SELECT 
     T1.AGEGROUP
    ,ROUND(T2.INHABITANTS_PERCENTAGE * 100,1) AS INHABITANTS_PERCENTAGE
    ,T1.DEATHS
    ,ROUND(T1.DEATHS / SUM(CAST(T1.DEATHS AS FLOAT)) OVER (PARTITION BY 1) * 100,1)  as DEATHS_PERCENTAGE
 FROM TOTAL_DEATHS T1
 LEFT JOIN INHABITANTS T2
   ON T1.AGEGROUP = T2.AGEGROUP_CBS

END;
GO