-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE [dbo].[SP_NICE_HOSPITAL_GM]
AS
BEGIN
WITH BASE_CTE AS (
SELECT
	DATE_OF_STATISTICS
,	MUNICIPALITY_CODE
,	SUM(HOSPITALIZED) AS HOSPITALIZED
,	SUM(REPORTED) AS REPORTED
FROM VWSINTER.NICE_HOSPITAL
WHERE MUNICIPALITY_CODE!='NA'
AND DATE_LAST_INSERTED=(SELECT MAX(DATE_LAST_INSERTED) FROM VWSINTER.NICE_HOSPITAL)
GROUP BY MUNICIPALITY_CODE, DATE_OF_STATISTICS
)
INSERT INTO VWSDEST.NICE_HOSPITAL_GM(
	DATE_OF_STATISTICS
,	GM_CODE
,	GM_NAME
,	HOSPITALIZED
,	REPORTED
,	HOSPITALIZED_3D_AVG
,	REPORTED_3D_AVG
,	REPORTED_PER_MIL_LAST_WEEK
,	WEEK_START
    )
SELECT
	DATE_OF_STATISTICS
,	MUNICIPALITY_CODE
,	GMNAAM
,	HOSPITALIZED
,	REPORTED
,	AVG(CAST([HOSPITALIZED] AS FLOAT)) OVER (PARTITION BY MUNICIPALITY_CODE ORDER BY DATE_OF_STATISTICS ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as HOSPITALIZED_3D_AVG
,	AVG(CAST([REPORTED] AS FLOAT)) OVER (PARTITION BY MUNICIPALITY_CODE ORDER BY DATE_OF_STATISTICS ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as REPORTED_3D_AVG
-- Reported per 1000000 over the last seven days including today. Do only report when there are seven days that can be totaled.
,   IIF( LAG ([DATE_OF_STATISTICS] ,6) OVER (PARTITION BY MUNICIPALITY_CODE ORDER BY [DATE_OF_STATISTICS] ASC ) IS NULL, NULL,
		CAST(ROUND(SUM(REPORTED) OVER 
		(PARTITION BY MUNICIPALITY_CODE ORDER BY [DATE_OF_STATISTICS] ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)
		/(T1.INHABITANTS/1000000.0),0) AS INT)
	) AS REPORTED_PER_MIL_LAST_WEEK
,   LAG ([DATE_OF_STATISTICS] ,6) OVER (PARTITION BY MUNICIPALITY_CODE ORDER BY [DATE_OF_STATISTICS] ASC ) WEEK_START
FROM BASE_CTE
LEFT JOIN (
	SELECT GMCODE, GMNAAM FROM [VWSSTATIC].[SAFETY_REGIONS_PER_MUNICIPAL]
	WHERE DATE_LAST_INSERTED=(SELECT MAX(DATE_LAST_INSERTED) FROM [VWSSTATIC].[SAFETY_REGIONS_PER_MUNICIPAL])) AS T
ON MUNICIPALITY_CODE=T.GMCODE
LEFT JOIN(
    SELECT GMCODE, INHABITANTS
    FROM [VWSSTATIC].[INHABITANTS_PER_MUNICIPALITY]
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSSTATIC].[INHABITANTS_PER_MUNICIPALITY])
) AS T1 ON MUNICIPALITY_CODE = T1.GMCODE 
END