-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE DBO.SP_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE
AS
BEGIN

WITH LAST_DATE_OF_REPORT AS (
	SELECT
		MUNICIPALITY_CODE AS GMCODE,
		CAST(MAX(DATE_OF_REPORT) as datetime) AS [LAST_DATE_OF_REPORT]
	FROM [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY]
	WHERE DATE_OF_REPORT >=  '2020-03-16 00:00:00.000'
		AND DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY])
	GROUP BY MUNICIPALITY_CODE
)
,
BASE_CTE AS
(
  SELECT 
        DATE_OF_REPORT,
        DATE_OF_REPORT_UNIX AS [NEW_DATE_OF_REPORT_UNIX],
        MUNICIPALITY_CODE AS GMCODE,

        -- Difference for absolute numbers of positive tests
        DBO.NO_NEGATIVE_NUMBER_F([INFECTED_DAILY_TOTAL]) AS INFECTED_TOTAL, --for comparison purpose
        LAG([DATE_OF_REPORT_UNIX], 1, NULL) OVER (PARTITION BY [MUNICIPALITY_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_REPORT_UNIX]) AS [OLD_DATE_OF_REPORT_UNIX],
        LAG(DBO.NO_NEGATIVE_NUMBER_F([INFECTED_DAILY_TOTAL]), 1, NULL) OVER (PARTITION BY [MUNICIPALITY_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_REPORT_UNIX]) AS [OLD_VALUE],
        DBO.NO_NEGATIVE_NUMBER_F([INFECTED_DAILY_TOTAL]) -
            LAG(DBO.NO_NEGATIVE_NUMBER_F([INFECTED_DAILY_TOTAL]), 1, NULL) OVER (PARTITION BY [MUNICIPALITY_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_REPORT_UNIX]) AS [DIFFERENCE],

        -- Difference for relative numbers of positive tests, numbers are per 100k
         DBO.NO_NEGATIVE_NUMBER_F([INFECTED_DAILY_INCREASE]) AS INFECTED_DAILY_INCREASE, --for comparison purpose
        LAG(DBO.NO_NEGATIVE_NUMBER_F([INFECTED_DAILY_INCREASE]), 1, NULL) OVER (PARTITION BY [MUNICIPALITY_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_REPORT_UNIX]) AS [OLD_VALUE_PER_100K],
        ROUND(DBO.NO_NEGATIVE_NUMBER_F([INFECTED_DAILY_INCREASE]) -
            LAG(DBO.NO_NEGATIVE_NUMBER_F([INFECTED_DAILY_INCREASE]), 1, NULL) OVER (PARTITION BY [MUNICIPALITY_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_REPORT_UNIX]),1) AS [DIFFERENCE_PER_100K]
   	FROM VWSDEST.POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY
    WHERE DATE_LAST_INSERTED = (SELECT max(DATE_LAST_INSERTED) FROM VWSDEST.POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY)
)

INSERT INTO VWSDEST.POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE
    (DATE_OF_REPORT, NEW_DATE_OF_REPORT_UNIX, GMCODE, OLD_DATE_OF_REPORT_UNIX, OLD_VALUE, DIFFERENCE, OLD_VALUE_PER_100K, DIFFERENCE_PER_100K)

SELECT 
        T1.[DATE_OF_REPORT],
        T1.[NEW_DATE_OF_REPORT_UNIX],
        T1.[GMCODE],
        T1.[OLD_DATE_OF_REPORT_UNIX],
        T1.[OLD_VALUE],
        T1.[DIFFERENCE],
        T1.[OLD_VALUE_PER_100K],
        T1.[DIFFERENCE_PER_100K]
FROM BASE_CTE AS T1
LEFT JOIN LAST_DATE_OF_REPORT AS T2
	ON T1.[GMCODE] = T2.[GMCODE]
WHERE T1.[DATE_OF_REPORT] = T2.[LAST_DATE_OF_REPORT]
END;