-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE [dbo].[SP_VWS_VACCINE_DELIVERIES_DEST]
AS
BEGIN

INSERT INTO VWSDEST.VWS_VACCINE_DELIVERIES
(
    [DATE_OF_REPORT_UNIX]
    ,[DATE_FIRST_DAY]
    ,DATE_START_UNIX
    ,DATE_END_UNIX
    ,[VALUE_TYPE]
    ,[REPORT_STATUS]
    ,[VALUE]
)
SELECT 
       [dbo].[CONVERT_DATETIME_TO_UNIX](DATE_OF_REPORT) AS DATE_OF_REPORT_UNIX
      ,[DATE_FIRST_DAY]
      ,[dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_FIRST_DAY])                 AS DATE_START_UNIX
      ,[dbo].[CONVERT_DATETIME_TO_UNIX](DATEADD(DAY,6,[DATE_FIRST_DAY]))  AS DATE_END_UNIX
      ,[VALUE_TYPE]
      ,[REPORT_STATUS]
      ,[VALUE]
  FROM [VWSINTER].[VWS_VACCINE_DELIVERIES_ADMINISTERED]
  WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSINTER].[VWS_VACCINE_DELIVERIES_ADMINISTERED]) 
    AND VALUE_TYPE = 'vaccine_delivery' 
    ORDER BY DATE_FIRST_DAY
END;
