-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE [dbo].[SP_RIVM_DECEASED_DAILY]
AS
BEGIN

WITH BASE_CTE AS (
SELECT
    DATE_OF_PUBLICATION
,   SUM(DECEASED) AS DECEASED_ACTUAL
,   SECURITY_REGION_CODE
FROM VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY)
GROUP BY DATE_OF_PUBLICATION, SECURITY_REGION_CODE
)

INSERT INTO VWSDEST.RIVM_DECEASED_DAILY_PER_REGION
(
    DATE_OF_REPORT
,   DATE_OF_REPORT_UNIX
,   DECEASED_ACTUAL
,   DECEASED_CUMULATIVE
,   VRCODE
)
SELECT
   DATE_OF_PUBLICATION
,  dbo.CONVERT_DATETIME_TO_UNIX(DATE_OF_PUBLICATION)
,   DECEASED_ACTUAL
,   SUM(DECEASED_ACTUAL) OVER(PARTITION BY SECURITY_REGION_CODE ORDER BY DATE_OF_PUBLICATION ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COVID_TOTAL
,   SECURITY_REGION_CODE
FROM BASE_CTE
GROUP BY SECURITY_REGION_CODE, DATE_OF_PUBLICATION, DECEASED_ACTUAL
END
GO