-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE DBO.SP_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY
AS
BEGIN
-- Move positively tested persons data from intermediate table to destination table. 
-- Main select and insert statement for people tested positively. Calculation per date of report.  
    INSERT INTO VWSDEST.POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY
    (DATE_OF_REPORT, DATE_OF_REPORT_UNIX, MUNICIPALITY_CODE, MUNICIPALITY_NAME, INFECTED_DAILY_TOTAL, INFECTED_DAILY_INCREASE)
    SELECT
        DATE_OF_PUBLICATION AS DATE_OF_REPORT
    ,   dbo.CONVERT_DATETIME_TO_UNIX(DATE_OF_PUBLICATION) AS [DATE_OF_REPORT_UNIX]
    ,   MUNICIPALITY_CODE
    ,   MUNICIPALITY_NAME
    ,   SUM(CAST(Total_reported AS FLOAT)) AS [INCREASE_ABSOLUTE]
    ,   SUM(CAST(Total_reported AS FLOAT))/dbo.NORMALIZATION(CAST(c.INHABITANTS AS FLOAT)) AS [INCREASE]
    FROM VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY a
        JOIN VWSSTATIC.INHABITANTS_PER_MUNICIPALITY c
               ON a.MUNICIPALITY_CODE = c.GMCODE
               AND c.DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSSTATIC.INHABITANTS_PER_MUNICIPALITY)
        WHERE a.DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY)
            AND MUNICIPALITY_CODE != ''
        GROUP BY DATE_OF_PUBLICATION, MUNICIPALITY_CODE, MUNICIPALITY_NAME, INHABITANTS
END;