-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE [dbo].[SP_RIVM_IC_OPNAME]
AS
BEGIN
    WITH BASE_CTE AS (
  SELECT
    [VERSION],
	DATE_OF_REPORT,
	[dbo].[CONVERT_DATETIME_TO_UNIX](DATE_OF_REPORT) AS DATE_OF_REPORT_UNIX,
    DATE_OF_STATISTICS,
	[dbo].[CONVERT_DATETIME_TO_UNIX](DATE_OF_STATISTICS) AS DATE_OF_STATISTICS_UNIX,
    IC_ADMISSION_NOTIFICATION,
    IC_ADMISSION,

    --Calculations for differences
    LAG([dbo].[CONVERT_DATETIME_TO_UNIX](DATE_OF_STATISTICS), 1) OVER (ORDER BY DATE_OF_STATISTICS) AS OLD_DATE_OF_STATISTICS_UNIX,
    LAG(IC_ADMISSION_NOTIFICATION, 1) OVER (ORDER BY DATE_OF_STATISTICS) AS OLD_IC_ADMISSION_NOTIFICATION,
    LAG(IC_ADMISSION, 1) OVER (ORDER BY DATE_OF_STATISTICS) AS OLD_IC_ADMISSION
    
	FROM 
        VWSINTER.RIVM_IC_OPNAME
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) 
                                  FROM VWSINTER.RIVM_IC_OPNAME)
)


INSERT INTO VWSDEST.RIVM_IC_OPNAME(
    [VERSION],
	DATE_OF_REPORT,
	DATE_OF_REPORT_UNIX,
    DATE_OF_STATISTICS,
	DATE_OF_STATISTICS_UNIX,
    IC_ADMISSION_NOTIFICATION,
    IC_ADMISSION,
    OLD_DATE_OF_STATISTICS_UNIX,
    OLD_IC_ADMISSION_NOTIFICATION,
    DIFFERENCE_IC_ADMISSION_NOTIFICATION,
    OLD_IC_ADMISSION,
    DIFFERENCE_IC_ADMISSION
    )
SELECT 
    [VERSION],
	DATE_OF_REPORT,
	DATE_OF_REPORT_UNIX,
    DATE_OF_STATISTICS,
	DATE_OF_STATISTICS_UNIX,
    IC_ADMISSION_NOTIFICATION,
    IC_ADMISSION,

    --Differences
    OLD_DATE_OF_STATISTICS_UNIX,
    OLD_IC_ADMISSION_NOTIFICATION,
    IC_ADMISSION_NOTIFICATION - OLD_IC_ADMISSION_NOTIFICATION   AS DIFFERENCE_IC_ADMISSION_NOTIFICATION,
    OLD_IC_ADMISSION,
    IC_ADMISSION - OLD_IC_ADMISSION                             AS DIFFERENCE_IC_ADMISSION
FROM BASE_CTE
END;
