-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE DBO.SP_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_BASE
AS
BEGIN
    INSERT INTO VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_BASE
    (DATE_OF_REPORT, NEW_DATE_OF_REPORT_UNIX, GMCODE, OLD_DATE_OF_REPORT_UNIX, OLD_VALUE, DIFFERENCE)
    SELECT 
        DATE_OF_REPORT,
        DATE_OF_REPORT_UNIX AS [NEW_DATE_OF_REPORT_UNIX],
        T1.MUNICIPALITY_CODE AS GMCODE,
        LAG([DATE_OF_REPORT_UNIX], 1, NULL) OVER (PARTITION BY T1.[MUNICIPALITY_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_REPORT_UNIX]) AS [OLD_DATE_OF_REPORT_UNIX],
        LAG(DBO.NO_NEGATIVE_NUMBER_F([MOVING_AVERAGE_HOSPITAL]), 1, NULL) OVER (PARTITION BY T1.[MUNICIPALITY_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_REPORT_UNIX]) AS [OLD_VALUE],
        DBO.NO_NEGATIVE_NUMBER_F([MOVING_AVERAGE_HOSPITAL]) -
            LAG(DBO.NO_NEGATIVE_NUMBER_F([MOVING_AVERAGE_HOSPITAL]), 1, NULL) OVER (PARTITION BY T1.[MUNICIPALITY_CODE] ORDER BY [DATE_LAST_INSERTED], [DATE_OF_REPORT_UNIX]) AS [DIFFERENCE]
        --  dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX
    FROM VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY T1
    WHERE DATE_OF_REPORT >=  '2020-03-16 00:00:00.000'
    AND DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                                FROM VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY)
END;