-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE DBO.SP_NURSING_HOMES_PER_REGION
AS
BEGIN

    WITH BASE_CTE AS (
        SELECT
            DATE_OF_STATISTIC_REPORTED AS DATE_OF_REPORT,
            dbo.CONVERT_DATETIME_TO_UNIX(DATE_OF_STATISTIC_REPORTED) AS DATE_OF_REPORT_UNIX,
            [SECURITY_REGION_CODE] AS VRCODE,
            TOTAL_CASES_REPORTED AS INFECTED_NURSERY_DAILY,
            TOTAL_DECEASED_REPORTED AS DECEASED_NURSERY_DAILY,
            TOTAL_NEW_INFECTED_LOCATIONS_REPORTED AS TOTAL_NEW_REPORTED_LOCATIONS,
            TOTAL_INFECTED_LOCATIONS_REPORTED AS TOTAL_REPORTED_LOCATIONS
        FROM
            VWSINTER.RIVM_NURSING_HOMES_COMBINED
        WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from VWSINTER.RIVM_NURSING_HOMES_COMBINED)
            AND DATE_OF_STATISTIC_REPORTED > '1900-01-01 00:00:00.000'
    )


,TOTALS_CTE AS (
SELECT  
       [DATE_OF_REPORT]
	  ,DATE_OF_REPORT_UNIX
	  ,VRCODE
      ,INFECTED_NURSERY_DAILY
	  ,DECEASED_NURSERY_DAILY
	  ,TOTAL_NEW_REPORTED_LOCATIONS
	  ,TOTAL_REPORTED_LOCATIONS
      ,LAG ([DATE_OF_REPORT] ,6)                 OVER (PARTITION BY VRCODE ORDER BY [DATE_OF_REPORT] ASC)  as [DATE_RANGE_START]
      ,LAG ([DATE_OF_REPORT] ,1)                   OVER (PARTITION BY VRCODE ORDER BY DATE_OF_REPORT ASC)  as [DATE_OF_REPORTS_LAG]
      ,LAG ([DATE_OF_REPORT] ,7)                   OVER (PARTITION BY VRCODE ORDER BY DATE_OF_REPORT ASC)  as [DATE_RANGE_START_LAG]
	  ,ROUND(AVG(CAST([INFECTED_NURSERY_DAILY]     AS FLOAT)) OVER (PARTITION BY VRCODE ORDER BY [DATE_OF_REPORT] ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW),1) as [7D_AVERAGE_TOTAL_INFECTED]
	  ,ROUND(AVG(CAST([INFECTED_NURSERY_DAILY]     AS FLOAT)) OVER (PARTITION BY VRCODE  ORDER BY [DATE_OF_REPORT] ASC ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING),1) as [7D_AVERAGE_TOTAL_INFECTED_LAG]
	  ,ROUND(AVG(CAST([DECEASED_NURSERY_DAILY]     AS FLOAT)) OVER (PARTITION BY VRCODE ORDER BY [DATE_OF_REPORT] ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW),1) as [7D_AVERAGE_TOTAL_DECEASED]
      ,ROUND(AVG(CAST([DECEASED_NURSERY_DAILY]     AS FLOAT)) OVER (PARTITION BY VRCODE  ORDER BY [DATE_OF_REPORT] ASC ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING),1) as [7D_AVERAGE_TOTAL_DECEASED_LAG]
FROM BASE_CTE
)


INSERT INTO VWSDEST.NURSING_HOMES_PER_REGION
    (
         DATE_OF_REPORT
        ,DATE_OF_REPORT_UNIX
		,VRCODE
        ,INFECTED_NURSERY_DAILY
		,DECEASED_NURSERY_DAILY
	    ,TOTAL_NEW_REPORTED_LOCATIONS
        ,TOTAL_REPORTED_LOCATIONS
        ,INFECTED_LOCATIONS_PERCENTAGE
		,[DATE_RANGE_START]
		,[DATE_OF_REPORTS_LAG]
		,[DATE_RANGE_START_LAG]
		,[7D_AVERAGE_TOTAL_INFECTED]
		,[7D_AVERAGE_TOTAL_INFECTED_LAG]
        ,[7D_AVERAGE_TOTAL_DECEASED]
		,[7D_AVERAGE_TOTAL_DECEASED_LAG]
    )
    SELECT
         DATE_OF_REPORT
        ,DATE_OF_REPORT_UNIX
        ,BASE.VRCODE
		,INFECTED_NURSERY_DAILY
        ,DECEASED_NURSERY_DAILY
        ,TOTAL_NEW_REPORTED_LOCATIONS
        ,TOTAL_REPORTED_LOCATIONS
        ,ROUND(
            100 * CAST(TOTAL_REPORTED_LOCATIONS AS FLOAT) / LOC.VERPLEEGHUIZEN
            , 2
        ) AS INFECTED_LOCATIONS_PERCENTAGE
		,[DATE_RANGE_START]
		,[DATE_OF_REPORTS_LAG]
		,[DATE_RANGE_START_LAG]
		,[7D_AVERAGE_TOTAL_INFECTED]
		,[7D_AVERAGE_TOTAL_INFECTED_LAG]
		,[7D_AVERAGE_TOTAL_DECEASED]
		,[7D_AVERAGE_TOTAL_DECEASED_LAG]
    FROM TOTALS_CTE BASE
    LEFT JOIN [VWSSTATIC].[NURSING_HOME_LOCATIONS_PER_REGION] LOC
        ON LOC.VRCODE = BASE.VRCODE
        AND LOC.DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSSTATIC].[NURSING_HOME_LOCATIONS_PER_REGION])
END;