-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
-- just because we can't do a where before join. This base table to select the last and than a join
CREATE OR ALTER PROCEDURE DBO.SP_CBS_DECEASED_PER_WEEK
AS
BEGIN
WITH BASE_CTE as(
SELECT * FROM [VWSINTER].[CBS_DECEASED_PER_WEEK]
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from [VWSINTER].[CBS_DECEASED_PER_WEEK])
),

SECOND_CTE as(
SELECT
    [dbo].[CONVERT_ISO_WEEK_TO_DATETIME](T1.YEAR, T1.WEEK) as WEEK_START
,   [dbo].[WEEK_END]([dbo].[CONVERT_ISO_WEEK_TO_DATETIME](T1.YEAR, T1.WEEK)) as WEEK_END
,   [dbo].[CONVERT_WEEKNUMBER_TO_UNIX](T1.YEAR, T1.WEEK) as WEEK_START_UNIX
,   [dbo].[CONVERT_DATETIME_TO_UNIX]([dbo].[WEEK_END]([dbo].[CONVERT_ISO_WEEK_TO_DATETIME](T1.YEAR, T1.WEEK))) as WEEK_END_UNIX
,    CASE WHEN T1.WEEK = 0 THEN T1.YEAR-1 ELSE T1.[YEAR] END AS [YEAR]
,   CASE WHEN T1.WEEK = 0 THEN 53 ELSE T1.WEEK END AS [WEEK]
,   T1.DECEASED_ACTUAL
FROM BASE_CTE AS T1
),

THIRD_CTE AS (
    SELECT 
        WEEK_START, 
        WEEK_END, 
        WEEK_START_UNIX, 
        WEEK_END_UNIX, 
        [YEAR], 
        [WEEK], 
        SUM(DECEASED_ACTUAL) AS DECEASED_ACTUAL
    FROM SECOND_CTE
    GROUP BY WEEK_START, WEEK_END, WEEK_START_UNIX, WEEK_END_UNIX, [YEAR], [WEEK]
)

INSERT INTO VWSDEST.CBS_DECEASED_PER_WEEK(
    WEEK_START
,   WEEK_END
,   WEEK_START_UNIX
,   WEEK_END_UNIX
,   YEAR
,   WEEK
,   DECEASED_ACTUAL
,   DECEASED_FORECAST
,   DECEASED_FORECAST_HIGH
,   DECEASED_FORECAST_LOW
)
select
    T1.WEEK_START
,   T1.WEEK_END
,   T1.WEEK_START_UNIX
,   T1.WEEK_END_UNIX
,   T1.YEAR
,   T1.WEEK
,   T1.DECEASED_ACTUAL
,   T2.DECEASED_FORECAST
,   T2.DECEASED_FORECAST_HIGH
,   T2.DECEASED_FORECAST_LOW
FROM THIRD_CTE AS T1
LEFT JOIN (
    SELECT * FROM [VWSINTER].[CBS_DECEASED_PER_WEEK_FORECAST]
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from [VWSINTER].[CBS_DECEASED_PER_WEEK_FORECAST])
) AS T2
ON T1.[YEAR]=T2.[YEAR] AND T1.[WEEK]=T2.[WEEK]
END