/****** Script for SelectTopNRows command from SSMS  ******/
CREATE    VIEW [V_DEPENDENCIES_LOAD] AS

SELECT [PROCESS_ID]
      ,[PROCESS]
      ,[PROCESS_SOURCE]
      ,[DEPENDENCY_ID]
      ,[DEPENDENCY]
      ,[DEPENDENCY_SOURCE]
      ,[WORKFLOW_NAME]

  FROM [DATATINO_ORCHESTRATOR].[V_DEPENDENCIES]

UNION 

select [PROCESS_ID]
      ,[PROCESS_NAME] AS [PROCESS]
      ,NULL AS [PROCESS_SOURCE]
      ,NULL AS [DEPENDENCY_ID]
      ,[SOURCE] AS [DEPENDENCY]
      ,NULL AS [DEPENDENCY_SOURCE]
      ,[WORKFLOW_NAME]
  FROM [DATATINO_ORCHESTRATOR].[V_PROCESSES]
  where [PROCESS_ID] not in (Select PROCESS_ID  FROM [DATATINO_ORCHESTRATOR].[V_DEPENDENCIES]) 
  AND SOURCE_COLUMNS is not null