CREATE   VIEW [VWSDEST].[V_CIMS_VACCINATED_PER_AGE_GROUP_ARCHIVED_20220908] 
 AS
     WITH CTE AS (
         SELECT
             [AGE_GROUP],
             [COVERAGE_AGEGROUP],
             [DATE_OF_STATISTICS],
             [AMOUNT_CUMULATIVE]
         FROM [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL_ARCHIVED_20220908] WITH(NOLOCK)
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) 
             FROM [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL_ARCHIVED_20220908] WITH(NOLOCK))
     )
     SELECT
         [DBO].[CONVERT_DATETIME_TO_UNIX](DATE_OF_REPORT) AS [DATE_OF_REPORT_UNIX],
         [DBO].[CONVERT_DATETIME_TO_UNIX](DATE_OF_STATISTICS_WEEK_END) AS [DATE_UNIX],
         T1.[AGE_GROUP] AS [AGE_GROUP_RANGE],
         [BIRTH_COHORT] AS [BIRTHYEAR_RANGE],
         [AGE_GROUP_POPULATION] AS [AGE_GROUP_TOTAL],
         [AGE_GROUP_POPULATION_PERCENTAGE] AS [AGE_GROUP_PERCENTAGE],
         [VACCINATION_COMPLETED] AS [FULLY_VACCINATED],
         [VACCINATION_ALL] AS [HAS_ONE_SHOT],
         T2.[AMOUNT_CUMULATIVE] AS [BOOSTER_SHOT],
         CAST(FLOOR(T2.[COVERAGE_AGEGROUP]) AS INT) AS [BOOSTER_SHOT_PERCENTAGE],
         CAST(FLOOR([VACCINATION_COVERAGE_ALL]) AS INT) AS [HAS_ONE_SHOT_PERCENTAGE],
         CAST(FLOOR([VACCINATION_COVERAGE_COMPLETED]) AS INT) AS [FULLY_VACCINATED_PERCENTAGE],
         [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
     FROM [VWSARCHIVE].[CIMS_VACCINATED_PER_AGE_GROUP_ARCHIVED_20220908] T1 WITH(NOLOCK)
         LEFT JOIN CTE T2 ON T1.[DATE_OF_STATISTICS_WEEK_END] = T2.[DATE_OF_STATISTICS]
             AND T1.[AGE_GROUP] = T2.[AGE_GROUP]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSARCHIVE].[CIMS_VACCINATED_PER_AGE_GROUP_ARCHIVED_20220908] WITH(NOLOCK))
         AND T1.[AGE_GROUP] NOT IN ('12+','18+', '5+');