-- 1) CREATE VIEW(S).....
 CREATE     VIEW [VWSDEST].[V_CIMS_VACCINATED_PER_AGE_GROUP_GM_ARCHIVED_20220908]
 AS   
     WITH BOOSTER_CTE AS (
         SELECT
             [REGION_CODE] AS [GMCODE],
             [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS]) AS [DATE_UNIX],   
             [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX],
             [PERCENTAGE],
             [PERCENTAGE_LABEL],
             [AGE_GROUP]
         FROM [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM_ARCHIVED_20220908] WITH(NOLOCK)
         WHERE [REGION_CODE] LIKE 'GM%'
             AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM_ARCHIVED_20220908] WITH(NOLOCK))
             AND UPPER([VACCINATION_TYPE]) IN ('BOOSTER1_COVERAGE')
     ),
     BOOSTER_FILTERED_CTE AS (
         SELECT 
             T2.[GMCODE],
             [PERCENTAGE], 
             [PERCENTAGE_LABEL],
             [DATE_OF_INSERTION_UNIX],
             T2.[DATE_UNIX],
                 [AGE_GROUP]
         FROM BOOSTER_CTE T1
         INNER JOIN (
         SELECT
             MAX([DATE_UNIX]) AS [DATE_UNIX],
             [GMCODE]
         FROM BOOSTER_CTE
         GROUP BY [GMCODE]
         ) AS T2 ON T1.[GMCODE] = T2.[GMCODE] AND T1.[DATE_UNIX] = T2.[DATE_UNIX]
     ),
     CTE AS (
         SELECT
             dbo.CONVERT_DATETIME_TO_UNIX(DATE_OF_REPORT)                     AS DATE_OF_REPORT_UNIX,
             dbo.CONVERT_DATETIME_TO_UNIX(DATE_OF_STATISTICS)                 AS DATE_UNIX,
             [REGION_CODE]                                                    AS GMCODE,
             AGE_GROUP                                                        AS AGE_GROUP_RANGE,
             [BIRTH_YEAR]                                                     AS BIRTHYEAR_RANGE,
             CAST(ROUND(VACCINATION_COVERAGE_ALL, 0) AS INT)                  AS HAS_ONE_SHOT_PERCENTAGE,
             VACCINATION_COVERAGE_ALL_LABEL                                   AS HAS_ONE_SHOT_PERCENTAGE_LABEL,
             CAST(ROUND(VACCINATION_COVERAGE_COMPLETED, 0) AS INT)            AS FULLY_VACCINATED_PERCENTAGE,
             VACCINATION_COVERAGE_COMPLETED_LABEL                             AS FULLY_VACCINATED_PERCENTAGE_LABEL,
             dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED)                 AS DATE_OF_INSERTION_UNIX
         FROM [VWSARCHIVE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR_ARCHIVED_20220908] WITH(NOLOCK)
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSARCHIVE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR_ARCHIVED_20220908])
             AND LEFT(REGION_CODE,2) = 'GM'
     )
     SELECT 
         [DATE_OF_REPORT_UNIX],
         T1.[DATE_UNIX],
         T1.[GMCODE],
         [AGE_GROUP_RANGE],
         [BIRTHYEAR_RANGE],
         [HAS_ONE_SHOT_PERCENTAGE],
         [HAS_ONE_SHOT_PERCENTAGE_LABEL],
         [FULLY_VACCINATED_PERCENTAGE],
         [FULLY_VACCINATED_PERCENTAGE_LABEL],
         CAST(ROUND(T2.[PERCENTAGE], 0) AS INT) AS [BOOSTER_SHOT_PERCENTAGE],
         T2.[PERCENTAGE_LABEL] AS [BOOSTER_SHOT_PERCENTAGE_LABEL],
         T1.[DATE_OF_INSERTION_UNIX]
     FROM CTE T1
         LEFT JOIN BOOSTER_FILTERED_CTE AS T2 ON T1.[AGE_GROUP_RANGE] = T2.[AGE_GROUP] AND T1.[GMCODE] = T2.[GMCODE]
     WHERE [AGE_GROUP_RANGE] NOT IN ('12-17')