CREATE   VIEW VWSDEST.V_CLUSTERS_INFECTED_PEOPLE AS
SELECT 
    [DATE_OF_REPORT_UNIX],
    DBO.NO_NEGATIVE_NUMBER_I([ACTIVE_CLUSTERS]) AS ACTIVE_CLUSTERS,
    DBO.NO_NEGATIVE_NUMBER_F([CLUSTER_AVERAGE]) AS CLUSTER_AVERAGE,
    dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED)  AS DATE_OF_INSERTION_UNIX
FROM VWSDEST.CLUSTERS_INFECTED_PEOPLE
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.CLUSTERS_INFECTED_PEOPLE);