-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
 -- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordination for more information.
 /****** Object:  View [VWSDEST].[V_DIFFERENCE_INTAKE_HOSPITAL_MA__MOVING_AVERAGE_HOSPITAL_NICE]    Script Date: 15-12-2020 14:54:38 ******/
 
 --Previously [VWSDEST].[V_DIFFERENCE_INTAKE_HOSPITAL_MA__MOVING_AVERAGE_HOSPITAL_NICE] was used
 CREATE   VIEW [VWSDEST].[V_DIFFERENCE_INTAKE_HOSPITAL_REPORTED_NL] AS
 WITH LAST_DATE_OF_REPORT AS (
 	SELECT
 		CAST(MAX(DATE_OF_STATISTICS) as datetime) AS [LAST_DATE_OF_REPORT]
 	FROM VWSDEST.NICE_HOSPITAL_NL
 	WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.NICE_HOSPITAL_NL)
 ),
 
 BASE_CTE AS (
 
 SELECT 
 	DATE_OF_STATISTICS AS DATE_OF_REPORT,
 	dbo.CONVERT_DATETIME_TO_UNIX([DATE_OF_STATISTICS]) AS [NEW_DATE_OF_REPORT_UNIX],
 	dbo.CONVERT_DATETIME_TO_UNIX([DATE_OF_STATISTICS]) AS [OLD_DATE_OF_REPORT_UNIX],
     REPORTED_7D_AVG AS [OLD_VALUE],
 	[REPORTED]
 FROM VWSDEST.NICE_HOSPITAL_NL
 WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                             FROM VWSDEST.NICE_HOSPITAL_NL)
 )
 
 SELECT DATE_OF_REPORT
 	  ,NEW_DATE_OF_REPORT_UNIX					AS NEW_DATE_UNIX
 	  ,OLD_DATE_OF_REPORT_UNIX					AS OLD_DATE_UNIX
 	  ,CAST(round(OLD_VALUE, 0) as INT)			AS [OLD_VALUE]
 	  ,DBO.NO_NEGATIVE_NUMBER_F([REPORTED]) -
 		CAST(round(OLD_VALUE, 0) as INT)		AS [DIFFERENCE]
 FROM BASE_CTE T1
 WHERE DATE_OF_REPORT = (SELECT LAST_DATE_OF_REPORT FROM LAST_DATE_OF_REPORT)