-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
 -- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
 
CREATE   VIEW [VWSDEST].[V_DIFFERENCE_HOSPITAL_BED_LCPS_API_2023] AS
 
WITH BASE_CTE AS (
    SELECT * FROM [VWSDEST].[V_HOSPITAL_BED_LCPS_API_2023]
),
CTE1 AS ( -- average last 7 days
SELECT
    t1.[DATE_UNIX] AS [DATE_UNIX],
    t1.[DATE_UNIX] AS [NEW_DATE_UNIX],
    CAST(AVG(CAST(t2.[BEDS_OCCUPIED_COVID] AS FLOAT)) AS DECIMAL(16,2)) AS [NEW_VALUE]
FROM BASE_CTE t1
LEFT OUTER JOIN BASE_CTE t2
    ON
    dbo.CONVERT_UNIX_TO_DATETIME(t2.[DATE_UNIX])
    BETWEEN
    dateadd(day,-6,dbo.CONVERT_UNIX_TO_DATETIME(t1.[DATE_UNIX]))
    AND
    dbo.CONVERT_UNIX_TO_DATETIME(t1.[DATE_UNIX])
GROUP BY 
    t1.[DATE_UNIX]
),
CTE2 AS ( -- average last 7-14 days
SELECT
    t1.[DATE_UNIX],
    dbo.CONVERT_DATETIME_TO_UNIX(dateadd(day,-7,dbo.CONVERT_UNIX_TO_DATETIME(t1.[DATE_UNIX]))) AS [OLD_DATE_UNIX],
    CAST(AVG(CAST(t2.[BEDS_OCCUPIED_COVID] AS FLOAT)) AS DECIMAL(16,2)) AS [OLD_VALUE]
FROM BASE_CTE t1
LEFT OUTER JOIN BASE_CTE t2
    ON
    dbo.CONVERT_UNIX_TO_DATETIME(t2.[DATE_UNIX])
    BETWEEN
    dateadd(day,-13,dbo.CONVERT_UNIX_TO_DATETIME(t1.[DATE_UNIX]))
    AND
    dateadd(day,-7,dbo.CONVERT_UNIX_TO_DATETIME(t1.[DATE_UNIX]))
GROUP BY 
    t1.[DATE_UNIX]
),
CTE3 AS (
SELECT 
    t1.[DATE_UNIX],
    t2.[NEW_DATE_UNIX],
    t2.[NEW_VALUE],
    t3.[OLD_DATE_UNIX],
    t3.[OLD_VALUE]
FROM BASE_CTE t1
JOIN CTE1 t2
    ON t1.[DATE_UNIX] = t2.[DATE_UNIX]
JOIN CTE2 t3
    ON t1.[DATE_UNIX] = t3.[DATE_UNIX]
)
SELECT 
    [NEW_DATE_UNIX],
    [OLD_DATE_UNIX],
    [NEW_VALUE] - [OLD_VALUE] AS [DIFFERENCE],
    [OLD_VALUE]
FROM CTE3
WHERE [DATE_UNIX] = (SELECT MAX([DATE_UNIX]) FROM CTE3)
