-- -- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 --1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_DIFFERENCES_POSITIVE_TESTED_PEOPLE_70_PLUS_OVER_TIME] AS 
 
   WITH BASE_CTE AS 
 (
     SELECT
 		[DATE_UNIX],
 		LAG([DATE_UNIX], 1) OVER (ORDER BY [DATE_UNIX]) AS [OLD_DATE_UNIX],
 		[INFECTED_AGE_70_PLUS] AS [NEW_VALUE],
 		LAG([INFECTED_AGE_70_PLUS], 1) OVER (ORDER BY [DATE_UNIX]) AS [OLD_VALUE],
 		ROW_NUMBER() OVER (ORDER BY [DATE_UNIX] DESC) AS RANK_DATE
     FROM [VWSDEST].[V_POSITIVE_TESTED_PEOPLE_70_PLUS_OVER_TIME]
 )
 SELECT
     [DATE_UNIX] AS [NEW_DATE_UNIX],
     [OLD_DATE_UNIX] AS [OLD_DATE_UNIX],
     [OLD_VALUE],
     ROUND([NEW_VALUE] - [OLD_VALUE], 1) AS [DIFFERENCE]
 FROM BASE_CTE
   WHERE RANK_DATE = 1 --Only the most recent record