-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
 -- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
 
 CREATE   VIEW [VWSDEST].[V_DIFFERENCE_RIVM_SEWER_MEASUREMENTS_GM_2023] AS
 
 WITH CTE1 AS
 (
 	SELECT
 		[GMCODE],
 		[DATE_START_UNIX] AS [NEW_DATE_UNIX],
 		LAG([DATE_START_UNIX], 1, NULL) OVER (PARTITION BY [GMCODE] ORDER BY [GMCODE], [DATE_START_UNIX]) AS [OLD_DATE_UNIX],
 		[AVERAGE],
 		LAG([AVERAGE], 1, NULL) OVER (PARTITION BY [GMCODE] ORDER BY [GMCODE], [DATE_START_UNIX]) AS [OLD_VALUE]
 	FROM [VWSDEST].[V_RIVM_SEWER_MEASUREMENTS_GM_2023]
 ),
 CTE2 AS 
 (
 	SELECT [GMCODE], MAX([NEW_DATE_UNIX]) AS MAX_DATE
 	FROM CTE1
 	GROUP BY [GMCODE]
 )
 SELECT
 	CTE1.[GMCODE], 
 	CTE1.[NEW_DATE_UNIX], 
 	CTE1.[OLD_DATE_UNIX], 
 	CTE1.[OLD_VALUE], 
 	CTE1.[AVERAGE] - CTE1.[OLD_VALUE] AS [DIFFERENCE]
 FROM CTE1
 JOIN CTE2 ON CTE1.[GMCODE] = CTE2.[GMCODE] AND CTE1.[NEW_DATE_UNIX]= CTE2.MAX_DATE -- only take last values per municipality