-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE    VIEW [VWSDEST].[V_DIFFERENCE_GGD__INFECTED_AVERAGE_VR] AS

WITH LAST_DATE_OF_REPORT AS (
	SELECT
        REGION_CODE
	   ,CAST(MAX(DATE_OF_STATISTICS) as datetime) AS [LAST_DATE_OF_REPORT]
	FROM VWSDEST.GGD_TESTED_PEOPLE_VR WITH(NOLOCK)
	WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.GGD_TESTED_PEOPLE_VR WITH(NOLOCK))
    GROUP BY REGION_CODE
)

SELECT
       DATE_OF_STATISTICS AS DATE_OF_REPORT
	  ,NEW_DATE_OF_REPORT_UNIX AS NEW_DATE_UNIX
	  ,NEW_DATE_OF_REPORT_UNIX AS OLD_DATE_UNIX --Old date does not make sense when comparing daily value to 7day average
      ,T1.REGION_CODE AS VRCODE
    --   ,[PERCENTAGE_POSITIVE] AS NEW_VALUE
	  ,CASE WHEN [7D_AVERAGE_PERCENTAGE_POSITIVE] IS NULL THEN 0 ELSE [7D_AVERAGE_PERCENTAGE_POSITIVE] END AS OLD_VALUE
	  ,CASE WHEN [PERCENTAGE_POSITIVE] - [7D_AVERAGE_PERCENTAGE_POSITIVE] IS NULL THEN 0 ELSE [PERCENTAGE_POSITIVE] - [7D_AVERAGE_PERCENTAGE_POSITIVE] END AS [DIFFERENCE]
FROM VWSDEST.GGD_TESTED_PEOPLE_VR T1 WITH(NOLOCK)
LEFT JOIN LAST_DATE_OF_REPORT T2 ON
    T1.REGION_CODE = T2.REGION_CODE
WHERE DATE_OF_STATISTICS = LAST_DATE_OF_REPORT
    AND DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.GGD_TESTED_PEOPLE_VR WITH(NOLOCK))