-- -- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 --1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_DIFFERENCE_RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL]
 AS
      WITH CTE1 AS
     (
 	    SELECT
 		    [DBO].[CONVERT_DATETIME_TO_UNIX](DATEADD(day, -7,  [DATE_OF_STATISTICS])) AS [NEW_DATE_UNIX],
 		    LAG([DBO].[CONVERT_DATETIME_TO_UNIX](DATEADD(day, -7,  [DATE_OF_STATISTICS])), 1, NULL) OVER (ORDER BY [DATE_OF_STATISTICS]) AS [OLD_DATE_UNIX],
 		    [PERC_COVID_TEST_POSITIVE] AS [NEW_VALUE],
 		    LAG([PERC_COVID_TEST_POSITIVE], 1, NULL) OVER (ORDER BY [DATE_OF_STATISTICS]) AS [OLD_VALUE]
 	        FROM [VWSDEST].[RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL] WITH(NOLOCK)
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL] WITH(NOLOCK))
     )
     SELECT
 	    CTE1.[NEW_DATE_UNIX], 
 	    CTE1.[OLD_DATE_UNIX], 
 	    CTE1.[OLD_VALUE], 
 	    CTE1.[NEW_VALUE] - CTE1.[OLD_VALUE] AS [DIFFERENCE]
     FROM CTE1
     WHERE CTE1.[NEW_DATE_UNIX] = (SELECT MAX([NEW_DATE_UNIX]) FROM CTE1); -- only take last value
