-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
 -- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
 
 CREATE   VIEW [VWSDEST].[V_DIFFERENCE_RIVM_SEWER_MEASUREMENTS_NL_2023] AS
 
 WITH CTE1 AS
 (
 	SELECT
 		[DATE_UNIX] AS [NEW_DATE_UNIX],
 		LAG([DATE_UNIX], 1, NULL) OVER (ORDER BY [DATE_UNIX]) AS [OLD_DATE_UNIX],
 		[AVERAGE],
 		LAG([AVERAGE], 1, NULL) OVER (ORDER BY [DATE_UNIX]) AS [OLD_VALUE]
 	FROM [VWSDEST].[RIVM_SEWER_MEASUREMENTS_NL_2023]
 	WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[RIVM_SEWER_MEASUREMENTS_NL_2023])
 )
 SELECT
 	CTE1.[NEW_DATE_UNIX], 
 	CTE1.[OLD_DATE_UNIX], 
 	CTE1.[OLD_VALUE], 
 	CTE1.[AVERAGE] - CTE1.[OLD_VALUE] AS [DIFFERENCE]
 FROM CTE1
 WHERE CTE1.[NEW_DATE_UNIX] = (SELECT MAX([NEW_DATE_UNIX]) FROM CTE1); -- only take last value