-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE    VIEW [VWSDEST].[V_DIFFERENCE_GGD__INFECTED_AVERAGE_NL] AS

WITH LAST_DATE_OF_REPORT AS (
	SELECT
		CAST(MAX(DATE_OF_STATISTICS) as datetime) AS [LAST_DATE_OF_REPORT]
	FROM VWSDEST.GGD_TESTED_PEOPLE_NL
	WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.GGD_TESTED_PEOPLE_NL)
)

SELECT
       DATE_OF_STATISTICS AS DATE_OF_REPORT
	  ,NEW_DATE_OF_REPORT_UNIX AS NEW_DATE_UNIX
	  ,NEW_DATE_OF_REPORT_UNIX AS OLD_DATE_UNIX --Old date does not make sense when comparing daily value to 7day average
    --   ,[PERCENTAGE_POSITIVE] AS NEW_VALUE
	  ,CASE WHEN [7D_AVERAGE_PERCENTAGE_POSITIVE] IS NULL THEN 0 ELSE [7D_AVERAGE_PERCENTAGE_POSITIVE] END AS OLD_VALUE
	  ,CASE WHEN [PERCENTAGE_POSITIVE] - [7D_AVERAGE_PERCENTAGE_POSITIVE] IS NULL THEN 0 ELSE [PERCENTAGE_POSITIVE] - [7D_AVERAGE_PERCENTAGE_POSITIVE] END AS [DIFFERENCE]
FROM VWSDEST.GGD_TESTED_PEOPLE_NL T1
WHERE DATE_OF_STATISTICS = (SELECT LAST_DATE_OF_REPORT FROM LAST_DATE_OF_REPORT)
    AND DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.GGD_TESTED_PEOPLE_NL)