-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
 -- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
 CREATE   VIEW [VWSDEST].[V_DIFFERENCES_RIVM__DECEASED_DAILY_GM_ARCHIVED_20221231] AS 
 
 	SELECT DATE_OF_REPORT
 		  ,DATE_OF_REPORT_UNIX											AS NEW_DATE_UNIX
 		  ,OLD_DATE_OF_REPORT_UNIX										AS OLD_DATE_UNIX
 		  ,MUNICIPALITY_CODE											AS GMCODE
 		  ,OLD_VALUE													AS OLD_VALUE
 		  ,[DIFFERENCE]													AS [DIFFERENCE]
 	FROM [VWSARCHIVE].[RIVM_DECEASED_DAILY_PER_MUNICIPALITY_ARCHIVED_20221231]
 	WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSARCHIVE].[RIVM_DECEASED_DAILY_PER_MUNICIPALITY_ARCHIVED_20221231])
 	AND dbo.CONVERT_UNIX_TO_DATETIME(DATE_OF_REPORT_UNIX) < '2023-01-01' -- added as RIVM reports 9999 after this date