CREATE   VIEW [VWSDEST].[V_DIFFERENCE_SEWER__AVERAGE] 
 AS
   WITH CTE 
   AS (
     SELECT
       [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_MEASUREMENT]) AS [DATE_UNIX]
       ,[DBO].[CONVERT_DATETIME_TO_UNIX](LAG(DATE_MEASUREMENT,1) OVER (PARTITION BY [REGIO_CODE] ORDER BY [DATE_MEASUREMENT])) AS [OLD_DATE_UNIX]
       ,CAST(ROUND([AVERAGE_RNA_FLOW_PER_100000],0) AS INT) AS [NEW_VALUE]
       ,CAST(ROUND(LAG([AVERAGE_RNA_FLOW_PER_100000],1) OVER (PARTITION BY [REGIO_CODE] ORDER BY [DATE_MEASUREMENT]),0) AS INT) AS [OLD_VALUE]
       ,[DBO].[CONVERT_DATETIME_TO_UNIX](DATE_LAST_INSERTED) AS [DATE_OF_INSERTION_UNIX]
       ,ROW_NUMBER() OVER (PARTITION BY [REGIO_CODE] ORDER BY [DATE_MEASUREMENT] DESC) AS [RANK_DATE]
     FROM [VWSDEST].[SEWER_PROLONGATED] WITH(NOLOCK)
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[SEWER_PROLONGATED] WITH(NOLOCK))
       AND UPPER([REGIO_CODE]) = 'NL'
   )
   SELECT
     [DATE_UNIX] AS [NEW_DATE_UNIX],
     [OLD_DATE_UNIX],
     [OLD_VALUE],
     ([NEW_VALUE] - [OLD_VALUE]) AS [DIFFERENCE]
   FROM CTE
   WHERE [RANK_DATE] = 1 -- ONLY THE MOST RECENT RECORD