-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
CREATE    VIEW [VWSDEST].[V_DIFFERENCE_HOSPITAL_ADMISSIONS__MOVING_AVERAGE_HOSPITAL] AS
WITH LAST_DATE_OF_REPORT AS (
	SELECT
		MUNICIPALITY_CODE,
		CAST(MAX(DATE_OF_REPORT) as datetime) AS [LAST_DATE_OF_REPORT]
	FROM VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY
	WHERE DATE_OF_REPORT >=  '2020-03-16 00:00:00.000'
		AND DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY)
	GROUP BY MUNICIPALITY_CODE
)

SELECT DATE_OF_REPORT
	  ,NEW_DATE_OF_REPORT_UNIX AS NEW_DATE_UNIX
	  ,OLD_DATE_OF_REPORT_UNIX AS OLD_DATE_UNIX
	  ,T1.GMCODE
	  ,CASE WHEN OLD_VALUE IS NULL THEN 0 ELSE OLD_VALUE END AS OLD_VALUE
	  ,CASE WHEN [DIFFERENCE] IS NULL THEN 0 ELSE [DIFFERENCE] END AS [DIFFERENCE]
FROM VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_BASE T1
LEFT JOIN LAST_DATE_OF_REPORT T2
	ON T1.[GMCODE] = T2.[MUNICIPALITY_CODE]
WHERE DATE_OF_REPORT = LAST_DATE_OF_REPORT
;