-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
 -- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
 
 CREATE   VIEW [VWSDEST].[V_ECDC_CASES] AS
 WITH NL_CTE AS (
 SELECT 
        'Netherlands' AS [COUNTRY]
       ,'NLD'         AS [COUNTRY_CODE]
       ,[POPULATION]
       ,DBO.CONVERT_DATETIME_TO_UNIX([WEEK_START])   AS [DATE_START_UNIX]
       ,DBO.CONVERT_DATETIME_TO_UNIX([WEEK_END])     AS [DATE_END_UNIX]
       ,[TOT_INFECTED]                               AS [INFECTED]
       ,ROUND([TOT_INFECTED_RATE] ,1)                           AS [INFECTED_TOTAL_AVERAGE]
       ,ROUND([REL_INFECTED]      ,1)                         AS [INFECTED_PER_100K]
       ,ROUND([REL_INFECTED_RATE] ,1)                         AS [INFECTED_PER_100K_AVERAGE]
       ,dbo.CONVERT_DATETIME_TO_UNIX([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
   FROM [VWSDEST].[POSITIVE_TESTED_PEOPLE_WEEKLY]
   WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[POSITIVE_TESTED_PEOPLE_WEEKLY])
 )
 ,
 INTERNATIONAL_CTE AS (
 SELECT 
 
        [COUNTRY]
       ,[COUNTRY_CODE]
       ,[POPULATION]
       ,DBO.CONVERT_DATETIME_TO_UNIX([WEEK_START]) AS [DATE_START_UNIX]
       ,DBO.CONVERT_DATETIME_TO_UNIX([WEEK_END])  AS [DATE_END_UNIX]
       ,[INFECTED_TOTAL] AS [INFECTED]
       ,ROUND([INFECTED_TOTAL_AVERAGE],1)        AS [INFECTED_TOTAL_AVERAGE]
       ,ROUND([INFECTED_PER_100K],1)             AS [INFECTED_PER_100K]
       ,ROUND([INFECTED_PER_100K_AVERAGE],1)     AS [INFECTED_PER_100K_AVERAGE]
       ,dbo.CONVERT_DATETIME_TO_UNIX([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
   FROM [VWSDEST].[ECDC_CASES]
   WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[ECDC_CASES])
   AND COUNTRY_CODE <> 'NLD'
 )
 ,
 --Select all rows
 COMBINED_CTE AS (
         SELECT * FROM NL_CTE
         UNION ALL 
         SELECT * FROM INTERNATIONAL_CTE
 )
 
 SELECT * 
 
 FROM COMBINED_CTE
 --Make sure the last dates of NL and international are aligned
 WHERE DATE_END_UNIX <= (SELECT MAX([DATE_END_UNIX]) FROM NL_CTE)
   AND DATE_END_UNIX <= (SELECT MAX([DATE_END_UNIX]) FROM INTERNATIONAL_CTE)