-- 1) CREATE VIEW(S).....
 CREATE    VIEW [VWSDEST].[V_G_NUMBER_NL] 
 AS
       SELECT [G_NUMBER] AS [G_NUMBER]
             ,[DATE_OF_REPORT_UNIX] AS [DATE_UNIX]
             ,[DBO].[CONVERT_DATETIME_TO_UNIX](DATE_LAST_INSERTED) AS [DATE_OF_INSERTION_UNIX]
       FROM [VWSDEST].[G_NUMBER_NL] WITH(NOLOCK)
       WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[G_NUMBER_NL] WITH(NOLOCK))
             AND [G_NUMBER] IS NOT NULL -- ONLY KEEP DATES FOR WHICH G-NUMBER CAN BE CALCULATED (REQUIRES 14 DAYS OF DATA)