-- -- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 --1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_HOSPITAL_ADMISSION_70_PLUS_OVER_TIME]
 AS
 	SELECT
 			SUM([HOSPITAL_ADMISSION_NOTIFICATION] + [IC_ADMISSION_NOTIFICATION]) AS [ADMISSIONS_AGE_70_PLUS],
 			[dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS_WEEK_START]) AS [DATE_START_UNIX],
 			[dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS_WEEK_END]) AS [DATE_END_UNIX],
 			[dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
 	FROM [VWSDEST].[RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]
 	WHERE [AGE_GROUP_GROUPED] IN ('70-79', '80-89', '90+')
 	AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP])
 	GROUP BY [DATE_OF_STATISTICS_WEEK_START], [DATE_OF_STATISTICS_WEEK_END], [DATE_LAST_INSERTED]