CREATE   VIEW VWSDEST.V_HOSPITAL_ADMISSIONS_BACK_UP AS
SELECT 
    ROW_NUMBER() OVER (ORDER BY DATE_OF_REPORT_UNIX ASC) AS ID,
    DATE_OF_REPORT,
	DATE_OF_REPORT_UNIX,
	TOTAL_COUNTS_PER_DAY,
	MOVING_AVERAGE_HOSPITAL,
	DATE_LAST_INSERTED
FROM VWSDEST.HOSPITAL_ADMISSIONS
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.HOSPITAL_ADMISSIONS);