CREATE   VIEW VWSDEST.V_INFECTIOUS_PEOPLE_BACK_UP AS
SELECT
    ROW_NUMBER() OVER(ORDER BY DATE_OF_REPORT_UNIX ASC) AS ID,
    DATE_OF_REPORT,
	DATE_OF_REPORT_UNIX,
	INFECTIOUS_LOW,
	INFECTIOUS_LOW_NORMALIZED,
	INFECTIOUS_AVG,
	INFECTIOUS_AVG_NORMALIZED,
	INFECTIOUS_HIGH,
	INFECTIOUS_HIGH_NORMALIZED,
	DATE_LAST_INSERTED
FROM VWSDEST.INFECTIOUS_PEOPLE
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.INFECTIOUS_PEOPLE);