
-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
-- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.

CREATE    VIEW [VWSDEST].[V_MANUAL_REPEATING_SHOTS_ADMINISTERED]
AS
	WITH CTE AS (
		SELECT *
		FROM [VWSSTAGE].[MANUAL_INPUT_REPEATING_SHOTS]
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[MANUAL_INPUT_REPEATING_SHOTS])
		AND CATEGORY = 'HERHAALPRIK_ADMINISTERED'
	)
    SELECT
        -- Select columns,
		Top (1)
		(SELECT CAST([VALUE] AS INT) FROM CTE WHERE [KEY] = 'GGD_ADMINISTERED_TOTAL')  AS GGD_ADMINISTERED_TOTAL,
		dbo.[CONVERT_DATETIME_TO_UNIX] (CONVERT([DATETIME], (SELECT [VALUE] FROM CTE WHERE [KEY] = 'DATE_UNIX'), 105)) AS DATE_UNIX,
        dbo.[CONVERT_DATETIME_TO_UNIX] ((SELECT [DATE_LAST_INSERTED] FROM CTE WHERE [KEY] = 'DATE_UNIX')) AS [DATE_OF_INSERTION_UNIX]
    FROM CTE