-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE       VIEW [VWSDEST].[V_MANUAL_BOOSTER_SHOT_PLANNED]
 AS
 	WITH CTE AS (
 		SELECT *
 		FROM [VWSSTAGE].[MANUAL_INPUT_BOOSTER_AND_THIRD_SHOTS]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[MANUAL_INPUT_BOOSTER_AND_THIRD_SHOTS])
 		AND CATEGORY = 'BOOSTER_SHOT_PLANNED'
 	)
     SELECT
         -- SELECT COLUMNS,
         Top (1)
 		(SELECT CAST([VALUE] AS INT) FROM CTE WHERE [KEY] = 'PLANNED_7_DAYS') AS PLANNED_7_DAYS,
 		dbo.[CONVERT_DATETIME_TO_UNIX] (CONVERT([DATETIME], (SELECT [VALUE] FROM CTE WHERE [KEY] = 'DATE_UNIX'), 105)) AS [DATE_UNIX],
         dbo.[CONVERT_DATETIME_TO_UNIX] ((SELECT [DATE_LAST_INSERTED] FROM CTE WHERE [KEY] = 'DATE_UNIX')) AS [DATE_OF_INSERTION_UNIX]
     FROM CTE