-- 1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_NICE_HOSPITAL_CHOROPLETH_GM] AS
 WITH
     CTE
     AS (
         SELECT DISTINCT
             MAX([DATE_OF_STATISTICS]) AS [DATE_OF_STATISTICS]
         FROM [VWSDEST].[NICE_HOSPITAL_GM] WITH(NOLOCK)
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[NICE_HOSPITAL_GM] WITH(NOLOCK))
             AND [HOSPITALIZED_7D_AVG_CUTOFF] IS NOT NULL
     )
     SELECT
         [dbo].[CONVERT_DATETIME_TO_UNIX](T1.[DATE_OF_STATISTICS]) AS [DATE_UNIX],
         [GM_CODE] AS [GMCODE],
         [GM_NAME] AS [MUNICIPALITY_NAME],
         DBO.NO_NEGATIVE_NUMBER_I(HOSPITALIZED) AS [ADMISSIONS_ON_DATE_OF_ADMISSION],
         DBO.NO_NEGATIVE_NUMBER_I(REPORTED) AS [ADMISSIONS_ON_DATE_OF_REPORTING],
         dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS [DATE_OF_INSERTION_UNIX]
     FROM VWSDEST.NICE_HOSPITAL_GM T1 WITH(NOLOCK)
         INNER JOIN CTE T2 ON T2.[DATE_OF_STATISTICS] = T1.[DATE_OF_STATISTICS]
     WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.NICE_HOSPITAL_GM WITH(NOLOCK))
         AND [WEEK_START] <> [WEEK_START_LAG]
         AND TRIM([GM_CODE]) != ''