-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
CREATE   VIEW [VWSDEST].[V_NURSING_HOME_REGIONS] AS 

SELECT 
    DATE_OF_REPORT_UNIX AS DATE_UNIX,
    VRCODE, 
    NEWLY_INFECTED_PEOPLE,
    NEWLY_INFECTED_LOCATIONS,
    INFECTED_LOCATIONS_TOTAL,
    INFECTED_LOCATIONS_PERCENTAGE,
    DECEASED_DAILY,
    DATE_OF_INSERTION_UNIX
FROM (
SELECT
    [DATE_OF_REPORT_UNIX],
    VRCODE,
    DBO.NO_NEGATIVE_NUMBER_I(INFECTED_NURSERY_DAILY) AS NEWLY_INFECTED_PEOPLE,
    DBO.NO_NEGATIVE_NUMBER_I(TOTAL_NEW_REPORTED_LOCATIONS) AS NEWLY_INFECTED_LOCATIONS,
    DBO.NO_NEGATIVE_NUMBER_I(TOTAL_REPORTED_LOCATIONS) AS INFECTED_LOCATIONS_TOTAL,
    DBO.NO_NEGATIVE_NUMBER_F(INFECTED_LOCATIONS_PERCENTAGE) AS INFECTED_LOCATIONS_PERCENTAGE,
    DBO.NO_NEGATIVE_NUMBER_I(DECEASED_NURSERY_DAILY) AS DECEASED_DAILY,
    dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX,
    RANK() OVER (PARTITION BY VRCODE ORDER BY DATE_OF_REPORT_UNIX DESC) RANKING
FROM VWSDEST.NURSING_HOMES_PER_REGION WITH(NOLOCK)
WHERE DATE_OF_REPORT >=  '2020-03-16 00:00:00.000'
AND DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.NURSING_HOMES_PER_REGION WITH(NOLOCK))
AND VRCODE IS NOT NULL
AND VRCODE != ' ') T1
WHERE T1.RANKING =2
;