CREATE   VIEW VWSDEST.V_POSITIVE_TESTED_PEOPLE_BACK_UP AS
SELECT 
    ROW_NUMBER() OVER (ORDER BY DATE_OF_REPORT_UNIX ASC) AS ID,
    DATE_OF_REPORT,
	DATE_OF_REPORT_UNIX,
	INFECTED_DAILY_INCREASE,
	INFECTED_DAILY_TOTAL,
	DATE_LAST_INSERTED
FROM VWSDEST.POSITIVE_TESTED_PEOPLE
WHERE DATE_LAST_INSERTED = (SELECT max(DATE_LAST_INSERTED) 
                            FROM VWSDEST.POSITIVE_TESTED_PEOPLE)