-- -- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 --1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_POSITIVE_TESTED_PEOPLE_70_PLUS_OVER_TIME]
 AS
 	SELECT   
 			SUM([CASES]) AS [INFECTED_AGE_70_PLUS],
 			[DATE_UNIX] AS [DATE_UNIX],
 			[dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
 	FROM [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP_OVER_TIME]
 	WHERE [AGEGROUP] IN ('70-79', '80-89', '90+')
 	AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP_OVER_TIME])
 	GROUP BY [DATE_UNIX], [DATE_LAST_INSERTED]