-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE   VIEW [VWSDEST].[V_RESTRICTIONS_NATIONAL] AS
SELECT
        dbo.CONVERT_DATETIME_TO_UNIX(VALID_FROM) AS VALID_FROM_UNIX
	,   RESTRICTION_ID
	,   TARGET_REGION
	,   ESCALATION_LEVEL
	,   CATEGORY_ID
	,   RESTRICTION_ORDER
    -- ,   dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX
FROM VWSDEST.RESTRICTIONS_NATIONAL
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.RESTRICTIONS_NATIONAL)