CREATE   VIEW VWSDEST.V_REPRODUCTION_NUMBER_BACK_UP AS 
SELECT
    ROW_NUMBER() OVER (ORDER BY DATE_OF_REPORT_UNIX ASC) AS ID,
    DATE_OF_REPORT,
	DATE_OF_REPORT_UNIX,
	REPRODUCTION_INDEX_LOW,
	REPRODUCTION_INDEX_AVG,
	REPRODUCTION_INDEX_HIGH,
	DATE_LAST_INSERTED
FROM VWSDEST.REPRODUCTION_NUMBER
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.REPRODUCTION_NUMBER);