-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
 -- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordination for more information.
 
 CREATE   VIEW [VWSDEST].[V_RIVM_SEWER_MEASUREMENTS_INSTALLATIONS_2023] AS
     WITH
     SEWER_MEASUREMENTS AS (
         SELECT [ID], [DATE_OF_REPORT], [DATE_MEASUREMENT], [RWZI_AWZI_CODE], [DATE_LAST_INSERTED] FROM [VWSDEST].[RIVM_SEWER_MEASUREMENTS_INSTALLATIONS_2023]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_SEWER_MEASUREMENTS_INSTALLATIONS_2023])
     ),
     MUNICIPALITY_RWZI AS (
         SELECT [ID], [REGIO_CODE] AS [GMCODE], [RWZI_CODE] FROM [VWSSTATIC].[MUNICIPALITY_RWZI_COUPLING]
         WHERE [ACTIEF] = 1
         AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[MUNICIPALITY_RWZI_COUPLING])
     ),
     TOTAL_INSTALLATION_COUNT AS (
         SELECT 
         [GMCODE],
         COUNT(*) AS [TOTAL_INSTALLATION_COUNT]
         FROM MUNICIPALITY_RWZI
         GROUP BY [GMCODE]
     ),
     START_END_DATE AS (
         SELECT
         dbo.WEEK_START(dateadd(day, -7, MAX([DATE_OF_REPORT]))) AS [DATE_START], --week before
         dbo.WEEK_END(dateadd(day, -7, MAX([DATE_OF_REPORT]))) AS [DATE_END], --week before
         MAX([DATE_LAST_INSERTED]) AS [DATE_LAST_INSERTED]
         FROM SEWER_MEASUREMENTS
     ),
     SEWER_MEASUREMENTS_WEEK AS (
         SELECT [ID], [DATE_OF_REPORT], [DATE_MEASUREMENT], [RWZI_AWZI_CODE]
         FROM SEWER_MEASUREMENTS
         WHERE [DATE_MEASUREMENT] >= (SELECT [DATE_START] FROM START_END_DATE) -- measurements within week
         AND [DATE_MEASUREMENT] <= (SELECT [DATE_END] FROM START_END_DATE) -- measurements within week
     ),
     SEWER_MEASUREMENTS_WEEK_MUNICIPALITY AS (
         SELECT smw.[ID], smw.[DATE_OF_REPORT], smw.[DATE_MEASUREMENT], smw.[RWZI_AWZI_CODE] AS [RWZI_CODE], mr.[GMCODE]
         FROM SEWER_MEASUREMENTS_WEEK smw
         RIGHT JOIN MUNICIPALITY_RWZI mr
         ON smw.[RWZI_AWZI_CODE] = mr.[RWZI_CODE]
     ),
     GMCODE_SAMPLES AS (
         SELECT
             [GMCODE],
             COUNT([ID]) AS [TOTAL_NUMBER_OF_SAMPLES],
             COUNT(DISTINCT [RWZI_CODE]) AS [SAMPLED_INSTALLATION_COUNT]
         FROM SEWER_MEASUREMENTS_WEEK_MUNICIPALITY
         GROUP BY [GMCODE]
     )
     SELECT
         gs.[GMCODE]																		AS [GMCODE],
         dbo.CONVERT_DATETIME_TO_UNIX((SELECT [DATE_START] FROM START_END_DATE))			AS [DATE_START_UNIX],
         dbo.CONVERT_DATETIME_TO_UNIX((SELECT [DATE_END] FROM START_END_DATE))			AS [DATE_END_UNIX], 
         gs.[TOTAL_NUMBER_OF_SAMPLES]													AS [TOTAL_NUMBER_OF_SAMPLES],
         gs.[SAMPLED_INSTALLATION_COUNT]													AS [SAMPLED_INSTALLATION_COUNT],
         tic.[TOTAL_INSTALLATION_COUNT]													AS [TOTAL_INSTALLATION_COUNT],
         dbo.CONVERT_DATETIME_TO_UNIX((SELECT [DATE_LAST_INSERTED] FROM START_END_DATE))	AS [DATE_OF_INSERTION_UNIX]
     FROM GMCODE_SAMPLES gs
     JOIN TOTAL_INSTALLATION_COUNT tic
     ON gs.[GMCODE] = tic.[GMCODE]