-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 -- 1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL]
 AS
     WITH CTE AS (
         SELECT
             [DATE_OF_STATISTICS],
             [AGE_GROUP],
             [BIRTH_COHORT],
             [VACCINATION_COVERAGE_PER_AGE_GROUP], 
             [DATE_LAST_INSERTED],
             [POPULATION_PER_AGE_GROUP]
         FROM [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL])
             AND [BOOSTER_TYPE] IN ('booster1')
             AND [AGE_GROUP] NOT IN ('12+', '18+')
     )
     SELECT
         [AGE_GROUP] AS [AGE_GROUP_RANGE],
         [BIRTH_COHORT] AS [BIRTHYEAR_RANGE],
         CAST([VACCINATION_COVERAGE_PER_AGE_GROUP] AS NUMERIC(10,1)) AS [RECEIVED_BOOSTER_PERCENTAGE],
         [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS]) AS [DATE_UNIX],
         [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX],
         [POPULATION_PER_AGE_GROUP] AS [AGE_GROUP_TOTAL]
     FROM CTE
     WHERE [DATE_OF_STATISTICS] = (SELECT MAX([DATE_OF_STATISTICS]) FROM CTE);