-- -- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 --1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL]
 AS
     WITH CTE AS (
         SELECT
             [PERC_COVID_TEST_POSITIVE],        
             [N_PARTICIPANTS_TOTAL_UNFILTERED],
             [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_LAST_INSERTED_UNIX],
             [DBO].[CONVERT_DATETIME_TO_UNIX](DATEADD(day, -7,  [DATE_OF_STATISTICS])) AS DATE_START_UNIX,
             [DBO].[CONVERT_DATETIME_TO_UNIX](DATEADD(day, -1,  [DATE_OF_STATISTICS])) AS DATE_END_UNIX
             
         FROM [VWSDEST].[RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL] WITH(NOLOCK)
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL] WITH(NOLOCK))
     )
     SELECT 
         [PERC_COVID_TEST_POSITIVE] AS [INFECTED_PERCENTAGE],
         [N_PARTICIPANTS_TOTAL_UNFILTERED],
         [DATE_LAST_INSERTED_UNIX] AS [DATE_OF_INSERTION_UNIX],
         [DATE_START_UNIX],
         [DATE_END_UNIX]
     FROM CTE