CREATE   VIEW [VWSDEST].[V_RIVM_CIMS_VACCINATED_PER_AGE_GROUP] 
 AS
     WITH CTE_ALL AS (
         SELECT
             [AGE_GROUP],
             [COVERAGE_AGEGROUP],
             [DATE_OF_STATISTICS],
             [AMOUNT_CUMULATIVE]
         FROM [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL] WITH(NOLOCK)
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) 
             FROM [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL] WITH(NOLOCK))
     ),
     CTE AS (
         SELECT
             [AGE_GROUP],
             [COVERAGE_AGEGROUP],
             [DATE_OF_STATISTICS],
             [AMOUNT_CUMULATIVE]
         FROM CTE_ALL
         WHERE [DATE_OF_STATISTICS] = (SELECT MAX([DATE_OF_STATISTICS]) FROM CTE_ALL WITH(NOLOCK))
     ),
     CTE_CAMPAIGN_ALL AS (
         SELECT
             [DATE_OF_REPORT],
             [DATE_OF_STATISTICS_WEEK_START],
             [DATE_OF_STATISTICS_WEEK_END],
             [AGE_GROUP],
             [COVERAGE],
             [RECEIVED]
         FROM [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) 
             FROM [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN] WITH(NOLOCK))
     ),
     CTE_CAMPAIGN AS (
         SELECT
             [DATE_OF_REPORT],
             [DATE_OF_STATISTICS_WEEK_START],
             [DATE_OF_STATISTICS_WEEK_END],
             [AGE_GROUP],
             [COVERAGE],
             [RECEIVED]
         FROM CTE_CAMPAIGN_ALL
         WHERE [DATE_OF_STATISTICS_WEEK_END] = (SELECT MAX([DATE_OF_STATISTICS_WEEK_END]) FROM CTE_CAMPAIGN_ALL WITH(NOLOCK))
     )
     SELECT
         [DBO].[CONVERT_DATETIME_TO_UNIX](CASE WHEN T1.DATE_OF_REPORT > T3.DATE_OF_REPORT THEN T1.DATE_OF_REPORT ELSE T3.DATE_OF_REPORT END) AS [DATE_OF_REPORT_UNIX],
         [DBO].[CONVERT_DATETIME_TO_UNIX](CASE WHEN T1.DATE_OF_STATISTICS_WEEK_END > T3.DATE_OF_STATISTICS_WEEK_END THEN T1.DATE_OF_STATISTICS_WEEK_END ELSE T3.DATE_OF_STATISTICS_WEEK_END END) AS [DATE_UNIX],
         T1.[AGE_GROUP] AS [AGE_GROUP_RANGE],
         [BIRTH_COHORT] AS [BIRTHYEAR_RANGE],
         [AGE_GROUP_POPULATION] AS [AGE_GROUP_TOTAL],
         [AGE_GROUP_POPULATION_PERCENTAGE] AS [AGE_GROUP_PERCENTAGE],
         [VACCINATION_COMPLETED] AS [FULLY_VACCINATED],
         -- T2.[AMOUNT_CUMULATIVE] AS [BOOSTER_SHOT],
         T3.[RECEIVED] AS [AUTUMN_2022_VACCINATED],
         -- CAST(FLOOR(T2.[COVERAGE_AGEGROUP]) AS INT) AS [BOOSTER_SHOT_PERCENTAGE],
         CAST(FLOOR([VACCINATION_COVERAGE_COMPLETED]) AS INT) AS [FULLY_VACCINATED_PERCENTAGE],
         CAST(FLOOR(T3.[COVERAGE]) AS INT) AS [AUTUMN_2022_VACCINATED_PERCENTAGE],
         [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
     FROM [VWSDEST].[CIMS_VACCINATED_AGE_GROUP] T1 WITH(NOLOCK)
         LEFT JOIN CTE T2 ON T1.[AGE_GROUP] = T2.[AGE_GROUP]
         LEFT JOIN CTE_CAMPAIGN T3 ON T1.[AGE_GROUP] = T3.[AGE_GROUP]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM VWSDEST.CIMS_VACCINATED_AGE_GROUP WITH(NOLOCK))
         AND T1.[AGE_GROUP] NOT IN ('12+','18+', '5+');