-- 1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_RIVM_VACCINE_ADMINISTERED_LAST_WEEK_NL] AS
 WITH CTE AS (
     SELECT
         [DATE_OF_REPORT],
         [DATE_FIRST_DAY],
         [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_REPORT]) AS [DATE_UNIX],
         [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_FIRST_DAY]) AS [DATE_START_UNIX],
         [dbo].[CONVERT_DATETIME_TO_UNIX](DATEADD(DAY, 6, [DATE_FIRST_DAY])) AS [DATE_END_UNIX],
         [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX],
         [VALUE_NAME] AS [VACCINE_TYPE_NAME],
         [VALUE] AS [VACCINE_TYPE_VALUE]
     FROM [VWSDEST].[RIVM_VACCINE_ADMINISTERED_LAST_WEEK_NL] WITH(NOLOCK)
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINE_ADMINISTERED_LAST_WEEK_NL] WITH(NOLOCK))
 )
 SELECT
     [DATE_UNIX],
     [DATE_START_UNIX],
     [DATE_END_UNIX],
     [DATE_OF_INSERTION_UNIX],
     [VACCINE_TYPE_NAME],
     [VACCINE_TYPE_VALUE]
 FROM CTE
 WHERE [DATE_START_UNIX] = ( -- last week with data
     SELECT MAX([DATE_START_UNIX]) 
     FROM CTE
     WHERE [DATE_END_UNIX] < ([dbo].[CONVERT_DATETIME_TO_UNIX](DATE_OF_REPORT)) -- make sure the date of report is ahead of DATE_END_UNIX
 )
 AND [VACCINE_TYPE_NAME] <> 'unknown'