-- 1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_RIVM_VACCINATION_SHOT_COVERAGES_NL] AS
     WITH CTE AS (
         SELECT
             [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX],
             [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS]) AS [DATE_UNIX],
             [DATE_OF_REPORT],
             [AGE_GROUP],
             REPLACE(REPLACE([BIRTH_YEAR],'<=', '-'),'<', '-') AS [BIRTH_YEAR],
             CAST([PERCENTAGE_COMPLETED] AS [NUMERIC](10,1)) AS [VACCINATION_COVERAGE_COMPLETED]
         FROM [VWSDEST].[RIVM_VACCINATION_SHOT_COVERAGES_PER_CAMPAIGN_NL] WITH(NOLOCK)
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINATION_SHOT_COVERAGES_PER_CAMPAIGN_NL] WITH(NOLOCK))
     ),
     COVERAGE_12_PLUS AS (
         SELECT
             [DATE_UNIX],
             [DATE_OF_INSERTION_UNIX],
             [DATE_OF_REPORT],
             [BIRTH_YEAR],
             [VACCINATION_COVERAGE_COMPLETED]
         FROM CTE
         WHERE [DATE_UNIX] = (SELECT MAX([DATE_UNIX]) FROM CTE)
             AND [AGE_GROUP] = '12+'
     ),
     COVERAGE_18_PLUS AS (
         SELECT
             [DATE_UNIX],
             [DATE_OF_INSERTION_UNIX],
             [DATE_OF_REPORT],
             [BIRTH_YEAR],
             [VACCINATION_COVERAGE_COMPLETED]
         FROM CTE
         WHERE [DATE_UNIX] = (SELECT MAX([DATE_UNIX]) FROM CTE)
             AND [AGE_GROUP] = '18+'
     )
     SELECT
         T1.[BIRTH_YEAR] AS [AGE_12_PLUS_BIRTHYEAR],
         T1.[VACCINATION_COVERAGE_COMPLETED] AS [AGE_12_PLUS_VACCINATED],
         T2.[BIRTH_YEAR] AS [AGE_18_PLUS_BIRTHYEAR],
         T2.[VACCINATION_COVERAGE_COMPLETED] AS [AGE_18_PLUS_VACCINATED],
         T2.[DATE_UNIX],
         T2.[DATE_OF_INSERTION_UNIX]
     FROM COVERAGE_12_PLUS T1
     INNER JOIN COVERAGE_18_PLUS T2 ON T1.[DATE_OF_REPORT] = T2.[DATE_OF_REPORT]