-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordination for more information.

-- Create view for pulling intensive care admissions
CREATE   VIEW [VWSDEST].[V_RIVM_INTENSIVE_CARE_ADMISSIONS] AS
WITH RANK_TABLE AS (
    SELECT
        [DATE_OF_STATISTICS_UNIX] AS DATE_UNIX
    ,   IC_admission AS ADMISSIONS_ON_DATE_OF_ADMISSION
    ,   IC_ADMISSION_7D_AVG AS ADMISSIONS_ON_DATE_OF_ADMISSION_MOVING_AVERAGE
    ,   CAST(ROUND(IC_ADMISSION_7D_AVG,0) AS INTEGER) AS ADMISSIONS_ON_DATE_OF_ADMISSION_MOVING_AVERAGE_ROUNDED
    ,   IC_admission_notification AS ADMISSIONS_ON_DATE_OF_REPORTING
    ,   dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED)  AS DATE_OF_INSERTION_UNIX
    ,   ROW_NUMBER() OVER (ORDER BY DATE_OF_STATISTICS DESC) AS RANK_DATE
    FROM VWSDEST.RIVM_IC_OPNAME
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.RIVM_IC_OPNAME)
)

SELECT
    DATE_UNIX
    ,ADMISSIONS_ON_DATE_OF_ADMISSION

    --This cutoff logic below is also used for the risk level determination in [dbo].[SP_RISK_LEVEL_NL_HISTORY]
    --Last values will be trimmed due to these being underreported
    ,IIF(RANK_DATE>3,ADMISSIONS_ON_DATE_OF_ADMISSION_MOVING_AVERAGE,NULL) AS ADMISSIONS_ON_DATE_OF_ADMISSION_MOVING_AVERAGE
    ,IIF(RANK_DATE>3,ADMISSIONS_ON_DATE_OF_ADMISSION_MOVING_AVERAGE_ROUNDED,NULL) AS ADMISSIONS_ON_DATE_OF_ADMISSION_MOVING_AVERAGE_ROUNDED
    ,ADMISSIONS_ON_DATE_OF_REPORTING
    ,DATE_OF_INSERTION_UNIX
FROM RANK_TABLE