-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 --1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_VR_ARCHIVED_20220904]
 AS
     WITH CTE AS (
         SELECT
             [REGION_CODE] AS [VRCODE],
             [AGE_GROUP],
             UPPER(DATENAME(dw, [DATE_OF_STATISTICS])) AS [DAY_OF_WEEK],
             [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS]) AS [DATE_UNIX],            
             [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX],
             [PERCENTAGE],
             [PERCENTAGE_LABEL]
         FROM [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_VR_ARCHIVED_20220904] WITH(NOLOCK)
         WHERE [REGION_CODE] LIKE 'VR%'
             AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM  [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_VR_ARCHIVED_20220904] WITH(NOLOCK))
             AND [AGE_GROUP] IN  ('18+', '12+')
             AND UPPER([VACCINATION_SERIE]) IN ('BOOSTER1_COVERAGE', 'PRIMARY_SERIES_PLUS_1', '')
 
     )
     SELECT 
         T2.[VRCODE],
         [AGE_GROUP],
         [PERCENTAGE], 
         [PERCENTAGE_LABEL],
         [DATE_OF_INSERTION_UNIX],
         T2.[DATE_UNIX]
     FROM CTE T1
     INNER JOIN (
         SELECT
             MAX([DATE_UNIX]) AS [DATE_UNIX],
             [VRCODE]
         FROM CTE
         -- WHERE [DAY_OF_WEEK] = 'SUNDAY'
         GROUP BY [VRCODE]
     ) AS T2 ON T1.[VRCODE] = T2.[VRCODE] AND T1.[DATE_UNIX] = T2.[DATE_UNIX]