-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordination for more information.

CREATE   VIEW  VWSDEST.V_RIVM_VACCINATIONSTATUS_IC_ADMISSIONS AS
    SELECT
       dbo.CONVERT_DATETIME_TO_UNIX (DATE_START) AS [DATE_START_UNIX]
      ,dbo.CONVERT_DATETIME_TO_UNIX (DATE_END) AS [DATE_END_UNIX]
      ,[GROUP_SIZE] as [TOTAL_AMOUNT_OF_PEOPLE]
      ,[FULLY_VACCINATED]
      ,[FULLY_VACCINATED_PERCENTAGE]
      ,[PARTIALLY_NOT_VACCINATED] AS [HAS_ONE_SHOT_OR_NOT_VACCINATED]
      ,[PARTIALLY_NOT_VACCINATED_PERCENTAGE] AS [HAS_ONE_SHOT_OR_NOT_VACCINATED_PERCENTAGE]
      ,dbo.CONVERT_DATETIME_TO_UNIX (DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX
    FROM  [VWSINTER].[RIVM_VACCINATIONSTATUS_IC_ADMISSIONS]
    WHERE 
        [DATE_LAST_INSERTED] =
            (SELECT MAX(DATE_LAST_INSERTED) FROM  [VWSINTER].[RIVM_VACCINATIONSTATUS_IC_ADMISSIONS])