-- 1) CREATE VIEW(S)....
 CREATE   VIEW [VWSDEST].[V_RIVM_VACCINATION_SERIES_NL] AS
 
     WITH SERIES_CTE AS (
         SELECT
             [DATE_OF_STATISTICS] AS [DATE_OF_STATISTICS],
             [VACCINE_SERIE_EN] AS [VACCINE_CAMPAIGN_NAME_EN_KEY],
             [TOTAL_VACCINATED] AS [VACCINE_ADMINISTERED]
         FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL])
         -- only data until the last ISO week
         AND DATE_OF_STATISTICS <= ([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL])))
     ),
     SERIES_CTE_AFTER_START_DATE AS (
         SELECT *
         FROM SERIES_CTE
         WHERE DATE_OF_STATISTICS >= (
             SELECT SERIES_START_DATE
             FROM [VWSSTATIC].[RIVM_VACCINATION_SERIES_MASTER_DATA]
             WHERE [DATE_LAST_INSERTED] = 
             (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RIVM_VACCINATION_SERIES_MASTER_DATA])
             AND LOWER(VACCINATION_KEY) = '202209_campaign'
         )
     ),
     SERIES_CTE_WEEK AS (
         SELECT *
         FROM SERIES_CTE
         WHERE DATE_OF_STATISTICS >= (dateadd(day, -6, [dbo].[WEEK_START_ISO](([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL]))))))
         AND DATE_OF_STATISTICS <= ([dbo].[WEEK_START_ISO](([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL])))))
     ),
     SERIES_CTE_TIMEFRAME AS (
         SELECT *
         FROM SERIES_CTE
         WHERE DATE_OF_STATISTICS >= (dateadd(day, -27, [dbo].[WEEK_START_ISO](([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL]))))))
         AND DATE_OF_STATISTICS <= ([dbo].[WEEK_START_ISO](([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL])))))
     ),
     SERIES_CTE_PRIMARY_TOTAL AS (
         SELECT SUM([VACCINE_ADMINISTERED]) AS [VACCINE_ADMINISTERED_TOTAL]
         FROM SERIES_CTE
         WHERE [VACCINE_CAMPAIGN_NAME_EN_KEY] = 'primary_completed'
     ),
     SERIES_CTE_PRIMARY_LAST_WEEK AS (
         SELECT COALESCE(SUM([VACCINE_ADMINISTERED]),0) AS [VACCINE_ADMINISTERED_LAST_WEEK]
         FROM SERIES_CTE_WEEK
         WHERE [VACCINE_CAMPAIGN_NAME_EN_KEY] = 'primary_completed'
     ),
     SERIES_CTE_PRIMARY_LAST_TIMEFRAME AS (
         SELECT COALESCE(SUM([VACCINE_ADMINISTERED]),0) AS [VACCINE_ADMINISTERED_LAST_TIMEFRAME]
         FROM SERIES_CTE_TIMEFRAME
         WHERE [VACCINE_CAMPAIGN_NAME_EN_KEY] = 'primary_completed'
     ),
     -- only count the ones after the startdate
     SERIES_CTE_CAMPAIGN_202209_TOTAL AS (
         SELECT SUM([VACCINE_ADMINISTERED]) AS [VACCINE_ADMINISTERED_TOTAL]
         FROM SERIES_CTE_AFTER_START_DATE
         WHERE [VACCINE_CAMPAIGN_NAME_EN_KEY] NOT IN ('primary_completed', 'primary_started')
     ),
     SERIES_CTE_CAMPAIGN_202209_LAST_WEEK AS (
         SELECT COALESCE(SUM([VACCINE_ADMINISTERED]),0) AS [VACCINE_ADMINISTERED_LAST_WEEK]
         FROM SERIES_CTE_WEEK
         WHERE [VACCINE_CAMPAIGN_NAME_EN_KEY] NOT IN ('primary_completed', 'primary_started')
     ),
     SERIES_CTE_CAMPAIGN_202209_LAST_TIMEFRAME AS (
         SELECT COALESCE(SUM([VACCINE_ADMINISTERED]),0) AS [VACCINE_ADMINISTERED_LAST_TIMEFRAME]
         FROM SERIES_CTE_TIMEFRAME
         WHERE [VACCINE_CAMPAIGN_NAME_EN_KEY] NOT IN ('primary_completed', 'primary_started')
     ),
     -- Construct Primary
     PRIMARY_SERIES AS (
         SELECT
             ([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL]))) AS [DATE_OF_STATISTICS],
             A.[VACCINE_ADMINISTERED_TOTAL] AS [VACCINE_ADMINISTERED_TOTAL],
             B.[VACCINE_ADMINISTERED_LAST_WEEK] AS [VACCINE_ADMINISTERED_LAST_WEEK],
             C.[VACCINE_ADMINISTERED_LAST_TIMEFRAME] AS [VACCINE_ADMINISTERED_LAST_TIMEFRAME],
             [dbo].[CONVERT_DATETIME_TO_UNIX]([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL]))) AS [DATE_UNIX],
             [dbo].[CONVERT_DATETIME_TO_UNIX](dateadd(day, -27, [dbo].[WEEK_START_ISO](([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL])))))) AS [DATE_START_UNIX],
             [dbo].[CONVERT_DATETIME_TO_UNIX]([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL]))) AS [DATE_END_UNIX],
             [dbo].[CONVERT_DATETIME_TO_UNIX]((SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL])) AS [DATE_OF_INSERTION_UNIX],
             r.[VACCINE_CAMPAIGN_NAME_EN],
             r.[VACCINE_CAMPAIGN_NAME_NL],
             r.[VACCINE_CAMPAIGN_ORDER]
         FROM SERIES_CTE_PRIMARY_TOTAL A
         CROSS JOIN SERIES_CTE_PRIMARY_LAST_WEEK B
         CROSS JOIN SERIES_CTE_PRIMARY_LAST_TIMEFRAME C
         -- Get Vaccine_Series name and Order
         CROSS JOIN (
              SELECT
                  LABEL_EN AS [VACCINE_CAMPAIGN_NAME_EN],
                  LABEL_NL AS [VACCINE_CAMPAIGN_NAME_NL],
                  SORT_ORDER AS [VACCINE_CAMPAIGN_ORDER]
              FROM [VWSSTATIC].[RIVM_VACCINATION_SERIES_MASTER_DATA] 
              WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RIVM_VACCINATION_SERIES_MASTER_DATA]) 
                  AND LOWER(VACCINATION_KEY) = 'primary_completed' 
          ) r
     ),
     -- Construct CAMPAIGN_202209
     CAMPAIGN_202209_SERIES AS (
         SELECT
             ([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL]))) AS [DATE_OF_STATISTICS],
             A.[VACCINE_ADMINISTERED_TOTAL] AS [VACCINE_ADMINISTERED_TOTAL],
             B.[VACCINE_ADMINISTERED_LAST_WEEK] AS [VACCINE_ADMINISTERED_LAST_WEEK],
             C.[VACCINE_ADMINISTERED_LAST_TIMEFRAME] AS [VACCINE_ADMINISTERED_LAST_TIMEFRAME],
             [dbo].[CONVERT_DATETIME_TO_UNIX]([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL]))) AS [DATE_UNIX],
             [dbo].[CONVERT_DATETIME_TO_UNIX](dateadd(day, -27, [dbo].[WEEK_START_ISO](([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL])))))) AS [DATE_START_UNIX],
             [dbo].[CONVERT_DATETIME_TO_UNIX]([dbo].[WEEK_START_ISO]((SELECT MAX([DATE_OF_STATISTICS]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL]))) AS [DATE_END_UNIX],
             [dbo].[CONVERT_DATETIME_TO_UNIX]((SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINATION_SERIES_NL])) AS [DATE_OF_INSERTION_UNIX],
             r.[VACCINE_CAMPAIGN_NAME_EN],
             r.[VACCINE_CAMPAIGN_NAME_NL],
             r.[VACCINE_CAMPAIGN_ORDER]
         FROM SERIES_CTE_CAMPAIGN_202209_TOTAL A
         CROSS JOIN SERIES_CTE_CAMPAIGN_202209_LAST_WEEK B
         CROSS JOIN SERIES_CTE_CAMPAIGN_202209_LAST_TIMEFRAME C
         -- Get Vaccine_Series name and Order
         CROSS JOIN (
              SELECT
                  LABEL_EN AS [VACCINE_CAMPAIGN_NAME_EN],
                  LABEL_NL AS [VACCINE_CAMPAIGN_NAME_NL],
                  SORT_ORDER AS [VACCINE_CAMPAIGN_ORDER]
              FROM [VWSSTATIC].[RIVM_VACCINATION_SERIES_MASTER_DATA] 
              WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RIVM_VACCINATION_SERIES_MASTER_DATA]) 
                  AND LOWER(VACCINATION_KEY) = '202209_campaign'
          ) r
     )
     SELECT DATE_OF_STATISTICS,
             VACCINE_CAMPAIGN_ORDER,
             VACCINE_CAMPAIGN_NAME_NL,
             VACCINE_CAMPAIGN_NAME_EN,
             VACCINE_ADMINISTERED_TOTAL,
             VACCINE_ADMINISTERED_LAST_WEEK,
             VACCINE_ADMINISTERED_LAST_TIMEFRAME,
             DATE_UNIX,
             DATE_END_UNIX,
             DATE_START_UNIX,
             DATE_OF_INSERTION_UNIX
     FROM PRIMARY_SERIES
 
         UNION
     
     SELECT  DATE_OF_STATISTICS,
             VACCINE_CAMPAIGN_ORDER,
             VACCINE_CAMPAIGN_NAME_NL,
             VACCINE_CAMPAIGN_NAME_EN,
             VACCINE_ADMINISTERED_TOTAL,
             VACCINE_ADMINISTERED_LAST_WEEK,
             VACCINE_ADMINISTERED_LAST_TIMEFRAME,
             DATE_UNIX,
             DATE_END_UNIX,
             DATE_START_UNIX,
             DATE_OF_INSERTION_UNIX
     FROM CAMPAIGN_202209_SERIES