CREATE   VIEW [VWSDEST].[V_RIVM_CIMS_VACCINATED_PER_AGE_GROUP_ARCHIVE] 
 AS
     SELECT
         [DBO].[CONVERT_DATETIME_TO_UNIX](DATE_OF_REPORT) AS [DATE_OF_REPORT_UNIX],
         [DBO].[CONVERT_DATETIME_TO_UNIX](DATE_OF_STATISTICS_WEEK_END) AS [DATE_UNIX],
         T1.[AGE_GROUP] AS [AGE_GROUP_RANGE],
         [BIRTH_COHORT] AS [BIRTHYEAR_RANGE],
         [AGE_GROUP_POPULATION] AS [AGE_GROUP_TOTAL],
         [AGE_GROUP_POPULATION_PERCENTAGE] AS [AGE_GROUP_PERCENTAGE],
         [VACCINATION_COMPLETED] AS [FULLY_VACCINATED],
         [VACCINATION_ALL] AS [HAS_ONE_SHOT],
         CAST(FLOOR([VACCINATION_COVERAGE_ALL]) AS INT) AS [HAS_ONE_SHOT_PERCENTAGE],
         CAST(FLOOR([VACCINATION_COVERAGE_COMPLETED]) AS INT) AS [FULLY_VACCINATED_PERCENTAGE],
         [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
     FROM [VWSARCHIVE].[CIMS_VACCINATED_AGE_GROUP] T1 WITH(NOLOCK)
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM VWSARCHIVE.CIMS_VACCINATED_AGE_GROUP WITH(NOLOCK))
         AND T1.[AGE_GROUP] NOT IN ('12+','18+', '5+');