-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 -- 1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL]
 AS
     WITH CTE AS (
         SELECT
             [CUMSUM_VACCINATIONS],
             [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS]) AS [DATE_UNIX],
             [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
         FROM [VWSDEST].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL])
     )
     SELECT
         [CUMSUM_VACCINATIONS] AS [ADMINISTERED_TOTAL],
         [DATE_OF_INSERTION_UNIX] ,
         [DATE_UNIX]
     FROM CTE
     WHERE [DATE_UNIX] = (SELECT MAX([DATE_UNIX]) FROM CTE)