-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 -- 1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_RIVM_BOOSTER_SHOT_COVERAGES_NL_ARCHIVED_20220904] AS
     WITH CTE AS (
         SELECT
             [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX],
             [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS]) AS [DATE_UNIX],            
             -- UPPER(DATENAME(dw, [DATE_OF_STATISTICS])) AS [DAY_OF_WEEK],
             [AGE_GROUP],
             CAST([PERCENTAGE] AS [NUMERIC](10,1)) AS [PERCENTAGE]
         FROM [VWSARCHIVE].[RIVM_BOOSTER_SHOT_COVERAGES_NL_ARCHIVED_20220904] WITH(NOLOCK)
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSARCHIVE].[RIVM_BOOSTER_SHOT_COVERAGES_NL_ARCHIVED_20220904] WITH(NOLOCK))
             AND [AGE_GROUP] IN ('18+', '12+')
     )
     SELECT
         [AGE_GROUP],
         [PERCENTAGE],
         [DATE_OF_INSERTION_UNIX],
         [DATE_UNIX]
     FROM CTE
     WHERE [DATE_UNIX] = (
         SELECT 
             MAX([DATE_UNIX]) 
         FROM CTE 
         -- WHERE [DAY_OF_WEEK] = 'SUNDAY'
     )