-- 1) CREATE VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_RIVM_VACCINATION_SHOTS_PLANNED_NL] AS
 WITH CTE AS (
     SELECT TOP(1)
         [DOSES],
         [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS_END]) AS [DATE_START_UNIX],
         [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS_START]) AS [DATE_END_UNIX],
         [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
     FROM 
         [VWSDEST].[RIVM_VACCINATION_SHOTS_PLANNED_NL] WITH(NOLOCK)
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINATION_SHOTS_PLANNED_NL] WITH(NOLOCK))
 )
 SELECT
     [DOSES],
     [DATE_END_UNIX],
     [DATE_START_UNIX],
     [DATE_START_UNIX] AS [DATE_UNIX],
     [DATE_OF_INSERTION_UNIX]
 FROM CTE