-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
 -- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordination for more information.
 
 CREATE   VIEW [VWSDEST].[V_SEWER_MEASUREMENTS_PER_RWZI_2023] As
     WITH
     SEWER_MEASUREMENTS AS (
         SELECT [ID], [DATE_OF_REPORT], [DATE_MEASUREMENT], [RWZI_AWZI_CODE], [RNA_FLOW_PER_100000], [DATE_LAST_INSERTED] FROM [VWSDEST].[RIVM_SEWER_MEASUREMENTS_INSTALLATIONS_2023]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_SEWER_MEASUREMENTS_INSTALLATIONS_2023])
         AND [DATE_MEASUREMENT] >= CAST('2020-09-07 00:00:00.000' AS DATETIME)
     ),
     MUNICIPALITY_RWZI AS (
         SELECT [ID], [REGIO_CODE] AS [GMCODE], [RWZI_CODE], [RWZI_NAAM] FROM [VWSSTATIC].[MUNICIPALITY_RWZI_COUPLING]
         WHERE [ACTIEF] = 1
         AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[MUNICIPALITY_RWZI_COUPLING])
     ),
 	SEWER_MEASUREMENTS_MUNICIPALITY AS (
         SELECT sm.[ID], sm.[DATE_OF_REPORT], sm.[DATE_MEASUREMENT], sm.[DATE_LAST_INSERTED], sm.[RNA_FLOW_PER_100000], mr.[RWZI_CODE], mr.[RWZI_NAAM], mr.[GMCODE]
         FROM SEWER_MEASUREMENTS sm
         JOIN MUNICIPALITY_RWZI mr
         ON sm.[RWZI_AWZI_CODE] = mr.[RWZI_CODE]
     )
 	SELECT 
 	    dbo.CONVERT_DATETIME_TO_UNIX([DATE_MEASUREMENT]) AS [DATE_UNIX],
 		CAST(ROUND(CAST([RNA_FLOW_PER_100000] / 1.0E+11 AS DECIMAL(16,2)),0) AS INT) AS [RNA_NORMALIZED],
 		dbo.CONVERT_DATETIME_TO_UNIX([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX],
         [RWZI_CODE] AS [RWZI_AWZI_CODE],
         [RWZI_NAAM] AS [RWZI_AWZI_NAME],
         [GMCODE] AS [GMCODE]
 	FROM SEWER_MEASUREMENTS_MUNICIPALITY