CREATE   VIEW [VWSDEST].[V_SEWER_MEASUREMENTS_REGIONS] 
 AS
   SELECT
     [VRCODE],
     [DATE_UNIX],
     [AVERAGE],
     [DATA_IS_OUTDATED],
     [DATE_OF_INSERTION_UNIX]
   FROM (
       SELECT
         [VRCODE],
         [DATE_UNIX],
         [AVERAGE],
         [DATA_IS_OUTDATED],
         [DATE_OF_INSERTION_UNIX],
         RANK() OVER (PARTITION BY [VRCODE] ORDER BY [DATE_UNIX] DESC) [RANKING]
       FROM [VWSDEST].[V_SEWER_MEASUREMENTS_PER_REGION]
   ) T1
   WHERE T1.[RANKING] = 1