
 CREATE   VIEW VWSDEST.V_VACCINATIONS_PARTLY_FULLY
 AS
     WITH BASE_CTE AS (
         SELECT
             [PARTIALLY_VACCINATED],
             [FULLY_VACCINATED],
             [PARTIALLY_OR_FULLY_VACCINATED],
             [BOOSTER1] AS [BOOSTER_VACCINATED],
             [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_REPORT]) AS [DATE_UNIX],
             [DBO].[CONVERT_DATETIME_TO_UNIX]([WEEK_START]) AS [DATE_START_UNIX],
             [DBO].[CONVERT_DATETIME_TO_UNIX]([WEEK_END]) AS [DATE_END_UNIX],
             [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
         FROM [VWSDEST].[RIVM_VACCINATIONS_PARTLY_FULLY] WITH(NOLOCK)
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[RIVM_VACCINATIONS_PARTLY_FULLY] WITH(NOLOCK))
             AND [WEEK_START] >= '2021-01-04 00:00:00.000' -- VACCINATION STARTED IN THE WEEK OF 4-1-2021
     )
 
     -- FILTER OUT:
     -- 1. ANY INCOMPLETE WEEKS / FUTURE WEEKS
     SELECT
         [PARTIALLY_VACCINATED],
         [FULLY_VACCINATED],
         [PARTIALLY_OR_FULLY_VACCINATED],
         [BOOSTER_VACCINATED],
         [DATE_UNIX],
         [DATE_START_UNIX],
         [DATE_END_UNIX],
         [DATE_OF_INSERTION_UNIX]
     FROM BASE_CTE
     WHERE [DATE_OF_INSERTION_UNIX] > [DATE_END_UNIX];