-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 -- 1) CREATE VWS_BEHAVIOR_ANNOTATIONS_NL VIEW(S).....
 CREATE   VIEW [VWSDEST].[V_VWS_BEHAVIOR_ANNOTATIONS_NL]
 AS
     SELECT
         [INDICATOR] AS [BEHAVIOR_INDICATOR],
         [MESSAGE_TITLE_NL],
         [MESSAGE_TITLE_EN],
         [MESSAGE_TEXT_NL] AS [MESSAGE_DESC_NL],
         [MESSAGE_TEXT_EN] AS [MESSAGE_DESC_EN],
         [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_FIRST_MEASUREMENT]) AS [DATE_START_UNIX],
         [dbo].[CONVERT_DATETIME_TO_UNIX](DATEADD(DAY, [MEASUREMENT_DURATION_IN_DAYS] - 1, [DATE_OF_FIRST_MEASUREMENT])) AS [DATE_END_UNIX],
         [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]   
     FROM 
         [VWSDEST].[VWS_BEHAVIOR_ANNOTATIONS_NL] WITH(NOLOCK)
     WHERE 
         [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[VWS_BEHAVIOR_ANNOTATIONS_NL] WITH(NOLOCK));