-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 -- 1) CREATE VIEW(S).....
 CREATE   VIEW VWSDEST.V_VWS_VACCINE_ADMINISTERED_PLANNED_TEMP
 AS
 	SELECT 
 		DOSES,
 		DATE_START_UNIX,
 		DATE_END_UNIX,
 		dbo.CONVERT_DATETIME_TO_UNIX([DATE_LAST_INSERTED])			AS [DATE_OF_INSERTION_UNIX]
 	FROM VWSDEST.VWS_VACCINE_PLANNED
 	WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.VWS_VACCINE_PLANNED)