CREATE   VIEW VWSDEST.V_VWS_VACCINE_DELIVERIES AS
 SELECT 
      [VALUE] AS TOTAL
     ,DATE_START_UNIX
     ,DATE_OF_REPORT_UNIX
     ,DATE_END_UNIX
     ,dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX
 FROM VWSDEST.VWS_VACCINE_DELIVERIES 
   WHERE [DATE_LAST_INSERTED] = (SELECT MAX ([DATE_LAST_INSERTED]) FROM [VWSDEST].[VWS_VACCINE_DELIVERIES])
   AND REPORT_STATUS = 'reported'