CREATE TABLE [VWSSTATIC].[CBS_INHABITANTS_PER_AGEGROUP] (
    [ID]                    INT          DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_CBS_INHABITANTS_PER_AGEGROUP]) NOT NULL,
    [GESLACHT]              VARCHAR (10) NULL,
    [LEEFTIJD]              VARCHAR (10) NULL,
    [BURGERLIJKESTAAT]      VARCHAR (10) NULL,
    [REGIOS]                VARCHAR (10) NULL,
    [PERIODEN]              VARCHAR (10) NULL,
    [BEVOLKINGOP1JANUARI_1] BIGINT       NULL,
    [GEMIDDELDEBEVOLKING_2] FLOAT (53)   NULL,
    [DATE_LAST_INSERTED]    DATETIME     DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

