CREATE TABLE [VWSSTATIC].[CBS_AGEGROUP_DISTRIBUTION] (
    [ID]                     INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_CBS_AGEGROUP_DISTRIBUTION]) NOT NULL,
    [AGEGROUP]               VARCHAR (10)    NULL,
    [INHABITANTS]            VARCHAR (100)   NULL,
    [INHABITANTS_PERCENTAGE] DECIMAL (10, 3) NULL,
    [DATE_LAST_INSERTED]     DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

