CREATE TABLE [VWSSTATIC].[CBS_AGEGROUP_MAPPING] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_CBS_AGEGROUP_MAPPING]) NOT NULL,
    [KEY]                VARCHAR (10)  NULL,
    [TITLE]              VARCHAR (25)  NULL,
    [DESCRIPTION]        VARCHAR (100) NULL,
    [CATEGORYGROUPID]    VARCHAR (10)  NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

