CREATE TABLE [VWSSTATIC].[CBS_POPULATION_AGEGROUP_10] (
    [ID]                 INT          DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_CBS_POPULATION_AGEGROUP_10]) NOT NULL,
    [AGEGROUP]           VARCHAR (10) NULL,
    [DATUM_PEILING]      DATE         NULL,
    [POPULATIE]          INT          NULL,
    [DATE_LAST_INSERTED] DATETIME     DEFAULT (getdate()) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE CLUSTERED INDEX [CI_DLI_VWSSTATIC_CBS_POPULATION_AGEGROUP_10]
    ON [VWSSTATIC].[CBS_POPULATION_AGEGROUP_10]([DATE_LAST_INSERTED] ASC);

