CREATE TABLE [VWSSTATIC].[CBS_POPULATION_GM] (
    [ID]                 INT          DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_CBS_POPULATION_GM]) NOT NULL,
    [GM_CODE]            VARCHAR (10) NULL,
    [DATUM_PEILING]      DATE         NULL,
    [POPULATIE]          INT          NULL,
    [DATE_LAST_INSERTED] DATETIME     DEFAULT (getdate()) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE CLUSTERED INDEX [CI_DLI_VWSSTATIC_CBS_POPULATION_GM]
    ON [VWSSTATIC].[CBS_POPULATION_GM]([DATE_LAST_INSERTED] ASC);

