CREATE TABLE [VWSSTATIC].[CBS_POPULATION_BASE] (
    [ID]                    INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_CBS_POPULATION_BASE]) NOT NULL,
    [GEMEENTE_CODE]         VARCHAR (10)  NULL,
    [GEMEENTE]              VARCHAR (100) NULL,
    [LEEFTIJD]              INT           NULL,
    [GESLACHT]              VARCHAR (10)  NULL,
    [DATUM_PEILING]         DATE          NULL,
    [POPULATIE]             INT           NULL,
    [VEILIGHEIDSREGIO_CODE] VARCHAR (10)  NULL,
    [VEILIGHEIDSREGIO_NAAM] VARCHAR (100) NULL,
    [PROVINCIE_CODE]        VARCHAR (10)  NULL,
    [PROVINCIE_NAAM]        VARCHAR (100) NULL,
    [GGD_CODE]              VARCHAR (10)  NULL,
    [GGD_NAAM]              VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]    DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_VWSSTATIC_CBS_POPULATION_BASE]
    ON [VWSSTATIC].[CBS_POPULATION_BASE]([DATE_LAST_INSERTED] ASC);


GO
CREATE CLUSTERED INDEX [CI_DLI_VWSSTATIC_CBS_POPULATION_BASE]
    ON [VWSSTATIC].[CBS_POPULATION_BASE]([DATE_LAST_INSERTED] ASC);

