CREATE TABLE [VWSSTATIC].[COHORT_TO_NAMES_MAPPING] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [COHORT_ORIGINAL] NVARCHAR (50) NOT NULL,
    [COHORT_ADJUSTED] NVARCHAR (50) NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [NCIX_COHORT_ORIGINAL_AND_ADJUSTED]
    ON [VWSSTATIC].[COHORT_TO_NAMES_MAPPING]([COHORT_ORIGINAL] ASC, [COHORT_ADJUSTED] ASC);

