CREATE TABLE [VWSSTATIC].[COHORT_TO_AGE_GROUPS_MAPPING] (
    [ID]        INT           IDENTITY (1, 1) NOT NULL,
    [COHORT]    VARCHAR (256) NOT NULL,
    [AGE_GROUP] VARCHAR (256) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_AGE_GROUP_AND_COHORT]
    ON [VWSSTATIC].[COHORT_TO_AGE_GROUPS_MAPPING]([COHORT] ASC, [AGE_GROUP] ASC);

