CREATE TABLE [VWSSTATIC].[COUNTRY_CODES] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_COUNTRY_CODES]) NOT NULL,
    [COUNTRY]            VARCHAR (255) NULL,
    [COUNTRY_CODE_ISO2]  CHAR (2)      NULL,
    [COUNTRY_CODE_ISO3]  CHAR (3)      NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

