CREATE TABLE [VWSSTATIC].[ELDERLY_AT_HOME] (
    [ID]                         INT           IDENTITY (1, 1) NOT NULL,
    [DATE_OF_REPORT]             VARCHAR (100) NULL,
    [DATE_OF_STATISTIC_REPORTED] VARCHAR (100) NULL,
    [SECURITY_REGION_CODE]       VARCHAR (100) NULL,
    [SECURITY_REGION]            VARCHAR (100) NULL,
    [TOTAL_CASES_REPORTED]       VARCHAR (100) NULL,
    [TOTAL_DECEASED_REPORTED]    VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]         DATETIME      DEFAULT (getdate()) NULL
);

