CREATE TABLE [VWSSTATIC].[ESCALATIONLEVEL_ESCALATIONTEXT] (
    [ESCALATION_LEVEL]   INT          NOT NULL,
    [ESCALATION_TEXT]    VARCHAR (50) NOT NULL,
    [DATE_LAST_INSERTED] DATETIME     DEFAULT (getdate()) NULL
);

