CREATE TABLE [VWSSTATIC].[GGD_TESTED_PEOPLE] (
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    [VERSION]              VARCHAR (100) NULL,
    [DATE_OF_REPORT]       VARCHAR (100) NULL,
    [DATE_OF_STATISTICS]   VARCHAR (100) NULL,
    [SECURITY_REGION_CODE] VARCHAR (100) NULL,
    [SECURITY_REGION_NAME] VARCHAR (100) NULL,
    [TESTED_WITH_RESULT]   VARCHAR (100) NULL,
    [TESTED_POSITIVE]      VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]   DATETIME      DEFAULT (getdate()) NULL
);

