CREATE TABLE [VWSSTATIC].[HOLIDAYS_NL] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [DATETIME]    DATETIME2 (7)  NOT NULL,
    [NAME]        NVARCHAR (200) NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX) NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DT_HOLIDAYS_NL]
    ON [VWSSTATIC].[HOLIDAYS_NL]([DATETIME] ASC);

