CREATE TABLE [VWSSTATIC].[INACTIVE_SEWER_INSTALLATION_MAPPING] (
    [ID]        INT           IDENTITY (1, 1) NOT NULL,
    [RWZI_CODE] INT           NOT NULL,
    [RWZI_NAME] VARCHAR (256) NULL,
    [ACTIVE]    BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_RWZI_CODE_AND_NAME]
    ON [VWSSTATIC].[INACTIVE_SEWER_INSTALLATION_MAPPING]([RWZI_CODE] ASC, [RWZI_NAME] ASC);

