CREATE TABLE [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_INHABITANTS_PER_SAFETY_REGION]) NOT NULL,
    [VGRNR]              VARCHAR (100) NULL,
    [VGRNAAM]            VARCHAR (100) NULL,
    [INHABITANTS]        INT           NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_INHABITANTS_PER_SAFETY_REGION]
    ON [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR] ASC);

