CREATE TABLE [VWSSTATIC].[INHABITANTS_PER_MUNICIPALITY] (
    [REGIO]              VARCHAR (50) NOT NULL,
    [GMCODE]             VARCHAR (50) NOT NULL,
    [VRCODE]             VARCHAR (50) NOT NULL,
    [VRNAME]             VARCHAR (50) NOT NULL,
    [INHABITANTS]        INT          NOT NULL,
    [DATE_LAST_INSERTED] DATETIME     DEFAULT (getdate()) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_INHABITANTS_PER_MUNICIPALITY]
    ON [VWSSTATIC].[INHABITANTS_PER_MUNICIPALITY]([GMCODE] ASC);

