CREATE TABLE [VWSSTATIC].[RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP] (
    [ID]                              INT           IDENTITY (1, 1) NOT NULL,
    [VERSION]                         VARCHAR (100) NULL,
    [DATE_OF_REPORT]                  VARCHAR (100) NULL,
    [DATE_OF_STATISTICS_WEEK_START]   VARCHAR (100) NULL,
    [AGE_GROUP]                       VARCHAR (100) NULL,
    [HOSPITAL_ADMISSION_NOTIFICATION] VARCHAR (100) NULL,
    [HOSPITAL_ADMISSION]              VARCHAR (100) NULL,
    [IC_ADMISSION_NOTIFICATION]       VARCHAR (100) NULL,
    [IC_ADMISSION]                    VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]              DATETIME      DEFAULT (getdate()) NULL
);

