CREATE TABLE [VWSSTATIC].[RWZI_INHIBITANTS_2021] (
    [ID]                 INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_RWZI_INHIBITANTS]) NOT NULL,
    [CODE_RWZI]          VARCHAR (100)   NULL,
    [NAME_RWZI]          VARCHAR (100)   NULL,
    [INHABITANTS]        INT             NULL,
    [GEBIEDSCODE]        VARCHAR (100)   NULL,
    [PERCENTAGE]         DECIMAL (12, 2) NULL,
    [DATE_LAST_INSERTED] DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RWZI_INHIBITANTS_2021_GEBIEDSCODE_PERCENTAGE]
    ON [VWSSTATIC].[RWZI_INHIBITANTS_2021]([GEBIEDSCODE] ASC, [PERCENTAGE] ASC)
    INCLUDE([CODE_RWZI], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_RWZI_INHIBITANTS_2021_GEBIEDSCODE_DATE_LAST_INSERTED]
    ON [VWSSTATIC].[RWZI_INHIBITANTS_2021]([GEBIEDSCODE] ASC, [DATE_LAST_INSERTED] ASC)
    INCLUDE([CODE_RWZI], [PERCENTAGE]);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_RWZI_INHIBITANTS_2021_DATE_LAST_INSERTED]
    ON [VWSSTATIC].[RWZI_INHIBITANTS_2021]([DATE_LAST_INSERTED] ASC, [GEBIEDSCODE] ASC)
    INCLUDE([CODE_RWZI], [PERCENTAGE]);

