CREATE TABLE [VWSSTATIC].[RWZI_AWZI] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_RWZI_AWZI]) NOT NULL,
    [RWZI_AWZI_CODE]     VARCHAR (100) NULL,
    [RWZI_AWZI_NAME]     VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_RWZI_AWZI]
    ON [VWSSTATIC].[RWZI_AWZI]([DATE_LAST_INSERTED] ASC);

