CREATE TABLE [VWSSTATIC].[RWZI_CONNECTED_INHABITANTS] (
    [ID]                    INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_RWZI_CONNECTED_INHABITANTS]) NOT NULL,
    [REGIO_CODE]            VARCHAR (100) NULL,
    [REGIO_NAME]            VARCHAR (100) NULL,
    [CONNECTED_INHABITANTS] INT           NULL,
    [DATE_LAST_INSERTED]    DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

