CREATE TABLE [VWSSTATIC].[SAFETY_REGIONS_PER_MUNICIPAL] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_SAFETY_REGIONS_PER_MUNICIPAL]) NOT NULL,
    [GMCODE]             VARCHAR (100) NULL,
    [GMNAAM]             VARCHAR (100) NULL,
    [VRCODE]             VARCHAR (100) NULL,
    [VRNAAM]             VARCHAR (100) NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STATIC_SAFETY_REGIONS_PER_MUNICIPAL_DLI]
    ON [VWSSTATIC].[SAFETY_REGIONS_PER_MUNICIPAL]([DATE_LAST_INSERTED] ASC)
    INCLUDE([GMNAAM], [VRCODE]);


GO
CREATE NONCLUSTERED INDEX [IX_SAFETY_REGIONS_PER_MUNICIPAL]
    ON [VWSSTATIC].[SAFETY_REGIONS_PER_MUNICIPAL]([GMCODE] ASC);

