CREATE TABLE [VWSSTATIC].[SITUATIONS_MAPPING] (
    [ID]                     INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_SITUATIONS_MAPPING]) NOT NULL,
    [SETTING_DEFINITION]     VARCHAR (100) NULL,
    [SETTING_REPORTED_LABEL] VARCHAR (100) NULL,
    [VWS_CATEGORY]           VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

