CREATE TABLE [VWSSTATIC].[SPLIT_FILE_SOURCES] (
    [ID]             INT            IDENTITY (1, 1) NOT NULL,
    [SOURCE_ID]      INT            NULL,
    [BASE_URL]       NVARCHAR (MAX) NOT NULL,
    [DOCUMENT_NAME]  NVARCHAR (MAX) NOT NULL,
    [TABLE_SCHEMA]   NVARCHAR (MAX) NOT NULL,
    [TABLE_NAME]     NVARCHAR (MAX) NOT NULL,
    [SOURCE_COLUMNS] NVARCHAR (MAX) NOT NULL,
    [TARGET_COLUMNS] NVARCHAR (MAX) NOT NULL
);

