CREATE TABLE [VWSSTATIC].[VARIANTS_MAPPING] (
    [ID]                          INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_VARIANTS_MAPPING]) NOT NULL,
    [VARIANT_CODE]                VARCHAR (100) NULL,
    [WHO_VARIANT]                 VARCHAR (100) NULL,
    [CLASSIFICATION]              VARCHAR (100) NULL,
    [SOURCE]                      VARCHAR (100) NULL,
    [EARLIEST_DOCUMENTED_SAMPLES] VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]          DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

