-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
CREATE OR ALTER VIEW [VWSDEST].[V_RIVM_DECEASED_DAILY_NATIONAL]
AS
--Retrieve the totals deceased on NL level by summing the region numbers.
WITH BASE_CTE AS (
        SELECT
        SUM(DECEASED_ACTUAL) AS DECEASED_ACTUAL
    ,   DATE_OF_REPORT_UNIX
    , DATE_LAST_INSERTED
    FROM VWSDEST.RIVM_DECEASED_DAILY_PER_REGION
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.RIVM_DECEASED_DAILY_PER_REGION)
    GROUP BY DATE_OF_REPORT_UNIX, DATE_LAST_INSERTED
)
,
--Determine the cumulative number as COVID_TOTAL
SECOND_CTE AS
(
    SELECT
        a.DECEASED_ACTUAL AS COVID_DAILY
    ,   SUM(DECEASED_ACTUAL) OVER(ORDER BY DATE_OF_REPORT_UNIX ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COVID_TOTAL
    ,   DATE_OF_REPORT_UNIX AS DATE_UNIX
    ,   [dbo].[CONVERT_DATETIME_TO_UNIX](DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX

    -- 7d average
	,LAG ([DATE_OF_REPORT_UNIX] ,6) OVER (ORDER BY [DATE_OF_REPORT_UNIX] ASC) WEEK_START
	,LAG ([DATE_OF_REPORT_UNIX] ,7) OVER (ORDER BY [DATE_OF_REPORT_UNIX] ASC) WEEK_START_LAG
	,AVG(CAST([DECEASED_ACTUAL] AS FLOAT)) OVER (ORDER BY DATE_OF_REPORT_UNIX ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as DECEASED_7D_AVG
	,AVG(CAST([DECEASED_ACTUAL] AS FLOAT)) OVER (ORDER BY DATE_OF_REPORT_UNIX ASC ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING) as DECEASED_7D_AVG_LAG
	
    FROM BASE_CTE a
)

SELECT
    COVID_DAILY
,   IIF(WEEK_START IS NULL, NULL, ROUND(DECEASED_7D_AVG,1)) AS COVID_DAILY_MOVING_AVERAGE
,   COVID_TOTAL
,   DATE_UNIX
,   DATE_OF_INSERTION_UNIX
FROM SECOND_CTE