-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
CREATE OR ALTER VIEW [VWSDEST].[V_RIVM_DECEASED_DAILY_NATIONAL]
AS
WITH BASE_CTE AS (
    SELECT
    SUM(DECEASED_ACTUAL) AS DECEASED_ACTUAL
,   DATE_OF_REPORT_UNIX
, DATE_LAST_INSERTED
FROM VWSDEST.RIVM_DECEASED_DAILY_PER_REGION
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.RIVM_DECEASED_DAILY_PER_REGION)
GROUP BY DATE_OF_REPORT_UNIX, DATE_LAST_INSERTED
)

SELECT
    a.DECEASED_ACTUAL AS COVID_DAILY
,  SUM(DECEASED_ACTUAL) OVER(ORDER BY DATE_OF_REPORT_UNIX ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COVID_TOTAL
,   DATE_OF_REPORT_UNIX AS DATE_UNIX
,   [dbo].[CONVERT_DATETIME_TO_UNIX](DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX
FROM BASE_CTE a