-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTATIC_CBS_AGEGROUP_DISTRIBUTION]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTATIC_CBS_AGEGROUP_DISTRIBUTION
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE VWSSTATIC.CBS_AGEGROUP_DISTRIBUTION(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_CBS_AGEGROUP_DISTRIBUTION]),
	[AGEGROUP] VARCHAR(10),
	[INHABITANTS] VARCHAR(100),
	[INHABITANTS_PERCENTAGE] DECIMAL(10,3),
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);
