-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTATIC_CBS_INHABITANTS_PER_AGEGROUP]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTATIC_CBS_INHABITANTS_PER_AGEGROUP
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE VWSSTATIC.CBS_INHABITANTS_PER_AGEGROUP(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_CBS_INHABITANTS_PER_AGEGROUP]),
    [GESLACHT] VARCHAR(10),
	[LEEFTIJD] VARCHAR(10),
	[BURGERLIJKESTAAT] VARCHAR(10),
	[REGIOS] VARCHAR(10),
	[PERIODEN] VARCHAR(10),
    [BEVOLKINGOP1JANUARI_1] BIGINT,
	[GEMIDDELDEBEVOLKING_2] BIGINT,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);
