-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTATIC_INHABITANTS_PER_SAFETY_REGION]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTATIC_INHABITANTS_PER_SAFETY_REGION
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSSTATIC.INHABITANTS_PER_SAFETY_REGION(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_INHABITANTS_PER_SAFETY_REGION]),
	VGRNR VARCHAR(100) NULL,
	VGRNAAM VARCHAR(100) NULL,
	INHABITANTS INT NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);