-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTATIC_CBS_INHABITANTS_ELDERLY_AT_HOME]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTATIC_CBS_INHABITANTS_ELDERLY_AT_HOME
  START WITH 1
  INCREMENT BY 1;
GO
-- 8-4-2021 -- fix for initial
CREATE TABLE VWSSTATIC.CBS_INHABITANTS_ELDERLY_AT_HOME(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTATIC_CBS_INHABITANTS_ELDERLY_AT_HOME]),
	[NAAM VEILIGHEIDSREGIO] VARCHAR(100) NULL,
	[CODE VEILIGHEIDSREGIO] VARCHAR(100) NULL,
	[PERSONEN VAN 70 JAAR OF OUDER IN PARTICULIERE HUISHOUDENS] INT NULL, 
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);