-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_CBS_INHABITANTS_PER_MUNICIPALITY]') AND type = 'SO')
CREATE SEQUENCE SEQ_CBS_INHABITANTS_PER_MUNICIPALITY
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE VWSSTATIC.CBS_INHABITANTS_PER_MUNICIPALITY(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_CBS_INHABITANTS_PER_MUNICIPALITY]),
    [VRCODE] VARCHAR(5),
    [GMCODE] VARCHAR(10),
	[INHABITANTS] BIGINT,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWS_VWSSTATIC_CBS_INHABITANTS_PER_MUNICIPALITY')
    CREATE NONCLUSTERED INDEX IX_VWS_VWSSTATIC_CBS_INHABITANTS_PER_MUNICIPALITY
    ON VWSSTATIC.CBS_INHABITANTS_PER_MUNICIPALITY(DATE_LAST_INSERTED, [VRCODE], [GMCODE])
    INCLUDE ([INHABITANTS]);
GO