-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordination for more information.

CREATE OR ALTER VIEW VWSDEST.V_SEWER_MEASUREMENTS_REGIONS AS
SELECT 
    DATE_START_UNIX,
    DATE_END_UNIX,
    VRCODE,
    AVERAGE,
    TOTAL_INSTALLATION_COUNT,
    DATE_OF_INSERTION_UNIX
FROM (
SELECT
        WEEK_UNIX
    ,   dbo.CONVERT_DATETIME_TO_UNIX(dbo.WEEK_START(dbo.CONVERT_UNIX_TO_DATETIME(WEEK_UNIX))) AS DATE_START_UNIX
    ,   dbo.CONVERT_DATETIME_TO_UNIX(dbo.WEEK_END(dbo.CONVERT_UNIX_TO_DATETIME(WEEK_UNIX))) AS DATE_END_UNIX
    ,   VRCODE
    ,   AVERAGE
    ,   TOTAL_INSTALLATION_COUNT
    ,   DATE_OF_INSERTION_UNIX
    ,   RANK() OVER (PARTITION BY VRCODE ORDER BY WEEK_UNIX DESC) RANKING
FROM VWSDEST.V_SEWER_MEASUREMENTS_PER_REGION
where VRCODE IS NOT NULL
AND VRCODE != ' ') T1
WHERE T1.RANKING =1
;
