-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) INTER -> DEST.....
 CREATE     PROCEDURE [dbo].[SP_BEHAVIOR_PER_REGION]
 AS
 BEGIN
     DECLARE @wash_hands VARCHAR(50) = 'was_vaak_je_handen';
     DECLARE @keep_distance VARCHAR(50) = 'houd_1_5m_afstand';
     DECLARE @works_home VARCHAR(50) = 'werkt_thuis';
     DECLARE @avoid_crowds VARCHAR(50) = 'vermijd_drukke_plekken';
     DECLARE @stays_home VARCHAR(50) = 'bij_klachten_blijf_thuis';
     DECLARE @gets_tested VARCHAR(50) = 'bij_klachten_laat_testen';
     DECLARE @public_mask VARCHAR(50) = 'draag_mondkapje_in_publieke_binnenruimtes';
     DECLARE @transit_mask VARCHAR(50) = 'draag_mondkapje_in_ov';
     DECLARE @cough_elbow VARCHAR(50) = 'hoest_niest_in_elleboog';
     DECLARE @max_visitors VARCHAR(50) = 'ontvang_max_bezoekers_thuis';
     DECLARE @curfew VARCHAR(50) = 'avondklok';
     DECLARE @ventilate_home VARCHAR (50)= 'ventileren_woning';
     DECLARE @selftest_visit VARCHAR (50)= 'zelftest_bezoek';
 
     -- SELECT ROWS WHICH ARE RELEVANT FOR THIS CALCULATION.
     WITH BASE_CTE AS (
         SELECT
             [DATE_OF_MEASUREMENT],
             [REGION_CODE],
             [INDICATOR_CATEGORY],
             [INDICATOR],
             [SAMPLE_SIZE],
             CONVERT(INT, ROUND([VALUE], 0)) AS [VALUE],
             [CHANGE_WRT_PREVIOUS_MEASUREMENT] AS CHANGE
         FROM VWSINTER.VWS_BEHAVIOR
         WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from VWSINTER.VWS_BEHAVIOR)
             AND LOWER(SUBGROUP) = 'totaal' -- IGNORE GROUP SPECIFIEC VALUES
             AND UPPER(REGION_CODE) LIKE '%VR%' -- ONLY TAKE REGIONAL VALUES
     ),
     -- SELECT ROWS RELATED TO COMPLIANCE.
     COMPLIANCE_CTE AS (
         SELECT
             [DATE_OF_MEASUREMENT],
             [REGION_CODE],
             [INDICATOR_CATEGORY],
             [INDICATOR],
             [SAMPLE_SIZE],
             [VALUE],
             [CHANGE]
         FROM BASE_CTE
             WHERE LOWER([INDICATOR_CATEGORY])  = 'naleving'
     ),
     -- SELECT ROWS RELATED TO SUPPORT.
     SUPPORT_CTE AS (
         SELECT
             [DATE_OF_MEASUREMENT],
             [REGION_CODE],
             [INDICATOR_CATEGORY],
             [INDICATOR],
             [SAMPLE_SIZE],
             [VALUE],
             [CHANGE]
         FROM BASE_CTE
             WHERE LOWER([INDICATOR_CATEGORY])  = 'draagvlak'
     ),
     DATE_CTE AS (
         SELECT DISTINCT [REGION_CODE],[DATE_OF_MEASUREMENT] FROM BASE_CTE
     )
     INSERT INTO VWSDEST.BEHAVIOR_PER_REGION
     (
         [DATE_OF_REPORT],
         [VRCODE],
         [NUMBER_OF_PARTICIPANTS],
         [WASH_HANDS_COMPLIANCE],
         [WASH_HANDS_COMPLIANCE_TREND],
         [KEEP_DISTANCE_COMPLIANCE],
         [KEEP_DISTANCE_COMPLIANCE_TREND],
         [WORK_FROM_HOME_COMPLIANCE],
         [WORK_FROM_HOME_COMPLIANCE_TREND],
         [AVOID_CROWDS_COMPLIANCE],
         [AVOID_CROWDS_COMPLIANCE_TREND],
         [SYMPTOMS_STAY_HOME_COMPLIANCE],
         [SYMPTOMS_GET_TESTED_COMPLIANCE],
         [WEAR_MASK_PUBLIC_INDOORS_COMPLIANCE],
         [WEAR_MASK_PUBLIC_INDOORS_COMPLIANCE_TREND],
         [WEAR_MASK_PUBLIC_TRANSPORT_COMPLIANCE],
         [SNEEZE_COUGH_ELBOW_COMPLIANCE],
         [SNEEZE_COUGH_ELBOW_COMPLIANCE_TREND],
         [MAX_VISITORS_COMPLIANCE],
         [MAX_VISITORS_COMPLIANCE_TREND],
         [CURFEW_COMPLIANCE],
         [CURFEW_COMPLIANCE_TREND],
         [VENTILATE_HOME_COMPLIANCE],
         [VENTILATE_HOME_COMPLIANCE_TREND],
 		[SELFTEST_VISIT_COMPLIANCE],
 		[SELFTEST_VISIT_COMPLIANCE_TREND],
         [WASH_HANDS_SUPPORT],
         [WASH_HANDS_SUPPORT_TREND],
         [KEEP_DISTANCE_SUPPORT],
         [KEEP_DISTANCE_SUPPORT_TREND],
         [WORK_FROM_HOME_SUPPORT],
         [WORK_FROM_HOME_SUPPORT_TREND],
         [AVOID_CROWDS_SUPPORT],
         [AVOID_CROWDS_SUPPORT_TREND],
         [SYMPTOMS_STAY_HOME_SUPPORT],
         [SYMPTOMS_GET_TESTED_SUPPORT],
         [WEAR_MASK_PUBLIC_INDOORS_SUPPORT],
         [WEAR_MASK_PUBLIC_INDOORS_SUPPORT_TREND],
         [WEAR_MASK_PUBLIC_TRANSPORT_SUPPORT],
         [SNEEZE_COUGH_ELBOW_SUPPORT],
         [SNEEZE_COUGH_ELBOW_SUPPORT_TREND],
         [MAX_VISITORS_SUPPORT],
         [MAX_VISITORS_SUPPORT_TREND],
         [CURFEW_SUPPORT],
         [CURFEW_SUPPORT_TREND],
         [VENTILATE_HOME_SUPPORT],
         [VENTILATE_HOME_SUPPORT_TREND],
 		[SELFTEST_VISIT_SUPPORT],
 		[SELFTEST_VISIT_SUPPORT_TREND]
     )
     SELECT
         [DATE_OF_MEASUREMENT] AS [DATE_OF_REPORT],
         TD.[REGION_CODE] AS [VRCODE],
         -- THE NUMBER OF PARTICIPANT DIFFERS BECUASE SOME QUESTIONS ARE NOT APPLICABLE TO ALL PARTICIPANTS. VWS HAS CHOSEN TO TAKE THE MAXIMUM AS THE AMOUNTOF PARTICIPANTS.
         (
             SELECT MAX([SAMPLE_SIZE]) FROM BASE_CTE TB
             WHERE TD.[DATE_OF_MEASUREMENT] = TB.[DATE_OF_MEASUREMENT]
             AND (LOWER(TB.[INDICATOR_CATEGORY])  = 'draagvlak' OR LOWER(TB.[INDICATOR_CATEGORY])  = 'naleving')
             AND TB.[REGION_CODE] = TD.[REGION_CODE]
         ) AS [NUMBER_OF_PARTICIPANTS],
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @wash_hands AND TD.REGION_CODE=T1.REGION_CODE) AS WASH_HANDS_COMPLIANCE,
         (SELECT [CHANGE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @wash_hands AND TD.REGION_CODE=T1.REGION_CODE) AS WASH_HANDS_COMPLIANCE_TREND,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @keep_distance AND TD.REGION_CODE=T1.REGION_CODE) AS KEEP_DISTANCE_COMPLIANCE,
         (SELECT [CHANGE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @keep_distance AND TD.REGION_CODE=T1.REGION_CODE) AS KEEP_DISTANCE_COMPLIANCE_TREND,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @works_home AND TD.REGION_CODE=T1.REGION_CODE) AS WORK_FROM_HOME_COMPLIANCE,
         (SELECT [CHANGE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @works_home AND TD.REGION_CODE=T1.REGION_CODE) AS WORK_FROM_HOME_COMPLIANCE_TREND,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @avoid_crowds AND TD.REGION_CODE=T1.REGION_CODE) AS AVOID_CROWDS_COMPLIANCE,
         (SELECT [CHANGE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @avoid_crowds AND TD.REGION_CODE=T1.REGION_CODE) AS AVOID_CROWDS_COMPLIANCE_TREND,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @stays_home AND TD.REGION_CODE=T1.REGION_CODE) AS SYMPTOMS_STAY_HOME_COMPLIANCE,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @gets_tested AND TD.REGION_CODE=T1.REGION_CODE) AS SYMPTOMS_GET_TESTED_COMPLIANCE,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @public_mask AND TD.REGION_CODE=T1.REGION_CODE) AS WEAR_MASK_PUBLIC_INDOORS_COMPLIANCE,
         (SELECT [CHANGE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @public_mask AND TD.REGION_CODE=T1.REGION_CODE) AS WEAR_MASK_PUBLIC_INDOORS_COMPLIANCE_TREND,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @transit_mask AND TD.REGION_CODE=T1.REGION_CODE) AS WEAR_MASK_PUBLIC_TRANSPORT_COMPLIANCE,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @cough_elbow AND TD.REGION_CODE=T1.REGION_CODE) AS SNEEZE_COUGH_ELBOW_COMPLIANCE,
         (SELECT [CHANGE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @cough_elbow AND TD.REGION_CODE=T1.REGION_CODE) AS SNEEZE_COUGH_ELBOW_COMPLIANCE_TREND,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @max_visitors AND TD.REGION_CODE=T1.REGION_CODE) AS MAX_VISITORS_COMPLIANCE,
         (SELECT [CHANGE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @max_visitors AND TD.REGION_CODE=T1.REGION_CODE) AS MAX_VISITORS_COMPLIANCE_TREND,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @curfew AND TD.REGION_CODE=T1.REGION_CODE) AS CURFEW_COMPLIANCE,
         (SELECT [CHANGE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @curfew AND TD.REGION_CODE=T1.REGION_CODE) AS CURFEW_COMPLIANCE_TREND,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @ventilate_home AND TD.REGION_CODE=T1.REGION_CODE) AS VENTILATE_HOME_COMPLIANCE,
         (SELECT [CHANGE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @ventilate_home AND TD.REGION_CODE=T1.REGION_CODE) AS VENTILATE_HOME_COMPLIANCE_TREND,
         (SELECT [VALUE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @selftest_visit AND TD.REGION_CODE=T1.REGION_CODE) AS SELFTEST_VISIT_COMPLIANCE,
         (SELECT [CHANGE] FROM COMPLIANCE_CTE T1 WHERE TD.DATE_OF_MEASUREMENT=T1.DATE_OF_MEASUREMENT AND LOWER(T1.[INDICATOR]) = @selftest_visit AND TD.REGION_CODE=T1.REGION_CODE) AS SELFTEST_VISIT_COMPLIANCE_TREND,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @wash_hands AND TD.REGION_CODE=T2.REGION_CODE) AS WASH_HANDS_SUPPORT,
         (SELECT [CHANGE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @wash_hands AND TD.REGION_CODE=T2.REGION_CODE) AS WASH_HANDS_SUPPORT_TREND,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @keep_distance AND TD.REGION_CODE=T2.REGION_CODE) AS KEEP_DISTANCE_SUPPORT,
         (SELECT [CHANGE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @keep_distance AND TD.REGION_CODE=T2.REGION_CODE) AS KEEP_DISTANCE_SUPPORT_TREND,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @works_home AND TD.REGION_CODE=T2.REGION_CODE) AS WORK_FROM_HOME_SUPPORT,
         (SELECT [CHANGE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @works_home AND TD.REGION_CODE=T2.REGION_CODE) AS WORK_FROM_HOME_SUPPORT_TREND,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @avoid_crowds AND TD.REGION_CODE=T2.REGION_CODE) AS AVOID_CROWDS_SUPPORT,
         (SELECT [CHANGE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @avoid_crowds AND TD.REGION_CODE=T2.REGION_CODE) AS AVOID_CROWDS_SUPPORT_TREND,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @stays_home AND TD.REGION_CODE=T2.REGION_CODE) AS SYMPTOMS_STAY_HOME_SUPPORT,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @gets_tested AND TD.REGION_CODE=T2.REGION_CODE) AS SYMPTOMS_GET_TESTED_SUPPORT,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @public_mask AND TD.REGION_CODE=T2.REGION_CODE) AS WEAR_MASK_PUBLIC_INDOORS_SUPPORT,
         (SELECT [CHANGE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @public_mask AND TD.REGION_CODE=T2.REGION_CODE) AS WEAR_MASK_PUBLIC_INDOORS_SUPPORT_TREND,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @transit_mask AND TD.REGION_CODE=T2.REGION_CODE) AS WEAR_MASK_PUBLIC_TRANSPORT_SUPPORT,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @cough_elbow AND TD.REGION_CODE=T2.REGION_CODE) AS SNEEZE_COUGH_ELBOW_SUPPORT,
         (SELECT [CHANGE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @cough_elbow AND TD.REGION_CODE=T2.REGION_CODE) AS SNEEZE_COUGH_ELBOW_SUPPORT_TREND,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @max_visitors AND TD.REGION_CODE=T2.REGION_CODE) AS MAX_VISITORS_SUPPORT,
         (SELECT [CHANGE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @max_visitors AND TD.REGION_CODE=T2.REGION_CODE) AS MAX_VISITORS_SUPPORT_TREND,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @curfew AND TD.REGION_CODE=T2.REGION_CODE) AS CURFEW_SUPPORT,
         (SELECT [CHANGE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @curfew AND TD.REGION_CODE=T2.REGION_CODE) AS CURFEW_SUPPORT_TREND,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @ventilate_home AND TD.REGION_CODE=T2.REGION_CODE) AS VENTILATE_HOME_SUPPORT,
         (SELECT [CHANGE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @ventilate_home AND TD.REGION_CODE=T2.REGION_CODE) AS VENTILATE_HOME_SUPPORT_TREND,
         (SELECT [VALUE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @selftest_visit AND TD.REGION_CODE=T2.REGION_CODE) AS SELFTEST_VISIT_SUPPORT_TREND_SUPPORT,
         (SELECT [CHANGE] FROM SUPPORT_CTE T2 WHERE TD.DATE_OF_MEASUREMENT=T2.DATE_OF_MEASUREMENT AND LOWER(T2.[INDICATOR]) = @selftest_visit AND TD.REGION_CODE=T2.REGION_CODE) AS SELFTEST_VISIT_SUPPORT_TREND_SUPPORT_TREND
     FROM DATE_CTE TD
 END;