-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_CBS_DECEASED_VR]
 AS
 BEGIN
 -- JUST BECAUSE WE CAN'T DO A WHERE BEFORE JOIN. THIS BASE TABLE TO SELECT THE LAST AND THAN A JOIN
 WITH BASE_CTE AS(
     SELECT 
         * 
     FROM [VWSINTER].[CBS_DECEASED_VR]
     WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSINTER].[CBS_DECEASED_VR])
 ),
 SECOND_CTE AS(
     SELECT
         [DBO].[CONVERT_ISO_WEEK_TO_DATETIME](T1.[YEAR], T1.[WEEK]) AS [WEEK_START],
         [DBO].[WEEK_END]([DBO].[CONVERT_ISO_WEEK_TO_DATETIME](T1.[YEAR], T1.[WEEK])) AS [WEEK_END],
         [DBO].[CONVERT_WEEKNUMBER_TO_UNIX](T1.[YEAR], T1.[WEEK]) AS [WEEK_START_UNIX],
         [DBO].[CONVERT_DATETIME_TO_UNIX] (
             [DBO].[WEEK_END](
                 [DBO].[CONVERT_ISO_WEEK_TO_DATETIME](T1.[YEAR], T1. [WEEK])
             )
         ) AS [WEEK_END_UNIX],
         [YEAR],
         [WEEK],
         T1.[DECEASED_ACTUAL],
         [REGIOS] AS [VRCODE]
     FROM BASE_CTE AS T1
 )
 INSERT INTO [VWSDEST].[CBS_DECEASED_VR](
     [WEEK_START],
     [WEEK_END],
     [WEEK_START_UNIX],
     [WEEK_END_UNIX],
     [YEAR],
     [WEEK],
     [VRCODE],
     [DECEASED_ACTUAL],
     [DECEASED_FORECAST],
     [DECEASED_FORECAST_HIGH],
     [DECEASED_FORECAST_LOW]
 )
 SELECT
     T1.[WEEK_START],
     T1.[WEEK_END],
     T1.[WEEK_START_UNIX],
     T1.[WEEK_END_UNIX],
     T1.[YEAR],
     T1.[WEEK],
     T1.[VRCODE],
     T1.[DECEASED_ACTUAL],
     T2.[DECEASED_FORECAST],
     T2.[DECEASED_FORECAST_HIGH],
     T2.[DECEASED_FORECAST_LOW]
 FROM SECOND_CTE AS T1
 LEFT JOIN (
     SELECT 
         * 
     FROM [VWSINTER].[CBS_DECEASED_VR_FORECAST]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSINTER].[CBS_DECEASED_VR_FORECAST])
 ) AS T2
 ON T1.[YEAR] = T2.[YEAR] 
     AND T1.[WEEK] = T2.[WEEK] 
     AND T1.[VRCODE] = T2.[VRCODE]
 END;