-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT. 
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_CBS_DECEASED_PER_WEEK_FORECAST_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[CBS_DECEASED_PER_WEEK_FORECAST] (
         [YEAR],
         [WEEK],
         [DECEASED_FORECAST],
         [DECEASED_FORECAST_LOW],
         [DECEASED_FORECAST_HIGH]
     )
     SELECT
         CAST(SUBSTRING([PERIODEN], 1, 4) AS INT),
         CAST(SUBSTRING([PERIODEN], 7, 2) AS INT),
         [VERWACHT_AANTAL_OVERLEDENEN],
         [ONDERGRENS],
         [BOVENGRENS]
     FROM [VWSSTAGE].[CBS_DECEASED_PER_WEEK_FORECAST]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[CBS_DECEASED_PER_WEEK_FORECAST])
 END;