-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT. 
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_CBS_DECEASED_VR_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[CBS_DECEASED_VR] (
         [YEAR],
         [WEEK],
         [REGIOS],
         [DECEASED_ACTUAL] 
     )
     SELECT    
         CAST(SUBSTRING([PERIODEN], 1, 4) AS INT),
         CAST(SUBSTRING([PERIODEN], 7, 2) AS INT),
         [REGIOS],
         CAST([OVERLEDENEN_1] AS INT) AS [DECEASED_ACTUAL]
     FROM [VWSSTAGE].[CBS_DECEASED_VR]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[CBS_DECEASED_VR])
 END;