-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_CBS_POPULATION_VR]
 AS
 BEGIN
     INSERT INTO [VWSSTATIC].[CBS_POPULATION_VR]
     (
     	[VR_CODE]
     	,[DATUM_PEILING]
     	,[POPULATIE]
     )
     SELECT 
          [VEILIGHEIDSREGIO_CODE] AS [VR_CODE]
         ,[DATUM_PEILING]
         ,SUM([POPULATIE]) AS [POPULATIE]
     FROM [VWSSTATIC].[CBS_POPULATION_BASE]
     WHERE [DATE_LAST_INSERTED] = ( SELECT MAX([DATE_LAST_INSERTED])  FROM [VWSSTATIC].[CBS_POPULATION_BASE] )
     GROUP BY [VEILIGHEIDSREGIO_CODE], [DATUM_PEILING]
     ORDER BY [VEILIGHEIDSREGIO_CODE], [DATUM_PEILING]
 END;