-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT. 
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_CBS_DECEASED_PER_WEEK_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[CBS_DECEASED_PER_WEEK](
         [YEAR],
         [WEEK],
         [DECEASED_ACTUAL]
     )
     SELECT
         -- WE MAKE SUBSTRINGS OF THE GIVEN PERIODEN COLUMN. THIS WILL WORK UNTIL THE YEAR
         -- 9999 WHICH SEEMS ADEQUATE FOR NOW
         CAST(SUBSTRING([PERIODEN], 1, 4) AS INT),
         CAST(SUBSTRING([PERIODEN], 7, 2) AS INT),
         [OVERLEDENEN_1]
     FROM [VWSSTAGE].[CBS_DECEASED_PER_WEEK]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[CBS_DECEASED_PER_WEEK])
 END;