-- Move cluster information data from intermediate to destination table.
CREATE   PROCEDURE [dbo].[SP_CLUSTERS_INFECTED_PEOPLE]
AS
BEGIN
    INSERT INTO VWSDEST.CLUSTERS_INFECTED_PEOPLE (DATE_OF_REPORT, DATE_OF_REPORT_UNIX, ACTIVE_CLUSTERS, CLUSTER_AVERAGE)
    SELECT
        DATE_STATISTICS AS DATE_OF_REPORT,
        dbo.CONVERT_DATETIME_TO_UNIX(DATE_STATISTICS) AS [DATE_OF_REPORT_UNIX],
        ACTIVE_CLUSTERS,
        AVERAGE_SIZE AS CLUSTER_AVERAGE
    FROM
        VWSINTER.RIVM_CLUSTERS_INFECTED_PEOPLE
    WHERE
        DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSINTER.RIVM_CLUSTERS_INFECTED_PEOPLE)
        -- The source file seperates regional and national lines by setting the security region data to one of these values.
        AND (SECURITY_REGION_NAME = 'Nederland' OR SECURITY_REGION_CODE = '-')
    ORDER BY DATE_STATISTICS
END;