CREATE   PROCEDURE [DBO].[SP_CIMS_VACCINATED_AGE_GROUP_VR_GM_DEST_TO_ARCHIVE]
 AS
 BEGIN
     INSERT INTO [VWSARCHIVE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR] (
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [REGION_CODE],
         [BIRTH_YEAR],
         [AGE_GROUP],    
         [VACCINATION_COVERAGE_ALL],  
         [VACCINATION_COVERAGE_ALL_LABEL],
         [VACCINATION_COVERAGE_COMPLETED],      
         [VACCINATION_COVERAGE_COMPLETED_LABEL],
         [DATE_LAST_INSERTED]
     )
     SELECT
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [REGION_CODE],
         [BIRTH_YEAR],
         [AGE_GROUP],    
         [VACCINATION_COVERAGE_ALL],  
         [VACCINATION_COVERAGE_ALL_LABEL],
         [VACCINATION_COVERAGE_COMPLETED],      
         [VACCINATION_COVERAGE_COMPLETED_LABEL],
         [DATE_LAST_INSERTED]
     FROM [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR] WITH(NOLOCK)
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR] WITH(NOLOCK));
 END;