-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT. 
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_CBS_DECEASED_VR_FORECAST_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[CBS_DECEASED_VR_FORECAST] (
         [YEAR],
         [WEEK],
         [DECEASED_FORECAST],
         [DECEASED_FORECAST_LOW],
         [DECEASED_FORECAST_HIGH],
         [VRNAME],
         [VRCODE] 
     )
     SELECT
         CAST(SUBSTRING([WEEK], 1, 4) AS INT) AS [YEAR],
         CAST(SUBSTRING([WEEK], 11, 2) AS INT) AS [WEEK],
         [SEIZOENSPATROON MET MARGES],
         [ONDERGRENS],
         [BOVENGRENS],
         [VR NAAM],
         [VR CODE] 
     FROM 
         [VWSSTAGE].[CBS_DECEASED_VR_FORECAST]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[CBS_DECEASED_VR_FORECAST])
 END;