-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [dbo].[SP_CBS_POPULATION_NL]
 AS
 BEGIN
     INSERT INTO [VWSSTATIC].[CBS_POPULATION_NL]
     (
         [DATUM_PEILING],
         [POPULATIE]
     )
     SELECT 
         [DATUM_PEILING],
         SUM([POPULATIE]) AS [POPULATIE]
     FROM [VWSSTATIC].[CBS_POPULATION_BASE]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[CBS_POPULATION_BASE])
     GROUP BY [DATUM_PEILING]
     ORDER BY [DATUM_PEILING]
 END;