-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) INTER -> DEST.....
 CREATE   PROCEDURE [DBO].[SP_CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR_INTER_TO_DEST]
 AS
 BEGIN
     WITH CTE AS (
         SELECT 
             A.[DATE_LAST_INSERTED],
             A.[VERSION],
             A.[DATE_OF_REPORT],
             A.[DATE_OF_STATISTICS],
             A.[POPULATION],
             A.[REGION_CODE],
             A.[REGION_LEVEL],
             A.[REGION_NAME],
             ISNULL(B.[COHORT_ADJUSTED], A.[BIRTH_YEAR]) AS [BIRTH_YEAR],
             C.[AGE_GROUP],
             A.[VACCINATION_CAMPAIGN],
             A.[PERCENTAGE],
             A.[PERCENTAGE_LABEL]
         FROM [VWSINTER].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR] A
             LEFT JOIN [VWSSTATIC].[COHORT_TO_NAMES_MAPPING] B ON A.[BIRTH_YEAR] = B.[COHORT_ORIGINAL]
             LEFT JOIN [VWSSTATIC].[COHORT_TO_AGE_GROUPS_MAPPING] C ON C.[COHORT] = A.[BIRTH_YEAR]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR])
     )
     INSERT INTO [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN_GM_VR] (
             [VERSION],
             [DATE_OF_REPORT],
             [DATE_OF_STATISTICS],
             [POPULATION],
             [REGION_CODE],
             [REGION_LEVEL],
             [REGION_NAME],
             [AGE_GROUP],
             [BIRTHYEAR_RANGE],
             [VACCINATION_CAMPAIGN],
             [PERCENTAGE],
             [PERCENTAGE_LABEL]
     )
     SELECT 
             [VERSION],
             [DATE_OF_REPORT],
             [DATE_OF_STATISTICS],
             [POPULATION],
             [REGION_CODE],
             [REGION_LEVEL],
             [REGION_NAME],
             [AGE_GROUP],
             [BIRTH_YEAR],
             [VACCINATION_CAMPAIGN],
             [PERCENTAGE],
             [PERCENTAGE_LABEL]
     FROM CTE
 END