-- Hiervoor eenmalig een query runnen die dit INTO een VWSARCHIVE tabel schrijft
 -- met als extensie 20220908 en die filtert op de datum 2022-0908
 
 
 -- 1) CREATE STORED PROCEDURE(S): ARCHIVE EXISTING DATA
 CREATE   PROCEDURE [DBO].[SP_CIMS_VACCINATED_PER_AGE_GROUP_GM_VR_DEST_TO_ARCHIVED_20220908]
 AS
 BEGIN
     TRUNCATE TABLE [VWSARCHIVE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR_ARCHIVED_20220908]
 
     INSERT INTO [VWSARCHIVE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR_ARCHIVED_20220908] (
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [REGION_CODE],
         [BIRTH_YEAR],
         [AGE_GROUP],    
         [VACCINATION_COVERAGE_ALL],  
         [VACCINATION_COVERAGE_ALL_LABEL],
         [VACCINATION_COVERAGE_COMPLETED],      
         [VACCINATION_COVERAGE_COMPLETED_LABEL],
         [DATE_LAST_INSERTED]
     )
     SELECT
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [REGION_CODE],
         [BIRTH_YEAR],
         [AGE_GROUP],    
         [VACCINATION_COVERAGE_ALL],  
         [VACCINATION_COVERAGE_ALL_LABEL],
         [VACCINATION_COVERAGE_COMPLETED],      
         [VACCINATION_COVERAGE_COMPLETED_LABEL],
         [DATE_LAST_INSERTED]
     FROM [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR] WITH(NOLOCK)
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR])
 END;