-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_CBS_POPULATION_GM]
 AS
 BEGIN
     INSERT INTO VWSSTATIC.CBS_POPULATION_GM
     (
      [GM_CODE]
     ,[DATUM_PEILING]
     ,[POPULATIE]
     )
     SELECT 
          [GEMEENTE_CODE] AS [GM_CODE]
         ,[DATUM_PEILING]
         ,SUM([POPULATIE]) AS [POPULATIE]
     FROM [VWSSTATIC].[CBS_POPULATION_BASE]
     WHERE [DATE_LAST_INSERTED] = ( SELECT MAX([DATE_LAST_INSERTED])  FROM [VWSSTATIC].[CBS_POPULATION_BASE] )
     GROUP BY GEMEENTE_CODE, [DATUM_PEILING]
     ORDER BY DATUM_PEILING, GEMEENTE_CODE
 END;