
 CREATE   PROCEDURE [dbo].[SP_DISABILITY_VR_ARCHIVED_20230126] AS
 BEGIN
     TRUNCATE TABLE [VWSARCHIVE].[DISABILITY_VR_ARCHIVED_20230126]
 
     INSERT INTO [VWSARCHIVE].[DISABILITY_VR_ARCHIVED_20230126] (
         	[ID],
             [DATE_OF_REPORT],
             [DATE_OF_REPORT_UNIX],
             [VRCODE],
             [INFECTED_DISABILITY_DAILY],
             [DECEASED_DISABILITY_DAILY],
             [TOTAL_NEW_INFECTED_LOCATIONS],
             [TOTAL_INFECTED_LOCATIONS],
             [TOTAL_LOCATIONS],
             [PERCENTAGE_INFECTED_LOCATIONS],
             [DATE_LAST_INSERTED],
             [DATE_RANGE_START],
             [DATE_OF_REPORTS_LAG],
             [DATE_RANGE_START_LAG],
             [7D_AVERAGE_TOTAL_INFECTED],
             [7D_AVERAGE_TOTAL_INFECTED_LAG],
             [7D_AVERAGE_TOTAL_DECEASED],
             [7D_AVERAGE_TOTAL_DECEASED_LAG]
     )
     SELECT 
         	[ID],
             [DATE_OF_REPORT],
             [DATE_OF_REPORT_UNIX],
             [VRCODE],
             [INFECTED_DISABILITY_DAILY],
             [DECEASED_DISABILITY_DAILY],
             [TOTAL_NEW_INFECTED_LOCATIONS],
             [TOTAL_INFECTED_LOCATIONS],
             [TOTAL_LOCATIONS],
             [PERCENTAGE_INFECTED_LOCATIONS],
             [DATE_LAST_INSERTED],
             [DATE_RANGE_START],
             [DATE_OF_REPORTS_LAG],
             [DATE_RANGE_START_LAG],
             [7D_AVERAGE_TOTAL_INFECTED],
             [7D_AVERAGE_TOTAL_INFECTED_LAG],
             [7D_AVERAGE_TOTAL_DECEASED],
             [7D_AVERAGE_TOTAL_DECEASED_LAG]
     FROM [VWSDEST].[DISABILITY_VR]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[DISABILITY_VR])
 END