CREATE   PROCEDURE [dbo].[SP_DECEASED_PER_PERIOD_STATIC]
AS
BEGIN
    INSERT INTO VWSSTATIC.CBS_DECEASED_PER_PERIOD
    ([PERIOD], WEEK_START, DECEASED)
    SELECT
        PERIODEN,
        DATEADD(week, CAST(SUBSTRING(perioden,7, 2) AS INT), DATEADD(YEAR, CAST(SUBSTRING(perioden,1, 4) AS INT)-1900, 0)) - 4 - 
        datepart(dw, DATEADD (week, CAST(SUBSTRING(perioden,7, 2) AS INT), DATEADD (YEAR, CAST(SUBSTRING(perioden,1, 4) AS INT)-1900, 0)) - 4) + 2,
        OVERLEDENEN_1
    FROM VWSSTAGE.CBS_DECEASED_PER_PERIOD
    WHERE PERIODEN NOT LIKE '%53'
END;