-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE   PROCEDURE [dbo].[SP_DECEASED_PER_AGE_GROUP]
AS
BEGIN
-- Move data from intermediate table to destination table.

WITH BASE_CTE AS (
SELECT
    DATE_LAST_INSERTED
,   CAST(CASE AGEGROUP
             WHEN '0-9'      THEN '0-49'
             WHEN '10-19'    THEN '0-49'
             WHEN '20-29'    THEN '0-49'
             WHEN '30-39'    THEN '0-49'
             WHEN '40-49'    THEN '0-49'
             WHEN '<50'      THEN '0-49'
             ELSE AGEGROUP
    END AS VARCHAR(100)) AS [AGEGROUP]
,   WEEK_OF_DEATH
FROM VWSINTER.RIVM_COVID_19_CASE_NATIONAL T1
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSINTER.RIVM_COVID_19_CASE_NATIONAL)
AND --WEEK_OF_DEATH <> ''
DECEASED = 'Yes'
)
,
TOTAL_DEATHS AS (
 SELECT 
             COUNT(*) AS DEATHS
            ,AGEGROUP
      FROM BASE_CTE
      GROUP BY AGEGROUP
)
,
AGEGROUP_POPULATION AS (  
SELECT 
     [AGEGROUP]
    ,[DATUM_PEILING]
    ,[POPULATIE]        AS [POPULATION]
    ,[POPULATIE_TOTAL] AS [POPULATION_TOTAL]
    ,INHABITANTS_PERCENTAGE
FROM VWSSTATIC.CBS_POPULATION_AGEGROUP_DECEASED
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSSTATIC.CBS_POPULATION_AGEGROUP_DECEASED)
)
,
AGEGROUP_POPULATION_RECENT AS (
SELECT 
     INHABITANTS_PERCENTAGE
    ,[POPULATION]
    ,[POPULATION_TOTAL]
    ,AGEGROUP
	,DATUM_PEILING
FROM AGEGROUP_POPULATION
WHERE DATUM_PEILING = (SELECT MAX([DATUM_PEILING]) FROM AGEGROUP_POPULATION )
)

-- Insert into dest table
INSERT INTO VWSDEST.DECEASED_PER_AGE_GROUP
    (
    AGEGROUP ,
    INHABITANTS_PERCENTAGE ,
    DEATHS ,
    DEATHS_PERCENTAGE 
    )


SELECT 
     T0.AGEGROUP
    ,ROUND(T1.INHABITANTS_PERCENTAGE * 100,1) AS INHABITANTS_PERCENTAGE
    ,T0.DEATHS
    ,ROUND(T0.DEATHS / SUM(CAST(T0.DEATHS AS FLOAT)) OVER (PARTITION BY 1) * 100,1)  as DEATHS_PERCENTAGE
 FROM TOTAL_DEATHS T0
 LEFT JOIN AGEGROUP_POPULATION_RECENT T1
    ON  T0.AGEGROUP = T1.AGEGROUP

END;