CREATE   PROCEDURE [dbo].[SP_Disability_Inter]
 AS
 BEGIN
 
    -- Zet de Date_Last_Inserted in een variabele
     DECLARE @DateTimeNow AS DateTime = GETDATE()
 
     INSERT INTO VWSINTER.DISABILITY (
         DATE_OF_REPORT,
         DATE_OF_STATISTIC_REPORTED,
         SECURITY_REGION_CODE,
         TOTAL_CASES_REPORTED,
         TOTAL_DECEASED_REPORTED,
         TOTAL_NEW_INFECTED_LOCATIONS_REPORTED,
         TOTAL_INFECTED_LOCATIONS_REPORTED,
         Date_Last_Inserted
         )
     SELECT
         DATE_OF_REPORT,
         DATE_OF_STATISTIC_REPORTED,
         SECURITY_REGION_CODE,
         TOTAL_CASES_REPORTED,
         TOTAL_DECEASED_REPORTED,
         TOTAL_NEW_INFECTED_LOCATIONS_REPORTED,
         TOTAL_INFECTED_LOCATIONS_REPORTED,
         @DateTimeNow
     FROM
         VWSSTAGE.DISABILITY
     WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from VWSSTAGE.DISABILITY)
 
     INSERT INTO VWSINTER.DISABILITY (
         DATE_OF_REPORT,
         DATE_OF_STATISTIC_REPORTED,
         SECURITY_REGION_CODE,
         TOTAL_CASES_REPORTED,
         TOTAL_DECEASED_REPORTED,
         TOTAL_NEW_INFECTED_LOCATIONS_REPORTED,
         TOTAL_INFECTED_LOCATIONS_REPORTED,
         Date_Last_Inserted
         )
     SELECT
         DATE_OF_REPORT,
         DATE_OF_STATISTIC_REPORTED,
         SECURITY_REGION_CODE,
         TOTAL_CASES_REPORTED,
         TOTAL_DECEASED_REPORTED,
         TOTAL_NEW_INFECTED_LOCATIONS_REPORTED,
         TOTAL_INFECTED_LOCATIONS_REPORTED,
         @DateTimeNow
     FROM
         VWSSTATIC.DISABILITY
     WHERE DATE_LAST_INSERTED  = (SELECT MAX(DATE_LAST_INSERTED)  FROM VWSSTATIC.DISABILITY)
 
 
 END;