
 CREATE   PROCEDURE [dbo].[SP_DECEASED_PER_AGE_GROUP_ARCHIVED_20221231] AS
 BEGIN
     TRUNCATE TABLE [VWSARCHIVE].[DECEASED_PER_AGE_GROUP_ARCHIVED_20221231]
 
     INSERT INTO [VWSARCHIVE].[DECEASED_PER_AGE_GROUP_ARCHIVED_20221231] (
         [ID],
         [AGEGROUP],
         [INHABITANTS_PERCENTAGE],
         [DEATHS],
         [DEATHS_PERCENTAGE],
         [DATE_LAST_INSERTED]
     )
     SELECT 
         [ID],
         [AGEGROUP],
         [INHABITANTS_PERCENTAGE],
         [DEATHS],
         [DEATHS_PERCENTAGE],
         [DATE_LAST_INSERTED]
     FROM [VWSDEST].[DECEASED_PER_AGE_GROUP]
     WHERE [DATE_LAST_INSERTED] > '2022-12-30' AND [DATE_LAST_INSERTED] < '2023-01-01' -- last updated on 30-12-2022
 END