CREATE   PROCEDURE [dbo].[SP_Elderly_At_Home_Inter]
 AS
 BEGIN
 
 -- Zet de Date_Last_Inserted in een variabele
 DECLARE @DateTimeNow AS DateTime = GETDATE()
 
 INSERT INTO VWSINTER.ELDERLY_AT_HOME (
     DATE_OF_REPORT,
     DATE_OF_STATISTIC_REPORTED,
     SECURITY_REGION_CODE,
     TOTAL_CASES_REPORTED,
     TOTAL_DECEASED_REPORTED,
     Date_Last_Inserted
     )
 SELECT
     DATE_OF_REPORT,
     DATE_OF_STATISTIC_REPORTED,
     SECURITY_REGION_CODE,
     TOTAL_CASES_REPORTED,
     TOTAL_DECEASED_REPORTED,
     @DateTimeNow
 FROM VWSSTAGE.ELDERLY_AT_HOME
 WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSSTAGE.ELDERLY_AT_HOME)
 
 
 INSERT INTO VWSINTER.ELDERLY_AT_HOME (
     DATE_OF_REPORT,
     DATE_OF_STATISTIC_REPORTED,
     SECURITY_REGION_CODE,
     TOTAL_CASES_REPORTED,
     TOTAL_DECEASED_REPORTED,
     Date_Last_Inserted
     )
 SELECT
     DATE_OF_REPORT,
     DATE_OF_STATISTIC_REPORTED,
     SECURITY_REGION_CODE,
     TOTAL_CASES_REPORTED,
     TOTAL_DECEASED_REPORTED,
     @DateTimeNow
 FROM VWSSTATIC.ELDERLY_AT_HOME
 WHERE DATE_LAST_INSERTED  = (SELECT MAX(DATE_LAST_INSERTED ) FROM VWSSTATIC.ELDERLY_AT_HOME)
 
 
 END;