-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) STAGE -> INTER.....
 CREATE   PROCEDURE [dbo].[SP_ECDC_VACCINATION_COVERAGES_STAGE_TO_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[ECDC_VACCINATION_COVERAGES] (
         [YEAR_WEEK_ISO],
         [REPORTING_COUNTRY],
         [DENOMINATOR],
         [NUMBER_DOSES_RECEIVED],
         [NUMBER_DOSES_EXPORTED],
         [FIRST_DOSE],
         [FIRST_DOSE_REFUSED],
         [SECOND_DOSE],
         [DOSE_ADDITIONAL1],
         [UNKNOWN_DOSE],
         [REGION],
         [TARGET_GROUP],
         [VACCINE],
         [POPULATION]
     )
     SELECT
         [YEAR_WEEK_ISO],
         [REPORTING_COUNTRY],
         CAST([DENOMINATOR] AS INT) AS [DENOMINATOR],
         CAST([NUMBER_DOSES_RECEIVED] AS INT) AS [NUMBER_DOSES_RECEIVED],
         CAST([NUMBER_DOSES_EXPORTED] AS INT) AS [NUMBER_DOSES_EXPORTED],
         CAST([FIRST_DOSE] AS INT) AS [FIRST_DOSE],
         CAST([FIRST_DOSE_REFUSED] AS INT) AS [FIRST_DOSE_REFUSED],
         CAST([SECOND_DOSE] AS INT) AS [SECOND_DOSE],
         CAST([DOSE_ADDITIONAL1] AS INT) AS [DOSE_ADDITIONAL1],
         CAST([UNKNOWN_DOSE] AS INT) AS [UNKNOWN_DOSE],
         [REGION],
         [TARGET_GROUP],
         [VACCINE],
         CAST ([POPULATION] AS INT) AS [POPULATION]
     FROM 
         [VWSSTAGE].[ECDC_VACCINATION_COVERAGES]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[ECDC_VACCINATION_COVERAGES]);
 
     --TRUNCATE TABLE [VWSSTAGE].[ECDC_VACCINATION_COVERAGES];
 END;