
 CREATE   PROCEDURE [dbo].[SP_ELDERLY_AT_HOME_ARCHIVED_20230126] AS
 BEGIN
     TRUNCATE TABLE [VWSARCHIVE].[ELDERLY_AT_HOME_ARCHIVED_20230126]
 
     INSERT INTO [VWSARCHIVE].[ELDERLY_AT_HOME_ARCHIVED_20230126] (
         [ID],
         [DATE_OF_REPORT],
         [DATE_OF_REPORT_UNIX],
         [INFECTED_ELDERLY_AT_HOME_DAILY],
         [INFECTED_ELDERLY_AT_HOME_DAILY_PER_100K],
         [DECEASED_ELDERLY_AT_HOME_DAILY],
         [DATE_LAST_INSERTED],
         [DATE_RANGE_START],
         [DATE_OF_REPORTS_LAG],
         [DATE_RANGE_START_LAG],
         [7D_AVERAGE_INFECTED_ELDERLY_AT_HOME_DAILY],
         [7D_AVERAGE_INFECTED_ELDERLY_AT_HOME_DAILY_LAG],
         [7D_AVERAGE_DECEASED_ELDERLY_AT_HOME_DAILY],
         [7D_AVERAGE_DECEASED_ELDERLY_AT_HOME_DAILY_LAG]
     )
     SELECT 
         [ID],
         [DATE_OF_REPORT],
         [DATE_OF_REPORT_UNIX],
         [INFECTED_ELDERLY_AT_HOME_DAILY],
         [INFECTED_ELDERLY_AT_HOME_DAILY_PER_100K],
         [DECEASED_ELDERLY_AT_HOME_DAILY],
         [DATE_LAST_INSERTED],
         [DATE_RANGE_START],
         [DATE_OF_REPORTS_LAG],
         [DATE_RANGE_START_LAG],
         [7D_AVERAGE_INFECTED_ELDERLY_AT_HOME_DAILY],
         [7D_AVERAGE_INFECTED_ELDERLY_AT_HOME_DAILY_LAG],
         [7D_AVERAGE_DECEASED_ELDERLY_AT_HOME_DAILY],
         [7D_AVERAGE_DECEASED_ELDERLY_AT_HOME_DAILY_LAG]
     FROM [VWSDEST].[ELDERLY_AT_HOME]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[ELDERLY_AT_HOME])
 END