-- 1) CREATE STORED PROCEDURE(S).....
 CREATE   PROCEDURE [DBO].[SP_G_Number_VR]
 AS
 BEGIN
     -- CALCULATE POSITIVE 7 DAILY SUM
     WITH CTE AS (
         SELECT 
             [DATE_OF_REPORT]
             ,[DATE_RANGE_START]
             ,CASE WHEN COUNT([TOTAL_REPORTED_INCREASE_PER_REGION]) OVER (PARTITION BY [VRCODE] ORDER BY [DATE_OF_REPORT] ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) = 7
                 THEN SUM(CAST([TOTAL_REPORTED_INCREASE_PER_REGION] AS FLOAT)) OVER (PARTITION BY [VRCODE] ORDER BY [DATE_OF_REPORT] ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)
                 ELSE NULL
             END AS [POSITIVE_DAILY_7D_SUM]
             ,[VRCODE]
         FROM [VWSDEST].[RESULTS_PER_REGION]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RESULTS_PER_REGION])
     )
     -- CALCULATE PERCENTUAL CHANGE BETWEEN WITH PREVIOUS 7D SUM
     INSERT INTO [VWSDEST].[G_NUMBER_VR] (
         [DATE_OF_REPORT]
         ,[DATE_RANGE_START]
         ,[VRCODE]
         ,[POSITIVE_DAILY_7D_SUM]
         ,[G_NUMBER]
     )
     SELECT 
         [DATE_OF_REPORT]
         ,[DATE_RANGE_START]
         ,[VRCODE]
         ,[POSITIVE_DAILY_7D_SUM]
         ,[DBO].[CALC_PERC_CHANGE]([POSITIVE_DAILY_7D_SUM], LAG([POSITIVE_DAILY_7D_SUM], 7, NULL) OVER (PARTITION BY [VRCODE] ORDER BY [DATE_OF_REPORT])) * 100 AS [G_NUMBER]
     FROM CTE
 END;