-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) INTER -> DEST.....
 CREATE   PROCEDURE [dbo].[SP_HOSPITAL_BED_OCCUPANCY]
 AS
 BEGIN
     INSERT INTO VWSDEST.HOSPITAL_BED_OCCUPANCY
         (   [DATE_OF_REPORT],
 	        [DATE_OF_REPORT_UNIX],
             [IC_BEDS_OCCUPIED_COVID],
             [IC_BEDS_OCCUPIED_NON_COVID],
             [IC_BEDS_OCCUPIED_COVID_PERCENTAGE],
             [NON_IC_BEDS_OCCUPIED_COVID],
             [IC_INFLUX_COVID],
             [NON_IC_INFLUX_COVID]
         )
     SELECT
         [DATUM] AS DATE_OF_REPORT,
         dbo.CONVERT_DATETIME_TO_UNIX(DATUM) AS DATE_OF_REPORT_UNIX,
         [IC_BEDDEN_COVID] AS IC_BEDS_OCCUPIED_COVID,
         [IC_BEDDEN_NON_COVID] AS IC_BEDS_OCCUPIED_NON_COVID,
         --If either IC_BEDDEN_COVID or IC_BEDDEN_NON_COVID equals NULL, NULL is the result of the line below
         ROUND((CAST([IC_BEDDEN_COVID] as DECIMAL)/([IC_BEDDEN_NON_COVID]+[IC_BEDDEN_COVID]) * 100.0),2) AS IC_BEDS_OCCUPIED_COVID_PERCENTAGE,
         [KLINIEK_BEDDEN] AS NON_IC_BEDS_OCCUPIED_COVID,
         [IC_NIEUWE_OPNAMES_COVID],
         [KLINIEK_NIEUWE_OPNAMES_COVID]
     FROM
        VWSINTER.LNAZ_HOSPITAL_BED_OCCUPANCY
     WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSINTER.LNAZ_HOSPITAL_BED_OCCUPANCY)
 END;