-- 1) CREATE STORED PROCEDURE(S): STAGING TO INTERMEDIATE.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_IL_RIVM_VACCINE_ADMINISTERED_LAST_WEEK_NL]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_VACCINE_ADMINISTERED_LAST_WEEK_NL] (
         [DATE_OF_REPORT],
         [DATE_FIRST_DAY],
         [VALUE_TYPE],
         [VALUE_NAME],
         [REPORT_STATUS],
         [VALUE]
     )
     SELECT
         [DBO].[TRY_CONVERT_TO_DATETIME]([DATE_OF_REPORT]), --dd-mm-yyyy
         [DBO].[TRY_CONVERT_TO_DATETIME]([DATE_FIRST_DAY]), --yyyy-mm-dd
         [VALUE_TYPE],
         [VALUE_NAME],
         [REPORT_STATUS],
         [VALUE]
     FROM
         [VWSSTAGE].[RIVM_VACCINE_ADMINISTERED_LAST_WEEK_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINE_ADMINISTERED_LAST_WEEK_NL])
 END;