CREATE PROCEDURE [dbo].[SP_INSERT_IL_RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY]
AS
BEGIN
    INSERT INTO [VWSINTER].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY] (
        [VERSION],
        [DATE_OF_REPORT],
        [DATE_OF_STATISTICS_WEEK_END],
        [AGE_GROUPS],
        [N_PARTICIPANTS],
        [PERC_COVID_SYMPTOMS]
    )
    SELECT
        [VERSION],
        CONVERT(DATETIME, [DATE_OF_REPORT], 102),
        CONVERT(DATETIME, [DATE_OF_STATISTICS_WEEK_END], 102),
        [AGE_GROUPS],
        NULLIF([N_PARTICIPANTS], 'NA'),
        CONVERT(DECIMAL(5,2), REPLACE(NULLIF([PERC_COVID_SYMPTOMS], 'NA'), ',', '.'))
    FROM
        [VWSSTAGE].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY]
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY])
END