-- 1) CREATE STORED PROCEDURE(S): STAGING TO INTERMEDIATE.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_IL_RIVM_VACCINATION_COVERAGES_NL]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_VACCINATION_COVERAGES_NL] (
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [BIRTH_YEAR],
         [AGE_GROUP],
         [VACCINATION_SERIES],
         [PERCENTAGE_COVERAGE]
     )
     SELECT
         [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_REPORT]),
         [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_STATISTICS]),
         TRIM([BIRTH_YEAR]),
         TRIM([AGEGROUP]),
         UPPER(TRIM([VACCINATION_SERIES])),
         REPLACE([PERCENTAGE_COVERAGE], ',', '.')
     FROM
         [VWSSTAGE].[RIVM_VACCINATION_COVERAGES_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINATION_COVERAGES_NL])
 END;