-- 1) CREATE STORED PROCEDURE(S): STAGING TO INTERMEDIATE.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_IL_RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD] (
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [PERC_COVID_SYMPTOMS],
         [MA_PERC_COVID_SYMPTOMS],
         [AGE_GROUPS]
     )
     SELECT
         [VERSION],
         [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_REPORT]),
         [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_STATISTICS]),
         CONVERT(FLOAT, IIF([PERC_COVID_SYMPTOMS] IN ('', 'NA'), NULL, Replace([PERC_COVID_SYMPTOMS], ',', '.'))),
         CONVERT(FLOAT, IIF([MA_PERC_COVID_SYMPTOMS] IN ('', 'NA'), NULL, Replace([MA_PERC_COVID_SYMPTOMS], ',', '.'))),
         [AGE_GROUPS]
     FROM
         [VWSSTAGE].[RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD])
 END;