-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_OL_RIVM_BOOSTER_SHOT_COVERAGES_NL]
 AS
 BEGIN
     INSERT INTO [VWSDEST].[RIVM_BOOSTER_SHOT_COVERAGES_NL] (
         [DATE_OF_STATISTICS],
         [DATE_OF_REPORT],
         [AGE_GROUP],
         [BIRTH_YEAR],
         [PERCENTAGE]
     )
     SELECT
         [DATE_OF_STATISTICS],
         [DATE_OF_REPORT],
         [AGE_GROUP],
         [BIRTH_YEAR],
         [PERCENTAGE_COVERAGE]
     FROM
         [VWSINTER].[RIVM_VACCINATION_COVERAGES_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINATION_COVERAGES_NL])
         AND [VACCINATION_SERIES] IN ('BOOSTER_COVERAGE', 'PRIMARY_PLUS_1')
 END;