-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_OL_RIVM_VACCINATION_SERIES_NL]
 AS
 BEGIN
     INSERT INTO [VWSDEST].[RIVM_VACCINATION_SERIES_NL] (
            [DATE_OF_REPORT],
            [DATE_OF_STATISTICS],
            [VACCINE_SERIE_EN],
            [TOTAL_VACCINATED],
            [TOTAL_VACCINATED_7DAYS],
            [CUMSUM_TOTAL_VACCINATED]
     )
     SELECT
        [DATE_OF_REPORT],
        [DATE_OF_STATISTICS],
        [VACCINE_SERIE] As VACCINE_SERIE_EN,
        [TOTAL_VACCINATED]
     FROM [VWSINTER].[RIVM_VACCINATION_SERIES_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINATION_SERIES_NL])
 END;