-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT. 
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_INTER_CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]
 AS
 BEGIN
   INSERT INTO [VWSINTER].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR] (
     [VERSION],
     [DATE_OF_REPORT],
     [DATE_OF_STATISTICS],
     [REGION_CODE],
     [REGION_LEVEL],
     [REGION_NAME],
     [BIRTH_YEAR],
     [VACCINATION_SERIE],
     [PERCENTAGE],
     [PERCENTAGE_LABEL]
   )
   SELECT
       CAST([VERSION] AS [INT]) AS [VERSION],
       CAST([DATE_OF_REPORT] AS [DATETIME]) AS [DATE_OF_REPORT],
       CAST([DATE_OF_STATISTICS] AS [DATETIME])  AS [DATE_OF_STATISTICS],
       [REGION_CODE],
       [REGION_LEVEL],
       [REGION_NAME],
       [BIRTH_YEAR],
       [VACCINATION_SERIE],
       --MAKE A SPLIT BETWEEN THE ACTUAL NUMBER AND WHEN A LABEL IS ASSIGNED. KEEP ORIGINAL SOURCE.\n",
       CASE
         WHEN [PERCENTAGE] IN ('<=5', '>=95', '9999', '9999.9') THEN NULL
         ELSE [PERCENTAGE]
         END AS [PERCENTAGE],
       CASE
         WHEN [PERCENTAGE] = '<=5' THEN [PERCENTAGE]
         WHEN [PERCENTAGE] = '>=95' THEN [PERCENTAGE]
         ELSE NULL
         END AS [PERCENTAGE_LABEL]
     FROM [VWSSTAGE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR])
 END;