-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT. 
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_INTER_CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN] (
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS_WEEK_START],
         [DATE_OF_STATISTICS_WEEK_END],
         [BIRTH_COHORT],
         [AGE_GROUP],
         [POPULATION_AGE_GROUP],
         [VACCINATION_CAMPAIGN],
         [RECEIVED],
         [COVERAGE]
     )
     SELECT
         dbo.TRY_CONVERT_TO_DATETIME([DATE_OF_REPORT]),
         dbo.TRY_CONVERT_TO_DATETIME([DATE_OF_STATISTICS_WEEK_START]),
         dbo.TRY_CONVERT_TO_DATETIME([DATE_OF_STATISTICS_WEEK_END]),
         [BIRTH_COHORT],
         -- HACK AS RIVM IS INCAPABLE OF PROVIDING AGE GROUPS NORMALLY
         (CASE WHEN [AGE_GROUP] = '5-nov' THEN '5-11' ELSE (CASE WHEN [AGE_GROUP] = 'dec-17' THEN '12-17' ELSE [AGE_GROUP] END) END) AS [AGE_GROUP],
         CAST(ISNULL(NULLIF(TRIM([POPULATION_AGE_GROUP]), ''), 0) AS INT),
         [VACCINATION_CAMPAIGN],
         ISNULL(TRY_CAST(TRIM([RECEIVED]) as INT),0)  AS [RECEIVED],
         CAST(
         CASE
         WHEN [COVERAGE] IN ('9999', '9999.9', 'NULL', '') THEN NULL
         ELSE [COVERAGE]
         END AS NUMERIC(5,2))
     FROM [VWSSTAGE].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[CIMS_VACCINATED_PER_AGE_GROUP_CAMPAIGN]);
 END;