-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_OL_RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD]
 AS
 BEGIN
     INSERT INTO [VWSDEST].[RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD] (
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [PERC_COVID_SYMPTOMS],
         [MA_PERC_COVID_SYMPTOMS],
         [AGE_GROUPS]
     )
     SELECT
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [PERC_COVID_SYMPTOMS],
         [MA_PERC_COVID_SYMPTOMS],
         [AGE_GROUPS]
     FROM
         [VWSINTER].[RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD])
 END;