CREATE PROCEDURE [dbo].[SP_INSERT_IL_RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY]
AS
BEGIN
    INSERT INTO [VWSINTER].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY] (
        [DATE_OF_REPORT],
        [DATE_OF_STATISTICS_WEEK_END],
        [AGE_GROUPS],
        [N_PARTICIPANTS],
        [PERC_COVID_SYMPTOMS]
    )
    SELECT
        [DATE_OF_REPORT],
        [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_REPORT]),
        [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_STATISTICS_WEEK_END]),
        [AGE_GROUPS],
        CONVERT(INT, IIF([N_PARTICIPANTS] IN ('', 'NA'), NULL, Replace([N_PARTICIPANTS], ',', '.'))),
        CONVERT(FLOAT, IIF([PERC_COVID_SYMPTOMS] IN ('', 'NA'), NULL, Replace([PERC_COVID_SYMPTOMS], ',', '.')))
    FROM
        [VWSSTAGE].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY]
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY])
END