CREATE PROCEDURE [dbo].[SP_INSERT_IL_RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY]
AS
BEGIN
    INSERT INTO [VWSINTER].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY] (
        [VERSION],
        [DATE_OF_REPORT],
        [DATE_OF_STATISTICS_WEEK_END],
        [AGE_GROUPS],
        [N_PARTICIPANTS],
        [PERC_COVID_SYMPTOMS]
    )
    SELECT
        [VERSION],
        [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_REPORT]),
        [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_STATISTICS_WEEK_END]),
        [AGE_GROUPS],
        [N_PARTICIPANTS],
        CONVERT(DECIMAL(5,2), REPLACE([PERC_COVID_SYMPTOMS], ',', '.'))
    FROM
        [VWSSTAGE].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY]
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY])
END