CREATE PROCEDURE [dbo].[SP_INSERT_OL_RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY]
AS
BEGIN
    INSERT INTO [VWSDEST].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY] (
        [VERSION],
        [DATE_OF_REPORT],
        [DATE_OF_STATISTICS_WEEK_END],
        [AGE_GROUPS],
        [N_PARTICIPANTS],
        [PERC_COVID_SYMPTOMS]
    )
    SELECT
        [VERSION],
        [DATE_OF_REPORT],
        [DATE_OF_STATISTICS_WEEK_END],
        [AGE_GROUPS],
        [N_PARTICIPANTS],
        [PERC_COVID_SYMPTOMS]
    FROM
        [VWSINTER].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY]
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_WEEKLY])
END