-- 1) CREATE STORED PROCEDURE(S): STAGING TO INTERMEDIATE.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_IL_RIVM_VACCINATION_SERIES_NL]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_VACCINATION_SERIES_NL] (
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [VACCINE_SERIE],
         [TOTAL_VACCINATED]
     )
     SELECT
         CAST([VERSION] as INT) as [VERSION],
         [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_REPORT]),
         [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_STATISTICS]),
         UPPER(TRIM([VACCINE_SERIE])),
         CAST([TOTAL_VACCINATED] as INT) as [TOTAL_VACCINATED]
     FROM
         [VWSSTAGE].[RIVM_VACCINATION_SERIES_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINATION_SERIES_NL])
 END;