-- 1) CREATE STORED PROCEDURE(S): STAGING TO INTERMEDIATE.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_IL_RIVM_VACCINATION_PLANNED_NL]
 AS
 BEGIN
     WITH CTE AS (
         SELECT
             [KEY],
             [VALUE] 
         FROM
             [VWSSTAGE].[RIVM_VACCINATION_PLANNED_NL]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINATION_PLANNED_NL])
             AND UPPER([CATEGORY]) = 'VACCINE_ADMINISTERED_PLANNED'
     )
     INSERT INTO [VWSINTER].[RIVM_VACCINATION_PLANNED_NL] (
         [DOSES],
         [DATE_OF_STATISTICS_START],
         [DATE_OF_STATISTICS_END]
     )
     SELECT
         (SELECT [VALUE] FROM CTE WHERE UPPER([KEY]) = 'DOSES'),
         (SELECT [dbo].[TRY_CONVERT_TO_DATETIME]([VALUE]) FROM CTE WHERE UPPER([KEY]) = 'DATE_START_UNIX'),
         (SELECT [dbo].[TRY_CONVERT_TO_DATETIME]([VALUE]) FROM CTE WHERE UPPER([KEY]) = 'DATE_END_UNIX')
     FROM
         CTE
 END;