-- 1) CREATE STORED PROCEDURE(S): STAGING TO INTERMEDIATE.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_IL_RIVM_VACCINATION_CAMPAIGNS_NL]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_VACCINATION_CAMPAIGNS_NL] (
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [CAMPAIGN],
         [TOTAL_VACCINATED]
     )
     SELECT
         [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_REPORT]),
         [dbo].[TRY_CONVERT_TO_DATETIME]([DATE_OF_STATISTICS]),
         UPPER(TRIM([CAMPAIGN])),
         [TOTAL_VACCINATED]
     FROM
         [VWSSTAGE].[RIVM_VACCINATION_CAMPAIGNS_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINATION_CAMPAIGNS_NL])
 END;