-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT. 
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_INTER_CIMS_VACCINATED_AGE_GROUP]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[CIMS_VACCINATED_AGE_GROUP] (
         [DATE_OF_REPORT]
         ,[DATE_OF_STATISTICS_WEEK_START]
         ,[DATE_OF_STATISTICS_WEEK_END]
         ,[BIRTH_COHORT]
         ,[VACCINATION_ALL]
         ,[VACCINATION_COVERAGE_ALL]
         ,[VACCINATION_COMPLETED]
         ,[VACCINATION_COVERAGE_COMPLETED]
     )
     SELECT
         [DATE_OF_REPORT] AS [DATE_OF_REPORT],
         [DATE_OF_STATISTICS_WEEK_START] AS [DATE_OF_STATISTICS_WEEK_START],
         [DATE_OF_STATISTICS_WEEK_END] AS [DATE_OF_STATISTICS_WEEK_END],
         [BIRTH_COHORT] AS [BIRTH_COHORT],
         [RECEIVED_PARTIAL_VACCINATION] AS [RECEIVED_PARTIAL_VACCINATION],
         [VACCINATION_COVERAGE_PARTLY] AS [VACCINATION_COVERAGE_PARTLY],
         [RECEIVED_COMPLETE_VACCINATION] AS [RECEIVED_COMPLETE_VACCINATION],
         CASE
         WHEN [VACCINATION_COVERAGE_COMPLETED] IN ('9999', '9999.9', 'NULL', '') THEN NULL
         ELSE [VACCINATION_COVERAGE_COMPLETED]
         END AS [VACCINATION_COVERAGE_COMPLETED]
     FROM [VWSSTAGE].[CIMS_VACCINATED_AGE_GROUP]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[CIMS_VACCINATED_AGE_GROUP]);
 END;