-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_OL_RIVM_VACCINATION_SHOT_COVERAGES_NL]
 AS
 BEGIN
     WITH CTE AS (
         SELECT
             [DATE_OF_STATISTICS],
             [DATE_OF_REPORT],
             [AGE_GROUP],
             [BIRTH_YEAR],
             [VACCINATION_SERIES],
             [PERCENTAGE_COVERAGE]
         FROM
             [VWSINTER].[RIVM_VACCINATION_COVERAGES_NL]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINATION_COVERAGES_NL])
     )
     INSERT INTO [VWSDEST].[RIVM_VACCINATION_SHOT_COVERAGES_PER_CAMPAIGN_NL] (
         [DATE_OF_STATISTICS],
         [DATE_OF_REPORT],
         [AGE_GROUP],
         [BIRTH_YEAR],
         [PERCENTAGE_COMPLETED],
         [PERCENTAGE_PARTLY]
     )
     SELECT
         [DATE_OF_STATISTICS],
         [DATE_OF_REPORT],
         [AGE_GROUP],
         [BIRTH_YEAR],
         [PRIMARY_COMPLETED],
         [PRIMARY_STARTED]
     FROM CTE
     PIVOT (
         MAX([PERCENTAGE_COVERAGE])
         FOR [VACCINATION_SERIES] 
         IN (
             [PRIMARY_STARTED],
             [PRIMARY_COMPLETED]
         )
     ) PivotTable
 END;