-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_OL_RIVM_VACCINATION_SHOTS_PLANNED_NL]
 AS
 BEGIN
     INSERT INTO [VWSDEST].[RIVM_VACCINATION_SHOTS_PLANNED_NL] (
         [DOSES],
         [DATE_OF_STATISTICS_START],
         [DATE_OF_STATISTICS_END] 
     )
     SELECT
         [DOSES],
         [DATE_OF_STATISTICS_START],
         [DATE_OF_STATISTICS_END] 
     FROM
         [VWSINTER].[RIVM_VACCINATION_PLANNED_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINATION_PLANNED_NL])
 END;