-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT. 
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_INHABITANTS_PER_AGEGROUP]
 AS
 BEGIN
     INSERT INTO [VWSSTATIC].[CBS_INHABITANTS_PER_AGEGROUP]
     (
 		[GESLACHT], 
 		[LEEFTIJD], 
 		[BURGERLIJKESTAAT], 
 		[REGIOS], 
 		[PERIODEN], 
 		[BEVOLKINGOP1JANUARI_1], 
 		[GEMIDDELDEBEVOLKING_2]
 	)
     SELECT
         [GESLACHT],
         [LEEFTIJD],
         [BURGERLIJKESTAAT],
         [REGIOS],
         [PERIODEN],
         [BEVOLKINGOP1JANUARI_1],
         CAST([GEMIDDELDEBEVOLKING_2] AS FLOAT)
     FROM [VWSSTAGE].[CBS_INHABITANTS_PER_AGEGROUP]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[CBS_INHABITANTS_PER_AGEGROUP])
 END;