-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_OL_RIVM_VACCINATION_SHOT_COVERAGES_PER_CAMPAIGN_NL]
 AS
 BEGIN
     WITH CTE AS (
         SELECT
             [DATE_OF_STATISTICS],
             [DATE_OF_REPORT],
             [AGE_GROUP],
             [BIRTH_YEAR],
             [VACCINATION_CAMPAIGN],
             [PERCENTAGE_COVERAGE]
         FROM
             [VWSINTER].[RIVM_VACCINATION_COVERAGES_PER_CAMPAIGN_NL]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINATION_COVERAGES_PER_CAMPAIGN_NL])
     )
     INSERT INTO [VWSDEST].[RIVM_VACCINATION_SHOT_COVERAGES_NL_AUTUMN_2022] (
         [DATE_OF_STATISTICS],
         [DATE_OF_REPORT],
         [AGE_GROUP],
         [BIRTH_YEAR],
         [AUTUMN_2022_VACCINATED],
         [PERCENTAGE_PARTLY],
         [PERCENTAGE_COMPLETED]
     )
     SELECT
         [DATE_OF_STATISTICS],
         [DATE_OF_REPORT],
         [AGE_GROUP],
         [BIRTH_YEAR],
         [202209_CAMPAIGN],
         NULL AS [PERCENTAGE_PARTLY], -- not used anymore
         NULL AS [PERCENTAGE_COMPLETED] -- not used anymore
     FROM CTE
     PIVOT (
         MAX([PERCENTAGE_COVERAGE])
         FOR [VACCINATION_CAMPAIGN] 
         IN (
             [202209_CAMPAIGN]
         )
     ) PivotTable
 END;