-- 1) CREATE STORED PROCEDURE(S): STAGING TO INTERMEDIATE.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_IL_RIVM_INFECTIE_RADAR_PERCENTAGE_PER_AGEGROUP_DAILY]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD] (
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [AGE_GROUPS],
         [N_PARTICIPANTS],
         [PERC_COVID_SYMPTOMS]
     )
     SELECT
         [VERSION],
         CONVERT(DATETIME, [DATE_OF_REPORT], 102),
         CONVERT(DATETIME, [DATE_OF_STATISTICS], 102),
         [AGE_GROUPS],
         NULLIF([N_PARTICIPANTS], 'NA'),
         CONVERT(DECIMAL(5,2), REPLACE(NULLIF([PERC_COVID_SYMPTOMS], 'NA'), ',', '.'))
     FROM
         [VWSSTAGE].[RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_INFECTIE_RADAR_TREND_PER_LEEFTIJD])
 END;