CREATE   PROCEDURE dbo.SP_INHABITANTS_PER_MUNICIPALITY_STAGE_TO_STATIC
 AS
 BEGIN
 
   INSERT INTO [VWSSTATIC].[INHABITANTS_PER_MUNICIPALITY] (
              [REGIO], 
              [GMCODE], 
              [VRCODE], 
              [VRNAME], 
              [INHABITANTS], 
              [DATE_LAST_INSERTED]
          )
      SELECT  ISNULL(B.[GM_NAME_NEW],A.[REGION]),
              ISNULL(B.[GM_CODE_NEW],A.[GM_CODE]),
              ISNULL(B.[VR_CODE],A.[VR_CODE]),
              ISNULL(B.[VR_NAME],A.[VR_NAME]),
              CAST(ROUND(SUM(CAST(A.[INHABITANTS] AS INT) * ISNULL(B.[SHARES],1.0)),0) AS INT),
              MAX(A.[DATE_LAST_INSERTED])
      FROM [VWSSTAGE].[INHABITANTS_PER_MUNICIPALITY] A
      LEFT JOIN (
          SELECT 
              * 
          FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING] 
          WHERE [ACTIVE]=1
              AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING])  
      ) B ON A.[GM_CODE] = B.[GM_CODE_ORIGINAL]
      WHERE A.[DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[INHABITANTS_PER_MUNICIPALITY])    
      GROUP BY ISNULL(B.[GM_NAME_NEW],A.[REGION]),
              ISNULL(B.[GM_CODE_NEW],A.[GM_CODE]),
              ISNULL(B.[VR_CODE],A.[VR_CODE]),
              ISNULL(B.[VR_NAME],A.[VR_NAME])
  END