CREATE   PROCEDURE [dbo].[SP_INHABITANTS_PER_REGION_STATIC]
 AS
 BEGIN
      INSERT INTO [VWSSTATIC].[CBS_INHABITANTS_PER_MUNICIPALITY]  (
          [VRCODE], 
          [GMCODE], 
          [INHABITANTS]
      )
      SELECT
          ISNULL(B.[VR_CODE], [CODE_42]),
          ISNULL(B.[GM_CODE_NEW], [CODE_1]),
          CAST(ROUND(SUM(CAST(A.[INWONERTAL_50] AS INT) * ISNULL(B.[SHARES],1.0)),0) AS INT)
      FROM [VWSSTAGE].[CBS_INHABITANTS_PER_MUNICIPALITY] A
          LEFT JOIN (
                      SELECT 
                          * 
                      FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING] 
                      WHERE [ACTIVE] = 1 
                          AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING])  
                  ) B ON A.[CODE_1] = B.[GM_CODE_ORIGINAL]
      WHERE A.[DATE_LAST_INSERTED] = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSSTAGE].[CBS_INHABITANTS_PER_MUNICIPALITY])
      GROUP BY ISNULL(B.[VR_CODE],[CODE_42]), ISNULL(B.[GM_CODE_NEW],[CODE_1])
  END