-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
 CREATE   PROCEDURE [dbo].[SP_INSERT_OL_RIVM_VACCINE_ADMINISTERED_LAST_WEEK_NL]
 AS
 BEGIN
     INSERT INTO [VWSDEST].[RIVM_VACCINE_ADMINISTERED_LAST_WEEK_NL] (
         [DATE_OF_REPORT],
         [DATE_FIRST_DAY],
         [VALUE_TYPE],
         [VALUE_NAME],
         [REPORT_STATUS],
         [VALUE]
     )
     SELECT
         [DATE_OF_REPORT],
         [DATE_FIRST_DAY],
         [VALUE_TYPE],
         [VALUE_NAME],
         [REPORT_STATUS],
         [VALUE]
     FROM
         [VWSINTER].[RIVM_VACCINE_ADMINISTERED_LAST_WEEK_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINE_ADMINISTERED_LAST_WEEK_NL])
 END;