-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
 -- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
 
 -- Move national data from staging to intermediate table.
 
 -- 1) CREATE STORE PROCEDURE(S) STAGE -> INTER.....
 CREATE   PROCEDURE [DBO].[SP_LNAZ_HOSPITAL_BED_OCCUPANCY_2023_STAGE_TO_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[LNAZ_HOSPITAL_BED_OCCUPANCY_2023] (
         [DATUM],
         [IC_CAPACITEIT_TOTAAL],
         [KLINIEK_CAPACITEIT_TOTAAL],
         [IC_BEZETTING_COVID],
         [IC_BEZETTING_COVID_INTERNATIONAAL],
         [IC_BEZETTING_ONTLABELD],
         [IC_BEZETTING_NONCOVID],
         [KLINIEK_BEZETTING_COVID],
         [KLINIEK_BEZETTING_ONTLABELD],
         [KLINIEK_BEZETTING_NONCOVID],
         [IC_OPNAMES_COVID],
         [KLINIEK_OPNAMES_COVID]
     )
     SELECT
         --- conversion of date in dd-mm-yyyy format ---
         CONVERT(DATETIME, [DATUM], 105),
         -- allow empty values and make them null
         IIF([IC_CAPACITEIT_TOTAAL] IN ('', 'NA'), NULL, TRIM([IC_CAPACITEIT_TOTAAL])),
         IIF([KLINIEK_CAPACITEIT_TOTAAL] IN ('', 'NA'), NULL, TRIM([KLINIEK_CAPACITEIT_TOTAAL])),
         IIF([IC_BEZETTING_COVID] IN ('', 'NA'), NULL, TRIM([IC_BEZETTING_COVID])),
         IIF([IC_BEZETTING_COVID_INTERNATIONAAL] IN ('', 'NA'), NULL, TRIM([IC_BEZETTING_COVID_INTERNATIONAAL])),
         IIF([IC_BEZETTING_ONTLABELD] IN ('', 'NA'), NULL, TRIM([IC_BEZETTING_ONTLABELD])),
         IIF([IC_BEZETTING_NONCOVID] IN ('', 'NA'), NULL, TRIM([IC_BEZETTING_NONCOVID])),
         IIF([KLINIEK_BEZETTING_COVID] IN ('', 'NA'), NULL, TRIM([KLINIEK_BEZETTING_COVID])),
         IIF([KLINIEK_BEZETTING_ONTLABELD] IN ('', 'NA'), NULL, TRIM([KLINIEK_BEZETTING_ONTLABELD])),
         IIF([KLINIEK_BEZETTING_NONCOVID] IN ('', 'NA'), NULL, TRIM([KLINIEK_BEZETTING_NONCOVID])),
         IIF([IC_OPNAMES_COVID] IN ('', 'NA'), NULL, TRIM([IC_OPNAMES_COVID])),
         IIF([KLINIEK_OPNAMES_COVID] IN ('', 'NA'), NULL, TRIM([KLINIEK_OPNAMES_COVID]))
     FROM 
         [VWSSTAGE].[LNAZ_HOSPITAL_BED_OCCUPANCY_2023]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[LNAZ_HOSPITAL_BED_OCCUPANCY_2023])
 END;