-- COPYRIGHT (C) 2022 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE     PROCEDURE [DBO].[SP_MERGE_MOVE_STATIC_CBS_RWZI]
 AS
 BEGIN
     WITH COMBINED_CBS_RWZI
     AS (
         SELECT 
             CAST([RWZI_CODE] AS INT) AS [RWZI_CODE]
             ,[RWZI_NAAM]
             ,CONVERT(DATE,[STARTDATUM],105) AS [STARTDATUM]
             ,CASE 
                 WHEN LEN([EINDDATUM]) = 0 THEN CAST('9999-12-31' AS DATE) 
                 ELSE CONVERT(DATE,[EINDDATUM],105) 
             END AS [EINDDATUM]
             ,[INWONERS]
             ,[REGIO_TYPE]
             ,[REGIO_CODE]
             ,[REGIO_NAAM]
             ,[AANDEEL]  
             , 'base' AS [TYPE]
         FROM [VWSSTAGE].[CBS_POPULATION_RWZI]
         WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSSTAGE.CBS_POPULATION_RWZI) AND LOWER([TOELICHTING]) = 'definitief'
         UNION
         SELECT 
             CAST([RWZI_CODE] AS INT)                AS [RWZI_CODE]
             ,[RWZI_NAAM]
             ,CONVERT(DATE,[STARTDATUM],105) AS [STARTDATUM]
             ,CASE WHEN LEN([EINDDATUM]) = 0 THEN CAST('9999-12-31' AS DATE) ELSE
             
                 CONVERT(DATE,[EINDDATUM],105) 
                 END
             ,[INWONERS]
             ,[REGIO_TYPE]
             ,[REGIO_CODE]
             ,[REGIO_NAAM]
             ,[AANDEEL]    
             ,'mutation' AS [TYPE]
         FROM [VWSSTAGE].[CBS_POPULATION_RWZI_MUTATIONS]
         WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSSTAGE.CBS_POPULATION_RWZI_MUTATIONS)
     ),
 SELECTED_CTE AS (
     SELECT	 [RWZI_CODE]
 			,[RWZI_NAAM]
 			,CASE
 				-- FOR THE RWZI / REGION COMBINATIONS THAT START AT 1-1-2021, CHANGE START DATE TO 1-1-2020
 				WHEN
 					-- ONLY SELECT RWZI / REGION COMBINATIONS THAT START AT 1-1-2021
 					MIN(STARTDATUM) OVER (PARTITION BY RWZI_CODE,REGIO_CODE) = CAST('2021-01-01' AS DATE)
 					-- FOR THE RWZI / REGION COMBINATION WHERE THE DATE IS ADJUSTED, ONLY ADJUST DATE 1-1-2021 TO 1-1-2020
 					AND MIN(STARTDATUM) OVER (PARTITION BY RWZI_CODE,REGIO_CODE, STARTDATUM) = CAST('2021-01-01' AS DATE)
 				THEN CAST('2020-01-01' AS DATE)
 				ELSE [STARTDATUM]
 			END                         AS [STARTDATUM]
 			,ISNULL([EINDDATUM], CAST('9999-12-31' AS DATE)) AS [EINDDATUM]
 			,[INWONERS]
 			,[REGIO_TYPE]
 			,[REGIO_CODE]
 			,[REGIO_NAAM]
 			,PARSE(REPLACE([AANDEEL], '%', '') AS DECIMAL(19,3) USING 'nl-NL') AS [AANDEEL]
 			--,[TYPE]
     FROM 
         COMBINED_CBS_RWZI
     WHERE 
         RWZI_CODE > 0
 
 )
     INSERT INTO [VWSSTATIC].CBS_POPULATION_RWZI (
         [RWZI_CODE]
         ,[RWZI_NAAM]
         ,[STARTDATUM]
         ,[EINDDATUM]
         ,[INWONERS]
         ,[REGIO_TYPE]
         ,[REGIO_CODE]
         ,[REGIO_NAAM]
         ,[AANDEEL]
       )
     SELECT 
         A.[RWZI_CODE]
         ,A.[RWZI_NAAM]
         ,A.[STARTDATUM]
         ,A.[EINDDATUM]
         ,MAX(A.[INWONERS]) AS INWONERS
         ,A.[REGIO_TYPE]
         ,ISNULL(B.[GM_CODE_NEW],A.[REGIO_CODE]) AS REGIO_CODE
         ,ISNULL(B.[GM_NAME_NEW],A.[REGIO_NAAM]) AS REGIO_NAAM
         ,SUM(A.[AANDEEL] * ISNULL(B.[SHARES], 1.0)) AS AANDEEL
         --,[TYPE]
     FROM SELECTED_CTE A
 		    LEFT JOIN   (
                     SELECT 
                         * 
                     FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING] 
                     WHERE [ACTIVE]=1
                         AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING])  
                 ) B ON A.[REGIO_CODE] = B.[GM_CODE_ORIGINAL]
 	GROUP BY A.[RWZI_CODE]
 			,A.[RWZI_NAAM]
 			,A.[STARTDATUM]
 			,A.[EINDDATUM]
 			,A.[REGIO_TYPE]
 			,ISNULL(B.[GM_CODE_NEW],A.[REGIO_CODE]) 
 			,ISNULL(B.[GM_NAME_NEW],A.[REGIO_NAAM]) 
 END