-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE   PROCEDURE [DBO].[SP_MUNICIPALITY_RWZI_COUPLING_STAGE_TO_STATIC]
 AS
 BEGIN
 
 INSERT INTO [VWSSTATIC].[MUNICIPALITY_RWZI_COUPLING] (
     [VERSIE],
     [DATUM_BESTAND],
     [DATUM_HERINDELING],
     [REGIO_CODE],
     [REGIO_CODE_INT],
     [REGIO_NAAM],
     [RWZI_CODE],
     [RWZI_NAAM],
     [ACTIEF]
     )
 SELECT
     [VERSIE],
     CONVERT(DATETIME, [DATUM_BESTAND], 102),
     CONVERT(DATETIME, [DATUM_HERINDELING], 102),
     [REGIO_CODE],
     [REGIO_CODE_INT],
     [REGIO_NAAM],
     [RWZI_CODE],
     [RWZI_NAAM],
     [ACTIEF]
 FROM [VWSSTAGE].[MUNICIPALITY_RWZI_COUPLING]
 WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[MUNICIPALITY_RWZI_COUPLING])
 END;