
 CREATE   PROCEDURE [dbo].[SP_NURSING_HOMES_TOTALS_ARCHIVED_20230126] AS
 BEGIN
     TRUNCATE TABLE [VWSARCHIVE].[NURSING_HOMES_TOTALS_ARCHIVED_20230126]
 
     INSERT INTO [VWSARCHIVE].[NURSING_HOMES_TOTALS_ARCHIVED_20230126] (
             [ID],
             [DATE_OF_REPORT],
             [DATE_OF_REPORT_UNIX],
             [INFECTED_NURSERY_DAILY],
             [DECEASED_NURSERY_DAILY],
             [TOTAL_NEW_REPORTED_LOCATIONS],
             [TOTAL_REPORTED_LOCATIONS],
             [DATE_LAST_INSERTED],
             [DATE_RANGE_START],
             [DATE_OF_REPORTS_LAG],
             [DATE_RANGE_START_LAG],
             [7D_AVERAGE_TOTAL_INFECTED],
             [7D_AVERAGE_TOTAL_INFECTED_LAG],
             [7D_AVERAGE_TOTAL_DECEASED],
             [7D_AVERAGE_TOTAL_DECEASED_LAG]
     )
     SELECT 
             [ID],
             [DATE_OF_REPORT],
             [DATE_OF_REPORT_UNIX],
             [INFECTED_NURSERY_DAILY],
             [DECEASED_NURSERY_DAILY],
             [TOTAL_NEW_REPORTED_LOCATIONS],
             [TOTAL_REPORTED_LOCATIONS],
             [DATE_LAST_INSERTED],
             [DATE_RANGE_START],
             [DATE_OF_REPORTS_LAG],
             [DATE_RANGE_START_LAG],
             [7D_AVERAGE_TOTAL_INFECTED],
             [7D_AVERAGE_TOTAL_INFECTED_LAG],
             [7D_AVERAGE_TOTAL_DECEASED],
             [7D_AVERAGE_TOTAL_DECEASED_LAG]
     FROM [VWSDEST].[NURSING_HOMES_TOTALS]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[NURSING_HOMES_TOTALS])
 END