-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE    PROCEDURE [dbo].[SP_NICE_HOSPITAL_INTER]
  AS
  BEGIN
  
  -- Zet de Date_Last_Inserted in een variabele
 DECLARE @DateTimeNow AS DateTime = GETDATE()
 
  -- MAIN SELECT AND INSERT INTO STATEMENT. FILTERED VALUES ON MAX DATELASTINSERTED.
  -- MOVE INFECTIOUS DATA FROM STAGING TO INTERMEDIATE TABLE.
  INSERT INTO [VWSINTER].[NICE_HOSPITAL](
  	[DATE_OF_REPORT]
      ,[DATE_OF_STATISTICS]
      ,[MUNICIPALITY_CODE]
      ,[MUNICIPALITY_NAME]
      ,[SECURITY_REGION_CODE]
      ,[SECURITY_REGION_NAME]
      ,[REPORTED]
      ,[HOSPITALIZED]
      ,DATE_LAST_INSERTED
  )
      SELECT
          CAST(A.[DATE_OF_REPORT] AS [DATETIME]) AS [DATE_OF_REPORT]
          ,CAST(A.[DATE_OF_STATISTICS] AS [DATETIME]) AS [DATE_OF_STATISTICS]
          ,ISNULL(B.[GM_CODE_NEW], A.[MUNICIPALITY_CODE])
          ,ISNULL(B.[GM_NAME_NEW], A.[MUNICIPALITY_NAME])
          ,ISNULL(B.[VR_CODE], A.[SECURITY_REGION_CODE])
          ,ISNULL(B.[VR_NAME], A.[SECURITY_REGION_NAME])
          ,CAST(SUM(CAST([HOSPITAL_ADMISSION_NOTIFICATION] AS [FLOAT]) * ISNULL(B.[SHARES], 1.0)) AS [INT]) AS [REPORTED]
          ,CAST(SUM(CAST([HOSPITAL_ADMISSION] AS [FLOAT]) * ISNULL(B.[SHARES], 1.0)) AS [INT]) AS [HOSPITALIZED]
          ,@DateTimeNow as Date_Last_Inserted
      FROM [VWSSTAGE].[NICE_HOSPITAL] A
      LEFT JOIN (
          SELECT 
              * 
          FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING] 
          WHERE [ACTIVE]=1
              AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING])  
      ) B ON A.[MUNICIPALITY_CODE] = B.[GM_CODE_ORIGINAL]
      WHERE A.[DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[NICE_HOSPITAL])
      GROUP BY ISNULL(B.[GM_CODE_NEW], A.[MUNICIPALITY_CODE])
              ,ISNULL(B.[GM_NAME_NEW], A.[MUNICIPALITY_NAME])
              ,ISNULL(B.[VR_CODE], A.[SECURITY_REGION_CODE])
              ,ISNULL(B.[VR_NAME], A.[SECURITY_REGION_NAME])
              ,A.[DATE_OF_REPORT]
              ,A.[DATE_OF_STATISTICS]
 
  INSERT INTO [VWSINTER].[NICE_HOSPITAL](
  	[DATE_OF_REPORT]
      ,[DATE_OF_STATISTICS]
      ,[MUNICIPALITY_CODE]
      ,[MUNICIPALITY_NAME]
      ,[SECURITY_REGION_CODE]
      ,[SECURITY_REGION_NAME]
      ,[REPORTED]
      ,[HOSPITALIZED]
      ,DATE_LAST_INSERTED
  )
      SELECT
          CAST(A.[DATE_OF_REPORT] AS [DATETIME]) AS [DATE_OF_REPORT]
          ,CAST(A.[DATE_OF_STATISTICS] AS [DATETIME]) AS [DATE_OF_STATISTICS]
          ,ISNULL(B.[GM_CODE_NEW], A.[MUNICIPALITY_CODE])
          ,ISNULL(B.[GM_NAME_NEW], A.[MUNICIPALITY_NAME])
          ,ISNULL(B.[VR_CODE], A.[SECURITY_REGION_CODE])
          ,ISNULL(B.[VR_NAME], A.[SECURITY_REGION_NAME])
          ,CAST(SUM(CAST([HOSPITAL_ADMISSION_NOTIFICATION] AS [FLOAT]) * ISNULL(B.[SHARES], 1.0)) AS [INT]) AS [REPORTED]
          ,CAST(SUM(CAST([HOSPITAL_ADMISSION] AS [FLOAT]) * ISNULL(B.[SHARES], 1.0)) AS [INT]) AS [HOSPITALIZED]
          ,@DateTimeNow as Date_Last_Inserted
      FROM [VWSSTATIC].[NICE_HOSPITAL] A
      LEFT JOIN (
          SELECT 
              * 
          FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING] 
          WHERE [ACTIVE]=1
              AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING])  
      ) B ON A.[MUNICIPALITY_CODE] = B.[GM_CODE_ORIGINAL]
      WHERE CAST(A.DATE_LAST_INSERTED as DATE) = (SELECT MAX(CAST(DATE_LAST_INSERTED as DATE)) FROM [VWSSTATIC].[NICE_HOSPITAL])
      GROUP BY ISNULL(B.[GM_CODE_NEW], A.[MUNICIPALITY_CODE])
              ,ISNULL(B.[GM_NAME_NEW], A.[MUNICIPALITY_NAME])
              ,ISNULL(B.[VR_CODE], A.[SECURITY_REGION_CODE])
              ,ISNULL(B.[VR_NAME], A.[SECURITY_REGION_NAME])
              ,A.[DATE_OF_REPORT]
              ,A.[DATE_OF_STATISTICS]
 
  END;