-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) STAGE -> INTER.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL_STAGE_TO_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL] (
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [BIRTH_COHORT],
         [POPULATION_PER_AGE_GROUP],
         [BASIC_SERIE_AMOUNT],
         [BOOSTER_TYPE],
         [CUMULATIVE_AMOUNT],
         [VACCINATION_COVERAGE_PER_AGE_GROUP],
         [VACCINATION_COVERAGE_VS_BASIC_SERIE]
     )
     SELECT
         CAST([VERSION] AS [INT]),
         CONVERT([DATETIME], [DATE_OF_REPORT], 105),
         CONVERT([DATETIME], [DATE_OF_STATISTICS], 105),
         [BIRTH_COHORT],
         CAST([POPULATION_PER_AGE_GROUP] AS [BIGINT]),
         CAST([BASIC_SERIE_AMOUNT] AS [BIGINT]),
         LOWER(TRIM([BOOSTER_TYPE])),
         CAST([CUMULATIVE_AMOUNT] AS [BIGINT]),
         CAST([VACCINATION_COVERAGE_PER_AGE_GROUP] AS [FLOAT]),
         CAST([VACCINATION_COVERAGE_VS_BASIC_SERIE] AS [FLOAT])
     FROM 
         [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL])
 END;