-- Move cluster information data from staging to intermediate table.
CREATE   PROCEDURE [dbo].[SP_RIVM_CLUSTERS_INFECTED_PEOPLE_INTER]
AS
BEGIN
    INSERT INTO VWSINTER.RIVM_CLUSTERS_INFECTED_PEOPLE
    (
        DATE_OF_REPORT,
        DATE_STATISTICS,
        SECURITY_REGION_NAME,
        SECURITY_REGION_CODE,
        ACTIVE_CLUSTERS,
        AVERAGE_SIZE,
        MEDIAN_SIZE,
        MIN_SIZE,
        MAX_SIZE
    )
    SELECT 
        DATE_OF_REPORT,
        DATE_STATISTICS,
        SECURITY_REGION_NAME,
        SECURITY_REGION_CODE,
        ACTIVE_CLUSTERS,
        CAST(NULLIF(AVERAGE_SIZE, '') AS DECIMAL(16,2)) AS AVERAGE_SIZE,
        CAST(NULLIF(MEDIAN_SIZE, '') AS DECIMAL(16,2)) AS MEDIAN_SIZE,
        CAST(NULLIF(MIN_SIZE, '') AS DECIMAL(16,2)) AS MIN_SIZE,
        CAST(NULLIF(MAX_SIZE, '') AS DECIMAL(16,2)) AS MAX_SIZE
    FROM 
       VWSSTAGE.RIVM_CLUSTERS_INFECTED_PEOPLE
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from VWSSTAGE.RIVM_CLUSTERS_INFECTED_PEOPLE)
END;