
 CREATE   PROCEDURE [dbo].[SP_RIVM_BOOSTER_SHOT_COVERAGES_NL_ARCHIVED_20220904] AS
 BEGIN
     TRUNCATE TABLE [VWSARCHIVE].[RIVM_BOOSTER_SHOT_COVERAGES_NL_ARCHIVED_20220904]
 
     INSERT INTO [VWSARCHIVE].[RIVM_BOOSTER_SHOT_COVERAGES_NL_ARCHIVED_20220904] (
         [DATE_LAST_INSERTED],
         [DATE_OF_STATISTICS],
         [DATE_OF_REPORT],
         [AGE_GROUP],
         [BIRTH_YEAR],
         [PERCENTAGE]
     )
     SELECT 
         [DATE_LAST_INSERTED],
         [DATE_OF_STATISTICS],
         [DATE_OF_REPORT],
         [AGE_GROUP],
         [BIRTH_YEAR],
         [PERCENTAGE]
     FROM [VWSDEST].[RIVM_BOOSTER_SHOT_COVERAGES_NL]
     WHERE [DATE_LAST_INSERTED] >= '2022-09-07' AND [DATE_LAST_INSERTED] < '2022-09-08' -- get first insertion after 20220904
 END