-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT. 
-- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.

-- MOVE MUNICIPALITY DATA FROM STAGING TO INTERMEDIATE TABLE.
CREATE    PROCEDURE [dbo].[SP_RIVM_COVID_19_MUNICIPALITY_INTER]
 AS
 BEGIN

    -- Zet de Date_Last_Inserted in een variabele
    DECLARE @DateTimeNow AS DateTime = GETDATE()

    -- Voeg de regels toe vanuit VWSSTAGE
    INSERT INTO [VWSINTER].[RIVM_COVID_19_NUMBER_MUNICIPALITY]
     (
         [DATE_OF_REPORT],
         [DATE_OF_PUBLICATION],
         [MUNICIPALITY_CODE],
         [MUNICIPALITY_NAME],
         [SECURITY_REGION_CODE],
         [SECURITY_REGION_NAME],
         [PROVINCE],
         [MUNICIPAL_HEALTH_SERVICE],
         [ROAZ_REGION],
         [TOTAL_REPORTED],
         [HOSPITAL_ADMISSION],
         [DECEASED],
         [Date_Last_Inserted]
     )
     SELECT 
         CAST(A.[DATE_OF_REPORT] AS [DATETIME]) AS [DATE_OF_REPORT],
         CAST(A.[DATE_OF_PUBLICATION] AS [DATETIME]) AS [DATE_OF_REPORT],
         ISNULL(B.[GM_CODE_NEW], TRIM(A.[MUNICIPALITY_CODE])),
         ISNULL(B.[GM_NAME_NEW], TRIM(A.[MUNICIPALITY_NAME])),
         ISNULL(B.[VR_CODE], TRIM(A.[SECURITY_REGION_CODE])),
         ISNULL(B.[VR_NAME], TRIM(A.[SECURITY_REGION_NAME])),
         ISNULL(B.[PROVINCE_CODE], TRIM(A.[PROVINCE])),
         ISNULL(B.[GGD_NAME], TRIM(A.[MUNICIPAL_HEALTH_SERVICE])),
         TRIM(A.[ROAZ_REGION]) AS [ROAZ_REGION],
         CAST(SUM(CAST(A.[TOTAL_REPORTED] AS [FLOAT]) * ISNULL(B.[SHARES], 1.0)) AS [INT]) AS [TOTAL_REPORTED],
         CAST(SUM(CAST(A.[HOSPITAL_ADMISSION] AS [FLOAT])* ISNULL(B.[SHARES], 1.0)) AS [INT]) AS [HOSPITAL_ADMISSION],
         CAST(SUM(CAST(A.[DECEASED] AS [FLOAT]) * ISNULL(B.[SHARES], 1.0)) AS [INT]) AS [DECEASED],
         @DateTimeNow
     FROM  [VWSSTAGE].[RIVM_COVID_19_NUMBER_MUNICIPALITY] A
     LEFT JOIN (
         SELECT 
             * 
         FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING] 
         WHERE [ACTIVE]=1
             AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING])  
     ) B ON A.[MUNICIPALITY_CODE] = B.[GM_CODE_ORIGINAL]
     WHERE A.[DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_COVID_19_NUMBER_MUNICIPALITY])
     GROUP BY ISNULL(B.[GM_CODE_NEW], TRIM(A.[MUNICIPALITY_CODE])),
         ISNULL(B.[GM_NAME_NEW], TRIM(A.[MUNICIPALITY_NAME])),
         ISNULL(B.[VR_CODE], TRIM(A.[SECURITY_REGION_CODE])),
         ISNULL(B.[VR_NAME], TRIM(A.[SECURITY_REGION_NAME])),
         ISNULL(B.[PROVINCE_CODE], TRIM(A.[PROVINCE])),
         ISNULL(B.[GGD_NAME], TRIM(A.[MUNICIPAL_HEALTH_SERVICE])),
         TRIM(A.[ROAZ_REGION]),
         A.[DATE_OF_REPORT],
         A.[DATE_OF_PUBLICATION]
 
  -- Voeg nu de regels toe uit VWSSTATIC
  INSERT INTO [VWSINTER].[RIVM_COVID_19_NUMBER_MUNICIPALITY]
     (
         [DATE_OF_REPORT],
         [DATE_OF_PUBLICATION],
         [MUNICIPALITY_CODE],
         [MUNICIPALITY_NAME],
         [SECURITY_REGION_CODE],
         [SECURITY_REGION_NAME],
         [PROVINCE],
         [MUNICIPAL_HEALTH_SERVICE],
         [ROAZ_REGION],
         [TOTAL_REPORTED],
         [HOSPITAL_ADMISSION],
         [DECEASED],
         [Date_Last_Inserted]
     )
     SELECT 
         CAST(A.[DATE_OF_REPORT] AS [DATETIME]) AS [DATE_OF_REPORT],
         CAST(A.[DATE_OF_PUBLICATION] AS [DATETIME]) AS [DATE_OF_REPORT],
         ISNULL(B.[GM_CODE_NEW], TRIM(A.[MUNICIPALITY_CODE])),
         ISNULL(B.[GM_NAME_NEW], TRIM(A.[MUNICIPALITY_NAME])),
         ISNULL(B.[VR_CODE], TRIM(A.[SECURITY_REGION_CODE])),
         ISNULL(B.[VR_NAME], TRIM(A.[SECURITY_REGION_NAME])),
         ISNULL(B.[PROVINCE_CODE], TRIM(A.[PROVINCE])),
         ISNULL(B.[GGD_NAME], TRIM(A.[MUNICIPAL_HEALTH_SERVICE])),
         TRIM(A.[ROAZ_REGION]) AS [ROAZ_REGION],
         CAST(SUM(CAST(A.[TOTAL_REPORTED] AS [FLOAT]) * ISNULL(B.[SHARES], 1.0)) AS [INT]) AS [TOTAL_REPORTED],
         CAST(SUM(CAST(A.[HOSPITAL_ADMISSION] AS [FLOAT])* ISNULL(B.[SHARES], 1.0)) AS [INT]) AS [HOSPITAL_ADMISSION],
         CAST(SUM(CAST(A.[DECEASED] AS [FLOAT]) * ISNULL(B.[SHARES], 1.0)) AS [INT]) AS [DECEASED],
         @DateTimeNow
     FROM  [VWSSTATIC].[RIVM_COVID_19_NUMBER_MUNICIPALITY] A
     LEFT JOIN (
         SELECT 
             * 
         FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING] 
         WHERE [ACTIVE]=1
             AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RECLASSIFIED_MUNICIPALITY_MAPPING])  
     ) B ON A.[MUNICIPALITY_CODE] = B.[GM_CODE_ORIGINAL]
     WHERE A.[DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RIVM_COVID_19_NUMBER_MUNICIPALITY])
     GROUP BY ISNULL(B.[GM_CODE_NEW], TRIM(A.[MUNICIPALITY_CODE])),
         ISNULL(B.[GM_NAME_NEW], TRIM(A.[MUNICIPALITY_NAME])),
         ISNULL(B.[VR_CODE], TRIM(A.[SECURITY_REGION_CODE])),
         ISNULL(B.[VR_NAME], TRIM(A.[SECURITY_REGION_NAME])),
         ISNULL(B.[PROVINCE_CODE], TRIM(A.[PROVINCE])),
         ISNULL(B.[GGD_NAME], TRIM(A.[MUNICIPAL_HEALTH_SERVICE])),
         TRIM(A.[ROAZ_REGION]),
         A.[DATE_OF_REPORT],
         A.[DATE_OF_PUBLICATION]

 END;