-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) STAGE -> INTER.....
 --TODO pick allready the boostershot_type1 column allready by VR
 CREATE   PROCEDURE [DBO].[SP_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_VR_STAGE_TO_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_VR] (
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
 	    [POPULATION],
 	    [REGION_CODE] ,
         [REGION_LEVEL],
         [REGION_NAME] ,
         [AGE_GROUP],
         [BIRTH_YEAR],
         [VACCINATION_SERIE],
         [PERCENTAGE_SOURCE],
         [PERCENTAGE],
         [PERCENTAGE_LABEL]
 
     )
     SELECT
         CAST([VERSION] AS INT),
         CONVERT(DATETIME, [DATE_OF_REPORT], 120),
         CONVERT(DATETIME, [DATE_OF_STATISTICS], 120),
         CAST([POPULATION] AS BIGINT),
         [REGION_CODE],
         [REGION_LEVEL],
         [REGION_NAME],
         [AGE_GROUP],
         [BIRTH_YEAR],
         [VACCINATION_SERIE],
         [PERCENTAGE] AS [PERCENTAGE_SOURCE],
         CASE
             WHEN [PERCENTAGE] IN ('<=5', '>=95') THEN NULL
             ELSE [PERCENTAGE]
             END AS [PERCENTAGE],
         CASE
             WHEN [PERCENTAGE] = '<=5' THEN [PERCENTAGE]
             WHEN [PERCENTAGE] = '>=95' THEN [PERCENTAGE]
             ELSE NULL
             END AS [PERCENTAGE_LABEL]
     FROM 
         [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_VR]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_VR])
 END;