-- MOVE SEWER MEASUREMENTS DATA FROM STAGING TO INTERMEDIATE TABLE.
 
 -- COMMENTS:
 -- 1. EITHER RNA_PER_ML OR RNA_FLOW_PER_100000 IS FILLED. THE OTHER IS EMPTY: RNA_PER_ML SEEMS LEGACY
 -- 2. RNA_FLOW_PER_100000 CAN BE EITHER EMPTY OR 0. RECORDS WITH NO VALUES ARE LEFT OUT (RNA_PER_ML WAS MEASURED)
 
 CREATE   PROCEDURE [DBO].[SP_RIVM_SEWER_MEASUREMENTS_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_SEWER_MEASUREMENTS] (
         T1.[DATE_MEASUREMENT],
         T1.[VERSION],
         T1.[RWZI_AWZI_CODE],
         T1.[RWZI_AWZI_NAME],
         T1.[RNA_PER_ML],
         T1.[RNA_FLOW_PER_100000]
     )
     SELECT 
         [DBO].[TRY_CONVERT_TO_DATETIME](T1.[DATE_MEASUREMENT]) AS [DATE_MEASUREMENT],
         T1.[VERSION],
         T1.[RWZI_AWZI_CODE],
         T1.[RWZI_AWZI_NAME],
         CAST((SELECT CONVERT(FLOAT, ISNULL(NULLIF(T1.[RNA_PER_ML], ''), '0'))) AS BIGINT) AS [RNA_PER_ML],
         CONVERT(BIGINT, CONVERT(FLOAT, REPLACE(T1.[RNA_FLOW_PER_100000],',','.'))) AS [RNA_FLOW_PER_100000]
     FROM 
         [VWSSTAGE].[RIVM_SEWER_MEASUREMENTS] T1
     LEFT JOIN [VWSSTATIC].[INACTIVE_SEWER_INSTALLATION_MAPPING] T2
         ON CAST(T1.[RWZI_AWZI_CODE] AS INT) = T2.[RWZI_CODE]
     WHERE T1.[DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_SEWER_MEASUREMENTS])
         AND T1.[RNA_FLOW_PER_100000] != ''
         AND ISNULL(T2.[ACTIVE], 1) != 0
 END;