CREATE    PROCEDURE [dbo].[SP_RIVM_IC_OPNAME_INTER]
 AS
 BEGIN
 
 -- Zet de Date_Last_Inserted in een variabele
 DECLARE @DateTimeNow AS DateTime = GETDATE()
 
 INSERT INTO VWSINTER.RIVM_IC_OPNAME(
     [VERSION],
 	DATE_OF_REPORT,
     DATE_OF_STATISTICS,
     IC_ADMISSION_NOTIFICATION,
     IC_ADMISSION,
     Date_Last_Inserted 
     )
 SELECT
     [VERSION],
 	DATE_OF_REPORT,
     DATE_OF_STATISTICS,
     IC_ADMISSION_NOTIFICATION,
     IC_ADMISSION,
     @DateTimeNow as Date_Last_Inserted 
 FROM 
         VWSSTAGE.RIVM_IC_OPNAME
 WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSSTAGE.RIVM_IC_OPNAME)
 
 
 INSERT INTO VWSINTER.RIVM_IC_OPNAME(
     [VERSION],
 	DATE_OF_REPORT,
     DATE_OF_STATISTICS,
     IC_ADMISSION_NOTIFICATION,
     IC_ADMISSION,
     Date_Last_Inserted 
     )
 SELECT
     [VERSION],
 	DATE_OF_REPORT,
     DATE_OF_STATISTICS,
     IC_ADMISSION_NOTIFICATION,
     IC_ADMISSION,
     @DateTimeNow as Date_Last_Inserted 
 FROM 
         VWSSTATIC.RIVM_IC_OPNAME
 WHERE CAST(DATE_LAST_INSERTED as DATE) = (SELECT MAX(CAST(DATE_LAST_INSERTED as DATE)) FROM VWSSTATIC.RIVM_IC_OPNAME)
 
 
 END;