
 CREATE   PROCEDURE [dbo].[SP_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM_ARCHIVED_20220904] AS
 BEGIN
     TRUNCATE TABLE [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM_ARCHIVED_20220904]
 
     INSERT INTO [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM_ARCHIVED_20220904] (
         [DATE_LAST_INSERTED],
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [POPULATION],
         [REGION_CODE],
         [REGION_LEVEL],
         [REGION_NAME],
         [AGE_GROUP],
         [VACCINATION_SERIE],
         [PERCENTAGE],
         [PERCENTAGE_LABEL]
     )
     SELECT
         [DATE_LAST_INSERTED],
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [POPULATION],
         [REGION_CODE],
         [REGION_LEVEL],
         [REGION_NAME],
         [AGE_GROUP],
         [VACCINATION_SERIE],
         [PERCENTAGE],
         [PERCENTAGE_LABEL]
     FROM [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM]
     WHERE [DATE_LAST_INSERTED] >= '2022-09-07' AND [DATE_LAST_INSERTED] < '2022-09-08' -- get first insertion after 20220904
 END