CREATE    PROCEDURE [dbo].[SP_RIVM_NURSING_HOMES_COMBINED_INTER]
 AS
 BEGIN
 -- Main select and insert into statement. Filtered values on max datelastinserted.
 -- Move nursery intake data from staging to intermediate table. 
 
 -- Zet de Date_Last_Inserted in een variabele
 DECLARE @DateTimeNow AS DateTime = GETDATE()
 
 INSERT INTO VWSINTER.RIVM_NURSING_HOMES_COMBINED
     (
         [DATE_OF_REPORT],
         [DATE_OF_STATISTIC_REPORTED],
         [SECURITY_REGION_CODE],
         [SECURITY_REGION_NAME],
         [TOTAL_CASES_REPORTED],
         [TOTAL_DECEASED_REPORTED],
         [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED],
         [TOTAL_INFECTED_LOCATIONS_REPORTED],
         [DATE_LAST_INSERTED]
     )
     SELECT
         -- Provided datetime format in source file is yyyy-mm-dd
         CONVERT(DATETIME, [DATE_OF_REPORT], 102),
         CONVERT(DATETIME, [DATE_OF_STATISTIC_REPORTED], 102),
         TRIM([SECURITY_REGION_CODE]),
         [SECURITY_REGION_NAME],
         ISNULL(TOTAL_CASES_REPORTED,0) AS [TOTAL_CASES_REPORTED],
         ISNULL(TOTAL_DECEASED_REPORTED,0) AS [TOTAL_DECEASED_REPORTED],
         ISNULL(TOTAL_NEW_INFECTED_LOCATIONS_REPORTED,0) AS [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED],
         ISNULL(TOTAL_INFECTED_LOCATIONS_REPORTED,0) AS [TOTAL_INFECTED_LOCATIONS_REPORTED],
         @DateTimeNow as [DATE_LAST_INSERTED]
     FROM VWSSTAGE.RIVM_NURSING_HOMES_COMBINED
         WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSSTAGE.RIVM_NURSING_HOMES_COMBINED)
 
 
 INSERT INTO VWSINTER.RIVM_NURSING_HOMES_COMBINED
     (
         [DATE_OF_REPORT],
         [DATE_OF_STATISTIC_REPORTED],
         [SECURITY_REGION_CODE],
         [SECURITY_REGION_NAME],
         [TOTAL_CASES_REPORTED],
         [TOTAL_DECEASED_REPORTED],
         [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED],
         [TOTAL_INFECTED_LOCATIONS_REPORTED],
         [DATE_LAST_INSERTED]
     )
     SELECT
         -- Provided datetime format in source file is yyyy-mm-dd
         CONVERT(DATETIME, [DATE_OF_REPORT], 102),
         CONVERT(DATETIME, [DATE_OF_STATISTIC_REPORTED], 102),
         TRIM([SECURITY_REGION_CODE]),
         [SECURITY_REGION_NAME],
         ISNULL(TOTAL_CASES_REPORTED,0) AS [TOTAL_CASES_REPORTED],
         ISNULL(TOTAL_DECEASED_REPORTED,0) AS [TOTAL_DECEASED_REPORTED],
         ISNULL(TOTAL_NEW_INFECTED_LOCATIONS_REPORTED,0) AS [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED],
         ISNULL(TOTAL_INFECTED_LOCATIONS_REPORTED,0) AS [TOTAL_INFECTED_LOCATIONS_REPORTED],
         @DateTimeNow as [DATE_LAST_INSERTED]
     FROM VWSSTATIC.RIVM_NURSING_HOMES_COMBINED
         WHERE CAST(DATE_LAST_INSERTED as DATE) = (SELECT MAX(CAST(DATE_LAST_INSERTED as DATE)) FROM VWSSTATIC.RIVM_NURSING_HOMES_COMBINED)
 
 
 
 END;