
 CREATE   PROCEDURE [dbo].[SP_RIVM_VACCINATION_SHOT_COVERAGES_PER_CAMPAIGN_NL_ARCHIVED_20220908] AS
 BEGIN
     TRUNCATE TABLE [VWSARCHIVE].[RIVM_VACCINATION_SHOT_COVERAGES_PER_CAMPAIGN_NL_ARCHIVED_20220908]
 
     INSERT INTO [VWSARCHIVE].[RIVM_VACCINATION_SHOT_COVERAGES_PER_CAMPAIGN_NL_ARCHIVED_20220908] (
         [ID],
         [DATE_LAST_INSERTED],
         [DATE_OF_STATISTICS],
         [DATE_OF_REPORT],
         [AGE_GROUP],
         [BIRTH_YEAR],
         [PERCENTAGE_PARTLY],
         [PERCENTAGE_COMPLETED]
     )
     SELECT 
         [ID],
         [DATE_LAST_INSERTED],
         [DATE_OF_STATISTICS],
         [DATE_OF_REPORT],
         [AGE_GROUP],
         [BIRTH_YEAR],
         [PERCENTAGE_PARTLY],
         [PERCENTAGE_COMPLETED]
     FROM VWSDEST.RIVM_VACCINATION_SHOT_COVERAGES_NL
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINATION_SHOT_COVERAGES_NL])
 END