-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) INTER -> DEST.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_SEWER_MEASUREMENTS_GM_2023_INTER_TO_DEST]
 AS
 BEGIN
     INSERT INTO [VWSDEST].[RIVM_SEWER_MEASUREMENTS_GM_2023] (
         [GMCODE],
         [DATE_START_UNIX],
         [DATE_END_UNIX],
         [AVERAGE]
     )
     SELECT
         [REGION_CODE],
         dbo.CONVERT_DATETIME_TO_UNIX([START_DATE]),
         dbo.CONVERT_DATETIME_TO_UNIX([END_DATE]),
         CAST(round(([RNA_FLOW_PER_100000_WEEKLYMEAN] / 1.0E+11),0) as INT)
     FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS_GM_2023]
     WHERE [REGION_CODE] IN ( -- only show active municipalities
         SELECT DISTINCT([NAME])
         FROM [DATATINO_PROTO_1].[PROTOS]
         WHERE [NAME] <> 'GM_COLLECTION'
         AND [NAME] LIKE 'GM%'
         AND [ACTIVE] = 1
     )
     AND [RNA_FLOW_PER_100000_WEEKLYMEAN] IS NOT NULL -- only take actual measurements
     AND [DATE_OF_REPORT] = (SELECT MAX([DATE_OF_REPORT]) FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS_GM_2023])
     AND [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS_GM_2023])
 END