-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) STAGE -> INTER.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL_STAGE_TO_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL] (
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [N_PARTICIPANTS_TOTAL],
         [N_WITH_SYMPTOMS],
         [N_WITH_SHARED_COVID_TEST_RESULT],
         [N_TESTED_POSITIVE],
         [PERC_COVID_TEST_POSITIVE]
     )
     SELECT
         CAST([VERSION] AS INT),
         CONVERT(DATETIME, [DATE_OF_REPORT], 126),
         CONVERT(DATETIME, [DATE_OF_STATISTICS], 126),
         NULLIF(TRIM([N_PARTICIPANTS_TOTAL]), ''),
         NULLIF(TRIM([N_WITH_SYMPTOMS]), ''),
         NULLIF(TRIM([N_WITH_SHARED_COVID_TEST_RESULT]), ''),
         NULLIF(TRIM([N_TESTED_POSITIVE]), ''),
         NULLIF(REPLACE([PERC_COVID_TEST_POSITIVE], ',', '.'), '')
     FROM 
         [VWSSTAGE].[RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL])
 END;