CREATE    PROCEDURE [dbo].[SP_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP_INTER]
 AS
 BEGIN
 
 -- Zet de Date_Last_Inserted in een variabele
 DECLARE @DateTimeNow AS DateTime = GETDATE()
 
 INSERT INTO 
         VWSINTER.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP (
             [VERSION]
             ,[DATE_OF_REPORT]
             ,[DATE_OF_STATISTICS_WEEK_START]
             ,[AGE_GROUP]
             ,[HOSPITAL_ADMISSION_NOTIFICATION]
             ,[HOSPITAL_ADMISSION]
             ,[IC_ADMISSION_NOTIFICATION]
             ,[IC_ADMISSION]
             ,[DATE_LAST_INSERTED]
     )
    SELECT
          [VERSION]
         ,CAST([DATE_OF_REPORT] AS DATETIME)
         ,CAST([DATE_OF_STATISTICS_WEEK_START] AS DATE)
         ,[AGE_GROUP]
         ,CASE 
 			WHEN LEN([HOSPITAL_ADMISSION_NOTIFICATION]) = 0 THEN NULL
 			ELSE CAST([HOSPITAL_ADMISSION_NOTIFICATION] AS INT)
 		END
         ,CASE 
 			WHEN LEN([HOSPITAL_ADMISSION]) = 0 THEN NULL
 			ELSE CAST([HOSPITAL_ADMISSION] AS INT)
 		END
         ,CASE 
 			WHEN LEN([IC_ADMISSION_NOTIFICATION]) = 0 THEN NULL
 			ELSE CAST([IC_ADMISSION_NOTIFICATION] AS INT)
 		END
         ,CASE 
 			WHEN LEN([IC_ADMISSION]) = 0 THEN NULL
 			ELSE CAST([IC_ADMISSION] AS INT)
 		END
        ,@DateTimeNow as Date_Last_Inserted
     FROM 
         VWSSTAGE.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP
     WHERE 
         DATE_LAST_INSERTED = (
             SELECT MAX(DATE_LAST_INSERTED) 
             FROM VWSSTAGE.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP)
 
 
 
 INSERT INTO 
         VWSINTER.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP (
             [VERSION]
             ,[DATE_OF_REPORT]
             ,[DATE_OF_STATISTICS_WEEK_START]
             ,[AGE_GROUP]
             ,[HOSPITAL_ADMISSION_NOTIFICATION]
             ,[HOSPITAL_ADMISSION]
             ,[IC_ADMISSION_NOTIFICATION]
             ,[IC_ADMISSION]
             ,[DATE_LAST_INSERTED]
     )
    SELECT
          [VERSION]
         ,CAST([DATE_OF_REPORT] AS DATETIME)
         ,CAST([DATE_OF_STATISTICS_WEEK_START] AS DATE)
         ,[AGE_GROUP]
         ,CASE 
 			WHEN LEN([HOSPITAL_ADMISSION_NOTIFICATION]) = 0 THEN NULL
 			ELSE CAST([HOSPITAL_ADMISSION_NOTIFICATION] AS INT)
 		END
         ,CASE 
 			WHEN LEN([HOSPITAL_ADMISSION]) = 0 THEN NULL
 			ELSE CAST([HOSPITAL_ADMISSION] AS INT)
 		END
         ,CASE 
 			WHEN LEN([IC_ADMISSION_NOTIFICATION]) = 0 THEN NULL
 			ELSE CAST([IC_ADMISSION_NOTIFICATION] AS INT)
 		END
         ,CASE 
 			WHEN LEN([IC_ADMISSION]) = 0 THEN NULL
 			ELSE CAST([IC_ADMISSION] AS INT)
 		END
        ,@DateTimeNow as Date_Last_Inserted
     FROM 
         VWSSTATIC.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP
     WHERE CAST(DATE_LAST_INSERTED as DATE) = (SELECT MAX(CAST(DATE_LAST_INSERTED as DATE)) FROM VWSSTATIC.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP)
 
 
 END;