
 CREATE   PROCEDURE [dbo].[SP_RIVM_VACCINATIONS_BOOSTER_SHOTS_ADMINISTERED_NL_ARCHIVED_20220904] AS
 BEGIN
     TRUNCATE TABLE [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_ADMINISTERED_NL_ARCHIVED_20220904]
 
     INSERT INTO [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_ADMINISTERED_NL_ARCHIVED_20220904] (
         [DATE_LAST_INSERTED],
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [GGD_ADMINISTERED_BOOSTER_SHOTS],
         [GGD_CUMSUM_ADMINISTERED_BOOSTER_SHOTS],
         [GGD_ADMINISTERED_BOOSTER_SHOTS_7DAYS],
         [OTHERS_ESTIMATED_BOOSTER_SHOTS],
         [OTHERS_CUMSUM_ESTIMATED_BOOSTER_SHOTS],
         [OTHERS_ESTIMATED_BOOSTER_SHOTS_7DAYS]
     )
     SELECT 
         [DATE_LAST_INSERTED],
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [GGD_ADMINISTERED_BOOSTER_SHOTS],
         [GGD_CUMSUM_ADMINISTERED_BOOSTER_SHOTS],
         [GGD_ADMINISTERED_BOOSTER_SHOTS_7DAYS],
         [OTHERS_ESTIMATED_BOOSTER_SHOTS],
         [OTHERS_CUMSUM_ESTIMATED_BOOSTER_SHOTS],
         [OTHERS_ESTIMATED_BOOSTER_SHOTS_7DAYS]
     FROM [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_ADMINISTERED_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_ADMINISTERED_NL])
 END