-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) INTER -> DEST.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL_INTER_TO_DEST]
 AS
 BEGIN
     WITH CTE AS (
         SELECT 
             DATEADD(DD,-6,DATE_OF_STATISTICS) AS [WEEK_START],
             [DATE_OF_STATISTICS] AS [WEEK_END],
             [DATE_OF_STATISTICS],                    
             [TOTAL_VACCINATIONS],
             SUM([TOTAL_VACCINATIONS]) OVER (ORDER BY [DATE_OF_STATISTICS]) AS [CUMSUM_VACCINATIONS],
             [ASTRA_ZENECA],
             [COMIRNATY],
             [MODERNA],
             [UNKNOWN]
         FROM [VWSINTER].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL] 
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL])
     )
     INSERT INTO [VWSDEST].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL] (
 		[WEEK_START],
         [WEEK_END],
         [DATE_OF_STATISTICS],                    
         [TOTAL_VACCINATIONS],
         [CUMSUM_VACCINATIONS],
         [VACCINATIONS_7DAYS],
         [ASTRA_ZENECA],
         [COMIRNATY],
         [MODERNA],
         [UNKNOWN]
     )
     SELECT    
         i.[WEEK_START],
         i.[WEEK_END],
         i.[DATE_OF_STATISTICS],                    
         i.[TOTAL_VACCINATIONS],
         i.[CUMSUM_VACCINATIONS],
         (i.[CUMSUM_VACCINATIONS] - j.[CUMSUM_VACCINATIONS]) AS [VACCINATIONS_7DAYS], 
         i.[ASTRA_ZENECA],
         i.[COMIRNATY],
         i.[MODERNA],
         i.[UNKNOWN]
     FROM CTE i
     LEFT JOIN CTE j ON CAST(i.[WEEK_START] AS DATE) = DATEADD(DD, 7, CAST(j.[WEEK_START] AS DATE))
 END;