-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE   PROCEDURE DBO.SP_RIVM_VACCINATIONSTATUS_HOSPITAL_ADMISSIONS
AS
BEGIN
    INSERT INTO VWSINTER.RIVM_VACCINATIONSTATUS_HOSPITAL_ADMISSIONS
    (
       [ID]
      ,[DATE_START]
      ,[DATE_END]
      ,[GROUP_SIZE]
      ,[FULLY_VACCINATED]
      ,[FULLY_VACCINATED_PERCENTAGE]
      ,[PARTIALLY_NOT_VACCINATED]
      ,[PARTIALLY_NOT_VACCINATED_PERCENTAGE]
    )
    SELECT
       [ID]
      ,CONVERT (date, [DATE_START] , 105)  as [DATE_START]
      ,CONVERT (date, [DATE_END]  , 105) AS  [DATE_END]
      ,CAST ([GROUP_SIZE] AS INT) AS [GROUP_SIZE]
      ,CAST ([FULLY_VACCINATED] AS INT) AS [FULLY_VACCINATED]
      ,CAST ([FULLY_VACCINATED_PERCENTAGE] AS decimal(18,1) ) AS [FULLY_VACCINATED_PERCENTAGE] 
	  ,CAST ([PARTIALLY_NOT_VACCINATED] AS INT) AS [PARTIALLY_NOT_VACCINATED]
      ,CAST ([PARTIALLY_NOT_VACCINATED_PERCENTAGE] AS decimal(18,1)) AS [PARTIALLY_NOT_VACCINATED_PERCENTAGE] 
    FROM 
       VWSSTAGE.RIVM_VACCINATIONSTATUS_HOSPITAL_ADMISSIONS
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from VWSSTAGE.RIVM_VACCINATIONSTATUS_HOSPITAL_ADMISSIONS)
END;