-- Hiervoor eenmalig een query runnen die dit INTO een VWSARCHIVE tabel schrijft
 -- met als extensie 20220908 en die filtert op de datum 2022-0908
 
 
 -- 1) CREATE STORED PROCEDURE(S): ARCHIVE EXISTING DATA
 CREATE   PROCEDURE [DBO].[SP_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL_DEST_TO_ARCHIVED_20220908]
 AS
 BEGIN
 TRUNCATE TABLE [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL_ARCHIVED_20220908]
 
     INSERT INTO [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL_ARCHIVED_20220908] (        
         [DATE_LAST_INSERTED],
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [AGE_GROUP],
         [POPULATION_AGEGROUP],
         [BASE_SERIES],
         [BOOSTER1],
         [AMOUNT_CUMULATIVE],
         [COVERAGE_AGEGROUP],
         [COVERAGE_TO_BASE_SERIES]
     )
     SELECT 
         [DATE_LAST_INSERTED],
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [AGE_GROUP],
         [POPULATION_AGEGROUP],
         [BASE_SERIES],
         [BOOSTER1],
         [AMOUNT_CUMULATIVE],
         [COVERAGE_AGEGROUP],
         [COVERAGE_TO_BASE_SERIES]
     FROM [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL] WITH(NOLOCK)
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL])
 END;