-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE   PROCEDURE DBO.SP_RIVM_DECEASED_PER_WEEK
AS
BEGIN
WITH BASE_CTE AS (
SELECT
    DECEASED AS DECEASED
,   SECURITY_REGION_CODE
,   [dbo].[WEEK_START](DATE_OF_PUBLICATION) as WEEK_START
FROM VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY)
)
INSERT INTO VWSDEST.RIVM_DECEASED_PER_WEEK
(
    WEEK_START
,   WEEK_START_UNIX
,   WEEK_END
,   WEEK_END_UNIX
,   DECEASED_ACTUAL
,   VRCODE
)
SELECT
    WEEK_START
,   [dbo].[CONVERT_DATETIME_TO_UNIX]([dbo].[WEEK_START](WEEK_START)) AS WEEK_START_UNIX
,   [dbo].[WEEK_END](WEEK_START) as WEEK_END
,   [dbo].[CONVERT_DATETIME_TO_UNIX]([dbo].[WEEK_END](WEEK_START)) AS WEEK_END_UNIX
,   SUM(DECEASED) AS DECEASED_ACTUAL
,   SECURITY_REGION_CODE
FROM BASE_CTE
GROUP BY WEEK_START, SECURITY_REGION_CODE
END