
 CREATE   PROCEDURE [dbo].[SP_RIVM_DECEASED_DAILY_PER_REGION_ARCHIVED_20221231] AS
 BEGIN
     TRUNCATE TABLE [VWSARCHIVE].[RIVM_DECEASED_DAILY_PER_REGION_ARCHIVED_20221231]
 
     INSERT INTO [VWSARCHIVE].[RIVM_DECEASED_DAILY_PER_REGION_ARCHIVED_20221231] (
         [ID],
         [DATE_OF_REPORT],
         [DATE_OF_REPORT_UNIX],
         [DECEASED_ACTUAL],
         [DECEASED_CUMULATIVE],
         [VRCODE],
         [DATE_LAST_INSERTED],
         [WEEK_START],
         [DECEASED_7D_AVG],
         [WEEK_START_LAG],
         [DECEASED_7D_AVG_LAG]
     )
     SELECT 
         [ID],
         [DATE_OF_REPORT],
         [DATE_OF_REPORT_UNIX],
         [DECEASED_ACTUAL],
         [DECEASED_CUMULATIVE],
         [VRCODE],
         [DATE_LAST_INSERTED],
         [WEEK_START],
         [DECEASED_7D_AVG],
         [WEEK_START_LAG],
         [DECEASED_7D_AVG_LAG]
     FROM [VWSDEST].[RIVM_DECEASED_DAILY_PER_REGION]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_DECEASED_DAILY_PER_REGION])
 END