-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) INTER -> DEST.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL_INTER_TO_DEST]
 AS
 BEGIN
     INSERT INTO [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL] (
 			[VERSION],
             [DATE_OF_REPORT],
             [DATE_OF_STATISTICS],
             [BIRTH_COHORT],
             [AGE_GROUP],
             [POPULATION_PER_AGE_GROUP],
             [BASIC_SERIE_AMOUNT],
             [BOOSTER_TYPE],
             [CUMULATIVE_AMOUNT],
             [VACCINATION_COVERAGE_PER_AGE_GROUP],
             [VACCINATION_COVERAGE_VS_BASIC_SERIE]
     )
     SELECT 
         rvbspag.[VERSION],
         rvbspag.[DATE_OF_REPORT],
         rvbspag.[DATE_OF_STATISTICS],
         ISNULL(ctnm.[COHORT_ADJUSTED], rvbspag.[BIRTH_COHORT]),
         ctagm.[AGE_GROUP],
         rvbspag.[POPULATION_PER_AGE_GROUP],
         ISNULL(rvbspag.[BASIC_SERIE_AMOUNT], 0),
         rvbspag.[BOOSTER_TYPE],
         ISNULL(rvbspag.[CUMULATIVE_AMOUNT], 0),
         ISNULL(rvbspag.[VACCINATION_COVERAGE_PER_AGE_GROUP], 0.0),
         ISNULL(rvbspag.[VACCINATION_COVERAGE_VS_BASIC_SERIE], 0.0)
     FROM [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL] rvbspag
         INNER JOIN [VWSSTATIC].[COHORT_TO_AGE_GROUPS_MAPPING] ctagm
             ON ctagm.[COHORT] = TRIM(rvbspag.[BIRTH_COHORT])
         LEFT JOIN [VWSSTATIC].[COHORT_TO_NAMES_MAPPING] ctnm
             ON ctnm.[COHORT_ORIGINAL] = ctagm.[COHORT]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL])
 END;