-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE   PROCEDURE DBO.SP_RIVM_SITUATIONS_INTER
AS
BEGIN
    INSERT INTO VWSINTER.RIVM_SITUATIONS
    (
        [VERSION],
        [DATE_OF_REPORT],
        [DATE_OF_PUBLICATION],
        [SECURITY_REGION_NAME],
        [SECURITY_REGION_CODE],
        [SOURCE_AND_CONTACT_TRACING_PHASE],
        [TOTAL_REPORTED],
        [REPORTS_WITH_SETTINGS],
        [SETTING_REPORTED],
        [NUMBER_SETTINGS_REPORTED]
    )
    SELECT
        CAST(ISNULL(NULLIF([VERSION], ''), 0) AS INT),
        CONVERT(DATETIME, [DATE_OF_REPORT], 120),
        CONVERT(DATETIME, [DATE_OF_PUBLICATION], 120),
        [SECURITY_REGION_NAME],
        [SECURITY_REGION_CODE],
        [SOURCE_AND_CONTACT_TRACING_PHASE],
        CAST(ISNULL(NULLIF([TOTAL_REPORTED], ''), 0) AS INT),
        CAST(ISNULL(NULLIF([REPORTS_WITH_SETTINGS], ''), 0) AS INT),
        [SETTING_REPORTED],
        CAST(ISNULL(NULLIF([NUMBER_SETTINGS_REPORTED], ''), 0) AS INT)
    FROM 
       VWSSTAGE.RIVM_SITUATIONS
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from VWSSTAGE.RIVM_SITUATIONS)
END;