-- Hiervoor eenmalig een query runnen die dit INTO een VWSARCHIVE tabel schrijft
 -- met als extensie _ARCHIVED_20220908 en die filtert op de datum 2022-0908
 
 -- 1) CREATE STORED PROCEDURE(S): ARCHIVE EXISTING DATA
 CREATE   PROCEDURE [dbo].[SP_RIVM_VACCINATION_SHOTS_PLANNED_NL_ARCHIVED_20220908]
 AS
 BEGIN
 
 TRUNCATE TABLE [VWSARCHIVE].[RIVM_VACCINATION_SHOTS_PLANNED_NL_ARCHIVED_20220908];
 
 WITH CTE AS (
     SELECT TOP(1)
         [DOSES],
         [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS_START]) AS [DATE_START_UNIX],
         [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS_END]) AS [DATE_END_UNIX],
         [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
     FROM 
         [VWSDEST].[RIVM_VACCINATION_SHOTS_PLANNED_NL] WITH(NOLOCK)
     WHERE [DATE_LAST_INSERTED] =(SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINATION_SHOTS_PLANNED_NL])
 )
 INSERT INTO [VWSARCHIVE].[RIVM_VACCINATION_SHOTS_PLANNED_NL_ARCHIVED_20220908] (
     DOSES,
     DATE_END_UNIX,
     DATE_START_UNIX,
     DATE_UNIX,
     DATE_OF_INSERTION_UNIX
 )
 SELECT
     [DOSES],
     [DATE_END_UNIX],
     [DATE_START_UNIX],
     [DATE_START_UNIX] AS [DATE_UNIX],
     [DATE_OF_INSERTION_UNIX]
 FROM CTE
 
 END;