-- 1) CREATE STORED PROCEDURE(S).....
 CREATE   PROCEDURE [DBO].[SP_RIVM_VACCINATION_SERIES_MASTER_DATA_STAGING_TO_STATIC]
 AS
 BEGIN
         INSERT INTO [VWSSTATIC].[RIVM_VACCINATION_SERIES_MASTER_DATA] (
             [VERSION],
             [VACCINATION_KEY],
             [SERIES_START_DATE],
             [SERIES_END_DATE],
             [LABEL_NL],
             [LABEL_EN],
             [SORT_ORDER]
         )
         SELECT
             CAST([VERSION] as INT),
             [VACCINATION_KEY],
             [dbo].[TRY_CONVERT_TO_DATETIME](NULLIF([SERIES_START_DATE], '')),
             [dbo].[TRY_CONVERT_TO_DATETIME](NULLIF([SERIES_END_DATE], '')),
             [LABEL_NL],
             [LABEL_EN],
             CAST([SORT_ORDER] as INT)
         FROM [VWSSTAGE].[RIVM_VACCINATION_SERIES_MASTER_DATA]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINATION_SERIES_MASTER_DATA])
 END;