-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) STAGE -> INTER.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL_STAGE_TO_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL] (
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [BIRTH_COHORT],
         [POPULATION_AGEGROUP],
         [BASE_SERIES],
         [BOOSTER1],
         [AMOUNT_CUMULATIVE],
         [COVERAGE_AGEGROUP],
         [COVERAGE_TO_BASE_SERIES]
     )
     SELECT
         CAST([VERSION] AS INT),
         CONVERT(DATETIME, [DATE_OF_REPORT], 105),
         CONVERT(DATETIME, [DATE_OF_STATISTICS], 105),
         [BIRTH_COHORT],
         CAST(ISNULL(NULLIF(TRIM([POPULATION_AGEGROUP]), ''), 0) AS INT),
         [BASE_SERIES],
         [BOOSTER1],
         CAST(ISNULL(NULLIF(TRIM([AMOUNT_CUMULATIVE]), ''), 0) AS INT),
         CAST(ISNULL(NULLIF([COVERAGE_AGEGROUP], ''), 0) AS NUMERIC(5,2)),
         CAST(ISNULL(NULLIF([COVERAGE_TO_BASE_SERIES], ''), 0) AS NUMERIC(5,2))
     FROM 
         [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL])
 END;