-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) STAGE -> INTER.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL_STAGE_TO_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL]
     (
         [DATE_OF_STATISTICS],
         [TOTAL_VACCINATIONS],
         [ASTRA_ZENECA],
         [COMIRNATY],
         [MODERNA],
         [UNKNOWN]
     )
     SELECT
         [DATE_OF_STATISTICS] = CONVERT(DATETIME, [DATE_OF_STATISTICS], 105),
         [TOTAL_VACCINATIONS] = CAST(ISNULL(NULLIF([TOTAL_VACCINATIONS],''),0) AS INT),
         [ASTRA_ZENECA] = CAST(ISNULL(NULLIF([ASTRA_ZENECA],''),0) AS INT) ,
         [COMIRNATY] = CAST(ISNULL(NULLIF([COMIRNATY],''),0) AS INT),
         [MODERNA] = CAST(ISNULL(NULLIF([MODERNA],''),0) AS INT),
         [UNKNOWN] = CAST(ISNULL(NULLIF([UNKNOWN],''),0) AS INT)
     FROM 
         [VWSSTAGE].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL])
 END;