-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) INTER -> DEST.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL_INTER_TO_DEST]
 AS
 BEGIN
     WITH CTE AS (
         SELECT 
             [VERSION],
             [DATE_LAST_INSERTED],
             [DATE_OF_REPORT],
             [DATE_OF_STATISTICS],
             [PLANNED_DATE],
             [TYPE_PLANNED_DATE],
             [PLANNED_BOOSTER_SHOTS],
             SUM([PLANNED_BOOSTER_SHOTS]) OVER (ORDER BY [PLANNED_DATE]) AS [CUMSUM_PLANNED_BOOSTER_SHOTS],  
             SUM([PLANNED_BOOSTER_SHOTS]) OVER (ORDER BY [PLANNED_DATE] ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS [WEEK_TOTAL_PLANNED_BOOSTER_SHOTS]
         FROM [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL] WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL])
     )
     INSERT INTO [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL] (
 			[VERSION],
 			[DATE_LAST_INSERTED],
 			[DATE_OF_REPORT],
 			[DATE_OF_STATISTICS],
 			[PLANNED_DATE],
 			[TYPE_PLANNED_DATE],
             [PLANNED_BOOSTER_SHOTS],
 			[CUMSUM_PLANNED_BOOSTER_SHOTS],
 			[WEEK_TOTAL_PLANNED_BOOSTER_SHOTS]
     )
     SELECT [VERSION],
 		[DATE_LAST_INSERTED],
 		[DATE_OF_REPORT],
 		[DATE_OF_STATISTICS],
 		[PLANNED_DATE],
 		[TYPE_PLANNED_DATE],
         [PLANNED_BOOSTER_SHOTS],
 		[CUMSUM_PLANNED_BOOSTER_SHOTS],
 		[WEEK_TOTAL_PLANNED_BOOSTER_SHOTS]
     FROM CTE
 END