-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) INTER -> DEST.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_SEWER_MEASUREMENTS_NL_2023_INTER_TO_DEST]
 AS
 BEGIN
     INSERT INTO [VWSDEST].[RIVM_SEWER_MEASUREMENTS_NL_2023] (
         [DATE_UNIX],
         [AVERAGE]
     )
     SELECT
         dbo.CONVERT_DATETIME_TO_UNIX([DATE_MEASUREMENT]),
         CAST(round(([RNA_FLOW_PER_100000] / 1.0E+11),0) as INT)
     FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS_NL_2023]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS_NL_2023])
     AND [DATE_OF_REPORT] = (SELECT MAX([DATE_OF_REPORT]) FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS_NL_2023])
     AND [VERSION] = (SELECT MAX([VERSION]) FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS_NL_2023])
     AND [RNA_FLOW_PER_100000] IS NOT NULL -- only take actual measurements
 END