-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) INTER -> DEST.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL_INTER_TO_DEST]
 AS
 BEGIN
     WITH CTE AS (
         SELECT 
             coverage.[VERSION],
             coverage.[DATE_OF_REPORT],
             coverage.[DATE_OF_STATISTICS],
             age_groups.[AGE_GROUP],
             coverage.[POPULATION_AGEGROUP],
             coverage.[BASE_SERIES],
             coverage.[BOOSTER1],
             coverage.[COVERAGE_AGEGROUP],
             coverage.[COVERAGE_TO_BASE_SERIES],
             coverage.[AMOUNT_CUMULATIVE]
         FROM [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL] coverage
         INNER JOIN [VWSSTATIC].[COHORT_TO_AGE_GROUPS_MAPPING] age_groups 
             ON age_groups.[COHORT] = coverage.[BIRTH_COHORT]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL])
     )
     INSERT INTO [VWSDEST].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL] (
 				[VERSION],
                 [DATE_OF_REPORT],
                 [DATE_OF_STATISTICS],
                 [AGE_GROUP],
                 [POPULATION_AGEGROUP],
                 [BASE_SERIES],
                 [BOOSTER1],
                 [COVERAGE_AGEGROUP],
                 [COVERAGE_TO_BASE_SERIES],
                 [AMOUNT_CUMULATIVE]
     )
     SELECT 
         [VERSION],
 		[DATE_OF_REPORT],
 		[DATE_OF_STATISTICS],
         [AGE_GROUP],
         [POPULATION_AGEGROUP],
         [BASE_SERIES],
         [BOOSTER1],
         [COVERAGE_AGEGROUP],
         [COVERAGE_TO_BASE_SERIES],
         [AMOUNT_CUMULATIVE]
     FROM CTE
 END