-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 CREATE    PROCEDURE [DBO].[SP_RIVM_CIMS_VACCINATED_PER_AGE_GROUP]
 AS
 BEGIN
 -- APPLY FILTERS ON MAIN INPUT TABLE AND PERFORM TRANSFORMATIONS
 WITH FILTERED_CTE AS (
     SELECT
         [DATE_OF_REPORT] AS [DATE_OF_REPORT],
         [DATE_OF_STATISTICS_WEEK_START] AS [DATE_OF_STATISTICS_WEEK_START],
         [DATE_OF_STATISTICS_WEEK_END] AS [DATE_OF_STATISTICS_WEEK_END],
         [BIRTH_COHORT] AS [BIRTH_COHORT],
         [VACCINATION_ALL] AS [VACCINATION_ALL],
         [VACCINATION_COMPLETED] AS [VACCINATION_COMPLETED],
         [VACCINATION_ALL] - [VACCINATION_COMPLETED] AS [VACCINATED_PARTIALLY],
         [VACCINATION_COVERAGE_ALL] AS [VACCINATION_COVERAGE_ALL],
         [VACCINATION_COVERAGE_COMPLETED] AS [VACCINATION_COVERAGE_COMPLETED],
         [VACCINATION_COVERAGE_ALL] - [VACCINATION_COVERAGE_COMPLETED] AS [VACCINATED_COVERAGE_PARTIALLY]
     FROM [VWSINTER].[CIMS_VACCINATED_AGE_GROUP]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[CIMS_VACCINATED_AGE_GROUP])
         AND LOWER([BIRTH_COHORT]) != 'unknown'
 ),
 LAST_CTE AS (
     SELECT
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS_WEEK_START],
         [DATE_OF_STATISTICS_WEEK_END],
         [BIRTH_COHORT],
         [VACCINATION_ALL],
         [VACCINATION_COMPLETED],
         [VACCINATED_PARTIALLY],
         [VACCINATION_COVERAGE_ALL],
         [VACCINATION_COVERAGE_COMPLETED],
         [VACCINATED_COVERAGE_PARTIALLY]
     FROM FILTERED_CTE
 ),
 POPULATION_CTE AS (
 SELECT 
     cpag.[BIRTH_COHORT],
     ctagnm.[BIRTH_COHORT_FORMATTED],
     ctagnm.[AGE_GROUP],
     cpag.[POPULATION]
     -- ,MAX([POPULATION]) OVER (PARTITION BY DATE_LAST_INSERTED) AS TOTAL_POPULATION
     FROM [VWSINTER].[CIMS_POPULATION_AGE_GROUP] cpag
     LEFT JOIN (
         SELECT
             ctagm.[COHORT],
             ctagm.[AGE_GROUP],
             ISNULL(ctnm.[COHORT_ADJUSTED], ctagm.[COHORT]) AS [BIRTH_COHORT_FORMATTED]
         FROM [VWSSTATIC].[COHORT_TO_AGE_GROUPS_MAPPING] ctagm
         LEFT JOIN [VWSSTATIC].[COHORT_TO_NAMES_MAPPING] ctnm ON ctnm.[COHORT_ORIGINAL] = ctagm.[COHORT]
     ) ctagnm ON ctagnm.[COHORT] = cpag.[BIRTH_COHORT]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[CIMS_POPULATION_AGE_GROUP]) 
         AND LOWER([BIRTH_COHORT]) != 'unknown'
 ),
 -- HERE WE SIMPLY GET THE SUM OF ALL POPULATIONS WHICH IS BASICALLY THE <=2016 ROW, BUT MIGHT CHANGE IN THE FUTURE.
 -- MAKE SURE A FLOAT IS RETURNED FOR DIVISION LATER ON!
 SUM_POPULATION_CTE AS (
     SELECT CAST([POPULATION] AS FLOAT) AS [SUM_POPULATION] FROM POPULATION_CTE
     WHERE [AGE_GROUP] IN ('12+')
 )
 INSERT INTO [VWSDEST].[CIMS_VACCINATED_AGE_GROUP](
     [DATE_OF_REPORT],
     [DATE_OF_STATISTICS_WEEK_START],
     [DATE_OF_STATISTICS_WEEK_END],
     [BIRTH_COHORT],
     [AGE_GROUP],
     [AGE_GROUP_POPULATION],
     [AGE_GROUP_POPULATION_PERCENTAGE],
     [VACCINATION_ALL],
     [VACCINATION_COMPLETED],
     [VACCINATED_PARTIALLY],
     [VACCINATION_COVERAGE_ALL],
     [VACCINATION_COVERAGE_COMPLETED],
     [VACCINATED_COVERAGE_PARTIALLY]
 )
 SELECT
     T0.[DATE_OF_REPORT],
     T0.[DATE_OF_STATISTICS_WEEK_START],
     T0.[DATE_OF_STATISTICS_WEEK_END],
     T1.[BIRTH_COHORT_FORMATTED] AS [BIRTH_COHORT],
     T1.[AGE_GROUP],
     T1.[POPULATION] AS [AGE_GROUP_POPULATION],
     T1.[PERCENTAGE_AGE_GROUP],
     T0.[VACCINATION_ALL],
     T0.[VACCINATION_COMPLETED],
     T0.[VACCINATED_PARTIALLY],
     T0.[VACCINATION_COVERAGE_ALL],
     T0.[VACCINATION_COVERAGE_COMPLETED],
     T0.[VACCINATED_COVERAGE_PARTIALLY]
     FROM LAST_CTE AS T0
     -- JOIN AGEGROUP DATA ON FILTERED CTE
     LEFT JOIN (
     SELECT
         [BIRTH_COHORT_FORMATTED],
         [BIRTH_COHORT],
         [AGE_GROUP],
         [POPULATION] AS [POPULATION],
         [POPULATION] / (SELECT [SUM_POPULATION] FROM SUM_POPULATION_CTE) AS [PERCENTAGE_AGE_GROUP]
     FROM POPULATION_CTE
     ) AS T1
     ON T0.[BIRTH_COHORT]=T1.[BIRTH_COHORT]
     --TAKE ONLY THE LAST VALUE
     WHERE T0.[DATE_OF_STATISTICS_WEEK_START] = (SELECT MAX([DATE_OF_STATISTICS_WEEK_START]) FROM LAST_CTE)
 END