CREATE   PROCEDURE [DBO].[SP_RIVM_CIMS_VACCINATED_PER_AGE_GROUP_DEST_TO_ARCHIVE]
 AS
 BEGIN
     INSERT INTO [VWSARCHIVE].[CIMS_VACCINATED_AGE_GROUP] (        
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS_WEEK_START],
         [DATE_OF_STATISTICS_WEEK_END],
         [AGE_GROUP],
         [AGE_GROUP_POPULATION],
         [AGE_GROUP_POPULATION_PERCENTAGE],
         [VACCINATION_ALL],
         [VACCINATION_COMPLETED],
         [VACCINATED_PARTIALLY],
         [VACCINATION_COVERAGE_ALL],
         [VACCINATED_COVERAGE_PARTIALLY],
         [VACCINATION_COVERAGE_COMPLETED],
         [DATE_LAST_INSERTED],
         [BIRTH_COHORT]
     )
     SELECT 
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS_WEEK_START],
         [DATE_OF_STATISTICS_WEEK_END],
         [AGE_GROUP],
         [AGE_GROUP_POPULATION],
         [AGE_GROUP_POPULATION_PERCENTAGE],
         [VACCINATION_ALL],
         [VACCINATION_COMPLETED],
         [VACCINATED_PARTIALLY],
         [VACCINATION_COVERAGE_ALL],
         [VACCINATED_COVERAGE_PARTIALLY],
         [VACCINATION_COVERAGE_COMPLETED],
         [DATE_LAST_INSERTED],
         [BIRTH_COHORT]
     FROM [VWSDEST].[CIMS_VACCINATED_AGE_GROUP] WITH(NOLOCK)
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[CIMS_VACCINATED_AGE_GROUP]  WITH(NOLOCK));
 END;