-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) INTER -> DEST.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_SEWER_MEASUREMENTS_NL_2023_INTER_TO_DEST]
 AS
 BEGIN
     WITH CTE1 AS (
         SELECT *
         FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS_NL_2023]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS_NL_2023])
     ),
     CTE2 AS (
         SELECT * FROM CTE1
         WHERE [DATE_OF_REPORT] = (SELECT MAX([DATE_OF_REPORT]) FROM CTE1)
     ),
     CTE3 AS (
         SELECT * FROM CTE2
         WHERE [VERSION] = (SELECT MAX([VERSION]) FROM CTE2)
     )
     INSERT INTO [VWSDEST].[RIVM_SEWER_MEASUREMENTS_NL_2023] (
         [DATE_MEASUREMENT],
         [RNA_FLOW_PER_100000]
     )
     SELECT
         [DATE_MEASUREMENT],
         [RNA_FLOW_PER_100000]
     FROM CTE3
     WHERE [RNA_FLOW_PER_100000] IS NOT NULL -- only take actual measurements
 END