-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) STAGE -> INTER.....
 CREATE   PROCEDURE [DBO].[SP_RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL_STAGE_TO_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL]
     (
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [PLANNED_DATE],
         [TYPE_PLANNED_DATE],
         [PLANNED_BOOSTER_SHOTS]
     )
     SELECT
         CAST([VERSION] AS INT) AS [VERSION],
 		CONVERT(DATETIME, [DATE_OF_REPORT], 105) AS [DATE_OF_REPORT],
 		CONVERT(DATETIME, [DATE_OF_STATISTICS], 105) AS [DATE_OF_STATISTICS],
 		CONVERT(DATETIME, [PLANNED_DATE], 105) AS [PLANNED_DATE],
 		[TYPE_PLANNED_DATE] AS [TYPE_PLANNED_DATE],
         CAST([PLANNED_BOOSTER_SHOTS] AS INT) AS [PLANNED_BOOSTER_SHOTS]
     FROM 
         [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PLANNED_NL])
 END;