CREATE   PROCEDURE [DBO].[SP_SEWER_BASE]
 AS
 BEGIN
     INSERT INTO [VWSDEST].[SEWER_BASE] (
         [WEEK],
         [WEEK_UNIX],
         [DATE_MEASUREMENT],
         [RWZI_AWZI_CODE],
         [RWZI_AWZI_NAME],
         [RNA_PER_ML],
         [RNA_FLOW_PER_100000],
         [COUNT_DAILY_MEASUREMENT]
     )
     SELECT
         DATEPART(ISO_WEEK, T1.[DATE_MEASUREMENT]) AS [WEEK],
         [DBO].[CONVERT_DATETIME_TO_UNIX](DATEADD(week, DATEDIFF(week, 0, T1.[DATE_MEASUREMENT] - 1), 0)) AS [WEEK_UNIX],
         T1.[DATE_MEASUREMENT],
         T1.[RWZI_AWZI_CODE],
         T1.[RWZI_AWZI_NAME],
         T1.[RNA_PER_ML],
         T1.[RNA_FLOW_PER_100000],
         -- SO FIRST OCCURENCE OF A DATE_MEASUREMENT, RWZI_AWZI_CODE GETS A 1, SECOND 2.
         -- WE DO THIS BECAUSE WE FILTER ON THIS LATER
         ROW_NUMBER() OVER (PARTITION BY [DATE_MEASUREMENT], [RWZI_AWZI_CODE] ORDER BY [DATE_MEASUREMENT], [RWZI_AWZI_CODE]) AS [COUNT_DAILY_MEASUREMENT]
     FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS] AS T1
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS] WITH(NOLOCK))
         AND [DATE_MEASUREMENT] >= CAST('2020-09-07 00:00:00.000' AS DATETIME)
         AND TRIM(UPPER([RWZI_AWZI_NAME])) != 'SCHIPHOL' 
 END