
 CREATE   PROCEDURE [dbo].[SP_STATIC_NURSING_HOME_LOCATIONS_PER_REGION_ARCHIVED_20230126] AS
 BEGIN
     TRUNCATE TABLE [VWSARCHIVE].[NURSING_HOME_LOCATIONS_PER_REGION_ARCHIVED_20230126]
 
     INSERT INTO [VWSARCHIVE].[NURSING_HOME_LOCATIONS_PER_REGION_ARCHIVED_20230126] (
         [VRCODE],
         [VRNAAM],
         [VERPLEEGHUIZEN],
         [GEHANDICAPTENZORGINSTELLINGEN],
         [DATE_LAST_INSERTED]
     )
     SELECT 
         [VRCODE],
         [VRNAAM],
         [VERPLEEGHUIZEN],
         [GEHANDICAPTENZORGINSTELLINGEN],
         [DATE_LAST_INSERTED]
     FROM [VWSSTATIC].[NURSING_HOME_LOCATIONS_PER_REGION]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[NURSING_HOME_LOCATIONS_PER_REGION])
 END