-- 1) CREATE VIEW(S).....
 CREATE   PROCEDURE [dbo].[SP_SEWER_MEASUREMENTS_PER_RWZI_GM_VR]
 AS
 BEGIN
 
 WITH BASE_CTE AS (
 SELECT 
        [WEEK]
       ,[DATE_MEASUREMENT]
       ,[RWZI_AWZI_CODE]
       ,[RWZI_AWZI_NAME]
       ,CAST(RNA_FLOW_PER_100000 / 1.0E+11 AS DECIMAL(16,2)) AS RNA_FLOW_PER_100000
   FROM [VWSDEST].[SEWER_BASE]
   WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[SEWER_BASE])
 )
 ,
 RWZI_POPULATION_CTE AS (
     SELECT
         REGIO_CODE 
         ,RWZI_CODE
         ,REGIO_TYPE
         ,STARTDATUM
         ,EINDDATUM
     FROM VWSSTATIC.CBS_POPULATION_RWZI WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSSTATIC.CBS_POPULATION_RWZI)
 )
 INSERT INTO VWSDEST.SEWER_MEASUREMENTS_PER_RWZI_GM_VR
 (
         [DATE_MEASUREMENT]		,	
 	    [RWZI_AWZI_CODE]        ,
 	    [RWZI_AWZI_NAME]        ,
 	    RNA_FLOW_PER_100000     ,					
         REGIO_TYPE			    ,									
         REGIO_CODE			    ,										
         WEEK				    ,														
         DATE_UNIX               ,        
         DATE_START_UNIX         ,        
         DATE_END_UNIX                 
 )
 SELECT        
          T0.[DATE_MEASUREMENT]
         ,T0.[RWZI_AWZI_CODE]
         ,T0.[RWZI_AWZI_NAME]
         ,T0.[RNA_FLOW_PER_100000]
         ,T1.REGIO_TYPE
         ,T1.REGIO_CODE
         ---Dates for view
         ,WEEK
         ,dbo.CONVERT_DATETIME_TO_UNIX(T0.[DATE_MEASUREMENT])                    AS DATE_UNIX
         ,dbo.CONVERT_DATETIME_TO_UNIX(dbo.WEEK_START(T0.[DATE_MEASUREMENT]))    AS DATE_START_UNIX
         ,dbo.CONVERT_DATETIME_TO_UNIX(dbo.WEEK_END(T0.[DATE_MEASUREMENT]))      AS DATE_END_UNIX
     FROM BASE_CTE AS T0
         LEFT JOIN RWZI_POPULATION_CTE T1 
             ON T0.RWZI_AWZI_CODE = T1.RWZI_CODE
             AND T1.STARTDATUM <= T0.DATE_MEASUREMENT AND T1.EINDDATUM > T0.DATE_MEASUREMENT
 
 
 
 END;