-- MOVE SEWER MEASUREMENTS DATA PER SEWER TREATMENT PLANT FROM INTERMEDIATE TO PRODUCTION TABLE.
 CREATE   PROCEDURE [DBO].[SP_SEWER_MEASUREMENTS_PER_RWZI]
 AS
 BEGIN
     -- ONLY TAKE ROWS INTO ACCOUNT WHICH ARE REPRESENTATIVE MEASUREMENTS AND REMOVE THE ROWS FROM PLANT 'SCHIPHOL'.
     WITH BASE_CTE AS (
         SELECT
             DATEPART(wk, [DATE_MEASUREMENT]) AS [WEEK]
             ,[DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_MEASUREMENT]) AS [DATE_MEASUREMENT_UNIX]
             ,[DATE_MEASUREMENT]
             ,CAST([RNA_FLOW_PER_100000] / 1.0E+11 AS DECIMAL(16,2)) AS [RNA_FLOW_PER_100000]
             ,[RWZI_AWZI_CODE]
         FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_SEWER_MEASUREMENTS])
         AND TRIM(UPPER([RWZI_AWZI_NAME])) != 'SCHIPHOL'
     ),
     RECENT_RWZI_AWZI AS (
         SELECT
             [RWZI_AWZI_CODE],
             [RWZI_AWZI_NAME]
         FROM [VWSSTATIC].[RWZI_AWZI]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTATIC].[RWZI_AWZI] )
     )
     INSERT INTO [VWSDEST].[SEWER_MEASUREMENTS_PER_RWZI] (   
         [DATE_MEASUREMENT]
         ,[DATE_MEASUREMENT_UNIX]
         ,[WEEK]
         ,[RWZI_AWZI_CODE]
         ,[RWZI_AWZI_NAME]
         ,[RNA_FLOW_PER_100000]
         )
     SELECT
         [DATE_MEASUREMENT]
         ,[DATE_MEASUREMENT_UNIX]
         ,[WEEK]
         ,T1.[RWZI_AWZI_CODE]
         ,[RWZI_AWZI_NAME]
         ,[RNA_FLOW_PER_100000]
         FROM BASE_CTE T1
             LEFT JOIN RECENT_RWZI_AWZI T2 ON T1.[RWZI_AWZI_CODE]= T2.[RWZI_AWZI_CODE]
 END;