-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 CREATE   PROCEDURE [DBO].[SP_VACCINATIONS_PARTLY_FULLY]
 AS
 BEGIN
     -- DETERMINE WEEK START BASED ON WEEK END
     WITH PREPARATION AS (
         SELECT 
             [DATE_OF_REPORT],
             [DATE_OF_STATISTICS],
             [END_ISO_WEEK] AS WEEK_END,
             [BIRTH_YEAR],
             [CUMSUM_VACCINATION_PARTLY] AS [PARTIALLY_VACCINATED],
             [CUMSUM_VACCINATION_COMPLETED] AS [FULLY_VACCINATED],
             [CUMSUM_VACCINATION_BOOSTER] AS [BOOSTER_VACCINATED],
             [POPULATION],
             [DBO].[WEEK_START](END_ISO_WEEK) AS WEEK_START
         FROM [VWSINTER].[RIVM_VACCINATIONS_PARTLY_FULLY]
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINATIONS_PARTLY_FULLY])
     )
 
     -- INSERT FINAL OUTPUT INTO DEST TABLE
     INSERT INTO [VWSDEST].[RIVM_VACCINATIONS_PARTLY_FULLY] (
         [DATE_OF_REPORT],
         [WEEK_START],
         [WEEK_END],
         [PARTIALLY_VACCINATED],
         [FULLY_VACCINATED],
         [PARTIALLY_OR_FULLY_VACCINATED],
         [BOOSTER1],
 		[BOOSTER1_INCREMENT]
     )
     SELECT 
         A.[DATE_OF_REPORT],
         A.[WEEK_START]
         ,A.[WEEK_END]
         ,A.[PARTIALLY_VACCINATED] - A.[FULLY_VACCINATED]
         ,A.[FULLY_VACCINATED]
         ,A.[PARTIALLY_VACCINATED] 
         ,A.[BOOSTER_VACCINATED]
 		,(A.[BOOSTER_VACCINATED] - B.[BOOSTER_VACCINATED])
     FROM [PREPARATION] A
 		LEFT JOIN [PREPARATION] B ON CAST(A.[WEEK_START] AS DATE) = DATEADD(DD, 7, CAST(B.[WEEK_START] AS DATE))
 END;