-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) STAGE -> INTER.....
 CREATE   PROCEDURE [DBO].[SP_VWS_VACCINE_DELIVERIES_ADMINISTERED_INTER]
 AS
 BEGIN
     INSERT INTO [VWSINTER].[VWS_VACCINE_DELIVERIES_ADMINISTERED] (
         [DATE_OF_REPORT],
         [DATE_FIRST_DAY],
         [VALUE_TYPE],
         [VALUE_NAME],
         [REPORT_STATUS],
         [VALUE] 
     )
     SELECT
         [DBO].[TRY_CONVERT_TO_DATETIME]([DATE_OF_REPORT]) AS [DATE_OF_REPORT],
         [DBO].[TRY_CONVERT_TO_DATETIME]([DATE_FIRST_DAY]) AS [DATE_FIRST_DAY],
         [VALUE_TYPE],
         [VALUE_NAME],
         [REPORT_STATUS],
         CAST([VALUE] AS BIGINT) AS [VALUE]
     FROM 
         [VWSSTAGE].[VWS_VACCINE_DELIVERIES_ADMINISTERED]
     WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[VWS_VACCINE_DELIVERIES_ADMINISTERED])
 END;