-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 -- 1) CREATE STORE PROCEDURE(S) STAGE -> INTER
 CREATE   PROCEDURE [DBO].[SP_VWS_BEHAVIOR_ANNOTATIONS_NL_INTER_TO_DEST]
 AS
 BEGIN
     INSERT INTO [VWSDEST].[VWS_BEHAVIOR_ANNOTATIONS_NL](
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_CHANGE],
         [FIRST_WAVE],
         [DATE_OF_FIRST_MEASUREMENT],
         [MEASUREMENT_DURATION_IN_DAYS],
         [INDICATOR],
         [STATUS],
         [MESSAGE_TITLE_NL],
         [MESSAGE_TITLE_EN],
         [MESSAGE_TEXT_NL],
         [MESSAGE_TEXT_EN],
         [MESSAGE_RIVM]
     )
     SELECT
         [VERSION],
         [DATE_OF_REPORT],
         [DATE_OF_CHANGE],
         [FIRST_WAVE], 
         [DATE_OF_FIRST_MEASUREMENT],
         [MEASUREMENT_DURATION_IN_DAYS],
         [INDICATOR],
         [STATUS],
         [MESSAGE_TITLE_NL],
         [MESSAGE_TITLE_EN],
         [MESSAGE_TEXT_NL],
         [MESSAGE_TEXT_EN],
         [MESSAGE_RIVM]
     FROM 
         [VWSINTER].[VWS_BEHAVIOR_ANNOTATIONS_NL]
     WHERE
         [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM  [VWSINTER].[VWS_BEHAVIOR_ANNOTATIONS_NL])
 END;