-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER VIEW VWSDEST.V_POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP_BACK_UP AS
SELECT
    ROW_NUMBER() OVER (ORDER BY DATE_OF_REPORT_UNIX ASC) AS ID,
    DATE_OF_REPORT,
	DATE_OF_REPORT_UNIX,
	AGEGROUP,
	INFECTED_PER_AGEGROUP_INCREASE,
	INFECTED_PER_AGEGROUP_TOTALS,
	DATE_LAST_INSERTED
FROM VWSDEST.POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP)