-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER VIEW VWSDEST.V_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_BACK_UP AS
SELECT 
	ROW_NUMBER() OVER (ORDER BY DATE_OF_REPORT_UNIX ASC) AS ID,
    DATE_OF_REPORT,
	DATE_OF_REPORT_UNIX,
	MUNICIPALITY_CODE,
	MUNICIPALITY_NAME,
	TOTAL_COUNTS_PER_DAY,
	MOVING_AVERAGE_HOSPITAL,
	DATE_LAST_INSERTED
FROM VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY);