-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER VIEW VWSDEST.V_RIVM_COVID_19_NUMBER_MUNICIPALITY_CUMULATIVE_BACK_UP AS
SELECT
    ROW_NUMBER() OVER(ORDER BY DATE_OF_REPORT ASC) AS ID,
    DATE_OF_REPORT,
	MUNICIPALITY_CODE,
	MUNICIPALITY_NAME,
	PROVINCE,
	TOTAL_REPORTED,
	HOSPITAL_ADMISSION,
	DECEASED,
	DATE_LAST_INSERTED
FROM VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY_CUMULATIVE
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY_CUMULATIVE);

