-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER VIEW VWSDEST.V_RIVM_COVID_19_CASE_NATIONAL_BACK_UP AS
SELECT
    ROW_NUMBER() OVER(ORDER BY a.ID ASC) AS ID,
    DATE_FILE,
	DATE_STATISTICS,
	DATE_STATISTICS_TYPE,
	AGEGROUP,
	SEX,
	PROVINCE,
	HOSPITAL_ADMISSION,
	DECEASED,
	WEEK_OF_DEATH,
	MUNICIPAL_HEALTH_SERVICE,
	DATE_LAST_INSERTED
FROM VWSINTER.RIVM_COVID_19_CASE_NATIONAL a
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSINTER.RIVM_COVID_19_CASE_NATIONAL)