trigger: 
  branches:
    include:
      - main
      - master
      - release/*
  paths:
    include:
      - "src/**/*.ipynb"
    exclude:
      - "**/*.md"

pool:
  vmImage: ubuntu-latest

variables:
  PipelineWorkspace: $(Build.SourcesDirectory)/.devops

stages:
  - stage: Build
    jobs:
      - job: "Build"
        steps:

          - task: PowerShell@2
            name: SelectModifiedScripts
            inputs:
              targetType: "inline"
              script: |              
                $scripts = $(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
                Write-Host '##vso[task.setvariable variable=ModifiedScripts]$scripts'
              errorActionPreference: "default" 
              failOnStderr: true
              pwsh: true
            displayName: "Task 1: Select Modified Scripts"

          - task: PowerShell@2
            inputs:
              filePath: "$(PipelineWorkspace)/scripts/build-script.ps1"
              arguments: '-SourceDirectory "$(Build.SourcesDirectory)" -ModifiedFiles $(SelectModifiedScripts.ModifiedScripts) -DatatinoDevOpsPAT "$(DatatinoDevOpsPAT)" -DatatinoDevOpsGitBranch "$(DatatinoDevOpsGitBranch)" -DatatinoDevOpsGitUrl "$(DatatinoDevOpsGitUrl)"'
              failOnStderr: true
              pwsh: true
            displayName: "Task 2: Build MSSQL Artifacts"

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/'
              Contents: '*.sql'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/$(Build.SourceVersion)/src'
              OverWrite: true
            displayName: "Task 3: Copy Files: MSSQL Scripts"

          - task: CopyFiles@2
            inputs:
              SourceFolder: "$(PipelineWorkspace)/scripts"
              Contents: "**/*.ps1"
              TargetFolder: "$(Build.ArtifactStagingDirectory)/$(Build.SourceVersion)/scripts"
              OverWrite: true
            displayName: "Task 4: Copy Files: Powershell Scripts"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"
            displayName: "Task 5: Publish Artifacts"

          - task: PowerShell@2
            condition: always()
            inputs:
              targetType: "inline"
              script: |
                $containerName = "local-mssql"
                Write-Host "Removing container(s)....."
                docker container stop $containerName
                docker container rm $containerName
              errorActionPreference: "default" 
              failOnStderr: true
              pwsh: true
            displayName: "Task 5: Post Build"
