trigger: 
  branches:
    include:
      - main
      - master
      - release/*
      - develop*
  paths:
    include:
      - "src/"
    exclude:
      - "**/*.md"
      - "**/*.ps1"

resources:
  repositories: 
    - repository: nl-cdb-be-apis
      type: git
      name: "Corona Dashboard/nl-cdb-be-apis"

variables:
  WORKING_DIRECTORY: $(Build.SourcesDirectory)/$(Build.Repository.Name)

stages:
  - stage: Build
    jobs:
      - job: "Build_dacpac"
        pool:
          vmImage: windows-2022
        steps:
          - task: VSBuild@1
            inputs:
              solution: '**\*.sln'
              platform: 'Any CPU'
              configuration: 'Release'
              clean: true

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/src/sln/CoronaDashboard.BusinessLogic/'
              Contents: '**\*.dacpac'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'business-logic-database'
              publishLocation: 'Container'
      - job: "Build_Business_Logic"
        pool:
          vmImage: ubuntu-20.04
        steps:

          - checkout: self
          - checkout: nl-cdb-be-apis

          - script: | 
              mv ./nl-cdb-be-apis ./__nl-cdb-be-apis 
              dir $(Build.SourcesDirectory)
            displayName: "Task 1: Set Checkouts"

          - task: UseDotNet@2
            displayName: 'Task 2: Install .NET 6.0 SDK'
            inputs:
              version: '6.0.x'

          - task: PowerShell@2
            displayName: "Task 3: Build MSSQL Artifacts"
            inputs:
              filePath: "$(WORKING_DIRECTORY)/.devops/scripts/build-script.ps1"
              arguments: > 
                -SourceDirectory "./src" 
                -ModifiedFiles $(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion)^..$(Build.SourceVersion))
                -DatatinoDevOpsGitRefUrl "../nl-cdb-be-apis"
              failOnStderr: true
              pwsh: true
              workingDirectory: $(WORKING_DIRECTORY)

          - task: CopyFiles@2
            displayName: "Task 4: Copy MSSQL Database Update Scripts"
            inputs:
              SourceFolder: '$(WORKING_DIRECTORY)'
              Contents: '*.sql'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/src'
              OverWrite: true

          - task: CopyFiles@2
            displayName: "Task 5: Copy Powershell Release Scripts"
            inputs:
              SourceFolder: "$(WORKING_DIRECTORY)/.devops/scripts"
              Contents: "**/*.ps1"
              TargetFolder: "$(Build.ArtifactStagingDirectory)/.devops/scripts"
              OverWrite: true

          - task: PublishBuildArtifacts@1
            displayName: "Task 6: Publish Artifacts"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"
