trigger: 
  branches:
    include:
      - main
      - master
      - release/*
      - develop/*
  paths:
    include:
      - "src/sln/"
      - ".devops/configs/"
    exclude:
      - "**/*.md"
      - "**/*.ps1"

resources:
  repositories: 
    - repository: nl-cdb-be-apis
      type: git
      name: "Corona Dashboard/nl-cdb-be-apis"

variables:
  WORKING_DIRECTORY: $(Build.SourcesDirectory)/$(Build.Repository.Name)

stages:
  - stage: Copy_to_Github
    jobs:
      - job: "Copy_to_Github"
        pool:
          vmImage: windows-2022
        steps:
        - bash: |
            git push --prune https://$(GITHUB_PAT)@github.com/minvws/nl-covid19-data-backend-processing \
                +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
          displayName: 'Copy to Github'

  - stage: Build
    jobs:
      - job: "Build_dacpac"
        pool:
          vmImage: windows-2022
        steps:
          - task: VSBuild@1
            inputs:
              solution: '**\*.sln'
              platform: 'Any CPU'
              configuration: 'Release'
              clean: true

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/src/sln/CoronaDashboard.BusinessLogic/'
              Contents: '**\*.dacpac'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'business-logic-database'
              publishLocation: 'Container'
      - job: "Build_Business_Logic"
        pool:
          vmImage: ubuntu-20.04
        steps:

          - checkout: self
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Get-Location
                (Get-ChildItem -Recurse).Fullname
          - task: CopyFiles@2
            displayName: "Task 5: Copy Powershell Release Scripts"
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)/.devops/scripts"
              Contents: "**/*.ps1"
              TargetFolder: "$(Build.ArtifactStagingDirectory)/.devops/scripts"
              OverWrite: true

          - task: CopyFiles@2
            displayName: "Task 5: Copy Powershell Release Scripts"
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)/.devops/configs"
              Contents: "**/*.json"
              TargetFolder: "$(Build.ArtifactStagingDirectory)/.devops/configs"
              OverWrite: true

          - task: PublishBuildArtifacts@1
            displayName: "Task 6: Publish Artifacts"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"
