# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - topic/*
 paths:
   include:
    - "src/sln/CoronaDashboard.BusinessLogic"

pool:
  vmImage: windows-latest

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    platform: 'Any CPU'
    configuration: 'Release'
    clean: true
