-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER VIEW [VWSDEST].[V_VWS_MAX_AND_MIN] AS
SELECT   DATEDIFF(SECOND,{d '1970-01-01'}, CONVERT(DATETIME, GETDATE(), 101)) AS DATE_OF_REPORT_UNIX, 
* 
FROM 
-- HOSPITAL ADMISSIONS  MAX/MIN
(SELECT MAX([MOVING_AVERAGE_HOSPITAL]) AS MAX_MOVING_AVERAGE_HOSPITAL
       ,MIN([MOVING_AVERAGE_HOSPITAL]) AS MIN_MOVING_AVERAGE_HOSPITAL
  FROM [VWSDEST].[V_HOSPITAL_ADMISSIONS]) a,

-- Verdenkingen Huisartsen MAX/MIN
(SELECT 
      MAX([INCIDENTIE]) AS MAX_INCIDENTIE
     ,MIN([INCIDENTIE]) AS MIN_INCIDENTIE
  FROM [VWSDEST].[V_GENERAL_PRACTITIONERS]) b,

-- Besmettelijke Personen Normalized (Timeline) MAX/MIN
(SELECT 
       MAX([INFECTIOUS_LOW_NORMALIZED]) AS MAX_INFECTIOUS_NORMALIZED_LOW
      ,MIN([INFECTIOUS_LOW_NORMALIZED]) AS MIN_INFECTIOUS_NORMALIZED_LOW
      ,MAX([INFECTIOUS_AVG_NORMALIZED]) AS MAX_INFECTIOUS_NORMALIZED_AVG
      ,MIN([INFECTIOUS_AVG_NORMALIZED]) AS MIN_INFECTIOUS_NORMALIZED_AVG
      ,MAX([INFECTIOUS_HIGH_NORMALIZED]) AS MAX_INFECTIOUS_NORMALIZED_HIGH
      ,MIN([INFECTIOUS_HIGH_NORMALIZED]) AS MIN_INFECTIOUS_NORMALIZED_HIGH
  FROM [VWSDEST].[V_INFECTIOUS_PEOPLE_NORMALIZED]) c,

-- Besmettelijke Personen (Timeline) MAX/MIN
(SELECT
       MAX([INFECTIOUS_LOW]) AS MAX_INFECTIOUS_LOW
      ,MIN([INFECTIOUS_LOW]) AS MIN_INFECTIOUS_LOW
      ,MAX([INFECTIOUS_AVG]) AS MAX_INFECTIOUS_AVG
      ,MIN([INFECTIOUS_AVG]) AS MIN_INFECTIOUS_AVG
      ,MAX([INFECTIOUS_HIGH]) AS MAX_INFECTIOUS_HIGH
      ,MIN([INFECTIOUS_HIGH]) AS MIN_INFECTIOUS_HIGH
  FROM [VWSDEST].[V_INFECTIOUS_PEOPLE]) d,

--Positief MAX/MIN
(SELECT MAX(INFECTED_DAILY_TOTAL) AS MAX_INFECTED_DAILY_TOTAL, 
       MIN(INFECTED_DAILY_TOTAL) AS MIN_INFECTED_DAILY_TOTAL
FROM VWSDEST.V_POSITIVE_TESTED_PEOPLE) e,

-- REGIO MAX/MIN      
(SELECT
      MAX([TOTAL_REPORTED_INCREASE_PER_REGION]) AS MAX_TOTAL_REPORTED_INCREASE_PER_REGION
      ,MIN([TOTAL_REPORTED_INCREASE_PER_REGION]) AS MIN_TOTAL_REPORTED_INCREASE_PER_REGION
      ,MAX([INFECTED_TOTAL_COUNTS_PER_REGION]) AS MAX_INFECTED_TOTAL_COUNTS_PER_REGION
      ,MIN([INFECTED_TOTAL_COUNTS_PER_REGION]) AS MIN_INFECTED_TOTAL_COUNTS_PER_REGION
      ,MAX([HOSPITAL_TOTAL_COUNTS_PER_REGION]) AS MAX_HOSPITAL_TOTAL_COUNTS_PER_REGION
      ,MIN([HOSPITAL_TOTAL_COUNTS_PER_REGION]) AS MIN_HOSPITAL_TOTAL_COUNTS_PER_REGION
      ,MAX([INFECTED_INCREASE_PER_REGION]) AS MAX_INFECTED_INCREASE_PER_REGION
      ,MIN([INFECTED_INCREASE_PER_REGION]) AS MIN_INFECTED_INCREASE_PER_REGION
      ,MAX([HOSPITAL_INCREASE_PER_REGION]) AS MAX_HOSPITAL_INCREASE_PER_REGION
      ,MIN([HOSPITAL_INCREASE_PER_REGION]) AS MIN_HOSPITAL_INCREASE_PER_REGION
      ,MAX([HOSPITAL_MOVING_AVG_PER_REGION]) AS MAX_HOSPITAL_MOVING_AVG_PER_REGION
      ,MIN([HOSPITAL_MOVING_AVG_PER_REGION]) AS MIN_HOSPITAL_MOVING_AVG_PER_REGION
  FROM [VWSDEST].[V_RESULTS_PER_REGION]
  WHERE VRCODE IS NOT NULL) f,


-- Reproductie MIN/MAX
(SELECT MAX([REPRODUCTION_INDEX_LOW]) MAX_REPRODUCTION_INDEX_LOW
      ,MIN([REPRODUCTION_INDEX_LOW]) MIN_REPRODUCTION_INDEX_LOW
      ,MAX([REPRODUCTION_INDEX_AVG]) MAX_REPRODUCTION_INDEX_AVG
      ,MIN([REPRODUCTION_INDEX_AVG]) MIN_REPRODUCTION_INDEX_AVG
      ,MAX([REPRODUCTION_INDEX_HIGH])MAX_REPRODUCTION_INDEX_HIGH
      ,MIN([REPRODUCTION_INDEX_HIGH])MIN_REPRODUCTION_INDEX_HIGH
  FROM [VWSDEST].[V_REPRODUCTION_NUMBER]) g,

-- IC Opnames MAX/MIN
(SELECT MAX([MOVING_AVERAGE_IC]) AS MAX_MOVING_AVERAGE_IC
      ,MIN([MOVING_AVERAGE_IC]) AS MIN_MOVING_AVERAGE_IC
  FROM [VWSDEST].[V_INTENSIVE_CARE_ADMISSIONS]) h,


-- Positief Geteste Personen Delta
(SELECT MAX([INFECTED_DAILY_INCREASE]) MAX_INFECTED_DAILY_INCREASE
       ,MIN([INFECTED_DAILY_INCREASE]) MIN_INFECTED_DAILY_INCREASE
  FROM [VWSDEST].[V_POSITIVE_TESTED_PEOPLE_DELTA]) i,

(SELECT 
       MAX([DECEASED_NURSERY_DAILY]) MAX_DECEASED_NURSERY_DAILY
      ,MIN([DECEASED_NURSERY_DAILY]) MIN_DECEASED_NURSERY_DAILY
  FROM [VWSDEST].[V_NURSING_HOMES_TOTALS_DECEASED]) j,

(SELECT 
       MAX([INFECTED_NURSERY_DAILY]) MAX_INFECTED_NURSERY_DAILY
      ,MIN([INFECTED_NURSERY_DAILY]) MIN_INFECTED_NURSERY_DAILY
  FROM [VWSDEST].[V_NURSING_HOMES_TOTALS_INFECTED]) k,

(SELECT 
       MAX([TOTAL_REPORTED_LOCATIONS]) MAX_TOTAL_REPORTED_LOCATIONS
      ,MIN([TOTAL_REPORTED_LOCATIONS]) MIN_TOTAL_REPORTED_LOCATIONS
  FROM [VWSDEST].[V_NURSING_HOMES_TOTALS_LOCATIONS]) l,

(SELECT 
       MAX([TOTAL_NEW_REPORTED_LOCATIONS]) MAX_TOTAL_NEW_REPORTED_LOCATIONS
      ,MIN([TOTAL_NEW_REPORTED_LOCATIONS]) MIN_TOTAL_NEW_REPORTED_LOCATIONS
  FROM [VWSDEST].[V_NURSING_HOMES_TOTALS_NEW_LOCATIONS]) m,

(SELECT MAX(AVERAGE) MAX_AVERAGE 
       ,MIN(AVERAGE) MIN_AVERAGE 
   FROM VWSDEST.V_SEWER_MEASUREMENTS) n,

(SELECT MAX([RNA_NORMALIZED]) AS MAX_LATEST_RNA_NORMALIZED
       ,MIN([RNA_NORMALIZED]) AS MIN_LATEST_RNA_NORMALIZED
   FROM VWSDEST.V_LATEST_SEWER_MEASUREMENTS_PER_RWZI) o,

(SELECT MAX(AVERAGE) MAX_AVERAGE_PER_REGION
       ,MIN(AVERAGE) MIN_AVERAGE_PER_REGION
   FROM VWSDEST.V_SEWER_MEASUREMENTS_PER_REGION) p,

(SELECT MAX([RNA_NORMALIZED]) AS MAX_RNA_NORMALIZED
       ,MIN([RNA_NORMALIZED]) AS MIN_RNA_NORMALIZED
    FROM VWSDEST.V_SEWER_MEASUREMENTS_PER_RWZI) q