-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Create view for pulling infectious people
CREATE OR ALTER VIEW VWSDEST.V_REPRODUCTION_NUMBER_LAST_KNOWN AS
SELECT
    [DATE_OF_REPORT_UNIX],
    DBO.NO_NEGATIVE_NUMBER_F(REPRODUCTION_INDEX_LOW) AS REPRODUCTION_INDEX_LOW,
    DBO.NO_NEGATIVE_NUMBER_F(REPRODUCTION_INDEX_AVG) AS REPRODUCTION_INDEX_AVG,
    DBO.NO_NEGATIVE_NUMBER_F(REPRODUCTION_INDEX_HIGH) AS REPRODUCTION_INDEX_HIGH,
    dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX
FROM VWSDEST.REPRODUCTION_NUMBER
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.REPRODUCTION_NUMBER)
AND REPRODUCTION_INDEX_AVG is not null
AND DATE_OF_REPORT_UNIX = (SELECT MAX(DATE_OF_REPORT_UNIX) FROM VWSDEST.REPRODUCTION_NUMBER WHERE REPRODUCTION_INDEX_AVG is not null AND DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.REPRODUCTION_NUMBER))