-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE VIEW [VWSDEST].[V_SEWER_MEASUREMENTS] AS
SELECT
         WEEK_UNIX
    ,   dbo.CONVERT_DATETIME_TO_UNIX(dbo.WEEK_START_FROM_WEEKNUMBER([WEEK])) AS WEEK_START_UNIX
    ,   dbo.CONVERT_DATETIME_TO_UNIX(dbo.WEEK_END_FROM_WEEKNUMBER([WEEK])) AS WEEK_END_UNIX
	,	[AVERAGE]
    ,   dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX
FROM VWSDEST.SEWER_MEASUREMENTS
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.SEWER_MEASUREMENTS)