-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER VIEW VWSDEST.V_ESCALATIONLEVELS_PER_REGION AS
SELECT
    [DATE_OF_REPORT_UNIX],
    VRCODE,
    ESCALATION_LEVEL,
    dbo.CONVERT_DATETIME_TO_UNIX(DATE_OF_START_VALIDITY) AS VALID_FROM_UNIX,
    dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX
FROM VWSDEST.ESCALATIONLEVELS_PER_REGION
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.ESCALATIONLEVELS_PER_REGION);