-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.


CREATE OR ALTER VIEW VWSDEST.V_HOSPITAL_ADMISSIONS_PER_REGION AS 
SELECT DATE_OF_REPORT_UNIX,
       VRCODE, 
   CAST(HOSPITAL_ADMISSIONS AS BIGINT) AS POSITIVE_TESTED_PEOPLE, 
       DATE_OF_INSERTION_UNIX
FROM (
SELECT
    [DATE_OF_REPORT_UNIX],
    VRCODE,
    DBO.NO_NEGATIVE_NUMBER_I(HOSPITAL_INCREASE_PER_REGION) AS HOSPITAL_ADMISSIONS,
    dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX,
    RANK() OVER (PARTITION BY VRCODE ORDER BY DATE_OF_REPORT_UNIX DESC) RANKING
FROM VWSDEST.RESULTS_PER_REGION
WHERE DATE_OF_REPORT >=  '2020-03-16 00:00:00.000'
AND DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.RESULTS_PER_REGION)
AND VRCODE IS NOT NULL
AND VRCODE != ' ') T1
WHERE T1.RANKING =1
AND VRCODE != NULL
;