-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Table with static information that supplies the amount of citizins per safety region
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('NL00', 'Nederland', 17408573);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR01', 'Groningen', 586061);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR02', 'Fryslân', 649944);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR03', 'Drenthe', 493657);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR04', 'IJsselland', 531354);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR05', 'Twente', 631146);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR06', 'Noord- en Oost-Gelderland', 827802);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR07', 'Gelderland-Midden', 696615);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR08', 'Gelderland-Zuid', 561725);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR09', 'Utrecht', 1354979);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR10', 'Noord-Holland-Noord', 662761);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR11', 'Zaanstreek-Waterland', 339116);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR12', 'Kennemerland', 550035);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR13', 'Amsterdam-Amstelland', 1070603);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR14', 'Gooi en Vechtstreek', 257096);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR15', 'Haaglanden', 1116334);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR16', 'Hollands-Midden', 808979);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR17', 'Rotterdam-Rijnmond', 1323816);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR18', 'Zuid-Holland-Zuid', 459456);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR19', 'Zeeland', 383519);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR20', 'Midden- en West-Brabant', 1119364);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR21', 'Brabant-Noord', 663315);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR22', 'Brabant-Zuidoost', 780753);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR23', 'Limburg-Noord', 520022);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR24', 'Limburg-Zuid', 597142);
INSERT INTO [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]([VGRNR],[VGRNAAM],[INHABITANTS]) VALUES('VR25', 'Flevoland', 422979);