-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF EXISTS ( SELECT RWZI_AWZI_CODE FROM VWSSTATIC.RWZI_AWZI WHERE RWZI_AWZI_CODE = '1023' )
    UPDATE VWSSTATIC.RWZI_AWZI SET RWZI_AWZI_NAME ='Zuidhorn 1' WHERE RWZI_AWZI_CODE = '1023'
ELSE
    INSERT INTO VWSSTATIC.RWZI_AWZI (RWZI_AWZI_CODE, RWZI_AWZI_NAME) VALUES ('1023', 'Zuidhorn 1')


IF EXISTS ( SELECT RWZI_CODE FROM VWSSTATIC.RWZI_GMCODE WHERE RWZI_CODE = '1023' )
    UPDATE VWSSTATIC.RWZI_GMCODE SET GM_CODE = 'GM1969' WHERE RWZI_CODE = '1023'
ELSE
    INSERT INTO VWSSTATIC.RWZI_GMCODE (RWZI_CODE, GM_CODE) VALUES ('1023' , 'GM1969')


IF EXISTS ( SELECT RWZI_AWZI_CODE FROM VWSSTATIC.RWZI_AWZI WHERE RWZI_AWZI_CODE = '1025' )
    UPDATE VWSSTATIC.RWZI_AWZI SET RWZI_AWZI_NAME ='Zuidhorn 2' WHERE RWZI_AWZI_CODE = '1025'
ELSE
    INSERT INTO VWSSTATIC.RWZI_AWZI (RWZI_AWZI_CODE, RWZI_AWZI_NAME) VALUES ('1025', 'Zuidhorn 2')


IF EXISTS ( SELECT RWZI_CODE FROM VWSSTATIC.RWZI_GMCODE WHERE RWZI_CODE = '1025' )
    UPDATE VWSSTATIC.RWZI_GMCODE SET GM_CODE = 'GM1969' WHERE RWZI_CODE = '1025'
ELSE
    INSERT INTO VWSSTATIC.RWZI_GMCODE (RWZI_CODE, GM_CODE) VALUES ('1025' , 'GM1969')
