-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_INFECTIOUS_PEOPLE')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_INFECTIOUS_PEOPLE
    ON VWSINTER.RIVM_INFECTIOUS_PEOPLE(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_FOUNDATION_NICE_IC_INTAKE_COUNT')
    CREATE NONCLUSTERED INDEX IX_INTER_FOUNDATION_NICE_IC_INTAKE_COUNT
    ON VWSINTER.FOUNDATION_NICE_IC_INTAKE_COUNT(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_REPRODUCTION_NUMBER')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_REPRODUCTION_NUMBER
    ON VWSINTER.RIVM_INFECTIOUS_PEOPLE(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_COVID_19_CASE_NATIONAL')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_COVID_19_CASE_NATIONAL
    ON VWSINTER.RIVM_COVID_19_CASE_NATIONAL(DATE_LAST_INSERTED, DATE_FILE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_NIVEL_SUSPICIONS_GENERAL_PRACTITIONERS')
    CREATE NONCLUSTERED INDEX IX_INTER_NIVEL_SUSPICIONS_GENERAL_PRACTITIONERS
    ON VWSINTER.NIVEL_SUSPICIONS_GENERAL_PRACTITIONERS(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_SEWER_MEASUREMENTS')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_SEWER_MEASUREMENTS
    ON VWSINTER.RIVM_SEWER_MEASUREMENTS(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_COVID_19_CASE_NATIONAL')
    CREATE NONCLUSTERED INDEX IX_RIVM_COVID_19_CASE_NATIONAL
    ON VWSSTAGE.RIVM_COVID_19_CASE_NATIONAL(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_FOUNDATION_NICE_IC_INTAKE_COUNT')
    CREATE NONCLUSTERED INDEX IX_FOUNDATION_NICE_IC_INTAKE_COUNT
    ON VWSSTAGE.FOUNDATION_NICE_IC_INTAKE_COUNT(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_NIVEL_SUSPICIONS_GENERAL_PRACTITIONERS')
    CREATE NONCLUSTERED INDEX IX_NIVEL_SUSPICIONS_GENERAL_PRACTITIONERS
    ON VWSSTAGE.NIVEL_SUSPICIONS_GENERAL_PRACTITIONERS(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_REPRODUCTION_NUMBER')
    CREATE NONCLUSTERED INDEX IX_RIVM_REPRODUCTION_NUMBER
    ON VWSSTAGE.RIVM_REPRODUCTION_NUMBER(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_INFECTIOUS_PEOPLE')
    CREATE NONCLUSTERED INDEX IX_RIVM_INFECTIOUS_PEOPLE
    ON VWSSTAGE.RIVM_INFECTIOUS_PEOPLE(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_SEWER_MEASUREMENTS')
    CREATE NONCLUSTERED INDEX IX_RIVM_SEWER_MEASUREMENTS
    ON VWSSTAGE.RIVM_SEWER_MEASUREMENTS(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_STAGE_RIVM_COVID_19_CASE_NATIONAL')
    CREATE NONCLUSTERED INDEX IX_STAGE_RIVM_COVID_19_CASE_NATIONAL
    ON VWSSTAGE.RIVM_COVID_19_CASE_NATIONAL (DATE_LAST_INSERTED) 
    INCLUDE (PROVINCE, HOSPITAL_ADMISSION, DECEASED, WEEK_OF_DEATH, MUNICIPAL_HEALTH_SERVICE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_STAGE_RIVM_COVID_19_NUMBER_MUNICIPALITY')
    CREATE NONCLUSTERED INDEX IX_STAGE_RIVM_COVID_19_NUMBER_MUNICIPALITY
    ON VWSSTAGE.RIVM_COVID_19_NUMBER_MUNICIPALITY (DATE_LAST_INSERTED) 
    INCLUDE (DATE_OF_REPORT, DATE_OF_PUBLICATION, MUNICIPALITY_CODE, MUNICIPALITY_NAME, PROVINCE, 
    SECURITY_REGION_CODE, SECURITY_REGION_NAME, MUNICIPAL_HEALTH_SERVICE, ROAZ_REGION, TOTAL_REPORTED, HOSPITAL_ADMISSION, DECEASED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_SEWER_MEASUREMENTS_DM')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_SEWER_MEASUREMENTS_DM
    ON VWSINTER.RIVM_SEWER_MEASUREMENTS (DATE_LAST_INSERTED) 
    INCLUDE (DATE_MEASUREMENT, RWZI_AWZI_CODE, RWZI_AWZI_NAME);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_STAGE_RIVM_SEWER_MEASUREMENTS')
    CREATE NONCLUSTERED INDEX IX_STAGE_RIVM_SEWER_MEASUREMENTS
    ON VWSSTAGE.RIVM_SEWER_MEASUREMENTS (DATE_LAST_INSERTED) 
    INCLUDE (DATE_MEASUREMENT, RWZI_AWZI_CODE, RWZI_AWZI_NAME, RNA_PER_ML);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY
    ON VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY (DATE_LAST_INSERTED) 
    INCLUDE (DATE_OF_PUBLICATION, SECURITY_REGION_CODE, TOTAL_REPORTED, HOSPITAL_ADMISSION, DECEASED)
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_MC')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_MC
    ON VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY (MUNICIPALITY_CODE) 
    INCLUDE (DATE_OF_PUBLICATION, MUNICIPALITY_NAME, TOTAL_REPORTED, DATE_LAST_INSERTED)
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_DLI')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_DLI
    ON VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY (DATE_LAST_INSERTED) 
    INCLUDE (DATE_OF_PUBLICATION, MUNICIPALITY_CODE, MUNICIPALITY_NAME, TOTAL_REPORTED)
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_FOUNDATION_NICE_IC_INTAKE_COUNT_DLI')
    CREATE NONCLUSTERED INDEX IX_INTER_FOUNDATION_NICE_IC_INTAKE_COUNT_DLI
    ON VWSINTER.FOUNDATION_NICE_IC_INTAKE_COUNT (DATE_LAST_INSERTED) 
    INCLUDE (DATE_OF_REPORT, VALUE)
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_MC_DP_MN_HA')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_MC_DP_MN_HA
    ON VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY (MUNICIPALITY_CODE) 
    INCLUDE (DATE_OF_PUBLICATION, MUNICIPALITY_NAME, HOSPITAL_ADMISSION)
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_MC_DP_MN_HA_DLI')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_MC_DP_MN_HA_DLI
    ON VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY (MUNICIPALITY_CODE) 
    INCLUDE (DATE_OF_PUBLICATION, MUNICIPALITY_NAME, HOSPITAL_ADMISSION, DATE_LAST_INSERTED)
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_DLI_DP_MC_MN_HA')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_DLI_DP_MC_MN_HA
    ON VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY (DATE_LAST_INSERTED) 
    INCLUDE (DATE_OF_PUBLICATION, MUNICIPALITY_CODE, MUNICIPALITY_NAME, HOSPITAL_ADMISSION)
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_STAGE_FOUNDATION_NICE_IC_INTAKE_COUNT')
    CREATE NONCLUSTERED INDEX IX_STAGE_FOUNDATION_NICE_IC_INTAKE_COUNT
    ON VWSSTAGE.FOUNDATION_NICE_IC_INTAKE_COUNT (DATE_LAST_INSERTED) 
    INCLUDE (DATE, VALUE)
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_ADMISSIONS_DOR')
    CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_DOR
    ON VWSDEST.HOSPITAL_ADMISSIONS (DATE_OF_REPORT) 
    INCLUDE (DATE_OF_REPORT_UNIX, MOVING_AVERAGE_HOSPITAL, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_ADMISSIONS_DLI_DOR')
    CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_DLI_DOR
    ON VWSDEST.HOSPITAL_ADMISSIONS (DATE_LAST_INSERTED, DATE_OF_REPORT) 
    INCLUDE (DATE_OF_REPORT_UNIX, MOVING_AVERAGE_HOSPITAL);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_DLI_DOR')
    CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_DLI_DOR
    ON VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY (DATE_LAST_INSERTED, DATE_OF_REPORT) 
    INCLUDE (DATE_OF_REPORT_UNIX, MUNICIPALITY_CODE, MUNICIPALITY_NAME, MOVING_AVERAGE_HOSPITAL);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY_DLI_DOR')
    CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY_DLI_DOR
    ON VWSDEST.POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY (DATE_LAST_INSERTED, DATE_OF_REPORT) 
    INCLUDE (DATE_OF_REPORT_UNIX, MUNICIPALITY_CODE, MUNICIPALITY_NAME, INFECTED_DAILY_TOTAL, INFECTED_DAILY_INCREASE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY_DLI')
    CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY_DLI
    ON VWSDEST.SEWER_MEASUREMENTS_PER_MUNICIPALITY (DATE_LAST_INSERTED) 
    INCLUDE (WEEK_UNIX, GMCODE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_MEASUREMENTS_PER_RWZI_DLI')
    CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_RWZI_DLI
    ON VWSDEST.SEWER_MEASUREMENTS_PER_RWZI (DATE_LAST_INSERTED) 
    INCLUDE (DATE_MEASUREMENT, DATE_MEASUREMENT_UNIX, WEEK, RWZI_AWZI_CODE, RWZI_AWZI_NAME, AVERAGE_RNA_FLOW_PER_100000);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_ARCHIVE_RIVM_COVID_19_CASE_NATIONAL')
    CREATE NONCLUSTERED INDEX IX_ARCHIVE_RIVM_COVID_19_CASE_NATIONAL 
    ON VWSARCHIVE.RIVM_COVID_19_CASE_NATIONAL_ARCHIVE_INTER (DATE_FILE, DATE_LAST_INSERTED)
    INCLUDE(AGEGROUP)
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_COVID_19_CASE_NATIONAL_DF')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_COVID_19_CASE_NATIONAL_DF
    ON VWSINTER.RIVM_COVID_19_CASE_NATIONAL (DATE_FILE)
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_MEASUREMENTS_PER_RWZI')
      CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_RWZI
      ON VWSDEST.SEWER_MEASUREMENTS_PER_RWZI (DATE_LAST_INSERTED)
      INCLUDE(DATE_MEASUREMENT, DATE_MEASUREMENT_UNIX, WEEK, RWZI_AWZI_CODE, RWZI_AWZI_NAME, AVERAGE_RNA_FLOW_PER_100000);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_MEASUREMENTS_PER_REGION')
      CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_REGION
      ON VWSDEST.SEWER_MEASUREMENTS_PER_REGION (DATE_LAST_INSERTED)
      INCLUDE(WEEK_UNIX, VRCODE, AVERAGE_RNA_FLOW_PER_100000);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION_DLI')
      CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION_DLI
      ON VWSDEST.POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION (DATE_LAST_INSERTED)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_GGD, PERCENTAGE_INFECTED_GGD, TOTAL_TESTED_GGD);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESULTS_PER_REGION_DOR_VR')
      CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DOR_VR
      ON VWSDEST.RESULTS_PER_REGION (DATE_OF_REPORT, VRCODE)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_INCREASE_PER_REGION, DATE_LAST_INSERTED);
GO


IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESULTS_PER_REGION_DOR_VR')
      CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DLI_DOR
      ON VWSDEST.RESULTS_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_INCREASE_PER_REGION);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESULTS_PER_REGION_DLI_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DLI_DOR
      ON VWSDEST.RESULTS_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_INCREASE_PER_REGION);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_POSITIVE_TESTED_PEOPLE_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_DOR
      ON VWSDEST.POSITIVE_TESTED_PEOPLE (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_DAILY_INCREASE, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_POSITIVE_TESTED_PEOPLE_DLI_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_DLI_DOR
      ON VWSDEST.POSITIVE_TESTED_PEOPLE (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_DAILY_INCREASE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_POSITIVE_TESTED_PEOPLE_DOR_DT')
      CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_DOR_DT
      ON VWSDEST.POSITIVE_TESTED_PEOPLE (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_DAILY_TOTAL);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_POSITIVE_TESTED_PEOPLE_DLI_DOR_DT')
      CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_DLI_DOR_DT
      ON VWSDEST.POSITIVE_TESTED_PEOPLE (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_DAILY_TOTAL);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_POSITIVE_TESTED_PEOPLE_DLI_DOR_DT')
      CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_DLI_DOR_DT
      ON VWSDEST.POSITIVE_TESTED_PEOPLE (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_DAILY_TOTAL);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_TOTALS_DOR_TNRL')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DOR_TNRL
      ON VWSDEST.NURSING_HOMES_TOTALS (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_NEW_REPORTED_LOCATIONS, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_TNRL')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_TNRL
      ON VWSDEST.NURSING_HOMES_TOTALS (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_NEW_REPORTED_LOCATIONS);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_TOTALS_DOR_TRL')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DOR_TRL
      ON VWSDEST.NURSING_HOMES_TOTALS (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_REPORTED_LOCATIONS, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_TRL')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_TRL
      ON VWSDEST.NURSING_HOMES_TOTALS (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_REPORTED_LOCATIONS);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_TOTALS_DOR_IND')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DOR_IND
      ON VWSDEST.NURSING_HOMES_TOTALS (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_NURSERY_DAILY, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_IND')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_IND
      ON VWSDEST.NURSING_HOMES_TOTALS (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_NURSERY_DAILY);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_TOTALS_DOR_DND')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DOR_DND
      ON VWSDEST.NURSING_HOMES_TOTALS (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, DECEASED_NURSERY_DAILY, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_TOTALS_DOR_DND')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DOR_DND
      ON VWSDEST.NURSING_HOMES_TOTALS (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, DECEASED_NURSERY_DAILY, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_DND')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_DND
      ON VWSDEST.NURSING_HOMES_TOTALS (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, DECEASED_NURSERY_DAILY);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_PER_REGION')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_PER_REGION
      ON VWSDEST.NURSING_HOMES_PER_REGION (DATE_LAST_INSERTED)
      INCLUDE([DATE_OF_REPORT_UNIX],[VRCODE],[INFECTED_NURSERY_DAILY],[DECEASED_NURSERY_DAILY]
            ,[TOTAL_NEW_REPORTED_LOCATIONS],[TOTAL_REPORTED_LOCATIONS],[INFECTED_LOCATIONS_PERCENTAGE]);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_MEASUREMENTS_PER_RWZI_DLI_2')
      CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_RWZI_DLI_2
      ON VWSDEST.SEWER_MEASUREMENTS_PER_RWZI (DATE_LAST_INSERTED)
      INCLUDE([DATE_MEASUREMENT],[DATE_MEASUREMENT_UNIX],[RWZI_AWZI_CODE],[RWZI_AWZI_NAME],[AVERAGE_RNA_FLOW_PER_100000]);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_INTENSIVE_CARE_ADMISSIONS_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_INTENSIVE_CARE_ADMISSIONS_DOR
      ON VWSDEST.INTENSIVE_CARE_ADMISSIONS (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, MOVING_AVERAGE_IC, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESULTS_PER_REGION_DOR_VR_HA')
      CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DOR_VR_HA
      ON VWSDEST.RESULTS_PER_REGION (DATE_OF_REPORT, VRCODE)
      INCLUDE(DATE_OF_REPORT_UNIX, HOSPITAL_INCREASE_PER_REGION, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESULTS_PER_REGION_DLI_DOR_HA')
      CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DLI_DOR_HA
      ON VWSDEST.RESULTS_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, HOSPITAL_INCREASE_PER_REGION);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_ADMISSIONS_DOR_2')
      CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_DOR_2
      ON VWSDEST.HOSPITAL_ADMISSIONS (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, MOVING_AVERAGE_HOSPITAL, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_ADMISSIONS_DLI_DOR_2')
      CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_DLI_DOR_2
      ON VWSDEST.HOSPITAL_ADMISSIONS (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, MOVING_AVERAGE_HOSPITAL);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_DOR
      ON VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, MUNICIPALITY_CODE, MOVING_AVERAGE_HOSPITAL, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_DLI_DOR_2')
      CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_DLI_DOR_2
      ON VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, MUNICIPALITY_CODE, MOVING_AVERAGE_HOSPITAL);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESULTS_PER_REGION_DOR_VR_DC')
      CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DOR_VR_DC
      ON VWSDEST.RESULTS_PER_REGION (DATE_OF_REPORT, VRCODE)
      INCLUDE(DATE_OF_REPORT_UNIX, DATE_LAST_INSERTED, DECEASED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESULTS_PER_REGION_DLI_DOR_DC')
      CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DLI_DOR_DC
      ON VWSDEST.RESULTS_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, DECEASED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESULTS_PER_REGION_DLI_DOR_DC')
      CREATE NONCLUSTERED INDEX IX_DATATINO_PROTO_DATATINO_PROTO_CONFIGURATIONS
      ON DATATINO_PROTO.PROTO_CONFIGURATIONS (ACTIVE, LAYOUT_ID)
      INCLUDE(PROTO_ID, ITEM_NAME, VIEW_ID, [CONSTRAINT], CONSTRAINT_KEY_NAME, 
            CONSTRAINT_VALUE, GROUPED, GROUPED_KEY_NAME, GROUPED_LAST_UPDATE_NAME);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_ESCALATIONLEVELS_PER_REGION_DEST')
    CREATE NONCLUSTERED INDEX IX_ESCALATIONLEVELS_PER_REGION_DEST
    ON VWSDEST.ESCALATIONLEVELS_PER_REGION(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_PER_SMALL_AGE_GROUP_DEST')
    CREATE NONCLUSTERED INDEX IX_POSITIVE_PER_SMALL_AGE_GROUP_DEST
    ON VWSDEST.POSITIVE_TESTED_PEOPLE_PER_SMALL_AGE_GROUP(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_PER_SMALL_AGE_GROUP_DEST')
    CREATE NONCLUSTERED INDEX IX_POSITIVE_PER_SMALL_AGE_GROUP_DEST
    ON VWSDEST.POSITIVE_TESTED_PEOPLE_PER_SMALL_AGE_GROUP(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWSDEST_DISABILITY_DEST')
    CREATE NONCLUSTERED INDEX IX_VWSDEST_DISABILITY_DEST
    ON VWSDEST.DISABILITY(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWSDEST_DISABILITY_VR')
    CREATE NONCLUSTERED INDEX IX_VWSDEST_DISABILITY_VR
    ON VWSDEST.DISABILITY_VR(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_NURSING_HOMES_COMBINED_INTER')
    CREATE NONCLUSTERED INDEX IX_RIVM_NURSING_HOMES_COMBINED_INTER
    ON VWSINTER.RIVM_NURSING_HOMES_COMBINED(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWSINTER_DISABILITY_INTER')
    CREATE NONCLUSTERED INDEX IX_VWSINTER_DISABILITY_INTER
    ON VWSINTER.DISABILITY(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWS_CORONALEVEL_REGIONS_STAGE')
    CREATE NONCLUSTERED INDEX IX_VWS_CORONALEVEL_REGIONS_STAGE
    ON VWSSTAGE.VWS_CORONALEVEL_REGIONS(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_NURSING_HOMES_COMBINED_STAGE')
    CREATE NONCLUSTERED INDEX IX_RIVM_NURSING_HOMES_COMBINED_STAGE
    ON VWSSTAGE.RIVM_NURSING_HOMES_COMBINED(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_SAFETY_REGIONS_PER_MUNICIPAL')
    CREATE NONCLUSTERED INDEX IX_SAFETY_REGIONS_PER_MUNICIPAL
    ON VWSSTATIC.SAFETY_REGIONS_PER_MUNICIPAL(GMCODE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INHABITANTS_PER_SAFETY_REGION')
    CREATE NONCLUSTERED INDEX IX_INHABITANTS_PER_SAFETY_REGION
    ON VWSSTATIC.INHABITANTS_PER_SAFETY_REGION(VGRNR);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INHABITANTS_PER_MUNICIPALITY')
    CREATE NONCLUSTERED INDEX IX_INHABITANTS_PER_MUNICIPALITY
    ON VWSSTATIC.INHABITANTS_PER_MUNICIPALITY(GMCODE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INHABITANTS_PER_MUNICIPALITY')
    CREATE NONCLUSTERED INDEX IX_INHABITANTS_PER_MUNICIPALITY
    ON VWSSTATIC.INHABITANTS_PER_MUNICIPALITY(GMCODE);
GO














IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_NURSING_HOME__DECEASED_DAILY_PER_REGION_DOR')
 CREATE NONCLUSTERED INDEX IX_DIFFERENCE_NURSING_HOME__DECEASED_DAILY_PER_REGION_DOR
      ON VWSDEST.NURSING_HOMES_PER_REGION (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, DECEASED_NURSERY_DAILY, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_NURSING_HOME__DECEASED_DAILY_PER_REGION_DLI_DOR')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_NURSING_HOME__DECEASED_DAILY_PER_REGION_DLI_DOR
      ON VWSDEST.NURSING_HOMES_PER_REGION (DATE_OF_REPORT, DATE_LAST_INSERTED)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, DECEASED_NURSERY_DAILY);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_NURSING_HOME__DECEASED_DAILY_PER_REGION_DOR_VR')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_NURSING_HOME__DECEASED_DAILY_PER_REGION_DOR_VR
      ON VWSDEST.NURSING_HOMES_PER_REGION (DATE_OF_REPORT)
      INCLUDE(VRCODE, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_NURSING_HOME__INFECTED_LOCATIONS_TOTAL_PER_REGION_VR_DOR')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_NURSING_HOME__INFECTED_LOCATIONS_TOTAL_PER_REGION_VR_DOR
      ON VWSDEST.NURSING_HOMES_PER_REGION (VRCODE, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_REPORTED_LOCATIONS, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_NURSING_HOME__INFECTED_LOCATIONS_TOTAL_PER_REGION_VR_DLI_DOR')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_NURSING_HOME__INFECTED_LOCATIONS_TOTAL_PER_REGION_VR_DLI_DOR
      ON VWSDEST.NURSING_HOMES_PER_REGION (VRCODE, DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_REPORTED_LOCATIONS);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_NURSING_HOME__INFECTED_LOCATIONS_TOTAL_PER_REGION_DOR')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_NURSING_HOME__INFECTED_LOCATIONS_TOTAL_PER_REGION_DOR
      ON VWSDEST.NURSING_HOMES_PER_REGION (VRCODE, DATE_OF_REPORT)
      INCLUDE(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_NURSING_HOME__NEWLY_INFECTED_PEOPLE_PER_REGION_DOR')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_NURSING_HOME__NEWLY_INFECTED_PEOPLE_PER_REGION_DOR
      ON VWSDEST.NURSING_HOMES_PER_REGION (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_NURSERY_DAILY, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_NURSING_HOME__NEWLY_INFECTED_PEOPLE_PER_REGION_DLI_DOR')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_NURSING_HOME__NEWLY_INFECTED_PEOPLE_PER_REGION_DLI_DOR
      ON VWSDEST.NURSING_HOMES_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_NURSERY_DAILY);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_RESULTS_PER_REGION__HOSPITAL_MOVING_AVG_PER_REGION_DLIR_DOR')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_RESULTS_PER_REGION__HOSPITAL_MOVING_AVG_PER_REGION_DLIR_DOR
      ON VWSDEST.RESULTS_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, HOSPITAL_MOVING_AVG_PER_REGION);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_RESULTS_PER_REGION__HOSPITAL_TOTAL_COUNTS_PER_REGION')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_RESULTS_PER_REGION__HOSPITAL_TOTAL_COUNTS_PER_REGION
      ON VWSDEST.RESULTS_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, HOSPITAL_TOTAL_COUNTS_PER_REGION);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_RESULTS_PER_REGION__TOTAL_REPORTED_INCREASE_PER_REGION_DLI_DOR')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_RESULTS_PER_REGION__TOTAL_REPORTED_INCREASE_PER_REGION_DLI_DOR
      ON VWSDEST.RESULTS_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, TOTAL_REPORTED_INCREASE_PER_REGION);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POS_TESTED_PEOPLE_PER_MUNICIPALITY_LAST_DOR')
CREATE NONCLUSTERED INDEX IX_POS_TESTED_PEOPLE_PER_MUNICIPALITY_LAST_DOR
      ON VWSDEST.POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, MUNICIPALITY_CODE, INFECTED_DAILY_TOTAL, INFECTED_DAILY_INCREASE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_TESTED_PEOPLE_PER_REGION_DOR_VR')
CREATE NONCLUSTERED INDEX IX_POSITIVE_TESTED_PEOPLE_PER_REGION_DOR_VR
      ON VWSDEST.RESULTS_PER_REGION (DATE_OF_REPORT, VRCODE)
      INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_REPORTED_INCREASE_PER_REGION, INFECTED_INCREASE_PER_REGION, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_TESTED_PEOPLE_PER_REGION_DLI_DOR')
CREATE NONCLUSTERED INDEX IX_POSITIVE_TESTED_PEOPLE_PER_REGION_DLI_DOR
      ON VWSDEST.RESULTS_PER_REGION (DATE_OF_REPORT, DATE_LAST_INSERTED)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, TOTAL_REPORTED_INCREASE_PER_REGION, INFECTED_INCREASE_PER_REGION);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_SEWER_MEASUREMENTS_PER_RWZI_RA_DLI')
CREATE NONCLUSTERED INDEX IX_SEWER_MEASUREMENTS_PER_RWZI_RA_DLI
      ON VWSDEST.SEWER_MEASUREMENTS_PER_RWZI (RWZI_AWZI_CODE, DATE_MEASUREMENT)
      INCLUDE(DATE_MEASUREMENT_UNIX, RWZI_AWZI_NAME, RNA_FLOW_PER_100000);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_SEWER_MEASUREMENTS_PER_RWZI_RA_DM')
CREATE NONCLUSTERED INDEX IX_SEWER_MEASUREMENTS_PER_RWZI_RA_DM
      ON VWSDEST.SEWER_MEASUREMENTS_PER_RWZI (RWZI_AWZI_CODE, DATE_MEASUREMENT)
      INCLUDE(DATE_MEASUREMENT_UNIX, RWZI_AWZI_NAME, RNA_FLOW_PER_100000, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_SEWER_MEASUREMENTS_PER_RWZI_DLI_VR')
CREATE NONCLUSTERED INDEX IX_SEWER_MEASUREMENTS_PER_RWZI_DLI_VR
      ON VWSDEST.SEWER_MEASUREMENTS_PER_RWZI ([DATE_LAST_INSERTED])
      INCLUDE([DATE_MEASUREMENT], [DATE_MEASUREMENT_UNIX], [RNA_FLOW_PER_100000], [RWZI_AWZI_CODE], [RWZI_AWZI_NAME]);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_RESULTS_PER_REGION__HOSPITAL_MOVING_AVG_PER_REGION_DOR_DLI')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_RESULTS_PER_REGION__HOSPITAL_MOVING_AVG_PER_REGION_DOR_DLI
      ON VWSDEST.RESULTS_PER_REGION (VRCODE, DATE_OF_REPORT, DATE_LAST_INSERTED)
      INCLUDE(DATE_OF_REPORT_UNIX, HOSPITAL_TOTAL_COUNTS_PER_REGION);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_RESULTS_PER_REGION__HOSPITAL_MOVING_AVG_PER_REGION_DOR_DLI')
CREATE NONCLUSTERED INDEX IX_DIFFERENCE_RESULTS_PER_REGION__HOSPITAL_MOVING_AVG_PER_REGION_DOR_DLI
      ON VWSDEST.RESULTS_PER_REGION (VRCODE, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_REPORTED_INCREASE_PER_REGION, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_RESULTS_PER_REGION__TOTAL_REPORTED_INCREASE_PER_REGION_DOR_DLI')
 CREATE NONCLUSTERED INDEX IX_DIFFERENCE_RESULTS_PER_REGION__TOTAL_REPORTED_INCREASE_PER_REGION_DOR_DLI
    ON VWSDEST.RESULTS_PER_REGION (VRCODE, DATE_OF_REPORT, DATE_LAST_INSERTED)
    INCLUDE(DATE_OF_REPORT_UNIX, HOSPITAL_TOTAL_COUNTS_PER_REGION);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DIFFERENCE_RESULTS_PER_REGION__HOSPITAL_MOVING_AVG_PER_REGION_VR_DOR')
    CREATE NONCLUSTERED INDEX IX_DIFFERENCE_RESULTS_PER_REGION__HOSPITAL_MOVING_AVG_PER_REGION_VR_DOR
    ON VWSDEST.RESULTS_PER_REGION (VRCODE, DATE_OF_REPORT)
    INCLUDE(DATE_OF_REPORT_UNIX, HOSPITAL_MOVING_AVG_PER_REGION, DATE_LAST_INSERTED);
GO

-- 26-1-21 additions based on R__Find_Missing_Indexes_With_Threshold
-- When pasting a new index, make sure no other with the same name or schema already exists.
IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_NICE_HOSPITAL_GM_BASE_GMCODE_DATE_LAST_INSERTED')
    CREATE NONCLUSTERED INDEX IX_NICE_HOSPITAL_GM_BASE_GMCODE_DATE_LAST_INSERTED ON [VWSDEST].[NICE_HOSPITAL_GM_BASE] ([GMCODE], [DATE_LAST_INSERTED]) INCLUDE ([DATE_OF_REPORT], [NEW_DATE_OF_REPORT_UNIX], [OLD_DATE_OF_REPORT_UNIX], [OLD_VALUE_REPORTED], [DIFFERENCE_REPORTED])
GO
IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_NICE_HOSPITAL_GM_BASE_GMCODE')
    CREATE NONCLUSTERED INDEX IX_NICE_HOSPITAL_GM_BASE_GMCODE ON [VWSDEST].[NICE_HOSPITAL_GM_BASE] ([GMCODE])
GO 
IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_GGD_TESTED_PEOPLE_VR_REGION_CODE_DATE_LAST_INSERTED')
    CREATE NONCLUSTERED INDEX IX_GGD_TESTED_PEOPLE_VR_REGION_CODE_DATE_LAST_INSERTED ON [VWSDEST].[GGD_TESTED_PEOPLE_VR] ([REGION_CODE], [DATE_LAST_INSERTED]) INCLUDE ([DATE_OF_STATISTICS])
GO
IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_GGD_TESTED_PEOPLE_VR_REGION_CODE')
    CREATE NONCLUSTERED INDEX IX_GGD_TESTED_PEOPLE_VR_REGION_CODE ON [VWSDEST].[GGD_TESTED_PEOPLE_VR] ([REGION_CODE]) INCLUDE ([DATE_OF_STATISTICS], [DATE_LAST_INSERTED])
GO

/* * Indexes on prod that where missing in codebase * */


/*
IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_NURSING_HOMES_DECEASED')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_NURSING_HOMES_DECEASED 
    ON [VWSINTER].[RIVM_NURSING_HOMES_DECEASED] ([DATE_LAST_INSERTED]) 
GO
*/

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_ADMISSIONS_DLI')
    CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_DLI 
    ON [VWSDEST].[HOSPITAL_ADMISSIONS] ([DATE_LAST_INSERTED]) 
    INCLUDE ([DATE_OF_REPORT],[DATE_OF_REPORT_UNIX],[TOTAL_COUNTS_PER_DAY],[MOVING_AVERAGE_HOSPITAL])
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RIVM_DECEASED_DAILY_VR_DLI')
    CREATE NONCLUSTERED INDEX IX_DEST_RIVM_DECEASED_DAILY_VR_DLI 
    ON [VWSDEST].[RIVM_DECEASED_DAILY_PER_REGION] ([DATE_LAST_INSERTED] ) 
    INCLUDE ([DATE_OF_REPORT],[DATE_OF_REPORT_UNIX],[DECEASED_ACTUAL],[VRCODE])
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY')
    CREATE NONCLUSTERED INDEX IX_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY 
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY] (MUNICIPALITY_CODE ) 
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY_TOTAL')
    CREATE NONCLUSTERED INDEX IX_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY_TOTAL 
    ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY] ([DATE_LAST_INSERTED], [DATE_OF_REPORT] ) 
    INCLUDE ([DATE_OF_REPORT_UNIX],[MUNICIPALITY_NAME],[MUNICIPALITY_CODE],[INFECTED_DAILY_TOTAL],[INFECTED_DAILY_INCREASE])
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_SEWER_MEASUREMENTS_PER_MUNICIPALITY')
    CREATE NONCLUSTERED INDEX IX_SEWER_MEASUREMENTS_PER_MUNICIPALITY 
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY] ([GMCODE] ) 
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY_DLI_WU')
    CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY_DLI_WU 
    ON [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY] ([DATE_LAST_INSERTED] ) 
    INCLUDE ([WEEK_UNIX],[GMCODE],[NUMBER_OF_MEASUREMENTS],[NUMBER_OF_LOCATIONS],[AVERAGE_RNA_FLOW_PER_100000])
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NICE_HOSPITAL_GM_DLI_2')
    CREATE NONCLUSTERED INDEX IX_DEST_NICE_HOSPITAL_GM_DLI_2 
    ON [VWSDEST].[NICE_HOSPITAL_GM] ([DATE_LAST_INSERTED] ) 
    INCLUDE ([DATE_OF_STATISTICS],[GM_CODE],[GM_NAME],[REPORTED],[HOSPITALIZED])
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_STAGE_RIVM_INFECTIOUS_PEOPLE_DLI')
    CREATE NONCLUSTERED INDEX IX_STAGE_RIVM_INFECTIOUS_PEOPLE_DLI 
    ON [VWSSTAGE].[RIVM_INFECTIOUS_PEOPLE] ([DATE_LAST_INSERTED] ) 
    INCLUDE ([DATE],[PREV_LOW],[PREV_AVG],[PREV_UP])
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY')
    CREATE NONCLUSTERED INDEX IX_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY 
    ON [VWSDEST].[HOSPITAL_ADMISSIONS_PER_MUNICIPALITY] ([MUNICIPALITY_CODE] ) 
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_TOTAL')
    CREATE NONCLUSTERED INDEX IX_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_TOTAL 
    ON [VWSDEST].[HOSPITAL_ADMISSIONS_PER_MUNICIPALITY] ([MUNICIPALITY_CODE],[DATE_LAST_INSERTED],[DATE_OF_REPORT] ) 
GO

--Indexes on redundant tables
/*
IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_CLUSTERS_INFECTED_PEOPLE')
    CREATE NONCLUSTERED INDEX IX_RIVM_CLUSTERS_INFECTED_PEOPLE 
    ON [VWSINTER].[RIVM_CLUSTERS_INFECTED_PEOPLE] ([DATE_LAST_INSERTED] ) 
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_CUMULATIVE')
    CREATE NONCLUSTERED INDEX IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_CUMULATIVE 
    ON [VWSINTER].[RIVM_COVID_19_NUMBER_MUNICIPALITY_CUMULATIVE] ([DATE_LAST_INSERTED], [MUNICIPALITY_CODE] ) 
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_COVID_19_NUMBER_MUNICIPALITY_CUMULATIVE')
    CREATE NONCLUSTERED INDEX IX_RIVM_COVID_19_NUMBER_MUNICIPALITY_CUMULATIVE 
    ON [VWSSTAGE].[RIVM_COVID_19_NUMBER_MUNICIPALITY_CUMULATIVE]( [DATE_LAST_INSERTED]) 
GO
*/

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_PROTO_CONFIGURATIONS_PROTO_ID_ACTIVE')
    CREATE NONCLUSTERED INDEX [IX_PROTO_CONFIGURATIONS_PROTO_ID_ACTIVE] 
    ON [DATATINO_PROTO].[PROTO_CONFIGURATIONS] ([PROTO_ID], [ACTIVE])
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_DECEASED_DAILY_PER_MUNICIPALITY_MUNICIPALITY_CODE_DATE_LAST_INSERTED')
    CREATE NONCLUSTERED INDEX [IX_RIVM_DECEASED_DAILY_PER_MUNICIPALITY_MUNICIPALITY_CODE_DATE_LAST_INSERTED] 
    ON [VWSDEST].[RIVM_DECEASED_DAILY_PER_MUNICIPALITY] ([MUNICIPALITY_CODE], [DATE_LAST_INSERTED]) 
    INCLUDE ([DATE_OF_REPORT], [DATE_OF_REPORT_UNIX], [OLD_DATE_OF_REPORT_UNIX], [OLD_VALUE], [DIFFERENCE])
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_RWZI_INHIBITANTS_2021_DATE_LAST_INSERTED')
    CREATE NONCLUSTERED INDEX [IX_RIVM_RWZI_INHIBITANTS_2021_DATE_LAST_INSERTED] 
    ON [VWSSTATIC].[RWZI_INHIBITANTS_2021] ([DATE_LAST_INSERTED], [GEBIEDSCODE]) 
    INCLUDE ([CODE_RWZI], [PERCENTAGE])
GO

