-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_ELDERLY_AT_HOME_VR_DLI_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_ELDERLY_AT_HOME_VR_DLI_DOR
      ON VWSDEST.ELDERLY_AT_HOME_VR (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_ELDERLY_AT_HOME_DAILY, INFECTED_ELDERLY_AT_HOME_DAILY_PER_100K, DECEASED_ELDERLY_AT_HOME_DAILY);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NICE_HOSPITAL_VR_DLI_DS')
      CREATE NONCLUSTERED INDEX IX_DEST_NICE_HOSPITAL_VR_DLI_DS
      ON VWSDEST.NICE_HOSPITAL_VR (DATE_LAST_INSERTED, DATE_OF_STATISTICS)
      INCLUDE(VR_CODE, HOSPITALIZED_CUMULATIVE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NICE_HOSPITAL_VR')
      CREATE NONCLUSTERED INDEX IX_DEST_NICE_HOSPITAL_VR
      ON VWSDEST.NICE_HOSPITAL_VR (DATE_LAST_INSERTED, DATE_OF_STATISTICS)
      INCLUDE(VR_CODE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NICE_HOSPITAL_VR_AVG')
      CREATE NONCLUSTERED INDEX IX_DEST_NICE_HOSPITAL_VR_AVG
      ON VWSDEST.NICE_HOSPITAL_VR (DATE_LAST_INSERTED, DATE_OF_STATISTICS)
      INCLUDE(VR_CODE, HOSPITALIZED_3D_AVG);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_MEASUREMENTS_PER_REGION_VR')
      CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_REGION_VR
      ON VWSDEST.SEWER_MEASUREMENTS_PER_REGION (VRCODE)
      INCLUDE(WEEK_UNIX, NUMBER_OF_LOCATIONS, AVERAGE_RNA_FLOW_PER_100000, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_MEASUREMENTS_PER_REGION_DLI')
      CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_REGION_DLI
      ON VWSDEST.SEWER_MEASUREMENTS_PER_REGION (DATE_LAST_INSERTED)
      INCLUDE(WEEK_UNIX, VRCODE, NUMBER_OF_LOCATIONS, AVERAGE_RNA_FLOW_PER_100000);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_STATIC_RWZI_GMCODE')
      CREATE NONCLUSTERED INDEX IX_STATIC_RWZI_GMCODE
      ON VWSSTATIC.RWZI_GMCODE (DATE_LAST_INSERTED)
      INCLUDE(RWZI_CODE, GM_CODE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY')
      CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY
      ON VWSDEST.SEWER_MEASUREMENTS_PER_MUNICIPALITY (DATE_LAST_INSERTED)
      INCLUDE(WEEK_UNIX, GMCODE, NUMBER_OF_LOCATIONS, AVERAGE_RNA_FLOW_PER_100000);
GO
      
IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY')
      CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY
      ON VWSDEST.RIVM_DECEASED_PER_WEEK (WEEK_START)
      INCLUDE(WEEK_START_UNIX, DECEASED_ACTUAL, VRCODE, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY_DLI_WS')
      CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_MUNICIPALITY_DLI_WS
      ON VWSDEST.RIVM_DECEASED_PER_WEEK (DATE_LAST_INSERTED, WEEK_START)
      INCLUDE(WEEK_START_UNIX, DECEASED_ACTUAL, VRCODE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESULTS_PER_REGION_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DOR
      ON VWSDEST.RESULTS_PER_REGION (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, TOTAL_REPORTED_INCREASE_PER_REGION, INFECTED_TOTAL_COUNTS_PER_REGION, INFECTED_INCREASE_PER_REGION, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESULTS_PER_REGION_DLI')
      CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DLI
      ON VWSDEST.RESULTS_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, TOTAL_REPORTED_INCREASE_PER_REGION, INFECTED_TOTAL_COUNTS_PER_REGION, INFECTED_INCREASE_PER_REGION);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESTRICTIONS_PER_REGION_DLI')
      CREATE NONCLUSTERED INDEX IX_DEST_RESTRICTIONS_PER_REGION_DLI
      ON VWSDEST.RESTRICTIONS_PER_REGION (DATE_LAST_INSERTED)
      INCLUDE(VRCODE, RESTRICTION_ID, ESCALATION_LEVEL, CATEGORY_ID, RESTRICTION_ORDER, VALID_FROM);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_REPRODUCTION_NUMBER_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_REPRODUCTION_NUMBER_DOR
      ON VWSDEST.REPRODUCTION_NUMBER (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, REPRODUCTION_INDEX_LOW, REPRODUCTION_INDEX_AVG, REPRODUCTION_INDEX_HIGH, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_REPRODUCTION_NUMBER_DLI_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_REPRODUCTION_NUMBER_DLI_DOR
      ON VWSDEST.REPRODUCTION_NUMBER (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, REPRODUCTION_INDEX_LOW, REPRODUCTION_INDEX_AVG, REPRODUCTION_INDEX_HIGH);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION_DLI_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION_DLI_DOR
      ON VWSDEST.POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION (DATE_LAST_INSERTED)
      INCLUDE(DATE_OF_REPORT, DATE_OF_REPORT_UNIX, VRCODE, INFECTED_GGD, PERCENTAGE_INFECTED_GGD, TOTAL_TESTED_GGD);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_INFECTIOUS_PEOPLE_DLI')
      CREATE NONCLUSTERED INDEX IX_DEST_INFECTIOUS_PEOPLE_DLI
      ON VWSDEST.INFECTIOUS_PEOPLE(DATE_LAST_INSERTED)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTIOUS_LOW, INFECTIOUS_AVG, INFECTIOUS_HIGH);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_BED_OCCUPANCY_DLI')
      CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_BED_OCCUPANCY_DLI
      ON VWSDEST.HOSPITAL_BED_OCCUPANCY (DATE_LAST_INSERTED)
      INCLUDE(DATE_OF_REPORT_UNIX, NON_IC_BEDS_OCCUPIED_COVID);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOME_REGIONS_DOR_VR')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOME_REGIONS_DOR_VR
      ON VWSDEST.NURSING_HOMES_PER_REGION (DATE_OF_REPORT, VRCODE)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_NURSERY_DAILY, DECEASED_NURSERY_DAILY, TOTAL_NEW_REPORTED_LOCATIONS, TOTAL_REPORTED_LOCATIONS, iNFECTED_LOCATIONS_PERCENTAGE, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOME_REGIONS_DLI_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOME_REGIONS_DLI_DOR
      ON VWSDEST.NURSING_HOMES_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_NURSERY_DAILY, DECEASED_NURSERY_DAILY, TOTAL_NEW_REPORTED_LOCATIONS, TOTAL_REPORTED_LOCATIONS, iNFECTED_LOCATIONS_PERCENTAGE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_DISABILITY_VR_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_DISABILITY_VR_DOR
      ON VWSDEST.DISABILITY_VR (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_DISABILITY_DAILY, DECEASED_DISABILITY_DAILY, TOTAL_NEW_INFECTED_LOCATIONS, TOTAL_INFECTED_LOCATIONS, PERCENTAGE_INFECTED_LOCATIONS, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_DISABILITY_VR_DLI')
      CREATE NONCLUSTERED INDEX IX_DEST_DISABILITY_VR_DLI
      ON VWSDEST.DISABILITY_VR (DATE_LAST_INSERTED)
      INCLUDE(DATE_OF_REPORT);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_DISABILITY_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_DISABILITY_DOR
      ON VWSDEST.DISABILITY (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_DISABILITY_DAILY, DECEASED_DISABILITY_DAILY, TOTAL_NEW_INFECTED_LOCATIONS, TOTAL_INFECTED_LOCATIONS, PERCENTAGE_INFECTED_LOCATIONS, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_ELDERLY_AT_HOME_VR_DLI_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_ELDERLY_AT_HOME_VR_DLI_DOR
      ON VWSDEST.ELDERLY_AT_HOME_VR (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_ELDERLY_AT_HOME_DAILY, INFECTED_ELDERLY_AT_HOME_DAILY_PER_100K, DECEASED_ELDERLY_AT_HOME_DAILY);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_CBS_DECEASED_PER_WEEK_WS')
      CREATE NONCLUSTERED INDEX IX_DEST_CBS_DECEASED_PER_WEEK_WS
      ON VWSDEST.CBS_DECEASED_PER_WEEK (WEEK_START)
      INCLUDE(WEEK_START_UNIX, WEEK_END_UNIX, DECEASED_ACTUAL, DECEASED_FORECAST, DECEASED_FORECAST_HIGH, DECEASED_FORECAST_LOW, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_CBS_DECEASED_PER_WEEK_DLI_WS')
      CREATE NONCLUSTERED INDEX IX_DEST_CBS_DECEASED_PER_WEEK_DLI_WS
      ON VWSDEST.CBS_DECEASED_PER_WEEK (DATE_LAST_INSERTED, WEEK_START)
      INCLUDE(WEEK_START_UNIX, WEEK_END_UNIX, DECEASED_ACTUAL, DECEASED_FORECAST, DECEASED_FORECAST_HIGH, DECEASED_FORECAST_LOW);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_BED_OCCUPANCY_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_BED_OCCUPANCY_DOR
      ON VWSDEST.HOSPITAL_BED_OCCUPANCY (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, NON_IC_BEDS_OCCUPIED_COVID, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_BED_OCCUPANCY_DOR_DLI')
      CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_BED_OCCUPANCY_DOR_DLI
      ON VWSDEST.HOSPITAL_BED_OCCUPANCY (DATE_OF_REPORT)
      INCLUDE(DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_INFECTIOUS_PEOPLE_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_INFECTIOUS_PEOPLE_DOR
      ON VWSDEST.INFECTIOUS_PEOPLE (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTIOUS_AVG_NORMALIZED, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_INTENSIVE_CARE_ADMISSIONS_DLI_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_INTENSIVE_CARE_ADMISSIONS_DLI_DOR
      ON VWSDEST.INTENSIVE_CARE_ADMISSIONS (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, MOVING_AVERAGE_IC);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_HOSPITAL_BED_OCCUPANCY_DOR_2')
      CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_BED_OCCUPANCY_DOR_2
      ON VWSDEST.HOSPITAL_BED_OCCUPANCY (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, IC_BEDS_OCCUPIED_COVID, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_DISABILITY_VR_DLI_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_DISABILITY_VR_DLI_DOR
      ON VWSDEST.DISABILITY_VR (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_DISABILITY_DAILY, DECEASED_DISABILITY_DAILY, TOTAL_NEW_INFECTED_LOCATIONS, TOTAL_INFECTED_LOCATIONS, PERCENTAGE_INFECTED_LOCATIONS);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_INFECTIOUS_PEOPLE_DLI_ALL')
      CREATE NONCLUSTERED INDEX IX_DEST_INFECTIOUS_PEOPLE_DLI_ALL
      ON VWSDEST.INFECTIOUS_PEOPLE (DATE_LAST_INSERTED)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTIOUS_LOW_NORMALIZED, INFECTIOUS_AVG_NORMALIZED, INFECTIOUS_HIGH_NORMALIZED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_STATIC_SAFETY_REGIONS_PER_MUNICIPAL_DLI')
      CREATE NONCLUSTERED INDEX IX_STATIC_SAFETY_REGIONS_PER_MUNICIPAL_DLI
      ON VWSSTATIC.SAFETY_REGIONS_PER_MUNICIPAL (DATE_LAST_INSERTED)
      INCLUDE(GMNAAM, VRCODE);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_TOTALS_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DOR
      ON VWSDEST.NURSING_HOMES_TOTALS (DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_NURSERY_DAILY, DECEASED_NURSERY_DAILY, TOTAL_NEW_REPORTED_LOCATIONS, TOTAL_REPORTED_LOCATIONS, DATE_LAST_INSERTED);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR')
      CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR
      ON VWSDEST.NURSING_HOMES_TOTALS (DATE_LAST_INSERTED, DATE_OF_REPORT)
      INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_NURSERY_DAILY, DECEASED_NURSERY_DAILY, TOTAL_NEW_REPORTED_LOCATIONS, TOTAL_REPORTED_LOCATIONS);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_RESTRICTIONS_PER_REGION_DLI_ALL')
      CREATE NONCLUSTERED INDEX IX_DEST_RESTRICTIONS_PER_REGION_DLI_ALL
      ON VWSDEST.RESTRICTIONS_PER_REGION (DATE_LAST_INSERTED)
      INCLUDE(VRCODE, RESTRICTION_ID, TARGET_REGION, ESCALATION_LEVEL, CATEGORY_ID, RESTRICTION_ORDER, VALID_FROM);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_NICE_HOSPITAL_VR_DLI')
      CREATE NONCLUSTERED INDEX IX_DEST_NICE_HOSPITAL_VR_DLI
      ON VWSDEST.NICE_HOSPITAL_VR (DATE_LAST_INSERTED)
      INCLUDE(DATE_OF_STATISTICS, VR_CODE, HOSPITALIZED, HOSPITALIZED_3D_AVG, HOSPITALIZED_CUMULATIVE);
GO


IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_DEST_SEWER_BASE')
      CREATE NONCLUSTERED INDEX IX_DEST_SEWER_BASE
      ON VWSDEST.SEWER_BASE (DATE_LAST_INSERTED, COUNT_DAILY_MEASUREMENT, RWZI_AWZI_CODE, WEEK_UNIX)
      INCLUDE(RNA_PER_ML, RNA_FLOW_PER_100000);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_SEWER_MEASUREMENTS_PER_RWZI_MINIMAL')
      CREATE NONCLUSTERED INDEX IX_SEWER_MEASUREMENTS_PER_RWZI_MINIMAL
      ON VWSDEST.SEWER_MEASUREMENTS_PER_RWZI_MINIMAL (DATE_LAST_INSERTED, GMCODE, RWZI_AWZI_NAME);      
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_2')
      CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_2] ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]
      (
      [GMCODE],
      [DATE_OF_REPORT]
      )
      INCLUDE([DATE_LAST_INSERTED])
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_3')
      CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_3] ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]
      (
      [GMCODE],
      [DATE_LAST_INSERTED],
      [DATE_OF_REPORT]
      )
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_4')
      CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_4]
      ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]
      (
      [DATE_LAST_INSERTED] ASC
      )

       INCLUDE (
      [DATE_OF_REPORT]
      ,[NEW_DATE_OF_REPORT_UNIX]
      ,[GMCODE]
      ,[OLD_DATE_OF_REPORT_UNIX]
      ,[OLD_VALUE]
      ,[DIFFERENCE]
      )
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_5')
      CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_5]
      ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]
      (
      [DATE_OF_REPORT] ASC
      )

      INCLUDE ([GMCODE], [DATE_LAST_INSERTED])
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_6')
      CREATE NONCLUSTERED INDEX [IX_POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE_6]
      ON [VWSDEST].[POSITIVE_TESTED_PEOPLE_INFECTED_DAILY_INCREASE_BASE]
      (
      [GMCODE] ASC
      )

      INCLUDE (
       [DATE_OF_REPORT]
      ,[NEW_DATE_OF_REPORT_UNIX]
      ,[OLD_DATE_OF_REPORT_UNIX]
      ,[OLD_VALUE]
      ,[DIFFERENCE]
      ,[DATE_LAST_INSERTED]
      )
GO


IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_COVID_19_CASE_NATIONAL_STAGE_CI')
      CREATE CLUSTERED INDEX [IX_RIVM_COVID_19_CASE_NATIONAL_STAGE_CI] ON [VWSSTAGE].[RIVM_COVID_19_CASE_NATIONAL]
      (
      	[DATE_LAST_INSERTED] ASC
      )
GO


IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_RIVM_COVID_19_CASE_NATIONAL_CI')
      CREATE CLUSTERED INDEX [IX_RIVM_COVID_19_CASE_NATIONAL_CI] ON [VWSINTER].[RIVM_COVID_19_CASE_NATIONAL]
      (
      	[DATE_LAST_INSERTED] ASC
      )
GO

