-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_RWZI
ON VWSDEST.SEWER_MEASUREMENTS_PER_RWZI (DATE_LAST_INSERTED)
INCLUDE(DATE_MEASUREMENT, DATE_MEASUREMENT_UNIX, WEEK, RWZI_AWZI_CODE, RWZI_AWZI_NAME, VRCODE, VRNAAM, RNA_PER_ML);

CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_REGION
ON VWSDEST.SEWER_MEASUREMENTS_PER_REGION (DATE_LAST_INSERTED)
INCLUDE(WEEK, WEEK_UNIX, VRCODE, AVERAGE);

CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION_DLI
ON VWSDEST.POSITIVE_TESTED_PEOPLE_PERCENTAGE_PER_REGION (DATE_LAST_INSERTED)
INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_GGD, PERCENTAGE_INFECTED_GGD, TOTAL_TESTED_GGD);

CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DOR_VR
ON VWSDEST.RESULTS_PER_REGION (DATE_OF_REPORT, VRCODE)
INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_INCREASE_PER_REGION, DATE_LAST_INSERTED);

CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DLI_DOR
ON VWSDEST.RESULTS_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, INFECTED_INCREASE_PER_REGION);

CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_DOR
ON VWSDEST.POSITIVE_TESTED_PEOPLE (DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_DAILY_INCREASE, DATE_LAST_INSERTED);

CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_DLI_DOR
ON VWSDEST.POSITIVE_TESTED_PEOPLE (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_DAILY_INCREASE);

CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_DOR_DT
ON VWSDEST.POSITIVE_TESTED_PEOPLE (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_DAILY_TOTAL);

CREATE NONCLUSTERED INDEX IX_DEST_POSITIVE_TESTED_PEOPLE_DLI_DOR_DT
ON VWSDEST.POSITIVE_TESTED_PEOPLE (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_DAILY_TOTAL);

CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DOR_TNRL
ON VWSDEST.NURSING_HOMES_TOTALS (DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_NEW_REPORTED_LOCATIONS, DATE_LAST_INSERTED);

CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_TNRL
ON VWSDEST.NURSING_HOMES_TOTALS (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_NEW_REPORTED_LOCATIONS);

CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DOR_TRL
ON VWSDEST.NURSING_HOMES_TOTALS (DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_REPORTED_LOCATIONS, DATE_LAST_INSERTED);

CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_TRL
ON VWSDEST.NURSING_HOMES_TOTALS (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, TOTAL_REPORTED_LOCATIONS);

CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DOR_IND
ON VWSDEST.NURSING_HOMES_TOTALS (DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_NURSERY_DAILY, DATE_LAST_INSERTED);

CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_IND
ON VWSDEST.NURSING_HOMES_TOTALS (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, INFECTED_NURSERY_DAILY);

CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DOR_DND
ON VWSDEST.NURSING_HOMES_TOTALS (DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, DECEASED_NURSERY_DAILY, DATE_LAST_INSERTED);

CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_TOTALS_DLI_DOR_DND
ON VWSDEST.NURSING_HOMES_TOTALS (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, DECEASED_NURSERY_DAILY);

CREATE NONCLUSTERED INDEX IX_DEST_NURSING_HOMES_PER_REGION
ON VWSDEST.NURSING_HOMES_PER_REGION (DATE_LAST_INSERTED)
INCLUDE([DATE_OF_REPORT_UNIX],[VRCODE],[INFECTED_NURSERY_DAILY],[DECEASED_NURSERY_DAILY]
      ,[TOTAL_NEW_REPORTED_LOCATIONS],[TOTAL_REPORTED_LOCATIONS],[INFECTED_LOCATIONS_PERCENTAGE]);

CREATE NONCLUSTERED INDEX IX_DEST_SEWER_MEASUREMENTS_PER_RWZI_DLI_2
ON VWSDEST.SEWER_MEASUREMENTS_PER_RWZI (DATE_LAST_INSERTED)
INCLUDE([DATE_MEASUREMENT],[DATE_MEASUREMENT_UNIX],[RWZI_AWZI_CODE],[RWZI_AWZI_NAME],[VRCODE],[VRNAAM],[RNA_PER_ML]);

CREATE NONCLUSTERED INDEX IX_DEST_INTENSIVE_CARE_ADMISSIONS_DOR
ON VWSDEST.INTENSIVE_CARE_ADMISSIONS (DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, MOVING_AVERAGE_IC, DATE_LAST_INSERTED);

CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DOR_VR_HA
ON VWSDEST.RESULTS_PER_REGION (DATE_OF_REPORT, VRCODE)
INCLUDE(DATE_OF_REPORT_UNIX, HOSPITAL_INCREASE_PER_REGION, DATE_LAST_INSERTED);

CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DLI_DOR_HA
ON VWSDEST.RESULTS_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, HOSPITAL_INCREASE_PER_REGION);

CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_DOR_2
ON VWSDEST.HOSPITAL_ADMISSIONS (DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, MOVING_AVERAGE_HOSPITAL, DATE_LAST_INSERTED);

CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_DLI_DOR_2
ON VWSDEST.HOSPITAL_ADMISSIONS (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, MOVING_AVERAGE_HOSPITAL);

CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_DOR
ON VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY (DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, MUNICIPALITY_CODE, MOVING_AVERAGE_HOSPITAL, DATE_LAST_INSERTED);

CREATE NONCLUSTERED INDEX IX_DEST_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY_DLI_DOR_2
ON VWSDEST.HOSPITAL_ADMISSIONS_PER_MUNICIPALITY (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, MUNICIPALITY_CODE, MOVING_AVERAGE_HOSPITAL);

CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DOR_VR_DC
ON VWSDEST.RESULTS_PER_REGION (DATE_OF_REPORT, VRCODE)
INCLUDE(DATE_OF_REPORT_UNIX, DATE_LAST_INSERTED, DECEASED);

CREATE NONCLUSTERED INDEX IX_DEST_RESULTS_PER_REGION_DLI_DOR_DC
ON VWSDEST.RESULTS_PER_REGION (DATE_LAST_INSERTED, DATE_OF_REPORT)
INCLUDE(DATE_OF_REPORT_UNIX, VRCODE, DECEASED);

CREATE NONCLUSTERED INDEX IX_DATATINO_PROTO_DATATINO_PROTO_CONFIGURATIONS
ON DATATINO_PROTO.PROTO_CONFIGURATIONS (ACTIVE, LAYOUT_ID)
INCLUDE(PROTO_ID, ITEM_NAME, VIEW_ID, [CONSTRAINT], CONSTRAINT_KEY_NAME, CONSTRAINT_VALUE, GROUPED, GROUPED_KEY_NAME, GROUPED_LAST_UPDATE_NAME);