CREATE TABLE [DATATINO_PROTO].[ITEM_SCHEDULE] (
    [ID]          INT    DEFAULT (NEXT VALUE FOR [dbo].[SEQ_DATATINO_PROTO_ITEM_SCHEDULE]) NOT NULL,
    [WORKFLOW_ID] BIGINT NULL,
    [PROTO_ID]    BIGINT NULL,
    [ITEM_ID]     BIGINT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

