CREATE TABLE [DATATINO_PROTO].[LAYOUTS] (
    [ID]          BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_PROTO].[SEQ_PROTO_LAYOUTS]) NOT NULL,
    [NAME]        VARCHAR (200) NOT NULL,
    [DESCRIPTION] VARCHAR (200) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([NAME] ASC),
    CONSTRAINT [UQ_NAME] UNIQUE NONCLUSTERED ([NAME] ASC)
);

