CREATE TABLE [DATATINO_PROTO].[MOCKS] (
    [ID]         BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_PROTO].[SEQ_MOCKS]) NOT NULL,
    [MOCK_NAME]  VARCHAR (200) NOT NULL,
    [COLUMNS]    VARCHAR (MAX) NOT NULL,
    [DATA_TYPES] VARCHAR (MAX) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_MNAME_LUN] UNIQUE NONCLUSTERED ([MOCK_NAME] ASC)
);

