CREATE TABLE [DATATINO_PROTO].[PROTO_CONFIGURATIONS] (
    [ID]                       BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_PROTO].[SEQ_PROTO_CONFIGURATIONS]) NOT NULL,
    [PROTO_ID]                 BIGINT        NOT NULL,
    [ITEM_NAME]                VARCHAR (200) NOT NULL,
    [VIEW_ID]                  BIGINT        NOT NULL,
    [CONSTRAINT]               BIGINT        NOT NULL,
    [CONSTRAINT_KEY_NAME]      VARCHAR (200) NULL,
    [CONSTRAINT_VALUE]         VARCHAR (200) NULL,
    [GROUPED]                  BIGINT        NOT NULL,
    [GROUPED_KEY_NAME]         VARCHAR (200) NULL,
    [GROUPED_LAST_UPDATE_NAME] VARCHAR (200) NULL,
    [LAYOUT_ID]                BIGINT        NULL,
    [COLUMNS]                  VARCHAR (MAX) NULL,
    [ACTIVE]                   INT           NULL,
    [MOCKABLE]                 BIGINT        DEFAULT ((0)) NULL,
    [MOCK_ID]                  BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [CHK_CONSTRAINT] CHECK ([CONSTRAINT]=(1) OR [CONSTRAINT]=(0)),
    CONSTRAINT [CHK_GROUPED] CHECK ([GROUPED]=(1) OR [GROUPED]=(0)),
    CONSTRAINT [FK_LAYOUT_ID] FOREIGN KEY ([LAYOUT_ID]) REFERENCES [DATATINO_PROTO].[LAYOUTS] ([ID]),
    CONSTRAINT [FK_MOCK_ID] FOREIGN KEY ([MOCK_ID]) REFERENCES [DATATINO_PROTO].[MOCKS] ([ID]),
    CONSTRAINT [FK_PROTO_ID] FOREIGN KEY ([PROTO_ID]) REFERENCES [DATATINO_PROTO].[PROTOS] ([ID]),
    CONSTRAINT [FK_VIEW_ID] FOREIGN KEY ([VIEW_ID]) REFERENCES [DATATINO_PROTO].[VIEWS] ([ID]),
    CONSTRAINT [UQ_ID_ITEM] UNIQUE NONCLUSTERED ([PROTO_ID] ASC, [ITEM_NAME] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_PROTO_CONFIGURATIONS_PROTO_ID_ACTIVE]
    ON [DATATINO_PROTO].[PROTO_CONFIGURATIONS]([PROTO_ID] ASC, [ACTIVE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PROTO_CONFIGURATIONS_CONSTRAINT_KEY_NAME]
    ON [DATATINO_PROTO].[PROTO_CONFIGURATIONS]([CONSTRAINT_KEY_NAME] ASC)
    INCLUDE([PROTO_ID]);

