CREATE TABLE [DATATINO_PROTO].[PROTOS] (
    [ID]            BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_PROTO].[SEQ_PROTOS]) NOT NULL,
    [PROTO_NAME]    VARCHAR (200) NOT NULL,
    [HEADER_NAMES]  VARCHAR (200) NULL,
    [HEADER_VALUES] VARCHAR (200) NULL,
    [ACTIVE]        INT           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([PROTO_NAME] ASC),
    CONSTRAINT [UQ_PROTO] UNIQUE NONCLUSTERED ([PROTO_NAME] ASC)
);

