CREATE TABLE [DATATINO_PROTO].[VIEWS] (
    [ID]               BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_PROTO].[SEQ_VIEWS]) NOT NULL,
    [VIEW_NAME]        VARCHAR (255) NOT NULL,
    [LAST_UPDATE_NAME] VARCHAR (255) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_VNAME_LUN] UNIQUE NONCLUSTERED ([VIEW_NAME] ASC, [LAST_UPDATE_NAME] ASC)
);

