-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_VWS_BEHAVIOR]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_VWS_BEHAVIOR
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.VWS_BEHAVIOR(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_VWS_BEHAVIOR]),
    [DATE_OF_REPORT] VARCHAR(100),
    [DATE_OF_MEASUREMENT] VARCHAR(100),
    [WAVE] VARCHAR(100),
    [REGION_CODE] VARCHAR(100),
    [REGION_NAME] VARCHAR(100),
    [SUBGROUP_CATEGORY] VARCHAR(100),
    [SUBGROUP] VARCHAR(100),
    [INDICATOR_CATEGORY] VARCHAR(100),
    [INDICATOR] VARCHAR(100),
    [SAMPLE_SIZE] VARCHAR(100),
    [FIGURE_TYPE] VARCHAR(100),
    [VALUE] VARCHAR(100),
    [LOWER_LIMIT] VARCHAR(100),
    [UPPER_LIMIT] VARCHAR(100),
    [CHANGE_WRT_PREVIOUS_MEASUREMENT] VARCHAR(100),
    [DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);

CREATE NONCLUSTERED INDEX IX_STAGE_VWS_BEHAVIOR_DLI
ON VWSSTAGE.VWS_BEHAVIOR (DATE_LAST_INSERTED);