-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_LNAZ_HOSPITAL_BED_OCCUPANCY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_LNAZ_HOSPITAL_BED_OCCUPANCY
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.LNAZ_HOSPITAL_BED_OCCUPANCY(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_LNAZ_HOSPITAL_BED_OCCUPANCY]),
    [DATUM] VARCHAR(100) NULL,
    [IC_BEDDEN_COVID] VARCHAR(100) NULL,
    [IC_BEDDEN_NON_COVID] VARCHAR(100) NULL,
    [IC_NIEUWE_OPNAMES_COVID] VARCHAR(100),
    [KLINIEK_NIEUWE_OPNAMES_COVID] VARCHAR(100),
    [KLINIEK_BEDDEN] VARCHAR(100) NULL,
	[DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);