-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_RIVM_SEWER_MEASUREMENTS]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_RIVM_SEWER_MEASUREMENTS
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.RIVM_SEWER_MEASUREMENTS_ARCHIVE(
  [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_RIVM_SEWER_MEASUREMENTS]),
  DATE_MEASUREMENT VARCHAR(100) NULL,
  RWZI_AWZI_CODE VARCHAR(100) NULL,
  RWZI_AWZI_NAME VARCHAR(100) NULL,
  X_COORDINATE VARCHAR(100) NULL,
  Y_COORDINATE VARCHAR(100) NULL,
  POSTAL_CODE VARCHAR(100) NULL,
  SECURITY_REGION_CODE VARCHAR(100) NULL,
  SECURITY_REGION_NAME VARCHAR(100) NULL,
  PERCENTAGE_IN_SECURITY_REGION VARCHAR(100) NULL,
  RNA_PER_ML VARCHAR(100) NULL,
  RNA_FLOW_PER_100000 VARCHAR(100) NULL,
  REPRESENTATIVE_MEASUREMENT VARCHAR(100) NULL,
  [DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);