-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_VACC_DELIVER_ADMIN]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_VACC_DELIVER_ADMIN
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.VWS_VACCINE_DELIVERIES_ADMINISTERED(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_VACC_DELIVER_ADMIN]),
    DATE_OF_REPORT VARCHAR(100) NULL,
    DATE_FIRST_DAY VARCHAR(100) NULL,
    VALUE_TYPE VARCHAR(100) NULL,
    VALUE_NAME VARCHAR(100) NULL,
    REPORT_STATUS VARCHAR(100) NULL,
    [VALUE] VARCHAR(100) NULL,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWS_VACCINE_DELIVERIES_ADMINISTERED_STAGE')
    CREATE NONCLUSTERED INDEX IX_VWS_VACCINE_DELIVERIES_ADMINISTERED_STAGE
    ON VWSSTAGE.VWS_VACCINE_DELIVERIES_ADMINISTERED(DATE_LAST_INSERTED)
    INCLUDE (DATE_OF_REPORT, DATE_FIRST_DAY, VALUE_TYPE, VALUE_NAME, REPORT_STATUS, [VALUE]);
GO