-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
BEGIN TRANSACTION T1;

DROP TABLE IF EXISTS VWSSTAGE.CBS_DECEASED_PER_PERIOD;

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_CBS_DECEASED_PER_WEEK]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_CBS_DECEASED_PER_WEEK
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.CBS_DECEASED_PER_WEEK(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CBS_DECEASED_PER_WEEK]),
    [PERIODEN] VARCHAR(100),
    [OVERLEDENEN_1] VARCHAR(100),
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);

COMMIT TRANSACTION T1;