-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_CBS_AGEGROUP_MAPPING]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_CBS_AGEGROUP_MAPPING
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.CBS_AGEGROUP_MAPPING(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CBS_AGEGROUP_MAPPING]),
    [KEY] VARCHAR(100),
	[TITLE] VARCHAR(100),
	[DESCRIPTION] VARCHAR(100),
	[CATEGORYGROUPID] VARCHAR(100),
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);
