-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_CBS_DECEASED_VR]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_CBS_DECEASED_VR
  START WITH 1
  INCREMENT BY 1;
GO


CREATE TABLE VWSSTAGE.CBS_DECEASED_VR(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_CBS_DECEASED_VR]),
    [PERIODEN] VARCHAR(100) NULL,
    [REGIOS] VARCHAR(100) NULL,
    [OVERLEDENEN_1] VARCHAR(100) NULL,
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_VWS_VWSSTAGE_CBS_DECEASED_VR')
    CREATE NONCLUSTERED INDEX IX_VWS_VWSSTAGE_CBS_DECEASED_VR
    ON VWSSTAGE.CBS_DECEASED_VR(DATE_LAST_INSERTED)
    INCLUDE (PERIODEN, REGIOS, OVERLEDENEN_1);
GO