-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_CBS_DECEASED_PER_WEEK_FORECAST]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_CBS_DECEASED_PER_WEEK_FORECAST
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.CBS_DECEASED_PER_WEEK_FORECAST(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CBS_DECEASED_PER_WEEK_FORECAST]),
    [PERIODEN] VARCHAR(100),
    [VERWACHT_AANTAL_OVERLEDENEN] VARCHAR(100),
    [ONDERGRENS] VARCHAR(100),
    [BOVENGRENS] VARCHAR(100),
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);