-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_VWS_RESTRICTIONS_MAPPING_PER_REGION]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_VWS_RESTRICTIONS_MAPPING_PER_REGION
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.VWS_RESTRICTIONS_MAPPING_PER_REGION(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_VWS_RESTRICTIONS_MAPPING_PER_REGION]),
    REGION_ID VARCHAR(100) NULL,
    RESTRICTION_IDENTIFIER VARCHAR(100) NULL,
    VALID_FROM VARCHAR(100) NULL,
    [DATE_LAST_INSERTED]  DATETIME DEFAULT GETDATE()
);

CREATE NONCLUSTERED INDEX IX_VWS_RESTRICTIONS_MAPPING_PER_REGION_STAGE
ON VWSSTAGE.VWS_RESTRICTIONS_MAPPING_PER_REGION(DATE_LAST_INSERTED);