-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_CBS_INHABITANTS_PER_AGEGROUP]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_CBS_INHABITANTS_PER_AGEGROUP
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.CBS_INHABITANTS_PER_AGEGROUP(
    [STAGE_ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CBS_INHABITANTS_PER_AGEGROUP]),
    [ID] VARCHAR(100),
	[GESLACHT] VARCHAR(100),
	[LEEFTIJD] VARCHAR(100),
	[BURGERLIJKESTAAT] VARCHAR(100),
	[REGIOS] VARCHAR(100),
	[PERIODEN] VARCHAR(100),
    [BEVOLKINGOP1JANUARI_1] VARCHAR(100),
	[GEMIDDELDEBEVOLKING_2] VARCHAR(100),
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);
