-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSSTAGE_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP]),
    [VERSION] VARCHAR(100) NULL,
	DATE_OF_REPORT VARCHAR(100) NULL,
    DATE_OF_STATISTICS_WEEK_START VARCHAR(100) NULL,
    AGE_GROUP VARCHAR(100) NULL,
    HOSPITAL_ADMISSION_NOTIFICATION VARCHAR(100) NULL,
    HOSPITAL_ADMISSION VARCHAR(100) NULL,
    IC_ADMISSION_NOTIFICATION VARCHAR(100) NULL,
    IC_ADMISSION VARCHAR(100) NULL,    
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME='IX_STAGE_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP')
    CREATE NONCLUSTERED INDEX IX_STAGE_RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP
    ON VWSSTAGE.RIVM_HOSPITAL_IC_ADMISSIONS_OVERTIME_BYAGEGROUP(DATE_LAST_INSERTED);
GO