-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_CBS_INHABITANTS_PER_MUNICIPALITY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_CBS_INHABITANTS_PER_MUNICIPALITY
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.CBS_INHABITANTS_PER_MUNICIPALITY(
    [ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_CBS_INHABITANTS_PER_MUNICIPALITY]),
    [REGIOS] VARCHAR(100),
    [CODE_1] VARCHAR(100),
	[CODE_42] VARCHAR(100),
	[NAAM_43] VARCHAR(100),
	[INWONERTAL_50] VARCHAR(100),
	[DATE_LAST_INSERTED] DATETIME DEFAULT GETDATE()
);