-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
-- Table for raw input of casus municipality data from the RIVM

IF NOT EXISTS(SELECT * FROM sys.sequences WHERE object_id = OBJECT_ID(N'[dbo].[SEQ_VWSSTAGE_COVID19_MUNICIPALITY]') AND type = 'SO')
CREATE SEQUENCE SEQ_VWSSTAGE_COVID19_MUNICIPALITY
  START WITH 1
  INCREMENT BY 1;
GO

CREATE TABLE VWSSTAGE.RIVM_COVID_19_NUMBER_MUNICIPALITY_CUMULATIVE(
	[ID] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSSTAGE_COVID19_MUNICIPALITY]),
	DATE_OF_REPORT VARCHAR(100) NULL,
	MUNICIPALITY_CODE VARCHAR(100) NULL,
	MUNICIPALITY_NAME VARCHAR(100) NULL,
	PROVINCE VARCHAR(100) NULL,
	TOTAL_REPORTED VARCHAR(100) NULL,
	HOSPITAL_ADMISSION VARCHAR(100) NULL,
	DECEASED VARCHAR(100) NULL,
	DATE_LAST_INSERTED DATETIME DEFAULT GETDATE()
);