-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Move percentage positive tested people data from staging to intermediate table.
CREATE OR ALTER PROCEDURE DBO.SP_GGD_PERCENTAGE_POSITIVE_TESTED_PEOPLE_PER_REGION_INTER
AS
BEGIN
    INSERT INTO VWSINTER.GGD_PERCENTAGE_POSITIVE_TESTED_PEOPLE_PER_REGION
    (
        [WEEK OF APPOINTMENT],
        [SECURITY REGION NAME],
        [SECURITY REGION CODE],
        [POPULATION PER SECURITY REGION],
        [TOTAL TESTED WITH RESULT],
        [TOTAL TESTED WITH RESULT/100.000],
        [TOTAL POSITIVE],
        [% POSITIVE],
        [POSITIVE/100.000]
    )
    SELECT
        [WEEK OF APPOINTMENT],
        [SECURITY REGION NAME],
        [SECURITY REGION CODE],
        [POPULATION PER SECURITY REGION],
        [TOTAL TESTED WITH RESULT],
        CAST(NULLIF([TOTAL TESTED WITH RESULT/100.000], '') AS DECIMAL(16,2)) AS [TOTAL TESTED WITH RESULT/100.000],
        [TOTAL POSITIVE],
        CAST(NULLIF([% POSITIVE], '') AS DECIMAL(16,2)) AS [% POSITIVE],
        CAST(NULLIF([POSITIVE/100.000], '') AS DECIMAL(16,2)) AS [POSITIVE/100.000]
    FROM
       VWSSTAGE.GGD_PERCENTAGE_POSITIVE_TESTED_PEOPLE_PER_REGION
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSSTAGE.GGD_PERCENTAGE_POSITIVE_TESTED_PEOPLE_PER_REGION)
END;