-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
CREATE OR ALTER PROCEDURE [dbo].[SP_CBS_DECEASED_PER_WEEK_FORECAST_INTER]
AS
BEGIN
INSERT INTO VWSINTER.CBS_DECEASED_PER_WEEK_FORECAST(
    [YEAR]
,   [WEEK]
,   [DECEASED_FORECAST]
,   [DECEASED_FORECAST_LOW]
,   [DECEASED_FORECAST_HIGH]
    )
SELECT
    CAST(SUBSTRING([PERIODEN], 1, 4) AS INT)
,   CAST(SUBSTRING([PERIODEN], 7, 2) AS INT)
,   [VERWACHT_AANTAL_OVERLEDENEN]
,   [ONDERGRENS]
,   [BOVENGRENS]
FROM [VWSSTAGE].[CBS_DECEASED_PER_WEEK_FORECAST]
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from VWSSTAGE.CBS_DECEASED_PER_WEEK_FORECAST)
END;

