-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE [dbo].[SP_Elderly_At_Home_Inter]
AS
BEGIN
INSERT INTO VWSINTER.ELDERLY_AT_HOME (
    DATE_OF_REPORT,
    DATE_OF_STATISTIC_REPORTED,
    SECURITY_REGION_CODE,
    TOTAL_CASES_REPORTED,
    TOTAL_DECEASED_REPORTED
    )
    SELECT
    DATE_OF_REPORT,
    DATE_OF_STATISTIC_REPORTED,
    SECURITY_REGION_CODE,
    TOTAL_CASES_REPORTED,
    TOTAL_DECEASED_REPORTED
    FROM
       VWSSTAGE.ELDERLY_AT_HOME
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from VWSSTAGE.ELDERLY_AT_HOME)
END;