CREATE    VIEW [DATATINO].[V_CRON_SCHEDULE] AS

WITH SP_DEST_MAPPING AS (
    SELECT
    So.name AS ProcedureName, SOO.Name AS TableName, SC.name AS SchemaName, SC.name + '.' + SOO.Name AS TargetName,
    ROW_NUMBER() OVER(partition by SO.Name,SOO.Name ORDER BY SO.Name,SOO.Name) AS R
    FROM sysdepends SD
    INNER JOIN sys.objects SO ON SO.object_id=Sd.id
    INNER JOIN sys.objects SOO ON Soo.object_id=Sd.depid
    LEFT JOIN sys.schemas SC ON SOO.schema_id = SC.schema_id
    WHERE So.type = 'P'
)

SELECT
WORKFLOWS.WORKFLOW_NAME
,PR.PROTO_NAME
,PROTOS.ITEM_NAME
,WORKFLOWS.SCHEDULE
FROM (
    SELECT *
    FROM DATATINO_PROTO.PROTO_CONFIGURATIONS
    WHERE ACTIVE = 1
) PROTOS
LEFT JOIN (
    SELECT *
    FROM [DATATINO_PROTO].[PROTOS]
    WHERE ACTIVE = 1
)PR
    ON PROTOS.PROTO_ID = PR.ID
LEFT JOIN DATATINO_PROTO.VIEWS VIEWS
    ON PROTOS.VIEW_ID = VIEWS.ID
LEFT JOIN (
    SELECT DISTINCT VIEW_SCHEMA, VIEW_NAME, VIEW_SCHEMA + '.' + VIEW_NAME AS TARGET_VIEW, TABLE_SCHEMA, TABLE_NAME, TABLE_SCHEMA + '.' + TABLE_NAME AS TARGET_TABLE
    FROM INFORMATION_SCHEMA.VIEW_COLUMN_USAGE
) MAPPING_VIEW_TABLE
    ON VIEWS.VIEW_NAME = MAPPING_VIEW_TABLE.TARGET_VIEW
LEFT JOIN (
    SELECT ProcedureName, TableName, SchemaName, TargetName
    FROM SP_DEST_MAPPING
    WHERE R = 1
) MAPPING_TABLE_SP
    ON MAPPING_VIEW_TABLE.TARGET_TABLE = MAPPING_TABLE_SP.TargetName
LEFT JOIN (
    SELECT *
    ,REPLACE(REPLACE(REPLACE(Source, '[', ''), ']', ''), 'dbo.', '') AS Cleaned_source
    FROM DATATINO_ORCHESTRATOR.Sources
) SOURCES
    ON MAPPING_TABLE_SP.ProcedureName = SOURCES.Cleaned_source
LEFT JOIN (
    SELECT *
    FROM DATATINO_ORCHESTRATOR.PROCESSES
    WHERE ACTIVE = 1
 ) PROCESSES
    ON SOURCES.ID = PROCESSES.SOURCE_ID
LEFT JOIN (
    SELECT *
    FROM DATATINO_ORCHESTRATOR.WORKFLOWS
    WHERE ACTIVE = 1
 ) WORKFLOWS
    ON PROCESSES.WORKFLOW_ID = WORKFLOWS.ID