CREATE   VIEW DATATINO.V_ITEM_SCHEDULE AS(
SELECT T2.WORKFLOW_NAME, 
 T4.PROTO_NAME,
 T3.ITEM_NAME, 
 T2.INTERVAL_ID, 
 T2.RUN_DAY, 
 T3.ACTIVE 
FROM DATATINO_PROTO.ITEM_SCHEDULE T1
JOIN DATATINO_ORCHESTRATOR.WORKFLOWS T2
ON T1.WORKFLOW_ID = T2.ID
JOIN DATATINO_PROTO.PROTO_CONFIGURATIONS T3
ON T1.ITEM_ID = T3.ID
JOIN DATATINO_PROTO.PROTOS T4
ON T3.PROTO_ID = T4.ID
)