CREATE TABLE [DATATINO].[VERSION] (
    [ID]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [CURRENT_VERSION] DECIMAL (18, 2) NOT NULL,
    [INSTALLED_AT]    DATETIME2 (7)   NOT NULL,
    [INSTALLED_BY]    NVARCHAR (MAX)  NOT NULL,
    [NAME]            NVARCHAR (200)  NOT NULL,
    [DESCRIPTION]     NVARCHAR (MAX)  NOT NULL,
    CONSTRAINT [PK_VERSION] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_VERSION_CURRENT_VERSION]
    ON [DATATINO].[VERSION]([CURRENT_VERSION] ASC);

