CREATE TABLE [VWSINTER].[CBS_DECEASED_VR] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSINTER_CBS_DECEASED_VR]) NOT NULL,
    [YEAR]               INT           NULL,
    [WEEK]               INT           NULL,
    [REGIOS]             VARCHAR (100) NULL,
    [DECEASED_ACTUAL]    INT           NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_VWSINTER_CBS_DECEASED_VR]
    ON [VWSINTER].[CBS_DECEASED_VR]([DATE_LAST_INSERTED] ASC)
    INCLUDE([YEAR], [WEEK], [REGIOS], [DECEASED_ACTUAL]);

