CREATE TABLE [VWSINTER].[CBS_DECEASED_PER_WEEK_FORECAST] (
    [ID]                     INT      DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_CBS_DECEASED_PER_WEEK_FORECAST]) NOT NULL,
    [YEAR]                   INT      NULL,
    [WEEK]                   INT      NULL,
    [DECEASED_FORECAST]      INT      NULL,
    [DECEASED_FORECAST_LOW]  INT      NULL,
    [DECEASED_FORECAST_HIGH] INT      NULL,
    [DATE_LAST_INSERTED]     DATETIME DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

