CREATE TABLE [VWSINTER].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR] (
    [ID]                                    INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]) NOT NULL,
    [VERSION]                               INT             NULL,
    [DATE_OF_REPORT]                        DATETIME        NULL,
    [DATE_OF_STATISTICS]                    DATETIME        NULL,
    [REGION_LEVEL]                          VARCHAR (100)   NULL,
    [REGION_CODE]                           VARCHAR (10)    NULL,
    [REGION_NAME]                           VARCHAR (100)   NULL,
    [BIRTH_YEAR]                            VARCHAR (100)   NULL,
    [VACCINATION_COVERAGE_ALL_SOURCE]       VARCHAR (100)   NULL,
    [VACCINATION_COVERAGE_ALL]              DECIMAL (19, 3) NULL,
    [VACCINATION_COVERAGE_ALL_LABEL]        VARCHAR (100)   NULL,
    [VACCINATION_COVERAGE_COMPLETED_SOURCE] VARCHAR (100)   NULL,
    [VACCINATION_COVERAGE_COMPLETED]        DECIMAL (19, 3) NULL,
    [VACCINATION_COVERAGE_COMPLETED_LABEL]  VARCHAR (100)   NULL,
    [DATE_LAST_INSERTED]                    DATETIME        DEFAULT (getdate()) NULL,
    [VACCINATION_SERIE]                     VARCHAR (100)   NULL,
    [PERCENTAGE]                            DECIMAL (19, 3) NULL,
    [PERCENTAGE_LABEL]                      VARCHAR (100)   NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCI_VWSINTER_CIMS_VACCINATED_AGE_GROUP]
    ON [VWSINTER].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC, [DATE_OF_STATISTICS] ASC, [REGION_CODE] ASC)
    INCLUDE([REGION_LEVEL], [REGION_NAME], [BIRTH_YEAR], [VACCINATION_COVERAGE_ALL], [VACCINATION_COVERAGE_ALL_LABEL], [VACCINATION_COVERAGE_COMPLETED], [VACCINATION_COVERAGE_COMPLETED_LABEL]);


GO
CREATE CLUSTERED INDEX [CI_DLI_VWSINTER_CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]
    ON [VWSINTER].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR]([DATE_LAST_INSERTED] ASC);

