CREATE TABLE [VWSINTER].[CIMS_VACCINATED_AGE_GROUP] (
    [ID]                             INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_CIMS_VACCINATED_AGE_GROUP]) NOT NULL,
    [DATE_OF_REPORT]                 DATETIME        NULL,
    [DATE_OF_STATISTICS_WEEK_START]  DATETIME        NULL,
    [DATE_OF_STATISTICS_WEEK_END]    DATETIME        NULL,
    [BIRTH_COHORT]                   VARCHAR (100)   NULL,
    [VACCINATION_ALL]                BIGINT          NULL,
    [VACCINATION_COVERAGE_ALL]       DECIMAL (16, 2) NULL,
    [VACCINATION_COMPLETED]          BIGINT          NULL,
    [VACCINATION_COVERAGE_COMPLETED] DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED]             DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCI_DLI_VWSINTER_CIMS_VACCINATED_AGE_GROUP]
    ON [VWSINTER].[CIMS_VACCINATED_AGE_GROUP]([DATE_LAST_INSERTED] ASC, [DATE_OF_STATISTICS_WEEK_START] ASC, [DATE_OF_STATISTICS_WEEK_END] ASC, [BIRTH_COHORT] ASC);


GO
CREATE CLUSTERED INDEX [CI_DLI_VWSINTER_CIMS_VACCINATED_AGE_GROUP]
    ON [VWSINTER].[CIMS_VACCINATED_AGE_GROUP]([DATE_LAST_INSERTED] ASC);

