CREATE TABLE [VWSINTER].[DISABILITY] (
    [ID]                                    INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_DISABILITY]) NOT NULL,
    [DATE_OF_REPORT]                        DATETIME      NULL,
    [DATE_OF_STATISTIC_REPORTED]            DATETIME      NULL,
    [SECURITY_REGION_CODE]                  VARCHAR (100) NULL,
    [TOTAL_CASES_REPORTED]                  INT           NULL,
    [TOTAL_DECEASED_REPORTED]               INT           NULL,
    [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED] INT           NULL,
    [TOTAL_INFECTED_LOCATIONS_REPORTED]     INT           NULL,
    [DATE_LAST_INSERTED]                    DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWSINTER_DISABILITY_INTER]
    ON [VWSINTER].[DISABILITY]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_DISABILITY_DLI]
    ON [VWSINTER].[DISABILITY]([DATE_LAST_INSERTED] ASC)
    INCLUDE([TOTAL_CASES_REPORTED], [TOTAL_DECEASED_REPORTED], [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED], [TOTAL_INFECTED_LOCATIONS_REPORTED]);


GO
CREATE NONCLUSTERED INDEX [IX_DISABILITY_DATE_OF_STATISTIC_REPORTED]
    ON [VWSINTER].[DISABILITY]([DATE_OF_STATISTIC_REPORTED] ASC)
    INCLUDE([SECURITY_REGION_CODE], [TOTAL_CASES_REPORTED], [TOTAL_DECEASED_REPORTED], [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED], [TOTAL_INFECTED_LOCATIONS_REPORTED], [DATE_LAST_INSERTED]);

