CREATE TABLE [VWSINTER].[GGD_TESTED_PEOPLE] (
    [ID]                   INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_GGD_TESTED_PEOPLE]) NOT NULL,
    [VERSION]              BIGINT        NULL,
    [DATE_OF_REPORT]       DATETIME      NULL,
    [DATE_OF_STATISTICS]   DATETIME      NULL,
    [SECURITY_REGION_CODE] VARCHAR (100) NULL,
    [SECURITY_REGION_NAME] VARCHAR (100) NULL,
    [TESTED_WITH_RESULT]   BIGINT        NULL,
    [TESTED_POSITIVE]      BIGINT        NULL,
    [DATE_LAST_INSERTED]   DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_REGION_CODE]
    ON [VWSINTER].[GGD_TESTED_PEOPLE]([SECURITY_REGION_CODE] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_STATISTICS], [SECURITY_REGION_NAME], [TESTED_WITH_RESULT], [TESTED_POSITIVE], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_INTER]
    ON [VWSINTER].[GGD_TESTED_PEOPLE]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_GGD_TESTED_PEOPLE_DATE_LAST_INSERTED]
    ON [VWSINTER].[GGD_TESTED_PEOPLE]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_STATISTICS], [SECURITY_REGION_CODE], [SECURITY_REGION_NAME], [TESTED_WITH_RESULT], [TESTED_POSITIVE]);

