CREATE TABLE [VWSINTER].[LNAZ_HOSPITAL_BED_OCCUPANCY] (
    [ID]                           INT      DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_LNAZ_HOSPITAL_BED_OCCUPANCY]) NOT NULL,
    [DATUM]                        DATETIME NULL,
    [IC_BEDDEN_COVID]              INT      NULL,
    [IC_BEDDEN_NON_COVID]          INT      NULL,
    [KLINIEK_BEDDEN]               INT      NULL,
    [DATE_LAST_INSERTED]           DATETIME DEFAULT (getdate()) NULL,
    [IC_NIEUWE_OPNAMES_COVID]      INT      NULL,
    [KLINIEK_NIEUWE_OPNAMES_COVID] INT      NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_LNAZ_HOSPITAL_BED_OCCUPANCY_DLI]
    ON [VWSINTER].[LNAZ_HOSPITAL_BED_OCCUPANCY]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATUM], [IC_BEDDEN_COVID], [IC_BEDDEN_NON_COVID], [KLINIEK_BEDDEN]);

