CREATE TABLE [VWSINTER].[LNAZ_HOSPITAL_BED_OCCUPANCY_2023] (
    [ID]                                INT      IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]                DATETIME DEFAULT (getdate()) NOT NULL,
    [DATUM]                             DATETIME NULL,
    [IC_CAPACITEIT_TOTAAL]              INT      NULL,
    [KLINIEK_CAPACITEIT_TOTAAL]         INT      NULL,
    [IC_BEZETTING_COVID]                INT      NULL,
    [IC_BEZETTING_COVID_INTERNATIONAAL] INT      NULL,
    [IC_BEZETTING_ONTLABELD]            INT      NULL,
    [IC_BEZETTING_NONCOVID]             INT      NULL,
    [KLINIEK_BEZETTING_COVID]           INT      NULL,
    [KLINIEK_BEZETTING_ONTLABELD]       INT      NULL,
    [KLINIEK_BEZETTING_NONCOVID]        INT      NULL,
    [IC_OPNAMES_COVID]                  INT      NULL,
    [KLINIEK_OPNAMES_COVID]             INT      NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_LNAZ_HOSPITAL_BED_OCCUPANCY_2023]
    ON [VWSINTER].[LNAZ_HOSPITAL_BED_OCCUPANCY_2023]([DATE_LAST_INSERTED] ASC);

