CREATE TABLE [VWSINTER].[NICE_IC_ADMISSIONS] (
    [ID]                 INT      DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_NICE_IC_ADMISSIONS]) NOT NULL,
    [DATE]               DATETIME NULL,
    [VALUE]              INT      NULL,
    [DATE_LAST_INSERTED] DATETIME DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_NICE_IC_ADMISSIONS]
    ON [VWSINTER].[NICE_IC_ADMISSIONS]([DATE_LAST_INSERTED] ASC);

