CREATE TABLE [VWSINTER].[NICE_HOSPITAL] (
    [ID]                   INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_NICE_HOSPITAL]) NOT NULL,
    [DATE_OF_REPORT]       DATETIME      NULL,
    [DATE_OF_STATISTICS]   DATETIME      NULL,
    [MUNICIPALITY_CODE]    VARCHAR (100) NULL,
    [MUNICIPALITY_NAME]    VARCHAR (100) NULL,
    [SECURITY_REGION_CODE] VARCHAR (100) NULL,
    [SECURITY_REGION_NAME] VARCHAR (100) NULL,
    [REPORTED]             INT           NULL,
    [HOSPITALIZED]         INT           NULL,
    [DATE_LAST_INSERTED]   DATETIME      DEFAULT (getdate()) NULL
);


GO
CREATE CLUSTERED INDEX [IX_NICE_HOSPITAL_INTER_IC]
    ON [VWSINTER].[NICE_HOSPITAL]([DATE_LAST_INSERTED] ASC);

