CREATE TABLE [VWSINTER].[NIVEL_SUSPICIONS_GENERAL_PRACTITIONERS] (
    [ID]                    INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_NIVEL_SUSPICIONS_GENERAL_PRACTITIONERS]) NOT NULL,
    [WEEK]                  INT             NULL,
    [INCIDENTIE_PER_100000] DECIMAL (16, 2) NULL,
    [BOVENGRENS]            INT             NULL,
    [DIAGNOSE]              VARCHAR (100)   NULL,
    [JAAR]                  INT             NULL,
    [GESCHAT_AANTAL]        INT             NULL,
    [ONDERGRENS]            INT             NULL,
    [DATE_LAST_INSERTED]    DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_NIVEL_SUSPICIONS_GENERAL_PRACTITIONERS]
    ON [VWSINTER].[NIVEL_SUSPICIONS_GENERAL_PRACTITIONERS]([DATE_LAST_INSERTED] ASC);

