CREATE TABLE [VWSINTER].[RIVM_NURSING_HOMES_DECEASED] (
    [ID]                   INT      DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_NURSING_HOMES_DECEASED]) NOT NULL,
    [DATUM_VAN_OVERLIJDEN] DATETIME NULL,
    [AANTAL]               INT      NULL,
    [DATE_LAST_INSERTED]   DATETIME DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_NURSING_HOMES_DECEASED]
    ON [VWSINTER].[RIVM_NURSING_HOMES_DECEASED]([DATE_LAST_INSERTED] ASC);

