CREATE TABLE [VWSINTER].[RIVM_NURSING_HOMES_HANDICAPPED_TOTALS] (
    [ID]                 INT      DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_NURSING_HOMES_HANDICAPPED_TOTAlS]) NOT NULL,
    [MELDINGSDATUM]      DATETIME NULL,
    [AANTAL]             INT      NULL,
    [DATE_LAST_INSERTED] DATETIME DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

