CREATE TABLE [VWSINTER].[RIVM_VACCINE_STOCK] (
    [ID]                 INT          DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_VACCINE_STOCK]) NOT NULL,
    [DATE_OF_STATISTICS] DATE         NULL,
    [VACCINE_NAME]       VARCHAR (50) NULL,
    [TOTAL_STOCK]        INT          NULL,
    [DATE_LAST_INSERTED] DATETIME     DEFAULT (getdate()) NULL,
    [FREE_STOCK]         INT          NULL,
    [DATE_OF_REPORT]     DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

