CREATE TABLE [VWSINTER].[RIVM_CLUSTERS_INFECTED_PEOPLE] (
    [ID]                   INT             DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_CLUSTERS_INFECTED_PEOPLE]) NOT NULL,
    [DATE_OF_REPORT]       DATETIME        NULL,
    [DATE_STATISTICS]      DATETIME        NULL,
    [SECURITY_REGION_NAME] VARCHAR (100)   NULL,
    [SECURITY_REGION_CODE] VARCHAR (100)   NULL,
    [ACTIVE_CLUSTERS]      INT             NULL,
    [AVERAGE_SIZE]         DECIMAL (16, 2) NULL,
    [MEDIAN_SIZE]          DECIMAL (16, 2) NULL,
    [MIN_SIZE]             DECIMAL (16, 2) NULL,
    [MAX_SIZE]             DECIMAL (16, 2) NULL,
    [DATE_LAST_INSERTED]   DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_CLUSTERS_INFECTED_PEOPLE]
    ON [VWSINTER].[RIVM_CLUSTERS_INFECTED_PEOPLE]([DATE_LAST_INSERTED] ASC);

