CREATE TABLE [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL] (
    [ID]                      INT             DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSINTER_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL]) NOT NULL,
    [DATE_LAST_INSERTED]      DATETIME        DEFAULT (getdate()) NOT NULL,
    [VERSION]                 INT             NULL,
    [DATE_OF_REPORT]          DATETIME        NULL,
    [DATE_OF_STATISTICS]      DATETIME        NULL,
    [YEAR_OF_BIRTH]           VARCHAR (256)   NULL,
    [COVERAGE_BOOSTER_SHOTS]  NUMERIC (10, 2) NULL,
    [CUMSUM_BOOSTER_SHOTS]    INT             NULL,
    [BIRTH_COHORT]            VARCHAR (256)   NULL,
    [POPULATION_AGEGROUP]     VARCHAR (256)   NULL,
    [BASE_SERIES]             VARCHAR (256)   NULL,
    [BOOSTER1]                VARCHAR (256)   NULL,
    [AMOUNT_CUMULATIVE]       VARCHAR (256)   NULL,
    [COVERAGE_AGEGROUP]       VARCHAR (256)   NULL,
    [COVERAGE_TO_BASE_SERIES] VARCHAR (256)   NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL]
    ON [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL]
    ON [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL]([DATE_LAST_INSERTED] ASC);

