CREATE TABLE [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL] (
    [ID]                                  INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSINTER_RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL]) NOT NULL,
    [DATE_LAST_INSERTED]                  DATETIME      DEFAULT (getdate()) NOT NULL,
    [VERSION]                             INT           NULL,
    [DATE_OF_REPORT]                      DATETIME      NULL,
    [DATE_OF_STATISTICS]                  DATETIME      NULL,
    [BIRTH_COHORT]                        VARCHAR (256) NULL,
    [POPULATION_PER_AGE_GROUP]            BIGINT        NULL,
    [BASIC_SERIE_AMOUNT]                  BIGINT        NULL,
    [BOOSTER_TYPE]                        VARCHAR (256) NULL,
    [CUMULATIVE_AMOUNT]                   BIGINT        NULL,
    [VACCINATION_COVERAGE_PER_AGE_GROUP]  FLOAT (53)    NULL,
    [VACCINATION_COVERAGE_VS_BASIC_SERIE] FLOAT (53)    NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE CLUSTERED INDEX [CIX_DLI_VWSINTER_RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL]
    ON [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_PER_AGE_GROUP_NL]([DATE_LAST_INSERTED] ASC);

