CREATE TABLE [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM] (
    [ID]                 INT             DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSINTER_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM]) NOT NULL,
    [DATE_LAST_INSERTED] DATETIME        DEFAULT (getdate()) NOT NULL,
    [VERSION]            INT             NULL,
    [DATE_OF_REPORT]     DATETIME        NULL,
    [DATE_OF_STATISTICS] DATETIME        NULL,
    [POPULATION]         BIGINT          NULL,
    [REGION_CODE]        VARCHAR (256)   NULL,
    [REGION_LEVEL]       VARCHAR (256)   NULL,
    [REGION_NAME]        VARCHAR (256)   NULL,
    [AGE_GROUP]          VARCHAR (256)   NULL,
    [BIRTH_YEAR]         VARCHAR (256)   NULL,
    [VACCINATION_SERIE]  VARCHAR (256)   NULL,
    [PERCENTAGE_SOURCE]  VARCHAR (256)   NULL,
    [PERCENTAGE]         NUMERIC (10, 2) NULL,
    [PERCENTAGE_LABEL]   VARCHAR (256)   NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM]
    ON [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM]
    ON [VWSINTER].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_GM]([DATE_LAST_INSERTED] ASC);

