CREATE TABLE [VWSINTER].[RIVM_NURSING_HOMES_INFECTED_LOCATIONS] (
    [ID]                                                  INT      DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_NURSING_HOMES_INFECTED_LOCATIONS]) NOT NULL,
    [PUBLICATIEDATUMRIVM]                                 DATETIME NULL,
    [AANTAL_NIEUW_BESMETTE_VERPLEEGHUIS_LOCATIES]         INT      NULL,
    [AANTAL_NIEUW_BESMETTINGSVRIJE_VERPLEEGHUIS_LOCATIES] INT      NULL,
    [AANTAL_BESMETTE_VERPLEEGHUIS_LOCATIES]               INT      NULL,
    [DATE_LAST_INSERTED]                                  DATETIME DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_NURSING_HOMES_INFECTED_LOCATIONS_PD]
    ON [VWSINTER].[RIVM_NURSING_HOMES_INFECTED_LOCATIONS]([PUBLICATIEDATUMRIVM] ASC)
    INCLUDE([AANTAL_NIEUW_BESMETTE_VERPLEEGHUIS_LOCATIES], [AANTAL_BESMETTE_VERPLEEGHUIS_LOCATIES], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_NURSING_HOMES_INFECTED_LOCATIONS_DLI]
    ON [VWSINTER].[RIVM_NURSING_HOMES_INFECTED_LOCATIONS]([DATE_LAST_INSERTED] ASC, [PUBLICATIEDATUMRIVM] ASC)
    INCLUDE([AANTAL_NIEUW_BESMETTE_VERPLEEGHUIS_LOCATIES], [AANTAL_BESMETTE_VERPLEEGHUIS_LOCATIES]);

