CREATE TABLE [VWSINTER].[RIVM_IC_OPNAME] (
    [ID]                        INT           DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSINTER_RIVM_IC_OPNAME]) NOT NULL,
    [VERSION]                   VARCHAR (100) NULL,
    [DATE_OF_REPORT]            DATETIME      NULL,
    [DATE_OF_STATISTICS]        DATETIME      NULL,
    [IC_ADMISSION_NOTIFICATION] INT           NULL,
    [IC_ADMISSION]              INT           NULL,
    [DATE_LAST_INSERTED]        DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_IC_OPNAME_INTER]
    ON [VWSINTER].[RIVM_IC_OPNAME]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_REPORT], [DATE_OF_STATISTICS], [IC_ADMISSION_NOTIFICATION], [IC_ADMISSION]);

