CREATE TABLE [VWSINTER].[RIVM_SEWER_MEASUREMENTS_INSTALLATIONS_2023] (
    [ID]                  BIGINT        IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]  DATETIME      DEFAULT (getdate()) NOT NULL,
    [VERSION]             INT           NOT NULL,
    [DATE_OF_REPORT]      DATETIME      NOT NULL,
    [DATE_MEASUREMENT]    DATETIME      NOT NULL,
    [RWZI_AWZI_CODE]      INT           NOT NULL,
    [RWZI_AWZI_NAME]      VARCHAR (256) NULL,
    [RNA_FLOW_PER_100000] BIGINT        NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_RIVM_SEWER_MEASUREMENTS_INSTALLATIONS_2023]
    ON [VWSINTER].[RIVM_SEWER_MEASUREMENTS_INSTALLATIONS_2023]([DATE_LAST_INSERTED] ASC);

