CREATE TABLE [VWSINTER].[RIVM_VACCINATION_COVERAGES_NL] (
    [ID]                  BIGINT        IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [DATE_OF_REPORT]      DATETIME      NULL,
    [DATE_OF_STATISTICS]  DATETIME      NULL,
    [BIRTH_YEAR]          VARCHAR (50)  NULL,
    [VACCINATION_SERIES]  VARCHAR (255) NULL,
    [PERCENTAGE_COVERAGE] FLOAT (53)    NULL,
    [AGE_GROUP]           VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

