CREATE TABLE [VWSINTER].[RIVM_REPRODUCTION_NUMBER] (
    [ID]                 INT        DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_REPRODUCTION_NUMBER]) NOT NULL,
    [DATE]               DATETIME   NULL,
    [RT_LOW]             FLOAT (53) NULL,
    [RT_AVG]             FLOAT (53) NULL,
    [RT_UP]              FLOAT (53) NULL,
    [DATE_LAST_INSERTED] DATETIME   DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_REPRODUCTION_NUMBER_DLI]
    ON [VWSINTER].[RIVM_REPRODUCTION_NUMBER]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE], [RT_LOW], [RT_AVG], [RT_UP]);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_REPRODUCTION_NUMBER]
    ON [VWSINTER].[RIVM_REPRODUCTION_NUMBER]([DATE_LAST_INSERTED] ASC);

