CREATE TABLE [VWSINTER].[RIVM_VACCINATIONSTATUS_IC_ADMISSIONS] (
    [ID]                                  INT            DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_VACCINATIONSTATUS_IC_ADMISSIONS]) NOT NULL,
    [DATE_START]                          DATETIME       NULL,
    [DATE_END]                            DATETIME       NULL,
    [GROUP_SIZE]                          INT            NULL,
    [FULLY_VACCINATED]                    INT            NULL,
    [FULLY_VACCINATED_PERCENTAGE]         DECIMAL (8, 1) NULL,
    [PARTIALLY_NOT_VACCINATED]            INT            NULL,
    [PARTIALLY_NOT_VACCINATED_PERCENTAGE] DECIMAL (8, 1) NULL,
    [DATE_LAST_INSERTED]                  DATETIME       DEFAULT (getdate()) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWSINTER_VACCINATIONSTATUS_IC_ADMISSIONS]
    ON [VWSINTER].[RIVM_VACCINATIONSTATUS_IC_ADMISSIONS]([DATE_LAST_INSERTED] ASC);

