CREATE TABLE [VWSINTER].[RIVM_NURSING_HOMES_COMBINED] (
    [ID]                                    INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_NURSING_HOMES_COMBINED]) NOT NULL,
    [DATE_OF_REPORT]                        DATETIME      NULL,
    [DATE_OF_STATISTIC_REPORTED]            DATETIME      NULL,
    [SECURITY_REGION_CODE]                  VARCHAR (100) NULL,
    [SECURITY_REGION_NAME]                  VARCHAR (100) NULL,
    [TOTAL_CASES_REPORTED]                  INT           NULL,
    [TOTAL_DECEASED_REPORTED]               INT           NULL,
    [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED] INT           NULL,
    [TOTAL_INFECTED_LOCATIONS_REPORTED]     INT           NULL,
    [DATE_LAST_INSERTED]                    DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_NURSING_HOMES_COMBINED_INTER]
    ON [VWSINTER].[RIVM_NURSING_HOMES_COMBINED]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_RIVM_NURSING_HOMES_COMBINED_DATE_LAST_INSERTED_DATE_OF_STATISTIC_REPORTED]
    ON [VWSINTER].[RIVM_NURSING_HOMES_COMBINED]([DATE_LAST_INSERTED] ASC, [DATE_OF_STATISTIC_REPORTED] ASC)
    INCLUDE([TOTAL_CASES_REPORTED], [TOTAL_DECEASED_REPORTED], [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED], [TOTAL_INFECTED_LOCATIONS_REPORTED]);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_NURSING_HOMES_COMBINED_DLI]
    ON [VWSINTER].[RIVM_NURSING_HOMES_COMBINED]([DATE_LAST_INSERTED] ASC)
    INCLUDE([SECURITY_REGION_CODE], [TOTAL_CASES_REPORTED], [TOTAL_DECEASED_REPORTED], [TOTAL_NEW_INFECTED_LOCATIONS_REPORTED], [TOTAL_INFECTED_LOCATIONS_REPORTED]);

