CREATE TABLE [VWSINTER].[RIVM_INFECTIOUS_PEOPLE] (
    [ID]                 INT      DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_INFECTIOUS_PEOPLE]) NOT NULL,
    [DATE]               DATETIME NULL,
    [PREV_LOW]           INT      NULL,
    [PREV_AVG]           INT      NULL,
    [PREV_UP]            INT      NULL,
    [DATE_LAST_INSERTED] DATETIME DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_INFECTIOUS_PEOPLE]
    ON [VWSINTER].[RIVM_INFECTIOUS_PEOPLE]([DATE_LAST_INSERTED] ASC);

