CREATE TABLE [VWSINTER].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL] (
    [ID]                 INT      DEFAULT (NEXT VALUE FOR [DBO].[SEQ_VWSINTER_RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL]) NOT NULL,
    [DATE_LAST_INSERTED] DATETIME DEFAULT (getdate()) NOT NULL,
    [DATE_OF_STATISTICS] DATETIME NULL,
    [TOTAL_VACCINATIONS] INT      NULL,
    [ASTRA_ZENECA]       INT      NULL,
    [COMIRNATY]          INT      NULL,
    [MODERNA]            INT      NULL,
    [UNKNOWN]            INT      NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL]
    ON [VWSINTER].[RIVM_VACCINATIONS_THIRD_SHOTS_ADMINISTERED_NL]([DATE_LAST_INSERTED] ASC);

