CREATE TABLE [VWSINTER].[RIVM_VACCINATION_PLANNED_NL] (
    [ID]                       BIGINT   IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]       DATETIME DEFAULT (getdate()) NULL,
    [DOSES]                    INT      NULL,
    [DATE_OF_STATISTICS_START] DATETIME NULL,
    [DATE_OF_STATISTICS_END]   DATETIME NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

