CREATE TABLE [VWSINTER].[RIVM_SEWER_MEASUREMENTS] (
    [ID]                  INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_RIVM_SEWER_MEASUREMENTS_2021]) NOT NULL,
    [DATE_MEASUREMENT]    DATETIME      NULL,
    [VERSION]             VARCHAR (100) NULL,
    [RWZI_AWZI_CODE]      BIGINT        NULL,
    [RWZI_AWZI_NAME]      VARCHAR (100) NULL,
    [RNA_PER_ML]          BIGINT        NULL,
    [RNA_FLOW_PER_100000] BIGINT        NULL,
    [DATE_LAST_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

