CREATE TABLE [VWSINTER].[RIVM_COVID_19_NUMBER_MUNICIPALITY] (
    [ID]                       INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_COVID19_MUNICIPALITY]) NOT NULL,
    [DATE_OF_REPORT]           DATETIME      NULL,
    [DATE_OF_PUBLICATION]      DATETIME      NULL,
    [MUNICIPALITY_CODE]        VARCHAR (100) NULL,
    [MUNICIPALITY_NAME]        VARCHAR (100) NULL,
    [PROVINCE]                 VARCHAR (100) NULL,
    [SECURITY_REGION_CODE]     VARCHAR (100) NULL,
    [SECURITY_REGION_NAME]     VARCHAR (100) NULL,
    [MUNICIPAL_HEALTH_SERVICE] VARCHAR (100) NULL,
    [ROAZ_REGION]              VARCHAR (100) NULL,
    [TOTAL_REPORTED]           INT           NULL,
    [HOSPITAL_ADMISSION]       INT           NULL,
    [DECEASED]                 INT           NULL,
    [DATE_LAST_INSERTED]       DATETIME      DEFAULT (getdate()) NULL
);


GO
CREATE CLUSTERED INDEX [IX_VWSINTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_CI]
    ON [VWSINTER].[RIVM_COVID_19_NUMBER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_MC_DP_MN_HA_DLI]
    ON [VWSINTER].[RIVM_COVID_19_NUMBER_MUNICIPALITY]([MUNICIPALITY_CODE] ASC)
    INCLUDE([DATE_OF_PUBLICATION], [MUNICIPALITY_NAME], [HOSPITAL_ADMISSION], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_MC_DP_MN_HA]
    ON [VWSINTER].[RIVM_COVID_19_NUMBER_MUNICIPALITY]([MUNICIPALITY_CODE] ASC)
    INCLUDE([DATE_OF_PUBLICATION], [MUNICIPALITY_NAME], [HOSPITAL_ADMISSION]);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_MC]
    ON [VWSINTER].[RIVM_COVID_19_NUMBER_MUNICIPALITY]([MUNICIPALITY_CODE] ASC)
    INCLUDE([DATE_OF_PUBLICATION], [MUNICIPALITY_NAME], [TOTAL_REPORTED], [DATE_LAST_INSERTED]);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_DLI_DP_MC_MN_HA]
    ON [VWSINTER].[RIVM_COVID_19_NUMBER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_PUBLICATION], [MUNICIPALITY_CODE], [MUNICIPALITY_NAME], [HOSPITAL_ADMISSION]);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY_DLI]
    ON [VWSINTER].[RIVM_COVID_19_NUMBER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_PUBLICATION], [MUNICIPALITY_CODE], [MUNICIPALITY_NAME], [TOTAL_REPORTED]);


GO
CREATE NONCLUSTERED INDEX [IX_INTER_RIVM_COVID_19_NUMBER_MUNICIPALITY]
    ON [VWSINTER].[RIVM_COVID_19_NUMBER_MUNICIPALITY]([DATE_LAST_INSERTED] ASC)
    INCLUDE([DATE_OF_PUBLICATION], [SECURITY_REGION_CODE], [TOTAL_REPORTED], [HOSPITAL_ADMISSION], [DECEASED]);

