CREATE TABLE [VWSINTER].[VWS_RESTRICTIONS_MAPPING_PER_REGION] (
    [ID]                     INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_VWS_RESTRICTIONS_MAPPING_PER_REGION]) NOT NULL,
    [REGION_ID]              VARCHAR (100) NULL,
    [RESTRICTION_IDENTIFIER] INT           NULL,
    [VALID_FROM]             DATETIME      NULL,
    [DATE_LAST_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_RESTRICTIONS_MAPPING_PER_REGION_INTER]
    ON [VWSINTER].[VWS_RESTRICTIONS_MAPPING_PER_REGION]([DATE_LAST_INSERTED] ASC, [RESTRICTION_IDENTIFIER] ASC);

