CREATE TABLE [VWSINTER].[VWS_RESTRICTIONS_MAPPING] (
    [ID]                 INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_VWS_RESTRICTIONS_MAPPING]) NOT NULL,
    [IDENTIFIER]         INT           NULL,
    [TARGET_REGION]      VARCHAR (100) NULL,
    [ESCALATION_LEVEL]   INT           NULL,
    [CATEGORY_ID]        VARCHAR (100) NULL,
    [RESTRICTION_ORDER]  INT           NULL,
    [VALID_FROM]         DATETIME      NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_RESTRICTIONS_MAPPING_INTER]
    ON [VWSINTER].[VWS_RESTRICTIONS_MAPPING]([DATE_LAST_INSERTED] ASC, [TARGET_REGION] ASC)
    INCLUDE([IDENTIFIER]);

