CREATE TABLE [VWSINTER].[VWS_VACCINATION_AVAILABILITY] (
    [ID]                  INT           DEFAULT (NEXT VALUE FOR [dbo].[SEQ_VWSINTER_VACCINATION_AVAILABILITY]) NOT NULL,
    [VALID_FROM]          DATETIME      NULL,
    [VACCIN_NAME]         VARCHAR (100) NULL,
    [EXPECTED_OR_OPTIONS] VARCHAR (100) NULL,
    [DATE_DELIVERY]       DATETIME      NULL,
    [AMOUNT_DELIVERY]     FLOAT (53)    NULL,
    [DATE_LAST_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_VWS_VACCINATION_AVAILABILITY_INTER]
    ON [VWSINTER].[VWS_VACCINATION_AVAILABILITY]([DATE_LAST_INSERTED] ASC, [VALID_FROM] ASC)
    INCLUDE([DATE_DELIVERY], [AMOUNT_DELIVERY]);

