CREATE    VIEW [DATATINO_PROTO].[V_PROTO_CONFIGURATIONS_ALL] AS
SELECT T2.ID
     ,T1.ID AS PROTO_ID
     ,T1.PROTO_NAME
     ,T2.ITEM_NAME
     ,T3.VIEW_NAME
     ,T2.[CONSTRAINT]
     ,T2.CONSTRAINT_KEY_NAME
     ,T2.CONSTRAINT_VALUE
     ,T2.GROUPED
     ,T2.GROUPED_KEY_NAME
     ,T2.GROUPED_LAST_UPDATE_NAME
     ,T4.ID AS LAYOUT_ID
     ,T2.[ACTIVE]
     ,T2.COLUMNS
     ,T2.MOCKABLE
     ,T5.MOCK_NAME
FROM DATATINO_PROTO.PROTOS T1
JOIN DATATINO_PROTO.PROTO_CONFIGURATIONS T2 ON T1.ID = T2.PROTO_ID
JOIN DATATINO_PROTO.VIEWS T3 ON T2.VIEW_ID = T3.ID
JOIN DATATINO_PROTO.LAYOUTS T4 ON T2.LAYOUT_ID = T4.ID
LEFT JOIN DATATINO_PROTO.MOCKS T5 ON T2.MOCK_ID = T5.ID