CREATE TABLE [DATATINO_ORCHESTRATOR].[DELIMITER_TYPES] (
    [ID]          BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_ORCHESTRATOR].[SEQ_DELIMITER_TYPES]) NOT NULL,
    [NAME]        VARCHAR (100) NOT NULL,
    [DESCRIPTION] VARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([NAME] ASC)
);

