CREATE TABLE [DATATINO_ORCHESTRATOR].[H_PROCESSES] (
    [ID]           BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_ORCHESTRATOR].[SEQ_H_PROCESSES]) NOT NULL,
    [IDENTIFIER]   BIGINT        NOT NULL,
    [PROCESS_NAME] VARCHAR (200) NOT NULL,
    [LAST_RUN]     DATETIME2 (7) NULL,
    [STATUS]       CHAR (5)      NOT NULL,
    CONSTRAINT [FK_H_PROCESS_ID] FOREIGN KEY ([IDENTIFIER]) REFERENCES [DATATINO_ORCHESTRATOR].[PROCESSES] ([ID])
);

