CREATE TABLE [DATATINO_ORCHESTRATOR].[H_WORKFLOWS] (
    [ID]            BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_ORCHESTRATOR].[SEQ_H_WORKFLOWS]) NOT NULL,
    [IDENTIFIER]    BIGINT        NOT NULL,
    [WORKFLOW_NAME] VARCHAR (200) NOT NULL,
    [LAST_RUN]      DATETIME2 (7) NULL,
    [STATUS]        CHAR (5)      NOT NULL,
    CONSTRAINT [FK_H_WORKFLOW_ID] FOREIGN KEY ([IDENTIFIER]) REFERENCES [DATATINO_ORCHESTRATOR].[WORKFLOWS] ([ID])
);

