CREATE TABLE [DATATINO_ORCHESTRATOR].[LOCATION_TYPES] (
    [ID]          BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_ORCHESTRATOR].[SEQ_LOCATION_TYPES]) NOT NULL,
    [NAME]        VARCHAR (100) NOT NULL,
    [DESCRIPTION] VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([NAME] ASC)
);

