CREATE TABLE [DATATINO_ORCHESTRATOR].[PROCESSES] (
    [ID]           BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_ORCHESTRATOR].[SEQ_PROCESSES]) NOT NULL,
    [PROCESS_NAME] VARCHAR (200) NOT NULL,
    [DESCRIPTION]  VARCHAR (200) NOT NULL,
    [SOURCE_ID]    BIGINT        NOT NULL,
    [WORKFLOW_ID]  BIGINT        NOT NULL,
    [LAST_RUN]     DATETIME2 (7) NULL,
    [ACTIVE]       INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [CHK_ACTIVE_PROCESS] CHECK ([ACTIVE]=(1) OR [ACTIVE]=(0)),
    CONSTRAINT [FK_SOURCE_ID] FOREIGN KEY ([SOURCE_ID]) REFERENCES [DATATINO_ORCHESTRATOR].[SOURCES] ([ID]),
    CONSTRAINT [FK_WORKFLOW_ID] FOREIGN KEY ([WORKFLOW_ID]) REFERENCES [DATATINO_ORCHESTRATOR].[WORKFLOWS] ([ID]),
    CONSTRAINT [UQ_WID_SOURCE] UNIQUE NONCLUSTERED ([PROCESS_NAME] ASC, [WORKFLOW_ID] ASC)
);

