CREATE TABLE [DATATINO_ORCHESTRATOR].[SECURITY_PROFILE_TYPES] (
    [ID]                    BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_ORCHESTRATOR].[SEQ_SECURITY_PROFILE_TYPES]) NOT NULL,
    [SECURITY_PROFILE_TYPE] VARCHAR (100) NOT NULL,
    [DESCRIPTION]           VARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([SECURITY_PROFILE_TYPE] ASC)
);

