CREATE TABLE [DATATINO_ORCHESTRATOR].[SOURCES] (
    [ID]                BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_ORCHESTRATOR].[SEQ_SOURCES]) NOT NULL,
    [SOURCE_NAME]       VARCHAR (200) NOT NULL,
    [DESCRIPTION]       VARCHAR (MAX) NOT NULL,
    [SOURCE]            VARCHAR (MAX) NOT NULL,
    [SOURCE_COLUMNS]    VARCHAR (MAX) DEFAULT ('*') NULL,
    [TARGET_COLUMNS]    VARCHAR (MAX) NULL,
    [TARGET_NAME]       VARCHAR (MAX) NULL,
    [SOURCE_TYPE_ID]    BIGINT        NOT NULL,
    [LOCATION_TYPE_ID]  BIGINT        NOT NULL,
    [DELIMITER_TYPE_ID] BIGINT        DEFAULT ((0)) NOT NULL,
    [SP_ID]             BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DELIMITER_TYPE_ID] FOREIGN KEY ([DELIMITER_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR].[DELIMITER_TYPES] ([ID]),
    CONSTRAINT [FK_LOCATION_TYPE_ID] FOREIGN KEY ([LOCATION_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR].[LOCATION_TYPES] ([ID]),
    CONSTRAINT [FK_SOURCE_TYPE_ID] FOREIGN KEY ([SOURCE_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR].[SOURCE_TYPES] ([ID]),
    CONSTRAINT [FK_SP_ID] FOREIGN KEY ([SP_ID]) REFERENCES [DATATINO_ORCHESTRATOR].[SECURITY_PROFILES] ([ID]),
    UNIQUE NONCLUSTERED ([SOURCE_NAME] ASC),
    CONSTRAINT [UQ_SOURCE] UNIQUE NONCLUSTERED ([SOURCE_NAME] ASC, [SOURCE_TYPE_ID] ASC, [LOCATION_TYPE_ID] ASC, [DELIMITER_TYPE_ID] ASC, [SP_ID] ASC)
);

