CREATE TABLE [DATATINO_ORCHESTRATOR].[SOURCE_CHECKSUMS] (
    [ID]                 BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_ORCHESTRATOR].[SEQ_SOURCE_CHECKSUMS]) NOT NULL,
    [DATE_LAST_INSERTED] DATETIME      DEFAULT (getdate()) NULL,
    [SOURCE]             VARCHAR (MAX) NULL,
    [CHECKSUM]           VARCHAR (MAX) NULL
);

