CREATE TABLE [DATATINO_ORCHESTRATOR].[WORKFLOWS] (
    [ID]            BIGINT        DEFAULT (NEXT VALUE FOR [DATATINO_ORCHESTRATOR].[SEQ_WORKFLOWS]) NOT NULL,
    [WORKFLOW_NAME] VARCHAR (200) NOT NULL,
    [INTERVAL_ID]   BIGINT        NULL,
    [TIME_TO_RUN]   TIME (7)      NULL,
    [RUN_DAY]       INT           NULL,
    [ALWAYS_RUN]    INT           NULL,
    [ACTIVE]        INT           NULL,
    [DESCRIPTION]   VARCHAR (MAX) NULL,
    [SCHEDULE]      VARCHAR (100) NULL,
    [NEXT_RUN]      DATETIME2 (7) NULL,
    [LAST_RUN]      DATETIME2 (7) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([WORKFLOW_NAME] ASC)
);

