-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER VIEW VWSDEST.V_HOSPITAL_ADMISSIONS_GM_NICE AS
SELECT
    [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_STATISTICS]) AS [DATE_UNIX],
    GM_CODE AS GMCODE,
    GM_NAME AS MUNICIPALITY_NAME,
    DBO.NO_NEGATIVE_NUMBER_I(HOSPITALIZED) AS ADMISSIONS_ON_DATE_OF_ADMISSION,
    DBO.NO_NEGATIVE_NUMBER_I(REPORTED) AS ADMISSIONS_ON_DATE_OF_REPORTING,
    dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX
FROM VWSDEST.NICE_HOSPITAL_GM
WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED)
                            FROM VWSDEST.NICE_HOSPITAL_GM);