-- View for only selecting the values that were inserted last.
CREATE   VIEW [VWSSTATIC].[V_NURSING_HOME_LOCATIONS_PER_REGION] AS
SELECT 
	VRCODE,
	VRNAAM,
	VERPLEEGHUIZEN,
	GEHANDICAPTENZORGINSTELLINGEN,
	DATE_LAST_INSERTED
    FROM ( 
		SELECT 
			VRCODE, 
			VRNAAM, 
			VERPLEEGHUIZEN, 
			GEHANDICAPTENZORGINSTELLINGEN,
			DATE_LAST_INSERTED,
			RANK() OVER (PARTITION BY VRCODE ORDER BY DATE_LAST_INSERTED DESC) RANK_ORDER
			FROM [VWSSTATIC].[NURSING_HOME_LOCATIONS_PER_REGION]
	) T1 WHERE RANK_ORDER = 1