-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

-- Values for national (NL.json) file
exec [dbo].[SafeInsertView] 'VWSDEST.V_GENERAL_PRACTITIONERS', 'WEEK_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_HOSPITAL_ADMISSIONS', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_INFECTIOUS_PEOPLE', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_INFECTIOUS_PEOPLE_NORMALIZED', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_INTENSIVE_CARE_ADMISSIONS', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_NURSING_HOMES_TOTALS_INFECTED', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_NURSING_HOMES_TOTALS_DECEASED', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_NURSING_HOMES_TOTALS_LOCATIONS', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_NURSING_HOMES_TOTALS_NEW_LOCATIONS', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_POSITIVE_TESTED_PEOPLE', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_POSITIVE_TESTED_PEOPLE_DELTA', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_POSITIVE_TESTED_PEOPLE_PER_AGE_GROUP', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_REPRODUCTION_NUMBER', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_REPRODUCTION_NUMBER_LAST_KNOWN', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_SEWER_MEASUREMENTS', 'WEEK_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_RESULTS_PER_REGION', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_VWS_MAX_AND_MIN', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_SEWER_MEASUREMENTS_PER_REGION', 'WEEK_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_SEWER_MEASUREMENTS_PER_RWZI', 'DATE_MEASUREMENT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_LATEST_SEWER_MEASUREMENTS_PER_RWZI', 'DATE_MEASUREMENT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_HOSPITAL_ADMISSIONS_PER_MUNICIPALITY', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_POSITIVE_TESTED_PEOPLE_PER_MUNICIPALITY', 'DATE_OF_REPORT_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_SEWER_MEASUREMENTS_PER_MUNICIPALITY', 'WEEK_UNIX';
exec [dbo].[SafeInsertView] 'VWSDEST.V_SEWER_MEASUREMENTS_PER_RWZI_MINIMAL', 'DATE_MEASUREMENT_UNIX';
GO