CREATE     VIEW [DATATINO_ORCHESTRATOR].[V_DEPENDENCIES] AS
SELECT 
      T0.PROCESS_ID,
      TX.PROCESS,
      TX.SOURCE AS PROCESS_SOURCE,
      TY.DEPENDENCY_ID,
      TY.DEPENDENCY,
      TY.SOURCE AS DEPENDENCY_SOURCE,
      T2.WORKFLOW_NAME,
      T2.ID AS WORKFLOW_ID
FROM DATATINO_ORCHESTRATOR.DEPENDENCIES T0
JOIN (SELECT X.ID AS PROCESS_ID, X.PROCESS_NAME AS PROCESS, Z.SOURCE
        FROM DATATINO_ORCHESTRATOR.PROCESSES  X
        JOIN DATATINO_ORCHESTRATOR.SOURCES Z
        ON Z.ID = X.SOURCE_ID) TX
ON TX.PROCESS_ID = T0.PROCESS_ID
JOIN (SELECT X.ID AS DEPENDENCY_ID, X.PROCESS_NAME AS DEPENDENCY, Z.SOURCE
        FROM DATATINO_ORCHESTRATOR.PROCESSES  X
        JOIN DATATINO_ORCHESTRATOR.SOURCES Z
        ON Z.ID = X.SOURCE_ID) TY
ON TY.DEPENDENCY_ID = T0.DEPENDENCY
JOIN DATATINO_ORCHESTRATOR.WORKfLOWS T2
ON T0.WORKFLOW_ID = T2.ID