CREATE    VIEW [DATATINO_ORCHESTRATOR].[V_DEPENDENCIES_CONFIG] AS
SELECT 
      TX.PROCESS AS PROCESS_NAME,
      TY.DEPENDENCY AS DEPENDENCY_NAME,
      T2.WORKFLOW_NAME,
      T0.ACTIVE
FROM DATATINO_ORCHESTRATOR.DEPENDENCIES T0
JOIN (SELECT X.ID AS PROCESS_ID, X.PROCESS_NAME AS PROCESS, Z.SOURCE
        FROM DATATINO_ORCHESTRATOR.PROCESSES  X
        JOIN DATATINO_ORCHESTRATOR.SOURCES Z
        ON Z.ID = X.SOURCE_ID) TX
ON TX.PROCESS_ID = T0.PROCESS_ID
JOIN (SELECT X.ID AS DEPENDENCY_ID, X.PROCESS_NAME AS DEPENDENCY, Z.SOURCE
        FROM DATATINO_ORCHESTRATOR.PROCESSES  X
        JOIN DATATINO_ORCHESTRATOR.SOURCES Z
        ON Z.ID = X.SOURCE_ID) TY
ON TY.DEPENDENCY_ID = T0.DEPENDENCY
JOIN DATATINO_ORCHESTRATOR.WORKfLOWS T2
ON T0.WORKFLOW_ID = T2.ID