CREATE   VIEW [DATATINO_ORCHESTRATOR].[V_PROCESSES] AS
SELECT 
     T1.ID AS PROCESS_ID
    ,T1.PROCESS_NAME
    ,T1.[DESCRIPTION]
    ,T1.WORKFLOW_ID
    ,T2.WORKFLOW_NAME
    ,T1.SOURCE_ID
    ,T3.SOURCE_NAME
    ,T3.SOURCE
    ,T3.SOURCE_COLUMNS
    ,T3.TARGET_COLUMNS
    ,T3.TARGET_NAME
    ,T3.SOURCE_TYPE_ID
    ,T6.NAME AS SOURCE_TYPE_NAME
    ,T3.LOCATION_TYPE_ID
    ,T7.NAME AS LOCATION_TYPE_NAME
    ,T3.DELIMITER_TYPE_ID
    ,T8.NAME AS DELIMITER_TYPE_NAME
    ,CASE WHEN T3.SP_ID IS NOT NULL THEN 1 ELSE 0 END AS SECURED
    ,T3.SP_ID
    ,T4.VALUE
    ,T5.ID AS SECURITY_PROFILE_TYPE
    ,T1.ACTIVE
FROM DATATINO_ORCHESTRATOR.PROCESSES T1
JOIN DATATINO_ORCHESTRATOR.WORKfLOWS T2
ON T1.WORKFLOW_ID = T2.ID
JOIN DATATINO_ORCHESTRATOR.SOURCES T3
ON T1.SOURCE_ID = T3.ID
LEFT JOIN DATATINO_ORCHESTRATOR.SECURITY_PROFILES T4
ON T3.SP_ID = T4.ID
LEFT JOIN DATATINO_ORCHESTRATOR.SECURITY_PROFILE_TYPES T5
ON T4.SPT_ID = T5.ID
JOIN DATATINO_ORCHESTRATOR.SOURCE_TYPES T6
ON T3.SOURCE_TYPE_ID = T6.ID
JOIN DATATINO_ORCHESTRATOR.LOCATION_TYPES T7
ON T3.LOCATION_TYPE_ID = T7.ID
JOIN DATATINO_ORCHESTRATOR.DELIMITER_TYPES T8
ON T3.DELIMITER_TYPE_ID = T8.ID