CREATE   VIEW DATATINO_ORCHESTRATOR.V_PROCESSES_CONFIG
AS
SELECT a.PROCESS_NAME, a.DESCRIPTION, b.SOURCE_NAME, c.WORKFLOW_NAME, a.ACTIVE
FROM DATATINO_ORCHESTRATOR.PROCESSES a
JOIN DATATINO_ORCHESTRATOR.SOURCES b
ON a.SOURCE_ID = b.ID
JOIN DATATINO_ORCHESTRATOR.WORKFLOWS c
ON a.WORKFLOW_ID = c.ID