CREATE   VIEW DATATINO_ORCHESTRATOR.V_SOURCES_CONFIG
AS
SELECT a.SOURCE_NAME, a.DESCRIPTION, a.SOURCE, a.SOURCE_COLUMNS, a.TARGET_COLUMNS, a.TARGET_NAME, b.NAME AS SOURCE_TYPE, c.NAME AS LOCATION_TYPE, d.NAME AS DELIMITER_TYPE, e.VALUE AS SECURITY_PROFILE 
FROM DATATINO_ORCHESTRATOR.SOURCES a
JOIN DATATINO_ORCHESTRATOR.SOURCE_TYPES b
ON a.SOURCE_TYPE_ID = b.ID
JOIN DATATINO_ORCHESTRATOR.LOCATION_TYPES c
ON a.LOCATION_TYPE_ID = c.ID
JOIN DATATINO_ORCHESTRATOR.DELIMITER_TYPES d
ON a.DELIMITER_TYPE_ID = d.ID
LEFT JOIN DATATINO_ORCHESTRATOR.SECURITY_PROFILES e
ON a.SP_ID = e.ID