-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION [dbo].[CALC_PERC_CHANGE] (@new BIGINT, @old BIGINT)
 RETURNS FLOAT
 AS BEGIN
     DECLARE @res FLOAT
     -- Return null if div through 0
     set @res = 1.0*(@new-@old)/NULLIF(@old, 0)
     RETURN @res
 END;