-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION [dbo].[CONVERT_WEEKNUMBER_TO_DATETIME] (@year VARCHAR(4), @week VARCHAR(2))
 RETURNS DATETIME
 AS BEGIN
     DECLARE @result DATETIME
     set @result = DATEADD(wk,DATEDIFF(wk,0,'01/04/'+@year),0)+((@week-1)*7)
     RETURN @result
 END;