-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION [dbo].[CONVERT_UNIX_TO_ISO_WEEKNUMBER] (@input BIGINT)
 RETURNS INT
 AS BEGIN
     DECLARE @res INT
     set @res = dbo.CONVERT_DATETIME_TO_ISO_WEEKNUMBER(dbo.CONVERT_UNIX_TO_DATETIME(@input))
     RETURN @res
 END;
GO
GRANT EXECUTE
    ON OBJECT::[dbo].[CONVERT_UNIX_TO_ISO_WEEKNUMBER] TO [db_execute_functions]
    AS [dbo];

