-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION [dbo].[CONVERT_ISO_WEEK_TO_UNIX] (@year INT, @week INT)
 RETURNS BIGINT
 AS BEGIN
     DECLARE @result BIGINT
     set @result=[dbo].[CONVERT_DATETIME_TO_UNIX]([dbo].[CONVERT_ISO_WEEK_TO_DATETIME](@year, @week))
     RETURN @result
 END;