-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION [dbo].[CONVERT_UNIX_TO_DATETIME] (@input BIGINT)
 RETURNS DATETIME
 AS BEGIN
     DECLARE @res DATETIME
     set @res = DATEADD(S, @input, '1970-01-01')
     RETURN @res
 END;
GO
GRANT EXECUTE
    ON OBJECT::[dbo].[CONVERT_UNIX_TO_DATETIME] TO [db_execute_functions]
    AS [dbo];

