-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE    FUNCTION [dbo].[CONVERT_ISO_WEEK_TO_DATETIME] (@year INT, @week INT)
 RETURNS DATETIME
 AS BEGIN
     DECLARE @result DATETIME
     -- 01/04 - 4th of January - to identify week 01 (see https://en.wikipedia.org/wiki/ISO_8601#Week_dates)
     SET @result = DATEADD(wk,DATEDIFF(wk,0,DATEFROMPARTS(@year,1,4)),0)+((@week-1)*7)
     RETURN @result
 END;