-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION [dbo].[CONVERT_DATETIME_TO_ISO_WEEKNUMBER] (@input DATETIME)
 RETURNS INT
 AS BEGIN
     DECLARE @res INT
     set @res = DATEPART(ISO_WEEK, @input)
     RETURN @res
 END;