-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION [dbo].[INT_TO_CHANGE] (@val INT)
 RETURNS VARCHAR(10)
 AS
 BEGIN
     RETURN
         CASE 
             WHEN @val > 0 THEN 'up'
             WHEN @val < 0 THEN 'down'
             WHEN @val = 0  THEN 'equal'
             ELSE NULL
         END 
 END;