-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION DBO.NO_NEGATIVE_NUMBER_F (@input FLOAT)
 RETURNS FLOAT
 AS BEGIN
     DECLARE @Work FLOAT
 
     SET @Work = @Input
     -- if the value was null keep 
     set @Work = (CASE WHEN @work IS NULL THEN NULL
     ELSE
         (SELECT CASE WHEN @work > 0 THEN @work ELSE 0.0 END)
     END)
     RETURN @work
 END;