-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION [dbo].[NORMALIZATION] (@input FLOAT)
 RETURNS FLOAT
 AS BEGIN
     DECLARE @NORMALIZATION FLOAT;
     SET @NORMALIZATION = @input /100000.0;
     RETURN @NORMALIZATION
 END