-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION [DBO].[TRY_CONVERT_TO_DATETIME](@input [VARCHAR](50))
 RETURNS [DATETIME]
 AS BEGIN
     DECLARE @dt DATETIME;
 
     SET @dt = CASE 
         WHEN TRY_CONVERT(DATE, @input, 126) IS NOT NULL THEN CONVERT(DATE, @input, 126)
         WHEN TRY_CONVERT(DATE, @input, 120) IS NOT NULL THEN CONVERT(DATE, @input, 120) -- MM-dd-yyyy
         WHEN TRY_CONVERT(DATE, @input, 105) IS NOT NULL THEN CONVERT(DATE, @input, 105) -- yyyy-MM-dd
         ELSE CONVERT(DATE, @input)
     END;
 
     RETURN @dt;
 END;