-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION [dbo].[WEEK_START] (@input DATETIME)
 RETURNS DATETIME
 AS BEGIN
     DECLARE @work DATETIME
     SET @work = @input
     set @work = DATEADD(week, DATEDIFF(day, 0, @work)/7, 0) 
     RETURN @work
 END
GO
GRANT EXECUTE
    ON OBJECT::[dbo].[WEEK_START] TO [db_execute_functions]
    AS [dbo];

