-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   FUNCTION [dbo].[WEEK_START_FROM_WEEKNUMBER] (@input INT)
 RETURNS DATETIME
 AS BEGIN
     DECLARE @work DATETIME
     SET @work = convert(datetime, DATEADD(day, 6, dateadd(week,@input-1, DATEADD(wk, DATEDIFF(wk,-1,DATEADD(yy, DATEDIFF(yy,0,getdate()), 0)), 0))), 101)
     set @work = DATEADD(week, DATEDIFF(day, 0, @work)/7, 0) 
     RETURN @work
 END;
GO
GRANT EXECUTE
    ON OBJECT::[dbo].[WEEK_START_FROM_WEEKNUMBER] TO [db_execute_functions]
    AS [dbo];

