CREATE TABLE [DATATINO_ORCHESTRATOR_1].[DATAFLOW_TYPES] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [NAME]        NVARCHAR (200) NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_DATAFLOW_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

