CREATE TABLE [DATATINO_ORCHESTRATOR_1].[DATAFLOWS] (
    [ID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [DATAFLOW_TYPE_ID] BIGINT         NOT NULL,
    [NAME]             NVARCHAR (200) NOT NULL,
    [DESCRIPTION]      NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_DATAFLOWS] PRIMARY KEY CLUSTERED ([ID] ASC, [DATAFLOW_TYPE_ID] ASC),
    CONSTRAINT [FK_DATAFLOW_DATAFLOW_TYPE] FOREIGN KEY ([DATAFLOW_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[DATAFLOW_TYPES] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DATAFLOWS_NAME]
    ON [DATATINO_ORCHESTRATOR_1].[DATAFLOWS]([NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DATAFLOWS_DATAFLOW_TYPE_ID]
    ON [DATATINO_ORCHESTRATOR_1].[DATAFLOWS]([DATAFLOW_TYPE_ID] ASC);

