CREATE TABLE [DATATINO_ORCHESTRATOR_1].[DATAFLOW_DOWNTIME] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [DATETIME]    DATETIME2 (7)  NOT NULL,
    [NAME]        NVARCHAR (200) NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_DATAFLOW_DOWNTIME] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DATAFLOW_DOWNTIME_DATETIME]
    ON [DATATINO_ORCHESTRATOR_1].[DATAFLOW_DOWNTIME]([DATETIME] ASC);

