CREATE TABLE [DATATINO_ORCHESTRATOR_1].[H_DATAFLOWS] (
    [ID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [NAME]             NVARCHAR (200) NOT NULL,
    [DATAFLOW_ID]      BIGINT         NOT NULL,
    [DATAFLOW_TYPE_ID] BIGINT         NOT NULL,
    [START_RUN]        DATETIME2 (7)  NULL,
    [END_RUN]          DATETIME2 (7)  NULL,
    [STATUS]           INT            NOT NULL,
    [MESSAGE]          NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_H_DATAFLOWS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_H_DATAFLOWS_DATAFLOW_TYPES_DATAFLOW_TYPE_ID] FOREIGN KEY ([DATAFLOW_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[DATAFLOW_TYPES] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_HDATAFLOW_DATAFLOW_TYPE] FOREIGN KEY ([DATAFLOW_ID], [DATAFLOW_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[DATAFLOWS] ([ID], [DATAFLOW_TYPE_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_H_DATAFLOWS_DATAFLOW_TYPE_ID]
    ON [DATATINO_ORCHESTRATOR_1].[H_DATAFLOWS]([DATAFLOW_TYPE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_H_DATAFLOWS_DATAFLOW_ID_DATAFLOW_TYPE_ID]
    ON [DATATINO_ORCHESTRATOR_1].[H_DATAFLOWS]([DATAFLOW_ID] ASC, [DATAFLOW_TYPE_ID] ASC);

