CREATE TABLE [DATATINO_ORCHESTRATOR_1].[PROCESSES] (
    [ID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [WORKFLOW_ID]      BIGINT         NULL,
    [SOURCE_ID]        BIGINT         NULL,
    [DATAFLOW_ID]      BIGINT         NULL,
    [DATAFLOW_TYPE_ID] BIGINT         NOT NULL,
    [SCHEDULE]         NVARCHAR (100) NOT NULL,
    [NEXT_RUN]         DATETIME2 (7)  NULL,
    [LAST_RUN]         DATETIME2 (7)  NULL,
    [ACTIVE]           INT            NOT NULL,
    CONSTRAINT [PK_PROCESSES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PROCESS_DATAFLOW] FOREIGN KEY ([DATAFLOW_ID], [DATAFLOW_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[DATAFLOWS] ([ID], [DATAFLOW_TYPE_ID]),
    CONSTRAINT [FK_PROCESS_SOURCE] FOREIGN KEY ([SOURCE_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[SOURCES] ([ID]),
    CONSTRAINT [FK_PROCESS_WORKFLOW] FOREIGN KEY ([WORKFLOW_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[WORKFLOWS] ([ID]),
    CONSTRAINT [FK_PROCESSES_DATAFLOW_TYPES_DATAFLOW_TYPE_ID] FOREIGN KEY ([DATAFLOW_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[DATAFLOW_TYPES] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PROCESSES_WORKFLOW_ID]
    ON [DATATINO_ORCHESTRATOR_1].[PROCESSES]([WORKFLOW_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PROCESSES_SOURCE_ID]
    ON [DATATINO_ORCHESTRATOR_1].[PROCESSES]([SOURCE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PROCESSES_DATAFLOW_TYPE_ID]
    ON [DATATINO_ORCHESTRATOR_1].[PROCESSES]([DATAFLOW_TYPE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PROCESSES_DATAFLOW_ID_DATAFLOW_TYPE_ID]
    ON [DATATINO_ORCHESTRATOR_1].[PROCESSES]([DATAFLOW_ID] ASC, [DATAFLOW_TYPE_ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROCESSES_DATAFLOW_ID]
    ON [DATATINO_ORCHESTRATOR_1].[PROCESSES]([DATAFLOW_ID] ASC) WHERE ([DATAFLOW_ID] IS NOT NULL);

