CREATE TABLE [DATATINO_ORCHESTRATOR_1].[SECURITY_PROFILES] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [SPT_ID]      BIGINT         NOT NULL,
    [ACTIVE]      INT            NOT NULL,
    [NAME]        NVARCHAR (200) NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_SECURITY_PROFILES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SECURITY_PROFILE_SECURITY_PROFILE_TYPE] FOREIGN KEY ([SPT_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[SECURITY_PROFILE_TYPES] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_SECURITY_PROFILES_SPT_ID]
    ON [DATATINO_ORCHESTRATOR_1].[SECURITY_PROFILES]([SPT_ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SECURITY_PROFILES_NAME_SPT_ID]
    ON [DATATINO_ORCHESTRATOR_1].[SECURITY_PROFILES]([NAME] ASC, [SPT_ID] ASC);

