CREATE TABLE [DATATINO_ORCHESTRATOR_1].[SOURCES] (
    [ID]                BIGINT         IDENTITY (1, 1) NOT NULL,
    [SOURCE_CONTENT]    NVARCHAR (MAX) NOT NULL,
    [SOURCE_COLUMNS]    NVARCHAR (MAX) NULL,
    [TARGET_COLUMNS]    NVARCHAR (MAX) NULL,
    [TARGET_NAME]       NVARCHAR (MAX) NULL,
    [SOURCE_TYPE_ID]    BIGINT         NOT NULL,
    [LOCATION_TYPE_ID]  BIGINT         NOT NULL,
    [DELIMITER_TYPE_ID] BIGINT         NOT NULL,
    [SP_ID]             BIGINT         NOT NULL,
    [NAME]              NVARCHAR (200) NOT NULL,
    [DESCRIPTION]       NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_SOURCES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SOURCE_DELIMITER_TYPE] FOREIGN KEY ([DELIMITER_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[DELIMITER_TYPES] ([ID]),
    CONSTRAINT [FK_SOURCE_LOCATION_TYPE] FOREIGN KEY ([LOCATION_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[LOCATION_TYPES] ([ID]),
    CONSTRAINT [FK_SOURCE_SECURITY_PROFILE] FOREIGN KEY ([SP_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[SECURITY_PROFILES] ([ID]),
    CONSTRAINT [FK_SOURCE_SOURCE_TYPE] FOREIGN KEY ([SOURCE_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[SOURCE_TYPES] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_SOURCES_SP_ID]
    ON [DATATINO_ORCHESTRATOR_1].[SOURCES]([SP_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SOURCES_SOURCE_TYPE_ID]
    ON [DATATINO_ORCHESTRATOR_1].[SOURCES]([SOURCE_TYPE_ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SOURCES_NAME_SOURCE_TYPE_ID_LOCATION_TYPE_ID_DELIMITER_TYPE_ID_SP_ID]
    ON [DATATINO_ORCHESTRATOR_1].[SOURCES]([NAME] ASC, [SOURCE_TYPE_ID] ASC, [LOCATION_TYPE_ID] ASC, [DELIMITER_TYPE_ID] ASC, [SP_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SOURCES_LOCATION_TYPE_ID]
    ON [DATATINO_ORCHESTRATOR_1].[SOURCES]([LOCATION_TYPE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SOURCES_DELIMITER_TYPE_ID]
    ON [DATATINO_ORCHESTRATOR_1].[SOURCES]([DELIMITER_TYPE_ID] ASC);

