CREATE TABLE [DATATINO_ORCHESTRATOR_1].[WORKFLOWS] (
    [ID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [DATAFLOW_ID]      BIGINT         NULL,
    [DATAFLOW_TYPE_ID] BIGINT         NOT NULL,
    [SCHEDULE]         NVARCHAR (100) NOT NULL,
    [NEXT_RUN]         DATETIME2 (7)  NULL,
    [LAST_RUN]         DATETIME2 (7)  NULL,
    [ACTIVE]           INT            NOT NULL,
    CONSTRAINT [PK_WORKFLOWS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_WORKFLOWS_DATAFLOW_TYPES_DATAFLOW_TYPE_ID] FOREIGN KEY ([DATAFLOW_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[DATAFLOW_TYPES] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_WORKFLOWS_DATAFLOWS_DATAFLOW_ID_DATAFLOW_TYPE_ID] FOREIGN KEY ([DATAFLOW_ID], [DATAFLOW_TYPE_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[DATAFLOWS] ([ID], [DATAFLOW_TYPE_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_WORKFLOWS_DATAFLOW_TYPE_ID]
    ON [DATATINO_ORCHESTRATOR_1].[WORKFLOWS]([DATAFLOW_TYPE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_WORKFLOWS_DATAFLOW_ID_DATAFLOW_TYPE_ID]
    ON [DATATINO_ORCHESTRATOR_1].[WORKFLOWS]([DATAFLOW_ID] ASC, [DATAFLOW_TYPE_ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_WORKFLOWS_DATAFLOW_ID]
    ON [DATATINO_ORCHESTRATOR_1].[WORKFLOWS]([DATAFLOW_ID] ASC) WHERE ([DATAFLOW_ID] IS NOT NULL);

