CREATE TABLE [VWSARCHIVE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR_ARCHIVED_20220908] (
    [ID]                                   BIGINT        IDENTITY (1, 1) NOT NULL,
    [DATE_OF_REPORT]                       DATETIME      NULL,
    [DATE_OF_STATISTICS]                   DATETIME      NULL,
    [REGION_CODE]                          VARCHAR (10)  NULL,
    [BIRTH_YEAR]                           VARCHAR (100) NULL,
    [AGE_GROUP]                            VARCHAR (10)  NULL,
    [VACCINATION_COVERAGE_ALL]             VARCHAR (100) NULL,
    [VACCINATION_COVERAGE_ALL_LABEL]       VARCHAR (100) NULL,
    [VACCINATION_COVERAGE_COMPLETED]       VARCHAR (100) NULL,
    [VACCINATION_COVERAGE_COMPLETED_LABEL] VARCHAR (100) NULL,
    [DATE_LAST_INSERTED]                   DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_DLI_DOF_DOS_RC_CIMS_VACCINATED_PER_AGE_GROUP_GM_VR_ARCHIVED_20220908]
    ON [VWSARCHIVE].[CIMS_VACCINATED_PER_AGE_GROUP_GM_VR_ARCHIVED_20220908]([DATE_LAST_INSERTED] ASC, [DATE_OF_REPORT] ASC, [DATE_OF_STATISTICS] ASC, [REGION_CODE] ASC)
    INCLUDE([BIRTH_YEAR], [AGE_GROUP], [VACCINATION_COVERAGE_ALL], [VACCINATION_COVERAGE_ALL_LABEL], [VACCINATION_COVERAGE_COMPLETED], [VACCINATION_COVERAGE_COMPLETED_LABEL]);

