CREATE TABLE [VWSARCHIVE].[DISABILITY_ARCHIVED_20230126] (
    [ID]                            INT             NOT NULL,
    [DATE_OF_REPORT]                DATETIME        NULL,
    [DATE_OF_REPORT_UNIX]           BIGINT          NULL,
    [INFECTED_DISABILITY_DAILY]     INT             NULL,
    [DECEASED_DISABILITY_DAILY]     INT             NULL,
    [TOTAL_NEW_INFECTED_LOCATIONS]  INT             NULL,
    [TOTAL_INFECTED_LOCATIONS]      INT             NULL,
    [TOTAL_LOCATIONS]               INT             NULL,
    [PERCENTAGE_INFECTED_LOCATIONS] FLOAT (53)      NULL,
    [DATE_LAST_INSERTED]            DATETIME        DEFAULT (getdate()) NULL,
    [DATE_RANGE_START]              DATETIME        NULL,
    [DATE_OF_REPORTS_LAG]           DATETIME        NULL,
    [DATE_RANGE_START_LAG]          DATETIME        NULL,
    [7D_AVERAGE_TOTAL_INFECTED]     DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_INFECTED_LAG] DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_DECEASED]     DECIMAL (16, 2) NULL,
    [7D_AVERAGE_TOTAL_DECEASED_LAG] DECIMAL (16, 2) NULL
);

