CREATE TABLE [VWSARCHIVE].[RIVM_VACCINATION_CAMPAIGNS_NL_ARCHIVED_20220908] (
    [VACCINE_CAMPAIGN_ORDER]         INT            NULL,
    [VACCINE_CAMPAIGN_NAME_NL]       NVARCHAR (250) NULL,
    [VACCINE_CAMPAIGN_NAME_EN]       NVARCHAR (250) NULL,
    [VACCINE_ADMINISTERED_TOTAL]     INT            NULL,
    [VACCINE_ADMINISTERED_LAST_WEEK] INT            NULL,
    [DATE_UNIX]                      BIGINT         NULL,
    [DATE_END_UNIX]                  BIGINT         NULL,
    [DATE_START_UNIX]                BIGINT         NULL,
    [DATE_OF_INSERTION_UNIX]         BIGINT         NULL
);

