CREATE TABLE [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL_ARCHIVED_20220908] (
    [ID]                      INT             IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED]      DATETIME        DEFAULT (getdate()) NOT NULL,
    [VERSION]                 INT             NULL,
    [DATE_OF_REPORT]          DATETIME        NULL,
    [DATE_OF_STATISTICS]      DATETIME        NULL,
    [AGE_GROUP]               VARCHAR (256)   NULL,
    [POPULATION_AGEGROUP]     INT             NULL,
    [BASE_SERIES]             VARCHAR (256)   NULL,
    [BOOSTER1]                VARCHAR (256)   NULL,
    [AMOUNT_CUMULATIVE]       INT             NULL,
    [COVERAGE_AGEGROUP]       NUMERIC (10, 2) NULL,
    [COVERAGE_TO_BASE_SERIES] NUMERIC (10, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCIX_RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL_ARCHIVED_20220908]
    ON [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_NL_ARCHIVED_20220908]([DATE_LAST_INSERTED] ASC);

