CREATE TABLE [VWSARCHIVE].[RIVM_VACCINATION_SHOTS_PLANNED_NL_ARCHIVED_20220908] (
    [DOSES]                  INT    NULL,
    [DATE_UNIX]              BIGINT NULL,
    [DATE_START_UNIX]        BIGINT NULL,
    [DATE_END_UNIX]          BIGINT NULL,
    [DATE_OF_INSERTION_UNIX] BIGINT NULL
);

