CREATE TABLE [VWSARCHIVE].[RIVM_VACCINATION_SHOT_COVERAGES_PER_CAMPAIGN_NL_ARCHIVED_20220908] (
    [ID]                   BIGINT       NULL,
    [DATE_LAST_INSERTED]   DATETIME     DEFAULT (getdate()) NULL,
    [DATE_OF_STATISTICS]   DATETIME     NULL,
    [DATE_OF_REPORT]       DATETIME     NULL,
    [AGE_GROUP]            VARCHAR (50) NULL,
    [BIRTH_YEAR]           VARCHAR (50) NULL,
    [PERCENTAGE_PARTLY]    FLOAT (53)   NULL,
    [PERCENTAGE_COMPLETED] FLOAT (53)   NULL
);

