CREATE TABLE [VWSARCHIVE].[RIVM_VACCINATIONS_BOOSTER_SHOTS_COVERAGE_VR_ARCHIVED_20220904] (
    [ID]                 INT             IDENTITY (1, 1) NOT NULL,
    [DATE_LAST_INSERTED] DATETIME        DEFAULT (getdate()) NOT NULL,
    [VERSION]            INT             NULL,
    [DATE_OF_REPORT]     DATETIME        NULL,
    [DATE_OF_STATISTICS] DATETIME        NULL,
    [POPULATION]         BIGINT          NULL,
    [REGION_CODE]        VARCHAR (256)   NULL,
    [REGION_LEVEL]       VARCHAR (256)   NULL,
    [REGION_NAME]        VARCHAR (256)   NULL,
    [AGE_GROUP]          VARCHAR (256)   NULL,
    [VACCINATION_SERIE]  VARCHAR (256)   NULL,
    [PERCENTAGE]         NUMERIC (10, 2) NULL,
    [PERCENTAGE_LABEL]   VARCHAR (256)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

