
CREATE   VIEW  [DATATINO_ORCHESTRATOR_1].[V_DEPENDENCIES] AS

SELECT 
       T0.[ID]
      ,T0.[NAME]
      ,T0.[DATAFLOW_ID]
      ,T4.NAME                              AS MAIN_NAME
      ,T0.[DATAFLOW_TYPE_ID]
      ,T5.NAME                              AS MAIN_TYPE

      ,T0.[DEPENDENCY_ID]
      ,T6.NAME                              AS DEPENDENCY_NAME
      ,T0.[DATAFLOW_TYPE_ID_DEPENDENCY]
      ,T7.NAME                              AS DEPENDENCY_TYPE

      ,T0.[WORKFLOW_ID]
      ,T2.[NAME]                            AS WORKFLOW_NAME
      ,T0.[ACTIVE]
      ,T0.[DESCRIPTION]
  FROM [DATATINO_ORCHESTRATOR_1].[DEPENDENCIES] AS T0
  --WORKFLOW
  LEFT JOIN [DATATINO_ORCHESTRATOR_1].[WORKFLOWS]           AS T1 ON T0.WORKFLOW_ID = T1.ID
  LEFT JOIN [DATATINO_ORCHESTRATOR_1].[DATAFLOWS]           AS T2 ON T2.ID = T1.DATAFLOW_ID

  --MAIN PROCESS
  LEFT JOIN [DATATINO_ORCHESTRATOR_1].[DATAFLOWS]           AS T4 ON T4.ID = T0.DATAFLOW_ID
  LEFT JOIN [DATATINO_ORCHESTRATOR_1].[DATAFLOW_TYPES]      AS T5 ON T5.ID = T0.DATAFLOW_TYPE_ID

  --DEPENDENCY PROCESS
  LEFT JOIN [DATATINO_ORCHESTRATOR_1].[DATAFLOWS]           AS T6 ON T6.ID = T0.DEPENDENCY_ID
  LEFT JOIN [DATATINO_ORCHESTRATOR_1].[DATAFLOW_TYPES]      AS T7 ON T7.ID = T0.DATAFLOW_TYPE_ID_DEPENDENCY