

CREATE    VIEW DATATINO_ORCHESTRATOR_1.V_H_WORKFLOWS AS
SELECT A.NAME, B.ID, A.START_RUN, A.END_RUN, A.[STATUS]
FROM DATATINO_ORCHESTRATOR_1.H_DATAFLOWS A
         JOIN DATATINO_ORCHESTRATOR_1.WORKFLOWS B
              ON A.DATAFLOW_ID = B.DATAFLOW_ID
WHERE A.DATAFLOW_TYPE_ID = 1