

CREATE   VIEW [DATATINO_ORCHESTRATOR_1].[V_PROCESS_OVERVIEW] AS
SELECT A.ID, B.NAME, B.ID AS DATAFLOW_ID,  A.LAST_RUN, A.NEXT_RUN, A.SCHEDULE
FROM DATATINO_ORCHESTRATOR_1.PROCESSES A
         JOIN DATATINO_ORCHESTRATOR_1.DATAFLOWS B
              ON A.DATAFLOW_ID = B.ID
WHERE A.ACTIVE = 1