
CREATE    VIEW [DATATINO_ORCHESTRATOR_1].[V_WORKFLOW_OVERVIEW] AS
SELECT A.ID, B.NAME, A.LAST_RUN, A.NEXT_RUN, A.SCHEDULE
FROM DATATINO_ORCHESTRATOR_1.WORKFLOWS A
         JOIN DATATINO_ORCHESTRATOR_1.DATAFLOWS B
              ON A.DATAFLOW_ID = B.ID
WHERE A.ACTIVE = 1