
CREATE   VIEW [DATATINO_ORCHESTRATOR_1].[V_WORKFLOW_PROCESSES] AS
SELECT 
      T3.NAME AS PROCESS_NAME
      ,T4.[DESCRIPTION]
      ,T4.NAME AS WORKFLOW_NAME
      ,T4.ID AS DATAFLOW_ID_WORKFLOW
      ,T3.ID AS DATAFLOW_ID_PROCESS
  FROM [DATATINO_ORCHESTRATOR_1].[PROCESSES] T1
  JOIN[DATATINO_ORCHESTRATOR_1].[WORKFLOWS] T2
  ON  t1.WORKFLOW_ID = t2.ID
  JOIN DATATINO_ORCHESTRATOR_1.DATAFLOWS T3
  ON T3.ID = T1.DATAFLOW_ID
  JOIN DATATINO_ORCHESTRATOR_1.DATAFLOWS T4
  ON T4.ID = T2.DATAFLOW_ID