

CREATE   VIEW  [DATATINO_ORCHESTRATOR_1].[V_WORKFLOWS] AS


SELECT T0.[ID]
      ,T0.[DATAFLOW_ID]
      ,T1.NAME
    --   ,T0.[DATAFLOW_TYPE_ID]
      ,T0.[SCHEDULE]
      ,T0.[NEXT_RUN]
      ,T0.[LAST_RUN]
      ,T0.[ACTIVE]
  FROM [DATATINO_ORCHESTRATOR_1].[WORKFLOWS] AS T0
  LEFT JOIN [DATATINO_ORCHESTRATOR_1].[DATAFLOWS]           AS T1 ON T1.ID = T0.DATAFLOW_ID