/*
 	Deze procedure maakt gebruik van de tabel Safety_Regions_per_municipal
 	voor de relatie tussen gemeenten en veiligheidsregios. 
 */
 
 CREATE   VIEW [VWSREPORT].[V_AANDEEL_POSITIEF_GETEST_PER_REGIO] AS
 -- Select base records
 WITH BASE_CTE AS (
 SELECT 
 	DATE_OF_PUBLICATION AS DATE_OF_REPORT
 ,	SECURITY_REGION_CODE AS VRCODE
 ,	MUNICIPALITY_CODE AS GMCODE
 ,	TOTAL_REPORTED
 ,	INHABITANTS
 ,   T1.DATE_LAST_INSERTED
 FROM VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY T1
 LEFT JOIN [VWSSTATIC].[INHABITANTS_PER_SAFETY_REGION]   T3	ON SECURITY_REGION_CODE	= T3.VGRNR
 WHERE T1.DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSINTER.RIVM_COVID_19_NUMBER_MUNICIPALITY)
 )
 
 ,SECOND_CTE AS (
 SELECT
     DATE_OF_REPORT
 ,   VRCODE
 ,   SUM(TOTAL_REPORTED) AS [TOTAL_REPORTED]
 ,   SUM(CAST(TOTAL_REPORTED AS FLOAT))/(CAST(INHABITANTS AS decimal(10,2))/CAST(100000 AS decimal(10,2))) AS [REPORTED_PER_REGION_100000]
 ,   INHABITANTS
 ,   DATE_LAST_INSERTED
 FROM BASE_CTE
 GROUP BY DATE_LAST_INSERTED, DATE_OF_REPORT, VRCODE, INHABITANTS
 )
 
 -- Final select and insert into statement. This part adds the calculation of a moving average of increased hospital admissions and cumulative calculations. It calculates it based on the previous 2 days as can be seen in row 59, after BETWEEN.
 
 ,THIRD_CTE AS  (
 	SELECT
 		T_SECOND.DATE_OF_REPORT
 	,	T_SECOND.VRCODE
 	,   ROUND((SUM(TOTAL_REPORTED) OVER (PARTITION BY T_SECOND.DATE_LAST_INSERTED, T_SECOND.VRCODE ORDER BY T_SECOND.DATE_OF_REPORT ASC)) / (CAST(INHABITANTS AS FLOAT)/100000.0), 2) AS DAGTOTAAL
 	,	ROUND(REPORTED_PER_REGION_100000, 1) AS [TOENAME_TOV_T-1]
 	FROM SECOND_CTE AS T_SECOND
 	where T_SECOND.date_of_report between ((SELECT MAX(DATE_OF_REPORT) FROM SECOND_CTE) - DAY(6)) and (SELECT MAX(DATE_OF_REPORT) FROM SECOND_CTE)
 	and vrcode != ''
 )
 
 ,FOURTH_CTE AS (
 	select DATE_OF_REPORT
 		, SUM(DAGTOTAAL) TOTAAL_WEEK
 	FROM
 	(
 		select  distinct a.*
 		from THIRD_CTE a
 		where date_of_report = (select max(DATE_OF_REPORT) from THIRD_CTE)
 	) a
 	group by DATE_OF_REPORT
 )
 
 select a.DATE_OF_REPORT
 , VRCODE
 , VRNAAM
 , (CAST(DAGTOTAAL AS FLOAT)/b.TOTAAL_WEEK) * 100 [AANDEEL]
 , DAGTOTAAL
 , [TOENAME_TOV_T-1]
 FROM(
 select  distinct a.*, b.VRNAAM
 from THIRD_CTE a
 	join (
 			SELECT * 
 			FROM [VWSSTATIC].[SAFETY_REGIONS_PER_MUNICIPAL] 
 			WHERE DATE_LAST_INSERTED=(SELECT MAX(DATE_LAST_INSERTED) FROM VWSSTATIC.SAFETY_REGIONS_PER_MUNICIPAL)
 		) B	on a.VRCODE = b.VRCODE
 	where date_of_report = (select max(DATE_OF_REPORT) from THIRD_CTE)
 ) a, FOURTH_CTE b