-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE   VIEW [VWSREPORT].[V_PBI_International_Data] 
AS
    SELECT
       [iso_code]							        AS [ISO Code]
      ,[continent]							        AS [Continent]
      ,[location]							        AS [Locatie]
      ,[date]								        AS [Datum]
      ,CAST([DATE_LAST_INSERTED] as date)           AS [Update datum]
      
       
	  --,[new_cases_smoothed]				      AS [Besmettingen gemiddeld]
      ,[total_deaths]						        AS [Sterfgevallen totaal]
      
      --,[new_deaths_smoothed]
	  ,[total_cases]						        AS [Besmettingen totaal]
      ,[total_cases_per_million]			        AS [Besmettingen totaal per 1M]
	  ,[new_cases_smoothed]					        AS [Besmettingen]
	  ,new_cases_smoothed_per_million / 10	        AS [Besmettingen per 100K]
      ,new_cases_smoothed_per_million		        AS [Besmettingen per 1M]
      --,[new_cases_smoothed_per_million]
      ,[total_deaths_per_million]			        AS [Sterfgevallen totaal per 1M]
      ,[new_deaths_smoothed]				        AS [Sterfgevallen]
	  ,[new_deaths_smoothed_per_million]	        AS [Sterfgevallen per 1M]
      --,[new_deaths_smoothed_per_million]
      ,[reproduction_rate]					        AS [Reproductie getal]
      ,[icu_patients]                               AS [IC bezetting]
      ,[icu_patients_per_million]                   AS [IC bezetting per 1M]
      ,[hosp_patients]                              AS [Ziekenhuis bezetting]
      ,[hosp_patients_per_million]                  AS [Ziekenhuis bezetting per 1M]
      ,[weekly_icu_admissions]                      AS [Wekelijkse IC opnames]
      ,[weekly_icu_admissions_per_million]          AS [Wekelijkse IC opnames per 1M]
      ,[weekly_hosp_admissions]                     AS [Wekelijkse ziekenhuisopnames]
      ,[weekly_hosp_admissions_per_million]         AS [Wekelijkse ziekenhuisopnames per 1M]
      --,[new_tests]
      ----,[total_tests]
      ----,[total_tests_per_thousand]
      --,[new_tests_per_thousand]
      --,[new_tests_smoothed]
      --,[new_tests_smoothed_per_thousand]
      --,[positive_rate]
      --,[tests_per_case]
      --,[tests_units]
      ,[total_vaccinations]			                AS [Gevaccinneerd totaal]
	  , CASE WHEN [population] <> 0 THEN 
            1000000 * [total_vaccinations]/[population]
        ELSE 0 
        END	AS [Gevaccinneerd totaal per 1M]
      --,[people_vaccinated]						    AS [Gevaccinneerd]
      --,[people_fully_vaccinated]						AS [Gevaccineerd volledig]
      ,[new_vaccinations_smoothed]				    AS [Gezette prikken]
	  ,new_vaccinations_smoothed_per_million		AS [Gezette prikken per 1M]
      --,[new_vaccinations_smoothed]
      ,[total_vaccinations_per_hundred]	    	  	AS [Gevaccinneerd totaal percentage]
      ,[people_vaccinated_per_hundred]			  	AS [Gevaccinneerd percentage]
      --,[people_fully_vaccinated_per_hundred]
      --,[new_vaccinations_smoothed_per_million]			AS [Vaccinaties per 1M]
      --,[stringency_index]
      ,[population]							      	AS [Bevolking]
      ,[population_density]					      	AS [Bevolkingsdichtheid]
      --,[median_age]
      --,[aged_65_older]
      --,[aged_70_older]
      --,[gdp_per_capita]
      --,[extreme_poverty]
      --,[cardiovasc_death_rate]
      --,[diabetes_prevalence]
      --,[female_smokers]
      --,[male_smokers]
      --,[handwashing_facilities]
      --,[hospital_beds_per_thousand]
      --,[life_expectancy]
      --,[human_development_index]
      --,[DATE_LAST_INSERTED]
    FROM [VWSDEST].[OIWD_International_Data]

    WHERE DATE_LAST_INSERTED = (
      SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[OIWD_International_Data])