-- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATION FOR MORE INFORMATION.
 
 CREATE   VIEW [VWSREPORT].[V_PBI_ECDC_VACCINATION_COVERAGES] 
 AS
   SELECT
     [REPORTING_COUNTRY],
     [UPTAKE_ONE_VACCINE_DOSE],
     CONCAT(CAST([UPTAKE_ONE_VACCINE_DOSE] AS VARCHAR(50)), '%') AS [UPTAKE_ONE_VACCINE_DOSE_FORMATTED]
   FROM [VWSREPORT].[ECDC_VACCINATION_COVERAGES]
   WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSREPORT].[ECDC_VACCINATION_COVERAGES])