CREATE   VIEW [VWSREPORT].[V_REPRODUCTION_NUMBER] AS
SELECT 
--dbo.CONVERT_UNIX_TO_DATETIME(DATE_OF_REPORT_UNIX) AS DATE_OF_REPORT
dbo.CONVERT_UNIX_TO_DATETIME(DATE_UNIX) AS DATE_OF_REPORT
,*  
FROM [VWSDEST].[V_REPRODUCTION_NUMBER]