-- -- COPYRIGHT (C) 2020 DE STAAT DER NEDERLANDEN, MINISTERIE VAN   VOLKSGEZONDHEID, WELZIJN EN SPORT.
 -- -- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
 
 --1) CREATE VIEW(S).....
 CREATE   VIEW [VWSREPORT].[V_RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL]
 AS
     WITH CTE AS (
         SELECT
             [VERSION],
             [DATE_LAST_INSERTED],
             [DATE_OF_REPORT],
             [DATE_OF_STATISTICS],
             [N_PARTICIPANTS_TOTAL],
             [N_WITH_SYMPTOMS],
             [N_WITH_SHARED_COVID_TEST_RESULT],
             [N_TESTED_POSITIVE],
             [PERC_COVID_TEST_POSITIVE]
         FROM [VWSDEST].[RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL] WITH(NOLOCK)
         WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_INFECTIE_RADAR_POSITIVE_TESTS_WEEKLY_NL] WITH(NOLOCK))
     )
     SELECT 
         [VERSION],
         [DATE_LAST_INSERTED],
         [DATE_OF_REPORT],
         [DATE_OF_STATISTICS],
         [N_PARTICIPANTS_TOTAL],
         [N_WITH_SYMPTOMS],
         [N_WITH_SHARED_COVID_TEST_RESULT],
         [N_TESTED_POSITIVE],
         [PERC_COVID_TEST_POSITIVE]
     FROM CTE