-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.
CREATE OR ALTER VIEW [VWSREPORT].[V_COMPLETE_MUNICIPALITY] AS
SELECT
T0.*,
SEWAGE_AVERAGE,

--Hospital Admissions Reported
HOSPITAL_NICE_DAILY_INCREASE AS HOSPITAL_NICE_REP_DAILY_INCREASE,
HOSPITAL_NICE_DAILY_INCREASE/(INHABITANTS/100000.0) as HOSPITAL_NICE_REP_DAILY_PER_100K,
HOSPITAL_NICE_DAILY_INCREASE/(INHABITANTS/1000000.0) as HOSPITAL_NICE_REP_DAILY_PER_1M,
SUM(HOSPITAL_NICE_DAILY_INCREASE) OVER(PARTITION BY GMCODE ORDER BY DATE_OF_REPORT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS HOSPITAL_NICE_REP_CUMMULATIVE,
AVG(CAST(HOSPITAL_NICE_DAILY_INCREASE AS FLOAT)) OVER (PARTITION BY GMCODE ORDER BY DATE_OF_REPORT ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as HOSPITAL_NICE_REP_3D_MovAvg,
AVG(Cast(HOSPITAL_NICE_DAILY_INCREASE AS FLOAT)) OVER (PARTITION BY GMCODE ORDER BY DATE_OF_REPORT ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)/(INHABITANTS/100000.0) as HOSPITAL_NICE_REP_3D_MovAvg_PER_100K,
SUM(CAST(HOSPITAL_NICE_DAILY_INCREASE AS FLOAT)) OVER (PARTITION BY GMCODE ORDER BY DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as HOSPITAL_NICE_REP_7D_SUM,
SUM(Cast(HOSPITAL_NICE_DAILY_INCREASE AS FLOAT)) OVER (PARTITION BY GMCODE ORDER BY DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)/(INHABITANTS/100000.0) as HOSPITAL_NICE_REP_7D_SUM_PER_100K,
SUM(Cast(HOSPITAL_NICE_DAILY_INCREASE AS FLOAT)) OVER (PARTITION BY GMCODE ORDER BY DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)/(INHABITANTS/1000000.0) as HOSPITAL_NICE_REP_7D_SUM_PER_1M,

--Hospital Admissions Hospitalized
HOSPITAL_NICE_H_DAILY_INCREASE AS HOSPITAL_NICE_HOS_DAILY_INCREASE,
HOSPITAL_NICE_H_DAILY_INCREASE/(INHABITANTS/100000.0) as HOSPITAL_NICE_HOS_DAILY_PER_100K,
HOSPITAL_NICE_H_DAILY_INCREASE/(INHABITANTS/1000000.0) as HOSPITAL_NICE_HOS_DAILY_PER_1M,
SUM(HOSPITAL_NICE_H_DAILY_INCREASE) OVER(PARTITION BY GMCODE ORDER BY T0.DATE_OF_REPORT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS HOSPITAL_NICE_HOS_CUMMULATIVE,
AVG(CAST(HOSPITAL_NICE_H_DAILY_INCREASE AS FLOAT)) OVER (PARTITION BY GMCODE ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as HOSPITAL_NICE_HOS_3D_MovAvg,
AVG(Cast(HOSPITAL_NICE_H_DAILY_INCREASE AS FLOAT)) OVER (PARTITION BY GMCODE ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)/(INHABITANTS/100000.0) as HOSPITAL_NICE_HOS_3D_MovAvg_PER_100K,
SUM(CAST(HOSPITAL_NICE_H_DAILY_INCREASE AS FLOAT)) OVER (PARTITION BY GMCODE ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as HOSPITAL_NICE_HOS_7D_SUM,
SUM(Cast(HOSPITAL_NICE_H_DAILY_INCREASE AS FLOAT)) OVER (PARTITION BY GMCODE ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)/(INHABITANTS/100000.0) as HOSPITAL_NICE_HOS_7D_SUM_PER_100K,
SUM(Cast(HOSPITAL_NICE_H_DAILY_INCREASE AS FLOAT)) OVER (PARTITION BY GMCODE ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)/(INHABITANTS/1000000.0) as HOSPITAL_NICE_HOS_7D_SUM_PER_1M

FROM [VWSREPORT].[V_BASE_MUNICIPALITY] AS T0
-- join escalatie ladder per GM.
LEFT JOIN (
    SELECT
    DATE_OF_REPORT as DATE_OF_REPORT_T1,
    VRCODE AS VRCODE_T1,
    ESCALATION_LEVEL
    FROM [VWSDEST].[ESCALATIONLEVELS_PER_REGION]
    WHERE DATE_LAST_INSERTED=(SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[ESCALATIONLEVELS_PER_REGION])
    ) AS T1 on T0.DATE_OF_REPORT=T1.DATE_OF_REPORT_T1 and T1.VRCODE_T1=T0.VRCODE
LEFT JOIN (
    SELECT
    [WEEK_UNIX]
    ,[GMCODE] AS GMCODE_T2
    ,[AVERAGE_RNA_FLOW_PER_100000] AS SEWAGE_AVERAGE
    FROM [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY]
    WHERE DATE_LAST_INSERTED=(SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY])
    ) AS T2 on T0.DATE_OF_REPORT_UNIX=T2.WEEK_UNIX and T2.GMCODE_T2=T0.GMCODE
LEFT JOIN (
    SELECT
    DATE_OF_STATISTICS,
    GM_CODE AS GMCODE_T3,
    REPORTED AS HOSPITAL_NICE_DAILY_INCREASE,
    HOSPITALIZED AS HOSPITAL_NICE_H_DAILY_INCREASE
    FROM [VWSDEST].[NICE_HOSPITAL_GM]
    WHERE DATE_LAST_INSERTED=(SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[NICE_HOSPITAL_GM])
    ) AS T3
    ON T0.DATE_OF_REPORT=T3.DATE_OF_STATISTICS AND T0.GMCODE=T3.GMCODE_T3
GO

-- SELECT * FROM [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY]
-- WHERE DATE_LAST_INSERTED=(SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[SEWER_MEASUREMENTS_PER_MUNICIPALITY])