-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordination for more information.
CREATE OR ALTER VIEW [VWSREPORT].[V_COMPLETE_NATIONAL]
AS
SELECT
    T0.*
,   INFECTED_GGD
,   PERCENTAGE_INFECTED_GGD
,   TOTAL_TESTED_GGD
,   SEWAGE_AVG

,   IC_BEDS_OCCUPIED_COVID as IC_BEDS_OCCUPIED_COVID_LNAZ
,   IC_BEDS_OCCUPIED_NON_COVID AS IC_BEDS_OCCUPIED_NON_COVID_LNAZ
-- Explicit naming because its not the percentage of all beds, its the fraction w non covid.
,   IC_BEDS_OCCUPIED_COVID_PERCENTAGE AS IC_BEDS_OCCUPIED_COVID_NON_COVID_FRACTION_LNAZ
,   NON_IC_BEDS_OCCUPIED_COVID AS NON_IC_BEDS_OCCUPIED_COVID_LNAZ,
-- ,   SUM(TOTAL_TESTED_GGD) OVER(ORDER BY T0.DATE_OF_REPORT ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS TOTAL_TESTED_GGD_7D_SUM

--Hospital Admissions Reported
HOSPITAL_NICE_DAILY_INCREASE AS HOSPITAL_NICE_REP_DAILY_INCREASE,
HOSPITAL_NICE_DAILY_INCREASE/(INHABITANTS/100000.0) as HOSPITAL_NICE_REP_DAILY_PER_100K,
HOSPITAL_NICE_DAILY_INCREASE/(INHABITANTS/1000000.0) as HOSPITAL_NICE_REP_DAILY_PER_1M,
SUM(HOSPITAL_NICE_DAILY_INCREASE) OVER(ORDER BY T0.DATE_OF_REPORT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS HOSPITAL_NICE_REP_CUMMULATIVE,
AVG(CAST(HOSPITAL_NICE_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as HOSPITAL_NICE_REP_3D_MovAvg,
AVG(Cast(HOSPITAL_NICE_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)/(INHABITANTS/100000.0) as HOSPITAL_NICE_REP_3D_MovAvg_PER_100K,
SUM(CAST(HOSPITAL_NICE_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as HOSPITAL_NICE_REP_7D_SUM,
SUM(Cast(HOSPITAL_NICE_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)/(INHABITANTS/100000.0) as HOSPITAL_NICE_REP_7D_SUM_PER_100K,
SUM(Cast(HOSPITAL_NICE_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)/(INHABITANTS/1000000.0) as HOSPITAL_NICE_REP_7D_SUM_PER_1M,
AVG(Cast(HOSPITAL_NICE_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS HOSPITAL_NICE_REP_7D_AVG,

--Hospital Admissions Hospitalized
HOSPITAL_NICE_H_DAILY_INCREASE AS HOSPITAL_NICE_HOS_DAILY_INCREASE,
HOSPITAL_NICE_H_DAILY_INCREASE/(INHABITANTS/100000.0) as HOSPITAL_NICE_HOS_DAILY_PER_100K,
HOSPITAL_NICE_H_DAILY_INCREASE/(INHABITANTS/1000000.0) as HOSPITAL_NICE_HOS_DAILY_PER_1M,
SUM(HOSPITAL_NICE_H_DAILY_INCREASE) OVER(ORDER BY T0.DATE_OF_REPORT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS HOSPITAL_NICE_HOS_CUMMULATIVE,
AVG(CAST(HOSPITAL_NICE_H_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as HOSPITAL_NICE_HOS_3D_MovAvg,
AVG(Cast(HOSPITAL_NICE_H_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)/(INHABITANTS/100000.0) as HOSPITAL_NICE_HOS_3D_MovAvg_PER_100K,
SUM(CAST(HOSPITAL_NICE_H_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as HOSPITAL_NICE_HOS_7D_SUM,
SUM(Cast(HOSPITAL_NICE_H_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)/(INHABITANTS/100000.0) as HOSPITAL_NICE_HOS_7D_SUM_PER_100K,
SUM(Cast(HOSPITAL_NICE_H_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)/(INHABITANTS/1000000.0) as HOSPITAL_NICE_HOS_7D_SUM_PER_1M,
AVG(Cast(HOSPITAL_NICE_H_DAILY_INCREASE AS FLOAT)) OVER (ORDER BY T0.DATE_OF_REPORT ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS HOSPITAL_NICE_HOS_7D_AVG

--Tested Positives
,   dbo.CALC_PERC_CHANGE(T0.POSITIVE_DAILY_7D_SUM, LAG(T0.POSITIVE_DAILY_7D_SUM, 7, NULL) OVER (ORDER BY T0.DATE_OF_REPORT)) as POSITIVE_DAILY_PERC_CHANGE_LAST_WEEK
,   SUM(T0.POSITIVE_DAILY_7D_SUM) OVER(ORDER BY T0.DATE_OF_REPORT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS POSITIVE_DAILY_CUMULATIVE

-- IC Admissions
,   T6.IC_ADMISSION_DAILY_NICE
,   SUM(T6.IC_ADMISSION_DAILY_NICE) OVER(ORDER BY T0.DATE_OF_REPORT ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS IC_ADMISSION_DAILY_NICE_3D_SUM
,   AVG(T6.IC_ADMISSION_DAILY_NICE) OVER(ORDER BY T0.DATE_OF_REPORT ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS IC_ADMISSION_DAILY_NICE_3D_AVG
,   AVG(T6.IC_ADMISSION_DAILY_NICE) OVER(ORDER BY T0.DATE_OF_REPORT ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS IC_ADMISSION_DAILY_NICE_7D_AVG
,   dbo.CALC_PERC_CHANGE(T6.IC_ADMISSION_DAILY_NICE_7D_SUM, LAG(T6.IC_ADMISSION_DAILY_NICE_7D_SUM, 7, NULL) OVER (ORDER BY T0.DATE_OF_REPORT)) as IC_ADMISSION_NICE_PERC_CHANGE_LAST_WEEK
,   SUM(T6.IC_ADMISSION_DAILY_NICE) OVER(ORDER BY T0.DATE_OF_REPORT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS IC_ADMISSION_NICE_CUMULATIVE

,   T7.INFECTIOUS_AVG
,   T7.INFECTIOUS_AVG_NORMALIZED AS INFECTIOUS_AVG_PER_100K
,   INHABITANTS/T7.INFECTIOUS_AVG AS INFECTIOUS_AVG_FACTOR_HEALTY_PERSONS_PER_1_INFECTED_PERSON

,   T8.INFECTED_NURSERY_DAILY
,   T8.DECEASED_NURSERY_DAILY
,   T8.TOTAL_REPORTED_LOCATIONS_NURSERY

,   T9.INFECTED_ELDERLY_AT_HOME_DAILY
,   T9.DECEASED_ELDERLY_AT_HOME_DAILY

,   T10.INFECTED_DISABILITY_DAILY
,   T10.DECEASED_DISABILITY_DAILY
,   T10.TOTAL_INFECTED_LOCATIONS_DISABILITY

-- IC admission RIVM data
,   T11.[RIVM_IC_OPNAMES_MELDINGSDATUM]
,   T11.[RIVM_IC_OPNAMES_OPNAMEDATUM]


from [VWSREPORT].[V_BASE_NATIONAL] as T0
-- join percentage positive
LEFT join (
    SELECT
       [NEW_DATE_OF_REPORT_UNIX] AS DATE_OF_REPORT_UNIX_T1
      ,[TESTS] AS TOTAL_TESTED_GGD
      ,[POSITIVE_TESTS] AS INFECTED_GGD
      ,[PERCENTAGE_POSITIVE] AS PERCENTAGE_INFECTED_GGD
      ,dbo.CONVERT_DATETIME_TO_UNIX(DATE_LAST_INSERTED) AS DATE_OF_INSERTION_UNIX
  FROM [VWSDEST].[GGD_TESTED_PEOPLE_NL]
WHERE DATE_LAST_INSERTED = (SELECT max(DATE_LAST_INSERTED)
                            FROM [VWSDEST].[GGD_TESTED_PEOPLE_NL])
) AS T1
ON T0.DATE_OF_REPORT_UNIX=T1.DATE_OF_REPORT_UNIX_T1

-- join sewage
LEFT JOIN (
    SELECT
    [WEEK_UNIX]
    , [AVERAGE_RNA_FLOW_PER_100000] AS SEWAGE_AVG
    FROM [VWSDEST].[SEWER_MEASUREMENTS]
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[SEWER_MEASUREMENTS])
) AS T2
ON DATE_OF_REPORT_UNIX=T2.WEEK_UNIX

LEFT JOIN(
-- FROM VWSINTER.LNAZ_HOSPITAL_BED_OCCUPANCY
    SELECT
    DATE_OF_REPORT
    , DATE_OF_REPORT_UNIX
    , IC_BEDS_OCCUPIED_COVID
    , IC_BEDS_OCCUPIED_NON_COVID
    , IC_BEDS_OCCUPIED_COVID_PERCENTAGE
    , NON_IC_BEDS_OCCUPIED_COVID
    , DATE_LAST_INSERTED AS T0_DATE_LAST_INSERTED
    , RANK() OVER(PARTITION BY DATE_OF_REPORT ORDER BY ID DESC) as RANK_ID
    FROM [VWSDEST].[HOSPITAL_BED_OCCUPANCY]
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM [VWSDEST].[HOSPITAL_BED_OCCUPANCY])
) AS T3
ON T0.DATE_OF_REPORT_UNIX=T3.DATE_OF_REPORT_UNIX
AND T3.RANK_ID = 1

LEFT JOIN (
    -- origin FROM VWSINTER.NICE_HOSPITAL_ADMISSIONS_NATIONAL
    SELECT
    dbo.convert_datetime_to_unix(DATE_OF_STATISTICS) AS DATE_OF_REPORT_UNIX
    , REPORTED AS HOSPITAL_NICE_DAILY_INCREASE
	, HOSPITALIZED AS HOSPITAL_NICE_H_DAILY_INCREASE
    , DATE_LAST_INSERTED FROM [VWSDEST].[NICE_HOSPITAL_NL]
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) from [VWSDEST].[NICE_HOSPITAL_NL])
) AS T4
ON T0.DATE_OF_REPORT_UNIX=T4.DATE_OF_REPORT_UNIX

LEFT JOIN (
    SELECT
    [DATE_OF_REPORT]
    , [VALUE] AS IC_ADMISSION_DAILY_NICE
    , SUM([VALUE]) OVER(ORDER BY DATE_OF_REPORT ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS IC_ADMISSION_DAILY_NICE_7D_SUM
    , [DATE_LAST_INSERTED]
    FROM [VWSINTER].[FOUNDATION_NICE_IC_INTAKE_COUNT]
    where DATE_LAST_INSERTED=(select MAX(DATE_LAST_INSERTED) FROM [VWSINTER].[FOUNDATION_NICE_IC_INTAKE_COUNT])
) AS T6
ON T0.DATE_OF_REPORT=T6.DATE_OF_REPORT

LEFT JOIN (
    SELECT
    [DATE_OF_REPORT_UNIX]
    , [INFECTIOUS_AVG]
    , [INFECTIOUS_AVG_NORMALIZED]
    FROM [VWSDEST].[INFECTIOUS_PEOPLE]
    WHERE DATE_LAST_INSERTED=(SELECT max(DATE_LAST_INSERTED) FROM [VWSDEST].[INFECTIOUS_PEOPLE])
) AS T7
ON T0.DATE_OF_REPORT_UNIX=T7.DATE_OF_REPORT_UNIX

LEFT JOIN (
    SELECT
      [DATE_OF_REPORT_UNIX]
      ,[INFECTED_NURSERY_DAILY]
      ,[DECEASED_NURSERY_DAILY]
      ,[TOTAL_REPORTED_LOCATIONS] AS TOTAL_REPORTED_LOCATIONS_NURSERY
    FROM [VWSDEST].[NURSING_HOMES_TOTALS]
    WHERE DATE_LAST_INSERTED=(SELECT max(DATE_LAST_INSERTED) FROM [VWSDEST].[NURSING_HOMES_TOTALS])
) AS T8
ON T0.DATE_OF_REPORT_UNIX=T8.DATE_OF_REPORT_UNIX

LEFT JOIN (
    SELECT
      [DATE_OF_REPORT_UNIX]
      ,[INFECTED_ELDERLY_AT_HOME_DAILY]
      ,[DECEASED_ELDERLY_AT_HOME_DAILY]
    FROM [VWSDEST].[ELDERLY_AT_HOME]
    WHERE DATE_LAST_INSERTED=(SELECT max(DATE_LAST_INSERTED) FROM [VWSDEST].[ELDERLY_AT_HOME])
) AS T9
ON T0.DATE_OF_REPORT_UNIX=T9.DATE_OF_REPORT_UNIX

LEFT JOIN (
    SELECT
      [DATE_OF_REPORT_UNIX]
      ,[INFECTED_DISABILITY_DAILY]
      ,[DECEASED_DISABILITY_DAILY]
      ,[TOTAL_INFECTED_LOCATIONS] AS TOTAL_INFECTED_LOCATIONS_DISABILITY
    FROM [VWSDEST].[DISABILITY]
    WHERE DATE_LAST_INSERTED=(SELECT max(DATE_LAST_INSERTED) FROM [VWSDEST].[DISABILITY])
) AS T10
ON T0.DATE_OF_REPORT_UNIX=T10.DATE_OF_REPORT_UNIX

LEFT JOIN (
    SELECT
      [DATE_OF_REPORT]
      ,[DATE_OF_REPORT_UNIX]
      ,[DATE_OF_STATISTICS]
      ,[DATE_OF_STATISTICS_UNIX]
      ,[IC_ADMISSION_NOTIFICATION]      AS [RIVM_IC_OPNAMES_MELDINGSDATUM]
      ,[IC_ADMISSION]                   AS [RIVM_IC_OPNAMES_OPNAMEDATUM]
    FROM [VWSDEST].[RIVM_IC_OPNAME]
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSDEST.RIVM_IC_OPNAME)
) AS T11
ON T0.DATE_OF_REPORT_UNIX = T11.DATE_OF_STATISTICS_UNIX