CREATE TABLE [DATATINO_1].[ASSOCIATIONS] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [WORKFLOW_ID] BIGINT         NULL,
    [PROTO_ID]    BIGINT         NULL,
    [NAME]        NVARCHAR (200) NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_ASSOCIATIONS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ASSOCIATION_PROTO] FOREIGN KEY ([PROTO_ID]) REFERENCES [DATATINO_PROTO_1].[PROTOS] ([ID]),
    CONSTRAINT [FK_ASSOCIATION_WORKFLOW] FOREIGN KEY ([WORKFLOW_ID]) REFERENCES [DATATINO_ORCHESTRATOR_1].[WORKFLOWS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_ASSOCIATIONS_WORKFLOW_ID_PROTO_ID]
    ON [DATATINO_1].[ASSOCIATIONS]([WORKFLOW_ID] ASC, [PROTO_ID] ASC) WHERE ([WORKFLOW_ID] IS NOT NULL AND [PROTO_ID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_ASSOCIATIONS_PROTO_ID]
    ON [DATATINO_1].[ASSOCIATIONS]([PROTO_ID] ASC);

