CREATE TABLE [DATATINO_1].[CONFIGURATION_VERSION] (
    [ID]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [VERSION]      NVARCHAR (200) NOT NULL,
    [INSTALLED_BY] NVARCHAR (200) NOT NULL,
    [INSTALLED_AT] DATETIME2 (7)  NOT NULL,
    [NAME]         NVARCHAR (200) NOT NULL,
    [DESCRIPTION]  NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_CONFIGURATION_VERSION] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CONFIGURATION_VERSION_VERSION]
    ON [DATATINO_1].[CONFIGURATION_VERSION]([VERSION] ASC);

