CREATE TABLE [DATATINO_1].[FLOW_ITEMS] (
    [ID]                BIGINT         IDENTITY (1, 1) NOT NULL,
    [FLOW_ID]           NVARCHAR (200) NOT NULL,
    [FLOW_ITEM_ID]      NVARCHAR (200) NOT NULL,
    [FLOW_ITEM_TYPE_ID] BIGINT         NOT NULL,
    [CREATED_AT]        DATETIME2 (7)  NOT NULL,
    [STARTED_AT]        DATETIME2 (7)  NOT NULL,
    [ENDED_AT]          DATETIME2 (7)  NOT NULL,
    [STATUS]            INT            NOT NULL,
    [NAME]              NVARCHAR (200) NOT NULL,
    [DESCRIPTION]       NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_FLOW_ITEMS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FLOW_ITEM_FLOW_ITEM_TYPE] FOREIGN KEY ([FLOW_ITEM_TYPE_ID]) REFERENCES [DATATINO_1].[FLOW_ITEM_TYPES] ([ID]),
    CONSTRAINT [FK_FLOW_ITEMS_FLOWS_FLOW_ID] FOREIGN KEY ([FLOW_ID]) REFERENCES [DATATINO_1].[FLOWS] ([FLOW_ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_FLOW_ITEMS_FLOW_ITEM_TYPE_ID]
    ON [DATATINO_1].[FLOW_ITEMS]([FLOW_ITEM_TYPE_ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FLOW_ITEMS_FLOW_ID_FLOW_ITEM_ID]
    ON [DATATINO_1].[FLOW_ITEMS]([FLOW_ID] ASC, [FLOW_ITEM_ID] ASC);

