CREATE TABLE [DATATINO_1].[FLOW_ITEM_TYPES] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [NAME]        NVARCHAR (200) NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_FLOW_ITEM_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

