CREATE TABLE [DATATINO_1].[FLOWS] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [FLOW_ID]     NVARCHAR (200) NOT NULL,
    [CREATED_AT]  DATETIME2 (7)  NOT NULL,
    [STARTED_AT]  DATETIME2 (7)  NOT NULL,
    [ENDED_AT]    DATETIME2 (7)  NOT NULL,
    [CREATED_BY]  NVARCHAR (200) NOT NULL,
    [STATUS]      INT            NOT NULL,
    [NAME]        NVARCHAR (200) NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_FLOWS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AK_FLOWS_FLOW_ID] UNIQUE NONCLUSTERED ([FLOW_ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FLOWS_FLOW_ID]
    ON [DATATINO_1].[FLOWS]([FLOW_ID] ASC);

