CREATE TABLE [DATATINO_PROTO_1].[LAYOUT_TYPES] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [NAME]        NVARCHAR (200) NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_LAYOUT_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

