CREATE TABLE [DATATINO_PROTO_1].[MOCKS] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [COLUMNS]     NVARCHAR (200) NOT NULL,
    [DATA_TYPES]  NVARCHAR (450) NOT NULL,
    [NAME]        NVARCHAR (200) NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_MOCKS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_MOCKS_NAME_COLUMNS_DATA_TYPES]
    ON [DATATINO_PROTO_1].[MOCKS]([NAME] ASC, [COLUMNS] ASC, [DATA_TYPES] ASC);

