CREATE TABLE [DATATINO_PROTO_1].[PROTOS] (
    [ID]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [HEADER_NAMES]  NVARCHAR (200) NOT NULL,
    [HEADER_VALUES] NVARCHAR (200) NOT NULL,
    [ACTIVE]        INT            NOT NULL,
    [NAME]          NVARCHAR (200) NOT NULL,
    [DESCRIPTION]   NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_PROTOS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROTOS_NAME]
    ON [DATATINO_PROTO_1].[PROTOS]([NAME] ASC);

