CREATE TABLE [DATATINO_PROTO_1].[VIEWS] (
    [ID]                       BIGINT         IDENTITY (1, 1) NOT NULL,
    [LAST_UPDATE_NAME]         NVARCHAR (450) NOT NULL,
    [CONSTRAINT_KEY_NAME]      NVARCHAR (200) NULL,
    [CONSTRAINT_VALUE]         NVARCHAR (200) NULL,
    [GROUPED_KEY_NAME]         NVARCHAR (200) NULL,
    [GROUPED_LAST_UPDATE_NAME] NVARCHAR (200) NULL,
    [NAME]                     NVARCHAR (200) NOT NULL,
    [DESCRIPTION]              NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_VIEWS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_VIEWS_NAME_LAST_UPDATE_NAME_CONSTRAINT_KEY_NAME_CONSTRAINT_VALUE_GROUPED_KEY_NAME_GROUPED_LAST_UPDATE_NAME]
    ON [DATATINO_PROTO_1].[VIEWS]([NAME] ASC, [LAST_UPDATE_NAME] ASC, [CONSTRAINT_KEY_NAME] ASC, [CONSTRAINT_VALUE] ASC, [GROUPED_KEY_NAME] ASC, [GROUPED_LAST_UPDATE_NAME] ASC) WHERE ([CONSTRAINT_KEY_NAME] IS NOT NULL AND [CONSTRAINT_VALUE] IS NOT NULL AND [GROUPED_KEY_NAME] IS NOT NULL AND [GROUPED_LAST_UPDATE_NAME] IS NOT NULL);

