# Copyright (c) 2021 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport.
# Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-covid19-data-backend-processing for more information.

# This is a basic workflow to help you get started with Actions
name: "cdb-ci"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    paths: 
      - "src/**/*.ipynb"
    branches:
      - "topic/*" # USED FOR TESTING!
  pull_request:
    branches:
      - master

env:
  GITHUB_WORKFLOWS: "./.github/workflows"

jobs:

  analyse:
    name: "select scripts"
    outputs:
      modified_scripts: ${{ steps.check_modified_scripts.outputs.modified_scripts }}
    runs-on: ubuntu-latest
    steps:
      - name: 1 - Checkout
        uses: actions/checkout@v2

      - name: 2 - Select Modified Scripts
        id: select_modified_scripts
        uses: jitterbit/get-changed-files@v1
      
      - name: 3 - Analyse Modified Scripts
        id: check_modified_scripts
        run: |
          $scripts = "${{ steps.select_modified_scripts.outputs.added_modified }}"
          $scripts += " ${{ steps.select_modified_scripts.outputs.renamed }}" 

          Write-Host "========== modified files =========="
          Write-Host $scripts

          echo "::set-output name=modified_scripts::${scripts}"          
        shell: pwsh

  build:
    name: "build scripts"
    needs: analyse
    runs-on: ubuntu-latest
    steps:
      - name: 1 - Checkout
        uses: actions/checkout@v2

      - name: 2 - Build MSSQL Artifacts
        run: |
          & "${{ env.GITHUB_WORKFLOWS }}/scripts/build-script.ps1" `
            -SourceDirectory "${{ github.workspace }}" `
            -ModifiedFiles "${{ needs.analyse.outputs.modified_scripts }}"
        shell: pwsh

      - name: "3 - Copy Files: MSSQL Scripts"
        uses: actions/upload-artifact@v2.3.1
        with:
          name: mssql-artifacts
          path: "${{ github.workspace }}/*.sql"
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
          retention-days: 28

      - name: "4 - Copy Files: Powershell Scripts"
        uses: actions/upload-artifact@v2.3.1
        with:
          name: pwsh-artifacts
          path: "${{ env.GITHUB_WORKFLOWS }}/scripts/"
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
          retention-days: 28

      - name: 5 - Post Build
        if: always()
        run: |
          $containerName = "a1049e34-6129-11ec-90d6-0242ac120003"
          Write-Host "Removing container(s)....."
          docker container stop $containerName
          docker container rm $containerName
        shell: pwsh
