name: "cdb-cd"

on:    
  workflow_run:
    workflows: ["cdb-ci"]
    types: 
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: 1 - Checkout
        uses: actions/checkout@v2
