-- Copyright (c) 2020 De Staat der Nederlanden, Ministerie van   Volksgezondheid, Welzijn en Sport. 
-- Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2 - see https://github.com/minvws/nl-contact-tracing-app-coordinationfor more information.

CREATE OR ALTER PROCEDURE [dbo].[SP_INHABITANTS_PER_AGEGROUP]
AS
BEGIN
    INSERT INTO VWSSTATIC.CBS_INHABITANTS_PER_AGEGROUP
    ([GESLACHT], [LEEFTIJD], [BURGERLIJKESTAAT], [REGIOS], [PERIODEN], [BEVOLKINGOP1JANUARI_1], [GEMIDDELDEBEVOLKING_2])
    SELECT
        [GESLACHT],
        [LEEFTIJD],
        [BURGERLIJKESTAAT],
        [REGIOS],
        [PERIODEN],
        [BEVOLKINGOP1JANUARI_1],
        [GEMIDDELDEBEVOLKING_2]
    FROM VWSSTAGE.CBS_INHABITANTS_PER_AGEGROUP
    WHERE DATE_LAST_INSERTED = (SELECT MAX(DATE_LAST_INSERTED) FROM VWSSTAGE.CBS_INHABITANTS_PER_AGEGROUP)
END;